### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by Vesterix** [firebase/quickstart-unity#1008]
### [REQUIRED] Please fill in the following fields:

  * Unity editor version: 2019.4.22f
  * Firebase Unity SDK version: 7.1.0
  * Source you installed the SDK: Unity Package Manager
  * Other Firebase Components in use: Message,Crashlytics, Dynamic Links, Remote Config
  * Additional SDKs you are using: Facebook, AdMob, IronSource, Applovin SDK, Helpshift, OneSignal
  * Platform you are using the Unity editor on: WEindows
  * Platform you are targeting: Android\IOS
  * Scripting Runtime: IL2CPP

### [REQUIRED] Please describe the issue here:
When we upgraded to version 7+ we have started get crashes in users. By logs I can assume that problem rise at the push notifications initialize, but not assured

Logs in Crashlytics:
[crash_1.txt](https://github.com/firebase/quickstart-unity/files/6220311/crash_1.txt)
[crash_2.txt](https://github.com/firebase/quickstart-unity/files/6220312/crash_2.txt)
[crash_3.txt](https://github.com/firebase/quickstart-unity/files/6220313/crash_3.txt)

**Comment by paulinon** [comment]
Hi @Vesterix,

I think this issue is going to be a little too broad to tackle with just the crash logs. We'll need to do some work here to isolate the cause. With that, I'd like you to provide the following:

- Problematic Firebase product
- A [minimal, reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of your project
- Confirmation that you are getting NDK crash reports

Additionally, please make sure that you're using the latest version of the Unity editor so that your implementation can have the latest updates and bug fixes. The latest version as of writing is Unity 2021.1.0.

**Comment by paradizIscool** [comment]
@paulinon 

Unity discourages us to use latest **TECH** release (2021.1.0) in production.
All **LTS** versions are stable releases and get bugfixes and latest updates.
