### ISSUE TITLE
im using firebase with unity to do my login screen everything works fine but when i build it to android it just doesnt work i tried putting a debug panel to give me the errors in android but i got nothing it works perfectly fine in the unity editor[Bug] 

### ISSUE THREAD

**Issue by XdKoro** [firebase/quickstart-unity#1015]
### [REQUIRED] Please fill in the following fields:

  * Unity editor version: _____
  * Firebase Unity SDK version: _____
  * Source you installed the SDK: _____ (.unitypackage or Unity Package Manager)
  * Problematic Firebase Component: _____ (Auth, Database, etc.)
  * Other Firebase Components in use: _____ (Auth, Database, etc.)
  * Additional SDKs you are using: _____ (Facebook, AdMob, etc.)
  * Platform you are using the Unity editor on: _____ (Mac, Windows, or Linux)
  * Platform you are targeting: _____ (iOS, Android, and/or desktop)
  * Scripting Runtime: _____ (Mono, and/or IL2CPP)

### [REQUIRED] Please describe the issue here:

(Please list the full steps to reproduce the issue. Include device logs, Unity logs, and stack traces if available.)

#### Steps to reproduce:

Have you been able to reproduce this issue with just the Firebase Unity quickstarts (this GitHub project)?
What's the issue repro rate? (eg 100%, 1/5 etc)

What happened? How can we make the problem occur?
This could be a description, log/console output, etc.

If you have a downloadable sample project that reproduces the bug you're reporting, you will
likely receive a faster response on your issue.

#### Relevant Code:

```
// TODO(you): code here to reproduce the problem
```

**Comment by paulinon** [comment]
Hi @XdKoro,

Could you provide a [minimal, reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of your project so that I can identify what prevents your app from being built?

Thanks!

**Comment by XdKoro** [comment]
Hi @paulinon what do you mean by a minimal reproducible example my project is very big and will be hard to import is there any way you can debug it?

**Comment by paulinon** [comment]
Hi @XdKoro,

Could you try using our quickstart and see if you're able to replicate this behavior? If so, please provide the steps you've taken before encountering the issue. You may also share screenshots of error messages if there are any.

**Comment by XdKoro** [comment]
Hello, @paulinon

I followed the instructions on your website for fixing this issue and nothing changed I used a mobile debug console and I didn't get any errors the only error I every time I open the project related to firebase is Generation of the Firebase Android resource file google-services.xml from Assets/StreamingAssets/GoogleService-Info.list failed.
If you have not included valid Firebase Android resources in your app it will fail to initialize.

**Comment by XdKoro** [comment]
just to not waste your time i already added those specific lines in the google services file and nothing changed

**Comment by paulinon** [comment]
Hi @XdKoro,

When you said "those specific lines", are you referring to the ones specified in this [thread](https://github.com/firebase/quickstart-unity/issues/946#issuecomment-774337225)? If so, it would be great if you could provide a simple project that reproduces your issue so that I can narrow down where the cause of your issue is. It would also help if you can confirm that you're able to reproduce this behavior using our [quickstart](https://github.com/firebase/quickstart-unity) project. This would help in giving us a baseline on whether it's a code bug or a problem with the SDK.

**Comment by pardo162** [comment]
I have the same problem

**Comment by XdKoro** [comment]
are you closing the comment section because you don't know how to fix it that's messed up i asked you guys what do you mean by a quick start I'm not ok with sending my project over

**Comment by XdKoro** [comment]
even still your quickstart project wont change anything its simply because android isn't communtacting with your script at all not even a debug message or an error

**Comment by paulinon** [comment]
Hi @XdKoro,

The bot is recognizing inactivity from your end. In the event that this issue will be closed, it's still possible for you to add a comment until this issue gets locked after a few weeks. 

Using our [quickstart](https://github.com/firebase/quickstart-unity) means cloning or downloading the code then trying it out on your end. Here, you can choose the folder corresponding to your problematic Firebase product for your Unity project. Since you don't consent to sending your project, you can add the relevant procedures and code to the quickstart project. If the issue persists with that project, please provide the complete steps you've taken before facing the issue.

Additionally, you've mentioned in a previous response that you have tried "those specific lines". Are you referring to the ones specified in this [thread](https://github.com/firebase/quickstart-unity/issues/946#issuecomment-774337225)?

I hope things have been clarified, and I look forward to hearing your results.

**Comment by XdKoro** [comment]
I have imported fireball through the package manager then made a script
using a YouTube tutorial I found then got this error when building to
android

**Comment by paulinon** [comment]
Hi @XdKoro,

I'm going to need more context from you so that I can understand your issue. With that, please provide the use case of your Unity project along with the expected and actual behavior. Also, could you provide the tutorial you've used as well as the platform you're using the Unity editor on?

Additionally, I would like to know how you're doing with trying to reproduce the behavior using our quickstart. We can use this as a baseline in troubleshooting your issue.

Hoping to hear more from you soon.
