### ISSUE TITLE
[FR] FCM for push notifications without Analytic and GoogleMeasurement dependencies.

### ISSUE THREAD

**Issue by rb18** [firebase/quickstart-unity#1017]
* Firebase Component: Firebase Cloud Messaging (For Push Notifications)

Hi there,
I decided to use Firebase just cloud messaging api without analytic option on our kids app category unity project. I use Firebase 7.1.0 for unity and set up firebase cloud messaging without analytic option on unity side. But when I export a build for App store I get rejection.I ask for details then make a phone call with apple side.They finally send an e-mail and you can find part of their reply on below.
"Thanks for your time on the phone today.

As we discussed, we noticed that your app includes code for the App Tracking Transparency framework, which is used when apps collect data about users and share it with third-parties for tracking purposes (e.g. Firebase):

-[APMIdentity retrieveAdTrackingConsentStatus]

Since Kids Category apps are not allowed to collect, transmit or share identifiable information with third-parties, you should not implement App Tracking Transparency in your app."

So as I noticed that I do not use any analytic apis of firebase.I just use firebase cloud messaging for push notifications without analytic option.But when I export a build our xcode project contains Firebase Analytics-CoreDiagnostics and GoogleAppMeasurement as you see on attached screen shot.So how can I prevent this analytic implementation and implement firebase cloud messaging for push notifications without any analytic or without any reason to get rejection.Please help, our project as a kids app and I want to publish it with firebase cloud messaging for push notifications. Thanks for any advice, have a good day.
![Screen Shot 2021-04-04 at 23 10 17](https://user-images.githubusercontent.com/5987372/113552545-f5066180-95fe-11eb-9eb7-5cb5f3d11565.png)

**Comment by paulinon** [comment]
Hi @rb18,

It seems that you've reported a known issue related to this Firebase iOS SDK ticket ([#7736](https://github.com/firebase/firebase-ios-sdk/issues/7736)). You may follow the workaround in this thread.

Any updates regarding this issue for the Unity SDK are being tracked in #994. With that, I'll be closing this ticket for now. Feel free to re-open if the issue persists or if your issue is different from the scenario I described.

Thanks!

**Comment by rb18** [comment]
I also reviewed #7736 and #994 but I want to just implement and use Firebase Cloud messaging for push notifications without any analytics and google measurement. Is it possible to use just FCM on that way.It is auto-implement firebase analytics and google measurement as dependencies.I implemented FCM without analytics from firebase-unity sdk 7.1.0 but it has dependencies Core and messaging on 7.5.0.
On the other hand I upgrade 
pod 'Firebase/Core', '7.9.0-k2'
pod 'Firebase/Messaging', '7.9.0-k2' from 7.5.0. Is there any way to decouple firebase cloud messaging from analaytics and google measurement ?.

**Comment by paulinon** [comment]
Hi @rb18,

Thanks for reaching out again. Currently, no process for this exists yet because the team has yet to figure out how to resolve it. With that, I've internally filed a request to decouple FCM from Analytics and GoogleMeasurement dependencies. I can't give you any timelines for updates regarding this, so I'll leave this open.

Thanks!

**Comment by rb18** [comment]
Hi @paulinon,
Thanks for replying. I wait for the any update.

**Comment by rb18** [comment]
Hi all,

**Comment by rb18** [comment]
Hi all,

"If you're only using FCM as me, you can remove the "Firebase/Core" dependency from the Pod file. This should remove any analytics-related methods."
