### ISSUE TITLE
Cannot find libmessaging_unity_player_activity.jar once importing FirebaseMessaging.unitypackage

### ISSUE THREAD

**Issue by dioniguerra** [firebase/quickstart-unity#1032]
### [REQUIRED] Please fill in the following fields:

  * Unity editor version: 2019.4.13f1
  * Firebase Unity SDK version: 7.1.0
  * Source you installed the SDK: .unitypackage
  * Problematic Firebase Component: FirebaseMessaging
  * Other Firebase Components in use: None
  * Additional SDKs you are using: None
  * Platform you are using the Unity editor on: Mac
  * Platform you are targeting: Android
  * Scripting Runtime: IL2CPP

### [REQUIRED] Please describe the question here:

After importing FirebaseMessaging.unitypackage I expect to see the bundled libmessaging_unity_player_activity.jar file under Assets/Plugins/Android, as per Firebase documentation. However, after importing and resolving dependencies (via Asset/External Dependency Manager/Android Resolver/Resolve) I still cannot find the bondled jar file. Is this been removed or should be imported separately? 

Thanks

**Comment by paulinon** [comment]
Hi @dioniguerra,

Since version 6.13.0 of the Unity SDK, `libmessaging_unity_player_activity.jar` has been packed into `com.google.firebase.firebase-messaging-unity-?.?.?.aar` (where `?.?.?` corresponds to the SDK version) in order to make resolving dependencies easier.

I'll be closing this for now. Feel free to comment if you have any other SDK-related questions.

**Comment by dioniguerra** [comment]
Thanks @paulinon that's clearer now.
