### ISSUE TITLE
A crash occurred when restarting the app

### ISSUE THREAD

**Issue by liwenchao4413** [firebase/quickstart-unity#1034]
### [REQUIRED] Please fill in the following fields:

  * Unity editor version: 2019.4.12f1
  * Firebase Unity SDK version: 7.1.0
  * Source you installed the SDK:.unitypackage
  * Problematic Firebase Component:dont know
  * Other Firebase Components in use: Analytics,Auth,Crashlytics 
  * Additional SDKs you are using: Facebook,AdMob,Mopub
  * Platform you are using the Unity editor on: Windows
  * Platform you are targeting:Android
  * Scripting Runtime:IL2CPP 

### [REQUIRED] Please describe the question here:
A crash occurred when restarting the app,But the second boot does not crash
This is the crash log
[tombstone_00.txt](https://github.com/firebase/quickstart-unity/files/6365123/tombstone_00.txt)

**Comment by paulinon** [comment]
Hi @liwenchao4413,

This is a rather unusual issue. In order to confirm if the Firebase SDKs are causing this to happen, could you try removing them from your implementation and see if the issue persists? If it does, I'd like you to try updating the editor to its latest version.

Let me know if doing these steps made any difference. Thanks!

**Comment by liwenchao4413** [comment]
Sorry, we found out where the problem occurred, it has nothing to do with firebase.
Thank you
