### ISSUE TITLE
FCM buffer verification failed. Failed to load FCM messages, some messages may have been dropped! 

### ISSUE THREAD

**Issue by hippogamesunity** [firebase/quickstart-unity#1041]
### [REQUIRED] Please fill in the following fields:

  * Unity editor version: 2020.3.6
  * Firebase Unity SDK version: 7.0.2
  * Source you installed the SDK: Unity Package Manager
  * Problematic Firebase Component: FCM
  * Other Firebase Components in use: Analytics
  * Additional SDKs you are using: Unity Ads, Unity Analytics
  * Platform you are using the Unity editor on: Windows 10
  * Platform you are targeting: Android 8, 9, 10
  * Scripting Runtime: _IL2CPP

### [REQUIRED] Please describe the issue here:

I just use Firebase in my project and receive the same errors from users (I show speical ErrorDialog on each error message handled).

#### Steps to reproduce:

Can't reproduce on test devices.

#### Relevant Code:

No.

**Comment by hippogamesunity** [comment]
FCM buffer verification failed. Failed to load FCM messages, some messages may have been dropped! This may be due to, (1) the device being out of space, (2) a crash on a previous run of the application, (3) a change in internal serialization format following an upgrade. at UnityEngine.Logger:Log(LogType, Object)

**Comment by paulinon** [comment]
Hi @hippogamesunity,

I noticed that you're using an old version of the SDK. Could you try using the latest version (7.2.0) and see if the issue persists? If it does, please provide a [minimal, reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of your project along with the detailed steps you've taken before facing the issue so that we can identify what's causing this behavior.

**Comment by hippogamesunity** [comment]
Hi! I've updated FCM and Analytics to 7.2.0 via Package Manager and still receiving Firebase related errors from users. They are not massive btw (isolated cases). This indeed may happen due to described reasons.

Detected premature end of a FCM message buffer. Failed to load FCM messages, some messages may have been dropped! This may be due to, (1) the device being out of space, (2) a crash on a previous run of the application, (3) a change in internal serialization format following an upgrade.

FCM buffer verification failed. Failed to load FCM messages, some messages may have been dropped! This may be due to, (1) the device being out of space, (2) a crash on a previous run of the application, (3) a change in internal serialization format following an upgrade.

**Comment by paulinon** [comment]
Hi @hippogamesunity,

It would be great if you could provide a minimal, reproducible example of your project so that we can try to isolate what's causing the issue. You may also try our [quickstart](https://github.com/firebase/quickstart-unity/tree/master/messaging/testapp) and see if the issue persists there. This way, we can use it as a baseline for troubleshooting.
