### ISSUE TITLE
[Question] Known issues with Android 12?

### ISSUE THREAD

**Issue by Nyankoo** [firebase/quickstart-unity#1066]
### [REQUIRED] Please fill in the following fields:

  * Unity editor version: 2020.3.9f1
  * Firebase Unity SDK version: 7.2.0
  * Source you installed the SDK: Unity Package Manager with tgz
  * Problematic Firebase Component: Unknown
  * Other Firebase Components in use: Auth, Crashlytics, Remote Config
  * Additional SDKs you are using: 
  * Platform you are using the Unity editor on: Windows
  * Platform you are targeting: Android
  * Scripting Runtime: IL2CPP

### [REQUIRED] Please describe the question here:

Are there any known issues with the latest Firebase SDKs and Android 12? We're getting user reports that our app is not loading on our splash screen, which is where we're initializing Firebase components and loading our Firestore database.

We don't have any real Android 12 devices to test this ourselves, and we sadly can't get the logcat from these users, as their devices are not rooted.

**Comment by paulinon** [comment]
Hi @Nyankoo,

Based on my understanding, it appears that you want to know if there are ongoing issues related to the Firebase SDK when using Android 12. You may redirect your question to our [Firebase Android SDK issue tracker](https://github.com/firebase/firebase-android-sdk/issues) as the Unity SDKs point to a specific build's SDK version. 

With that, I'll be closing this for now. Let me know if you have any other questions or if your issue is different from the scenario I described.
