### ISSUE TITLE
[Bug] Code is not being sent when Device fails SafetyNet Test

### ISSUE THREAD

**Issue by adityathoutam** [firebase/quickstart-unity#1103]
### [REQUIRED] Please fill in the following fields:

  * Unity editor version: 2020.3.15.f2
  * Firebase Unity SDK version: 8.1.0
  * Source you installed the SDK: unitypackage
  * Problematic Firebase Component: Auth
  * Other Firebase Components in use: Auth, Database, Storage, Messaging etc
  * Additional SDKs you are using: AppsFlyer
  * Platform you are using the Unity editor on: Mac
  * Platform you are targeting: Android
  * Scripting Runtime: IL2CPP

### [REQUIRED] Please describe the issue here:

While implementing Phone Authentication, the SMS/OTP code is not being sent to the devices if the device fails the safetyNet test

The fallback method of browser reCAPTCHA (which can only be enabled if  implementation 'androidx.browser:browser:1.3.0' is added to the mainTemplate.gradle) is not documented anywhere.

After adding it to the gradle file, the VerifyPhoneNumber method opens a custom tab and closes it automatically. Nothing happens after that, No callback is received in either Failed, Completed or CodeSent.

Also several Android methods such as 
```
FirebaseAuth.getInstance().getFirebaseAuthSettings()
   .setAppVerificationDisabledForTesting();
```
   
   are absent from the wrapper classes, making it difficult to diagnose the issue

**Comment by paulinon** [comment]
Hi @adityathoutam,

For Android builds, it's expected for phone number sign in not to proceed when your device fails Android SafetyNet as seen [here](https://firebase.google.com/docs/auth/android/phone-auth#enable-app-verification). However, you mentioned that you received no callback after the VerifyPhoneNumber method. In order to identify the cause of this, could you provide a [minimal, reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) along with the steps you've taken before facing this issue?
