### ISSUE TITLE
Where is the MessageForwardingService?

### ISSUE THREAD

**Issue by ShonnVR** [firebase/quickstart-unity#111]
I use the custom activity, but when I override onNewIntent , I couldn't found the MessageForwardingService. It's not in the reference.

**Comment by stewartmiles** [comment]
Docs are here: https://firebase.google.com/docs/cloud-messaging/cpp/client#custom_message_handling_on_android 

The MessageForwardingService isn't in the reference since it only responds to an Intent there isn't really a function level API surface.

If you're looking for the AAR / JAR to build your activity library against, it's distributed in firebase-messaging-unity.srcaar - it's actually just a plain aar - which is copied / renamed into `Plugins/Android/` when the [Android Resolver](https://github.com/googlesamples/unity-jar-resolver#android-resolver) runs so that it can be built as part of your final APK.

**Comment by stewartmiles** [comment]
@ShonnVR haven't heard from you so I'll assume your problem is resolved, please ping this issue if it isn't.
