### ISSUE TITLE
After I imported Unity-Messaging, I solved the reference problem through Android Resolver, exported to AndroidStudio, and exported to Android12apk crashed when it was first started.Restart again without crash, but with the same log.This issue only appears on Pixcel3 Android12 and I can use notifications normally.When I click unity's Build button directly, the exported APK works fine.I don't know what went wrong

### ISSUE THREAD

**Issue by 1096257226** [firebase/quickstart-unity#1128]
After I imported Unity-Messaging, I solved the reference problem through Android Resolver, exported to AndroidStudio, and exported to Android12apk crashed when it was first started.Restart again without crash, but with the same log.This issue only appears on Pixcel3 Android12 and I can use notifications normally.When I click unity's Build button directly, the exported APK works fine.I don't know what went wrong

### [REQUIRED] Please fill in the following fields:

  * Unity editor version: _____
  * Firebase Unity SDK version: _____
  * Source you installed the SDK: _____ (.unitypackage or Unity Package Manager)
  * Problematic Firebase Component: _____ (Auth, Database, etc.)
  * Other Firebase Components in use: _____ (Auth, Database, etc.)
  * Additional SDKs you are using: _____ (Facebook, AdMob, etc.)
  * Platform you are using the Unity editor on: _____ (Mac, Windows, or Linux)
  * Platform you are targeting: _____ (iOS, Android, and/or desktop)
  * Scripting Runtime: _____ (Mono, and/or IL2CPP)

**Comment by paulinon** [comment]
Hi @1096257226,

Based on the information you provided, I'm getting that you exported your Unity project to Android Studio, and the app crashed on the first try. On the second try, there were no crashes, but both tests produced the same logs. Could you confirm if I got that right?

Also, could you provide a use case for your app that requires your project to be exported to Android Studio instead of directly building from Unity?

Additionally, I'd like you to provide the versions of the Unity editor and Firebase SDK used. This way, we can identify what's causing your issue.
