### ISSUE TITLE
[Question]  How to use KeepSynced()?

### ISSUE THREAD

**Issue by shlighter** [firebase/quickstart-unity#1145]
### [REQUIRED] Please fill in the following fields:

  * Unity editor version: 2021.1.3f1
  * Firebase Unity SDK version:7.2.0
  * Source you installed the SDK: unitypackage (.unitypackage or Unity Package Manager)
  * Problematic Firebase Component: Database(Auth, Database, etc.)
  * Other Firebase Components in use: Database(Auth, Database, etc.)
  * Additional SDKs you are using: AdMob(Facebook, AdMob, etc.)
  * Platform you are using the Unity editor on: Windows(Mac, Windows, or Linux)
  * Platform you are targeting: Android(iOS, Android, and/or desktop)
  * Scripting Runtime: IL2CPP(Mono, and/or IL2CPP)

### [REQUIRED] Please describe the question here:
I use OrderByKey().EndAt(lastKey).LimitToLast(10) 
My DB is big so I use that code to only get 10 keys each time instead of the entire snapshot.
But it returns an old DataSnapshot and doesn't return new Keys unless I reset the app.
The solution is to add KeepSynced()

My question is how should I use KeepSynced()?
When I use it on the entire location- It made my app slow because I have a big DB
    DatabaseReference dtr = FirebaseDatabase.DefaultInstance.GetReference(path);
                    dtr.KeepSynced(true);
dtr.OrderByKey().EndAt(lastKey).LimitToLast(10) .GetValueAsync().ContinueWith(t => t);

or should use it as a query for every 10 items?-
  var query = dtr.OrderByKey().EndAt(lastKey).LimitToLast(10) 
                   query.KeepSynced(true);
 query.GetValueAsync().ContinueWith(t => t);

**Comment by alexames** [comment]
Take a look at the quick start app to see an example

https://github.com/firebase/quickstart-unity/blob/86f5b37cf8f643089c6302c9cb2add423cb0a5e6/database/testapp/Assets/Firebase/Sample/Database/UIHandler.cs#L74

What this does is assign a callback function to the ValueChanged listener. Whenever a value changes at that reference the database will call that callback and you can react to it however you want.

Listeners are generally the preferred way to receive updates from the database rather than polling with GetValueAsync. If, for example, the network request hangs for an indeterminate amount of time there's no way to cancel the call to GetValueAsync. Listeners are easier to add and remove and better at communicating errors.

**Comment by shlighter** [comment]
I understand that, but my app doesn't need only new values or updates.
I have a database that stores cars for sale-  I want the user to see all the cars that were posted in the last month, retrieving 10 cars each time sorted by the newest.
GetValueAsync can get what already exists in the DB and that's what I need to show the user.
A listener in that case is good for only newer posts/updates since the user's last query.
Keep synced was perfect because every time the user entered the app and clicked Search, they saw everything in the DB including new posts.

Also, isn't it the same thing- adding a listener to the entire path or using keepSynced, in terms of large local cache ?

**Comment by shlighter** [comment]
I have too many entries, sub entries and users (DB of car posts, DB for comments for a car post, DB for user's posts, DB for likes for a comment of a car post), it sounds too much to set listeners for everything. Some paths are not that important to be subscribed to, but I still want to retrieve updated values when entering there. Firebase makes it so hard for us.
Was I wrong in choosing real-time database for my app? Is firestore a better solution? It sounds so wrong to create listeners for every random path on my DB

**Comment by alexames** [comment]
Okay, I think I had my wires crossed yesterday. Yeah, since the location you're keeping synced has the relevant filters applied to it I'm not sure why that wouldn't work. The local cache should only contain the values you request, respecting the filters you're applying. 

This snippet:
```
var query = dtr.OrderByKey().EndAt(lastKey).LimitToLast(10)
query.KeepSynced(true);
query.GetValueAsync().ContinueWith(t => t);
```
Looks like it should keep just the values you care about in memory, so the cache shouldn't grow without bound. How are you profiling this to determine that the issue with the DB? It's possible that the DB isn't evicting fields that it should, but it would be good to verify with some kind of minimal example that can reproduce the issue. (unfortunately the DB's api doesn't give you good access to the internal state so it's hard to see what is actually being cached on disk and in memory)

To clarify, is this slowdown happening on a desktop platform or on a mobile device?

**Comment by shlighter** [comment]
To clarify- I use EndAt(lastKey).LimitToLast(10), meaning at first I retrieve the 10 last items, and then 10 items before that, etc... (depends how much the user scrolls down the list, I keep calling that command to get 10 more items from the DB, saving the last key)
So you recommend the second snippet? KeepSynced only a query of every 10 items? It looks kind of strange, to call KeepSynced   on every 10 items and not the entire node.

I know it's an issue with the DB, because after GetValueAsync nothing happens, no task result, nothing, but suddenly after 40 seconds it suddenly returns. It only happens with large nodes.

To be honest, it happens mostly on Desktop, but I suspect that it affects the android somehow as well not that long.
But it became impossible for me to use Unity Editor, I can't wait so long to get data, it's crazy and wasn't like that in the begining.

**Comment by paulinon** [comment]
Hi @shlighter,

The second snippet is more recommended because you're downloading less data compared to when using the first snippet.

In analyzing why retrieving your data takes too long, you may [profile your database](https://firebase.google.com/docs/database/usage/profile) using a tool built into the Firebase CLI so that you can measure its performance. It's possible that you're exceeding or getting close to the database's [limits](https://firebase.google.com/docs/database/usage/limits), so you may consider [scaling with multiple databases](https://firebase.google.com/docs/database/usage/sharding) for optimal performance.
