### ISSUE TITLE
TypeLoadException: Could not load type 'Firebase.MonoPInvokeCallbackAttribute'

### ISSUE THREAD

**Issue by MohHeader** [firebase/quickstart-unity#119]
I am receiving this error, when building to Android after adding Firebase.Messaging lib.

```
TypeLoadException: Could not load type 'Firebase.MonoPInvokeCallbackAttribute' from assembly 'Firebase.Messaging'.
System.MonoType.GetMethods (BindingFlags bindingAttr) (at /Users/builduser/buildslave/mono/build/mcs/class/corlib/System/MonoType.cs:204)
UnityEditor.Build.BuildPipelineInterfaces.InitializeBuildCallbacks (BuildCallbacks findFlags) (at /Users/builduser/buildslave/unity/build/Editor/Mono/BuildPipeline/BuildPipelineInterfaces.cs:182)
UnityEditor.BuildPlayerWindow:BuildPlayerAndRun()
```

any clues ?

Firebase SDK version 4.2.1 ( I am using Analytics, Database, Auth ) & they were working fine.
Unity version 2017.1.1p4

Thanks

**Comment by MohHeader** [comment]
Not sure where is the error,
I changed some settings and now worked, 

But now I have the 
Too many field references to fit in one dex file: 81486; max is 65536.

I think this is easy to solve by googling it :)

**Comment by MohHeader** [comment]
Was able to get it to run ( by exporting Android studio project )
anything else,, fail :(

**Comment by stewartmiles** [comment]
@MohHeader I assume the problem you've run into when trying to get your application to run is due to the dex limit for Android applications.  You need to proguard your project.  We have an experimental feature in development in the [Play Services Resolver](https://github.com/googlesamples/unity-jar-resolver) called "Gradle Prebuild" that should *eventually* help with this sort of thing.  TBH You'll run into exactly the same problem when including any non-trivial number of Android libraries in a Unity project.  I would be nice if Unity updated their build system to build with Gradle and enable proguard for internal (i.e non-export) builds.
