### ISSUE TITLE
iOS code signing team profile setting is overridden after rebuild

### ISSUE THREAD

**Issue by comtaler** [firebase/quickstart-unity#12]
The iOS project's code signing team profile setting is overwritten every time I build the iOS project with Unity. It wasn't overwritten before I add the firebase plugin.

**Comment by stewartmiles** [comment]
You're referring to the xcode setting "Target > General > Team" (
https://developer.apple.com/library/content/qa/qa1814/_index.html) ?  If so
we don't touch that option AFAIK.

Any chance you could provide an example diff that compares when using
Firebase vs. not using Firebase so that we can reproduce the problem you're
seeing?

If not, could you describe the steps you're following to run into this
issue so that we can reproduce and hopefully debug it?

Cheers,
Stewart

**Comment by comtaler** [comment]
Sorry, it was busy here to get the information you need. The team profile information is in:
Unity-iPhone.xcodeproj/project.pbxproj

The line that is reset is:
DEVELOPMENT_TEAM = <team name>

For now, we just use sed command to replace the team in our build script.

**Comment by stewartmiles** [comment]
We definitely don't mess with this property in the Xcode project but we do load / save the project after modifying it so it's possible Unity's xcodeapi is clobbering it.

Are you sure you have followed
http://answers.unity3d.com/questions/1248794/ios-build-error-devleopment-team.html ?

**Comment by comtaler** [comment]
Thanks for the link. That helped. The problem is solved now.
