### ISSUE TITLE
Did  Apple For Sign in Package Needed For   Firebase

### ISSUE THREAD

**Issue by CLOUDFIRE91** [firebase/quickstart-unity#1225]
Hi All 

   I am working in sign up with apple option from unity. When i read the  this post..

https://firebase.google.com/docs/auth/unity/apple.

In this post it mentioned 

Install a third party plugin to handle Apple sign in nonce and token generation, such as the Unity's Sign In With Apple Asset Storage Package.

https://blog.unity.com/technology/support-for-apple-sign-in

Did this package is needed to implement sign in with apple option...  

I am running on 10.3 ipad. So i cant run the above  package. It says unsupported platform...

can anyone can share the code for sign in with apple option in firebase like they gave for sign in with microsoft/yahoo like that?

i found trouble in implementing in it..

**Comment by DellaBitta** [comment]
Hi @CLOUDFIRE91,

[Apple Sign In support requires iOS 13.0 +](https://developer.apple.com/documentation/authenticationservices/asauthorizationappleidprovider?language=objc).  I'm sorry to say that if your iPad is running iOS 10 then it won't be able to support Apple Sign In.  

The errors that you're encountering with the third party plugins are probably due to the fact that the underlying iOS API surface required to generate Apple ID tokens isn't present on your device.

**Comment by CLOUDFIRE91** [comment]
@DellaBitta  Thanks For your reply...
