### ISSUE TITLE
[FR] The latest version of unity (8.9.0) IOS is not 8.14.0

### ISSUE THREAD

**Issue by China-Deng** [firebase/quickstart-unity#1258]
[IOS 8.14.0 fixes a serious problem](https://firebase.google.com/support/release-notes/ios#version_8140_-_march_22_2022)

**Comment by chkuang-g** [comment]
Since this is an Unity SDK issue, allow me to transfer this to `quickstart-unity`

Unfortunately we are not able to verify this from our end.

However, I think the chance of compatibility is pretty high due to the following reasons:
- That most of the breaking changes will be released for the Google I/O release, which is the next next release.
- There is no significant breaking changes from `8.13.0` to `8.14.0` based on [the release note](https://firebase.google.com/support/release-notes/ios#version_8140_-_march_22_2022)
- We were in the process to bump up iOS deps for the next release ([PR](https://github.com/firebase/firebase-cpp-sdk/pull/902)) and did not notice any significant incompatibility issue.

And again, since we have never tested Unity SDK `8.9.0` with iOS pods `8.14.0` before, I would recommend you to run your test after changing `Dependencies.xml`

Hope this answer your question.

**Comment by jsvitek** [comment]
Hello @jonsimantov,
when do you plan to include latest iOS Firebase 9.0.0 into the Unity Firebase SDK please?

Unity version 8.10.1 includes iOS Firebase pods 8.11.0 (not even 8.14.0). I hope I am not mistaken but I just updated the Unity SDK from 8.7.0 to 8.10.1 and iOS pods got bumped from 8.10.0 to 8.11.0

We are getting many reports that our game is freezing upon start with our current version of the Unity Firebase SDK (8.7.0) and I have my fingers crossed that the inclusion of iOS Firebase pods 9.0.0 will solve many headaches for us.
