### ISSUE TITLE
[Bug] Can't get build for iOS and android build doesn't work

### ISSUE THREAD

**Issue by IgorGalimski** [firebase/quickstart-unity#1259]
### [REQUIRED] Please fill in the following fields:

  * Unity editor version: 2020.3.20f1
  * Firebase Unity SDK version: 8.9.0
  * Source you installed the SDK: unitypackage (.unitypackage or Unity Package Manager)
  * Problematic Firebase Component: Analytics, Crashlytics, Config, Installation (Auth, Database, etc.)
  * Other Firebase Components in use: _____ (Auth, Database, etc.)
  * Additional SDKs you are using: Admob, Appsflyer (Facebook, AdMob, etc.)
  * Platform you are using the Unity editor on: Mac (Mac, Windows, or Linux)
  * Platform you are targeting: iOS, Android (iOS, Android, and/or desktop)
  * Scripting Runtime: IL2CPP (Mono, and/or IL2CPP)

### [REQUIRED] Please describe the issue here:

We are updating from 8.8.0 to 8.9.0
We use packages Analytics, Config, Crashlitics, Installation
After I import all these packages into new project - I saw this compile error
<img width="350" alt="Screenshot 2022-04-21 at 13 04 36" src="https://user-images.githubusercontent.com/19680568/164433957-a8cea9e5-88aa-4e73-a59e-7304bf931ad3.png">

I tried to ignore it and try to build for iOS. But I couldn't do it, because of this errors

<img width="467" alt="Screenshot 2022-04-21 at 13 12 48" src="https://user-images.githubusercontent.com/19680568/164434044-02e52f4e-c04d-4e27-a9d7-2bc87462b6ed.png">
<img width="441" alt="Screenshot 2022-04-21 at 13 12 58" src="https://user-images.githubusercontent.com/19680568/164434049-fe12b8a8-9d41-4634-8d82-24b4e079e642.png">

After this I tried to build for Android, and I could do it. But when I stated an app - it says error connecting to the server. But Wifi is working and also the previous version(8.8.0) works fine
![Screenshot_20220701-123649_Block Puzzle Blast](https://user-images.githubusercontent.com/19680568/164434224-3bd7eaa4-96a5-484c-afc0-671be7c8fb49.jpg)

**Comment by chkuang-g** [comment]
If you saw `Unable to resolve reference 'Google.VersionHandlerImpl'`, that means the entire EDM4U is not workin properly in your project.  And EDM4U is actually the main component to add iOS and Android dependencies used by Firebase.

However, `Unable to resolve reference 'Google.VersionHandlerImpl'` is pretty common when you upgrade Firebase, which includes newer version of EDM4U, since those libraries will be disabled for a couple of frames before being re-enable again.

Let's see if EDM4U is really not working.
1. Please take a look of menu item `Assets > External Dependency Manager` and see if this menu item exist.
2. Click on `Assets > External Dependency Manager > Version Handler > Settings`.  See if you can find the version on the top.  It should look like `Version Handler (version x.x.x)`.  Firebase `8.9.0` includes EDM4U `1.2.170`. Therefore, you should see `1.2.170` here.
3. See if you can find the following files under `Assets` folder
   ```
   Assets/ExternalDependencyManager/Editor/1.2.170/Google.IOSResolver.dll
   Assets/ExternalDependencyManager/Editor/1.2.170/Google.JarResolver.dll
   Assets/ExternalDependencyManager/Editor/1.2.170/Google.VersionHandlerImpl.dll
   ```
  If so, click on it and see they are enabled for `Editor` platform.

If either one of the steps above is not true, it is possible that the EDM4U in your project is messed up.

A quick way to resolve this is to remove `Assets/ExternalDependencyManager` folder and reinstall it.
You can download the latest version [here](https://developers.google.com/unity/packages#tools).

Let me know if this helps.

**Comment by equizo** [comment]
hi there, is there any solution for iOS?
![photo_2022-05-11_13-45-49](https://user-images.githubusercontent.com/6953056/167832141-5f205d2e-8455-4e1f-a169-e87da4090b35.jpg)
?

**Comment by IgorGalimski** [comment]
@equizo 
Try the latest version, it works well for me
