### ISSUE TITLE
Targeting iOS version numbers requires upgrading to SDK version 6.24.0 or later

### ISSUE THREAD

**Issue by p0w1nd** [firebase/quickstart-unity#1283]
I want to set a remote config value based on App Version condition. However, I'm encountering this error:

<img width="821" alt="Screen Shot 2022-06-01 at 11 37 15" src="https://user-images.githubusercontent.com/14937764/171328727-a48fcaa6-7ac2-474c-b8b0-06c39bd9a908.png">

Unity 2020.3.34f1
Firebase 9.0.0
XCode 13.4

**Comment by paulinon** [comment]
Hi @p0w1nd,

It looks like you're trying to create a Remote Config experiment using the console. When performing the experiment, make sure your Apple app is using Firebase Apple platforms SDK version 6.24.0 or above, as `CFBundleShortVersionString` is not being sent in earlier versions. You may refer to our [documentation](https://firebase.google.com/docs/remote-config/parameters) for more information.

I'll be closing this for now. If an issue arises with your experiment, please reach out to [Firebase Support](https://firebase.google.com/support) so that one of our agents can assist you.

**Comment by p0w1nd** [comment]
> It looks like you're trying to create a Remote Config experiment using the console.

Actually I was creating Conditional value, not Experiment:

<img width="300" alt="Screen Shot 2022-06-06 at 16 04 06" src="https://user-images.githubusercontent.com/14937764/172146683-5e048c6c-6f09-4e8f-bf6f-e712077c7a50.png">
