### ISSUE TITLE
java.lang.UnsatisfiedLinkError on CppStorageListener

### ISSUE THREAD

**Issue by gclaret** [firebase/quickstart-unity#1322]
We started seeing this error on our Unity game.
We tried updating firebase libraries to the latest (10.4.0), and it's still happening.
We cannot reproduce it locally, but see it when we do a live push of our app.

[REQUIRED] Please fill in the following fields:

Unity editor version: 2021.3.13f1
Firebase Unity SDK version: 10.4.0 (but was also happening in 9.x)
Source you installed the SDK: .unitypackage
Problematic Firebase Component: storage
Other Firebase Components in use: auth, messaging, firestore
Additional SDKs you are using: Applovin, singular
Platform you are using the Unity editor on: Mac
Platform you are targeting: Android
Scripting Runtime: IL2CPP

<img width="1226" alt="image" src="https://user-images.githubusercontent.com/2690945/218081083-4cb30375-fb68-41bc-83b7-a6bd69bab217.png">

**Comment by chkuang-g** [comment]
Could you provide snippet of code about how you use Storage APIs?

The implementation of `nativeCallback` should be here and is pretty fundamental to Storage API. The implementation should be this
https://github.com/firebase/firebase-cpp-sdk/blob/8f3e19226639a3b91e5d879cdf5f3d867dbf8db4/storage/src/android/controller_android.cc#L227

We did not see this issue from our daily testapp. Therefore we would like to learn more about your situation.

Ex.
- Since you cannot repro locally, could you describe how you get this callstack?
- Is there certain device having this issue?
- Can you find any patterns?

Thank you!
