### ISSUE TITLE
The custom token format is incorrect. Please check the documentation.

### ISSUE THREAD

**Issue by criistii** [firebase/quickstart-unity#139]
Hi,

I am trying to use the .SignInWithCustomTokenAsync(token) function to re-authenticate the user. This works without an issue in the Editor and on iOS, but I am getting the following exception on Android:
"The custom token format is incorrect. Please check the documentation."

Please note that SignInWithEmailAndPasswordAsync(email, password) works as intended. After the authentication, I am using .TokenAsync(false). This is the token I am using.

Please advice,
Thanks

**Comment by stewartmiles** [comment]
@criistii could you share the code you're using here?

BTW: In the editor there is no auth implementation, it's just a stub so if it *works* it's because it's just ignoring the token and pretending the login is successful.

**Comment by stewartmiles** [comment]
It sounds like you're using TokenAsync() caching the token and trying to sign in again with the cached token.  That isn't going to work as the intended use case for the user token is to generate a custom token generated on your own authentication server, see https://firebase.google.com/docs/auth/unity/custom-auth for more details.  If you want to refresh the credentials of a logged in user, instead - since logins are persistent - you can request a refreshed token for the currently logged in user when the app starts.

**Comment by criistii** [comment]
Thanks for clearing this up. I was under the impression the authentication is not persistent and that I need to re-authenticate each time I start the app.
