### ISSUE TITLE
DllNotFoundException: App Error on Android Device

### ISSUE THREAD

**Issue by Oni22** [firebase/quickstart-unity#143]
hey :)
I'm using the FirebaseAnalytics plugin for unity and I got this error message.: 

DllNotFoundException: App
03-14 19:12:21.159 12740 12759 E Unity   :   at (wrapper managed-to-native) Firebase.AppUtilPINVOKE/SWIGExceptionHelper:SWIGRegisterExceptionCallbacks_AppUtil (Firebase.AppUtilPINVOKE/SWIGExceptionHelper/ExceptionDelegate,Firebase.AppUtilPINVOKE/SWIGExceptionHelper/ExceptionDelegate,Firebase.AppUtilPINVOKE/SWIGExceptionHelper/ExceptionDelegate,Firebase.AppUtilPINVOKE/SWIGExceptionHelper/ExceptionDelegate,Firebase.AppUtilPINVOKE/SWIGExceptionHelper/ExceptionDelegate,Firebase.AppUtilPINVOKE/SWIGExceptionHelper/ExceptionDelegate,Firebase.AppUtilPINVOKE/SWIGExceptionHelper/ExceptionDelegate,Firebase.AppUtilPINVOKE/SWIGExceptionHelper/ExceptionDelegate,Firebase.AppUtilPINVOKE/SWIGExceptionHelper/ExceptionDelegate,Firebase.AppUtilPINVOKE/SWIGExceptionHelper/ExceptionDelegate,Firebase.AppUtilPINVOKE/SWIGExceptionHelper/ExceptionDelegate)

I build the game and test it on an android device. I got this error while running the app and see it in the android logcat console. So in the start function in unity I'm running the firebase code and at this point the game stucks and throws this error

**Comment by stewartmiles** [comment]
@Oni22 for future reference, it would be great to point out when you cross post an issue.
This is cross posted here https://stackoverflow.com/questions/49285840/firebase-unity-error-dllnotfoundexception-app

We (like many other plugins) use the Android Resolver to download and incorporate Android library dependencies:
https://github.com/googlesamples/unity-jar-resolver#auto-resolution

From my response to https://github.com/firebase/quickstart-unity/issues/53

"
Perhaps you have no AAR files in your project under Plugins/Android?

You may have disabled the Android Resolver which would add the AAR dependencies for you. You can enable the Android Resolver from the menu under

`Assets --> Play Services Resolver--> Android --> Settings`
Then check `Enable Background Resolution`

Finally, since resolution was probably disabled run it manually using the
`Assets --> Play Services Resolver--> Android --> Force Resolve` menu option
"

Cheers,
Stewart

**Comment by Oni22** [comment]
Okey, I will pay attention :)

So but the problem is I cant find this option "Enable Background Resolution" and I installed the newest Playe Service Resolver...

![aaaaaaaaaaaaaaaaaaa](https://user-images.githubusercontent.com/17254331/37545313-bf5c1bc0-2968-11e8-9d02-a7157722b4ab.PNG)

This is my Path
Assets --> Play Services Resolver--> Android Resolver --> Settings

**Comment by stewartmiles** [comment]
'Enable Background Resolution' was renamed to 'Enable Auto-Resolution' looks like you have it checked.

**Comment by Oni22** [comment]
Oh okey and I do Force Resolve but nothing changed

**Comment by Oni22** [comment]
I'm using Unity 2017.3.1f1 and JDK 8u162, android sdk is up to date

**Comment by stewartmiles** [comment]
Which architecture are you building for?

What is in your Plugins/Android/ directory?

**Comment by Oni22** [comment]
![ssss](https://user-images.githubusercontent.com/17254331/37545650-df059c98-2969-11e8-9f78-fbcf150a1798.PNG)

for android

**Comment by Oni22** [comment]
I guess there missing files how you said

**Comment by stewartmiles** [comment]
Is the Android Resolver failing?  Did you check the console for error messages?

You've shared a screenshot of the folder view, it should contains a load of files / folders like com.google.firebase.* etc.

**Comment by Oni22** [comment]
Yeah i know. So after I clicked on Force Resolve this window appears:

![eeeeeeeee](https://user-images.githubusercontent.com/17254331/37546549-93146d4c-296d-11e8-9b04-22eaaaf43123.PNG)

I  hit yes but after that this error appears:

![wwwwwwwwwwww](https://user-images.githubusercontent.com/17254331/37546559-a1ab6720-296d-11e8-8f1e-506194a7d895.PNG)

**Comment by Oni22** [comment]
and I got "Gradle failed to fetch dependencies" error in the unity console

**Comment by stewartmiles** [comment]
Any chance you could share your Unity.log file?  It sounds like a bug in the resolver that we just happen to be looking at right now.

**Comment by stewartmiles** [comment]
Ok we resolved an issue with the Android Resolver, you can give this a try https://github.com/googlesamples/unity-jar-resolver/blob/master/play-services-resolver-1.2.64.0.unitypackage

**Comment by Oni22** [comment]
Hmm same issue. I got the same error windows as I showed you in the previous post of me. So here is my editor log file:
[Editor.log](https://github.com/firebase/quickstart-unity/files/1821438/Editor.log)

Meanwhile I tested if the issue appears on another machine but nothing of them. On another machine the plugin imports all files and folder. I thought my android  sdk or something like that is broken but after reinstall of all components nothing changed.

**Comment by Oni22** [comment]
Here the Error from the console:


Gradle failed to fetch dependencies.

Failed to run 'C:\Users\On\Desktop\TEEEST\Test\Temp\PlayServicesResolverGradle\gradlew.bat -b "C:\Users\On\Desktop\TEEEST\Test\Temp\PlayServicesResolverGradle\PlayServicesResolver.scripts.download_artifacts.gradle" --daemon "-PANDROID_HOME=C:/Users/On/AppData/Local/Android/Sdk" "-PTARGET_DIR=C:\Users\On\Desktop\TEEEST\Test\Assets\Plugins\Android" "-PMAVEN_REPOS=" "-PPACKAGES_TO_COPY="'
stdout:
Starting a Gradle Daemon (subsequent builds will be faster)

stderr:

FAILURE: Build failed with an exception.

* What went wrong:
Unable to start the daemon process.
This problem might be caused by incorrect configuration of the daemon.
For example, an unrecognized jvm option is used.
Please refer to the user guide chapter on the daemon at https://docs.gradle.org/4.2.1/userguide/gradle_daemon.html
Please read the following process output to find out more:
-----------------------

FAILURE: Build failed with an exception.

* What went wrong:
Could not create service of type ClassLoaderRegistry using GlobalScopeServices.createClassLoaderRegistry().

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

* Get more help at https://help.gradle.org


* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

* Get more help at https://help.gradle.org

exit code: 1

UnityEngine.Debug:LogError(Object)
Google.Logger:Log(String, LogLevel)
GooglePlayServices.PlayServicesResolver:Log(String, LogLevel)
GooglePlayServices.<GradleResolution>c__AnonStorey14:<>m__1F(Result)
GooglePlayServices.<GradleResolution>c__AnonStorey15:<>m__28()
GooglePlayServices.PlayServicesResolver:PumpUpdateQueue()
UnityEditor.EditorApplication:Internal_CallUpdateFunctions()

**Comment by stewartmiles** [comment]
@Oni22 is it possible you have any anti-virus software or anything else on your machine that is preventing Gradle from executing?
If you manually run the command that is failing from the command line does it work?

**Comment by Oni22** [comment]
I tested both but no change.

**Comment by Oni22** [comment]
I reinstall JDK and Android SDK but nothing changed this is very strange

**Comment by stewartmiles** [comment]
@Oni22 when you mention you tested both, what do you mean?  Did you try running Gradle from the command line (you'll need to keep Unity open so that it doesn't delete the Temp directory) ?

Have you reproduced this on another machine?

Is there anything you can share regarding your OS version or anything else installed on your machine that may be causing this to fail?  It's certainly very strange that it simply can't run Gradle.  Is the machine not connected to the internet, if so the Gradle wrapper (which bootstraps Gradle) won't be able to fetch Gradle or download the Android dependencies.

**Comment by Oni22** [comment]
Yes I run gradle from command line while Unity was open. I import the package on another machine but there was everything ok. On the other machine my app works well after building. So no I couldn't reproduce this on another machine. My internet works. On my machine unity always trys to import the m2repository and after that it fails. On the other machine nothing of this happened.

Im using:
-Windows 10 Version 1709 Pro
- JDK 8u162
- Latest Android SDK all compnents are up to date
- Unity 2017.3.1f1

**Comment by stewartmiles** [comment]
I had a quick Google on this since it's related more to Gradle than our use of it...

https://www.minecraftforum.net/forums/mapping-and-modding-java-edition/minecraft-mods/modification-development/2881869-could-not-create-service-of-type

Thread ends on a solution here:
https://stackoverflow.com/questions/30840526/gradle-could-not-create-service-of-type-initscripthandler-using-buildscopeservic

**Comment by Oni22** [comment]
nothing helps still same error...

**Comment by vratislavino** [comment]
Hello, I've got the same problem. Is there anything new? I've read [this](https://github.com/firebase/quickstart-unity/issues/134)  and there i found that this error is because of missing (C/C++) .so files. Where are these files located? I've seen a lot of .arr libs, even .pom and .srcaar, but no .so.

Build will proceed without errors, but when I start application and try to use anything from Firebase (like FirebaseStorage or FirebaseDatabase), the error from original question will apear (even with library version so: 
`DllNotFoundException: App-4.5.2`
I attach full error
![image](https://user-images.githubusercontent.com/9168663/39428142-a4a47bec-4c86-11e8-8881-ff22bcfeb897.png)

Thanks in advance, guys

**Comment by stewartmiles** [comment]
@vratislavino it sounds like you didn't run the [Android Resolver](https://github.com/googlesamples/unity-jar-resolver#android-resolver) (by default it runs automatically) to pull the Android components required by Firebase into your build.  The .so files for Android are in the *.srcaar files that are distributed as part of the plugin.

@Oni22 I suggest opening up a ticket with support https://firebase.google.com/support/ where you can have someone debug this with you.

**Comment by stewartmiles** [comment]
Haven't heard from anyone on this in a while, I'll assume you solved the issue, closing this out.

**Comment by ctykaya** [comment]
Hello @stewartmiles I am struggling with the same problem in Firebase SDK 5.5.0. I read all your answers but nothing help. I am using latest GPS and AdMob services in my game.  Pass through all the step in firebase.com. Can you help ?

**Comment by alexames** [comment]
Can you open a new issue and give some more detail on what steps you took? Have you tried reproducing the issue in the quickstart testapp? If you can get the quickstart working, we can start drilling down into what might be wrong in your app.
