### ISSUE TITLE
SignInAnonymouslyAsync don't work after user been created.

### ISSUE THREAD

**Issue by rami-diwip** [firebase/quickstart-unity#16]
`auth.SignInAnonymouslyAsync().ContinueWith(HandleSigninResult);` 
after the first anonymous sign in new user is created in Firebase console.
when trying to signin again `HandleSigninResult` is not being called. 
only after signout `HandleSigninResult is called but creating new user in console.

**Comment by stewartmiles** [comment]
Are you seeing this on iOS or Android?  Any chance you could share an example of this, preferably by modifying our auth sample?

**Comment by stewartmiles** [comment]
Are you trying to sign in twice with the same app?

**Comment by stewartmiles** [comment]
I believed we fixed the issue of user sign-in persistence in our 1.1.0 release.  If a user signs in anonymously - and they don't sign out - relaunching the application should result in the user continuing to be signed in.  Could you verify?

**Comment by stewartmiles** [comment]
We finally got a chance to debug this issue and it turns out that on Android we had a problem where if an async operation completes immediately it would never call the task completion handler.

The workaround for the moment - which I'm sure you're already doing - is to check to see whether the user is already signed in and not sign in if they are. 

We'll have a fix out in our next release.

**Comment by stewartmiles** [comment]
This should be resolved in version 1.1.1
https://firebase.google.com/support/release-notes/unity#1.1.1
