### ISSUE TITLE
Why Can't We Run Multiple Dependent Transactions?

### ISSUE THREAD

**Issue by exzizt** [firebase/quickstart-unity#198]
**What I want to do**: Have a group of transactions be atomic. That is, if at least one in the group fails, all of the transactions fail (the transaction succeeds only if all of the transactions in the group succeed).

**Why I need it**: I want users to be able to buy cosmetics with in-game currency. As you can make out, there are two dependent transactions here:
1. Transaction to subtract the cost of the item from the user's available currency.
2. Transaction to update that the user now owns this item.

**How I am doing it**:
```
// (This is inside the method where the user selects to buy a certain cosmetic.)
// Pay for the cosmetic.
DataManager.ModifyCoinsBy(-cosmetic.Cost, task =>
{
    // Payment was not successful.
    if (task.Exception != null || task.IsCanceled || task.IsFaulted)
    {
    	// Notify user of reason.
    }

    // Payment was successful.
    else
    {
    	// Register the user as now owning this new cosmetic.
    	// NOTE: This is the problem. What if this transaction fails? We took the user's payment
    	// without successfully registering their newly owned cosmetic item.
        DataManager.AddNewOwnedCosmeticId(cosmetic.Id);
    }
});

// Modifies the user's coins by amount and runs continueWith when the modification has completed.
internal static void ModifyCoinsBy(int amount, Action<Task<DataSnapshot>> continueWith = null)
{
    coinsReference.RunTransaction(data =>
    {
        if (Convert.ToInt32(data.Value) + amount >= 0)
        {
            data.Value = Convert.ToInt32(data.Value) + amount;
            return TransactionResult.Success(data);
        }
        return TransactionResult.Abort();
    }).ContinueWith(continueWith);
}

// Adds a new owned cosmetic ID to the user's list of owned cosmetic IDs.
internal static void AddNewOwnedCosmeticId(int id, Action<Task<DataSnapshot>> continueWith = null)
{
    ownedCosmeticIdsReference.RunTransaction(data =>
    {
        List<object> currentlyOwnedCosmeticIds = data.Value as List<object>;
        if (currentlyOwnedCosmeticIds == null)
        {
            data.Value = new List<int> { id };
        }
        else
        {
            currentlyOwnedCosmeticIds.Add(id);
            data.Value = currentlyOwnedCosmeticIds;
        }
        return TransactionResult.Success(data);
    }).ContinueWith(continueWith);
}
```

**Picture of my Firebase database**:

![image](https://user-images.githubusercontent.com/17113094/44305166-fbe4e680-a325-11e8-8597-354144bdc42a.png)

Any help is appreciated! Is there any way to do this properly as I've described above? I've searched high and low.

**Comment by exzizt** [comment]
I think I've solved my own problem. Why didn't I realize I could just do this!

```
internal static void PurchaseCosmeticItem(int cosmeticPrice, int cosmeticID, Action<Task<DataSnapshot>> continueWith = null)
{
    // Run the transaction to modify the user's coins.
    coinsReference.RunTransaction(currentCoinsData =>
    {
        // If the user can afford this cosmetic.
        if (Convert.ToInt32(currentCoinsData.Value) + cosmeticPrice >= 0)
        {
            // Modify their coins accordingly.
            currentCoinsData.Value = Convert.ToInt32(currentCoinsData.Value) + cosmeticPrice;

            // Now run the transaction to modify that they now own this cosmetic.
            Task<DataSnapshot> task = ownedCosmeticIdsReference.RunTransaction(currentOwnedCosmeticIdsData =>
            {
                // Get the user's currently owned cosmetic IDs.
                List<object> currentOwnedCosmeticIds = currentOwnedCosmeticIdsData.Value as List<object>;

                // This is the first cosmetic they've purchased.
                if (currentOwnedCosmeticIds == null)
                {
                    currentOwnedCosmeticIdsData.Value = new List<int> { cosmeticID };
                }
                else
                {
                    // Abort if the user already owns this cosmetic (this shouldn't ever happen!).
                    if (currentOwnedCosmeticIds.Contains(cosmeticID))
                    {
                        return TransactionResult.Abort();
                    }

                    // They now own this cosmetic.
                    currentOwnedCosmeticIds.Add(cosmeticID);
                    currentOwnedCosmeticIdsData.Value = currentOwnedCosmeticIds;
                }
                return TransactionResult.Success(currentOwnedCosmeticIdsData);
            });

            // If adding the new cosmetic ID failed, make the transaction to modify their coins fail as well.
            if (task.Exception != null || task.IsCanceled || task.IsFaulted)
            {
                return TransactionResult.Abort();
            }

            // The transaction to modify the user's coins and add their newly owned cosmetic item succeeded!
            return TransactionResult.Success(currentCoinsData);
        }

        // The user could not afford the cosmetic.
        return TransactionResult.Abort();

    }).ContinueWith(continueWith);
}
```

Let me know if this is _good_! 😁

**Comment by chkuang-g** [comment]
Regarding to your solution, I don't think it will work because you have to wait until the nested transaction is done before you evaluate **task.Exception**, **task.IsCanceled** and **task.IsFaulted**.  However, you can chain the second transaction using the ContinueWith() from the first transaction.  This would not allow you to abort the first transaction but I will explain how you can do it later.

Also, if you are using Unity 2017+, and your app works well with .NET 4.6, I would recommend you to utilize **await**, which would make your chain of transaction looks cleaner.
https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/keywords/await

I do not know anyway to abort one transaction when another one fails.  However, you can use a third transaction to credit the balance back if the second one fails.  You can chain it with ContinueWith() or use await for cleaner code.

Another consideration is: what is the scenario that it fails to grant cosmetic?  You may not even need a transaction to grand the cosmetic. 
- You can use ownedCosmeticIdsReference.Push().SetValue() to add your cosmetic id to the list with auto-generated key, which is a combination of server time and a random key.
  https://firebase.google.com/docs/reference/unity/class/firebase/database/database-reference#class_firebase_1_1_database_1_1_database_reference_1a0eb02bbcb15c6ac458a1a4240a25e1af
- You can use the cosmetic id as the key and quantity as value (1 for example).  If you are expecting single client scenario, or no consumable , SetValue() should be sufficient. Otherwise, you may still need to use transaction, but in smaller scale.

In addition, you may consider to use Firebase Function for slightly complicated transaction like this.
https://firebase.google.com/docs/reference/unity/namespace/firebase/functions
You may still need to use RunTransactoin() in the Function, depending on your case, however, it has some benefits.
- It is generally a better practice to have the server to handle currency and entitlement.  You can control the client to only able to write to certain part of the database through Firebase Function and only allow the client to read data.  
- Simpler client side code.  Only one request/response should handle multiple transactions.
- Able to extend on the server side.  Ex. add more validation without pushing new client, add real-money transaction.

Shawn

**Comment by exzizt** [comment]
@chkuang-g 

> Regarding to your solution, I don't think it will work because you have to wait until the nested transaction is done before you evaluate task.Exception, task.IsCanceled and task.IsFaulted.
That is precisely what I want to do, though. I want to wait for the nested transaction to finish before I evaluate those. Also, it works great! 😉 

> I do not know anyway to abort one transaction when another one fails. However, you can use a third transaction to credit the balance back if the second one fails. You can chain it with ContinueWith() or use await for cleaner code.
This method would only add to the current problem. _What if this third transaction fails?..._
Also, a way to "abort one transaction when another one fails" is in my solution.

_In addition, you may consider to use Firebase Function for slightly complicated transaction like this._
I've been looking into Firebase Cloud Functions for other parts of my project. Thanks. 😄

**Comment by exzizt** [comment]
Closed until I guess my "solution" is shown to not work.
