### ISSUE TITLE
Firebase initialisation problem 

### ISSUE THREAD

**Issue by cemozturk** [firebase/quickstart-unity#2]
Hi,

In your papers, you said just put the GoogleService-Info.plist file at proper location and call for desired functions to initalize the Firebase connection and play with it.

When i tried 

		Firebase.Messaging.FirebaseMessaging.TokenReceived += OnTokenReceived;
		Firebase.Messaging.FirebaseMessaging.MessageReceived += OnMessageReceived;

it says,

The project's Bundle ID is inconsistent with either the Bundle ID in 'GoogleService-Info.plist', or the Bundle ID in the options if you are using a customized options. To ensure that everything can be configured correctly, you may need to make the Bundle IDs consistent. To continue with this plist file, you may change your app's bundle identifier to '__FIRAPP_DEFAULT'. Or you can download a new configuration file that matches your bundle identifier from https://console.firebase.google.com/ and replace the current one.

I debugged the logs and saw that your initalizing process is not waiting for Firebase to fully init. (  reading google-plist file, connecting to FCM etc.. ) 

When i wait for 10 seconds and trigger Firebase.Messaging.FirebaseMessaging.TokenReceived, i can get the token.

Please give us a proper create/build/init function with proper result delegate.

**Comment by stewartmiles** [comment]
The error about the inconsistent bundle ID does not affect the behavior of Firebase Messaging, though it's a bug we're working on fixing right now, see https://groups.google.com/d/msg/firebase-talk/HXSy9IIPEVY/_GT12d39CQAJ .

If I understand you correctly, the delay you see a consistent regarding the reception of the registration token?  Since this is an asynchronous process that depends upon network conditions you're not guaranteed to receive a token immediately after startup.

Also, are you able to reproduce this problem with our sample application?

Cheers,
Stewart

**Comment by stewartmiles** [comment]
I'm pleased to announce that we released:

- Firebase C++ SDK 2.1.0 (release notes [here](https://firebase.google.com/support/release-notes/cpp-relnotes#2.1.0), download [here](https://firebase.google.com/docs/cpp/setup))
- Firebase Unity SDK 1.1.0 (release notes [here](https://firebase.google.com/support/release-notes/unity#1.1.0), download [here](https://firebase.google.com/docs/unity/setup))

I believe this should resolve your issue.  If not, please let us know and we'll take a look.

Cheers,
Stewart
