### ISSUE TITLE
Cannot call Functions on localhost

### ISSUE THREAD

**Issue by rusitschka** [firebase/quickstart-unity#218]
Using Unity SDK 5.2.1 during development I'm running my Firebase Functions on localhost via

`firebase serve`

I couldn't figure out a way to call these functions when running my app in Unity Editor. There is no config setting, e.g. in AppOptions to specify the local Functions URL. It always seems to be generated from AppOptions.ProjectId, e.g. ProjectID=mydevapp results in https://us-central1-mydevapp.cloudfunctions.net/addMessage

Is there a way to change this behavior so http://localhost:5000/mydevapp/us-central1/addMessage is called?

**Comment by bklimt** [comment]
Hi @rusitschka. Thank you for bringing this to our attention. This is a feature that is available in our other SDKs, but was missing in Unity. We should be able to add it in an upcoming version of our Unity SDK.

**Comment by stewartmiles** [comment]
This is fixed in release 5.3.1.
https://firebase.google.com/support/release-notes/unity#5.3.1

We have some commented out sample code that demonstrates using the emulator here:
https://github.com/firebase/quickstart-unity/blob/fe63718246942a212554e8a0a46fb76140753b3b/functions/testapp/Assets/Firebase/Sample/Functions/UIHandler.cs#L56

**Comment by rusitschka** [comment]
https://firebase.google.com/docs/unity/setup still points to 5.3.0 - is it not yet updated or did you pull 5.3.1?
