### ISSUE TITLE
Authentication and Database dont work together

### ISSUE THREAD

**Issue by Whenami** [firebase/quickstart-unity#220]
Hi folks, I hava a problem and need your help.

I am making a school app and firebase auth and database works well together on pc but when i get 
android build in unity and run app,nothing happens.

They works perfectly  when i seperate them and run one by one on my android phone.I can sign up a new account.I can sign in while only auth api is in the project or i can get every data via Firebase  while only database api is in the project but when i get them together and run ,nothing happens.

Do you have any suggestion ? i will be very appreciated if you guys help me.
Thanks

Unity 2018
Firebase 5.2.1

**Comment by chkuang-g** [comment]
Hi @Whenami 

That is odd.  I did some test with 5.2.1 in Unity 2018 but I cannot reproduce the problem you described.
I was using Unity 2018.1.5f1 and [Unity TestApp](https://github.com/firebase/quickstart-unity/tree/master/database/testapp).

Couple of questions
- What do you mean by "nothing happens"?  Does it mean the app just froze?  Or both your sign-in attempt and fetching data from database failed?
- Which Unity 2018 version are you using?
- Do you have a chance to use "adb logcat" to see if any exception or crash happened?
- Could you try the TestApp and see if this works on your device?

Shawn

**Comment by Whenami** [comment]
- No man it doesnt freeze.For example, when i try to verify the mail adress which was stored in Firebase before and press Login button,it says Connection Succesful or wrong mail pattern or password is wrong.Everything seems fine.The problem begins actually when i install Database API over Auth API or vice versa.Press Login button and it says absolutely nothing.I think Firebase functions,somehow, dont work 
![firebaseauthenticationsignin](https://user-images.githubusercontent.com/43493064/46395162-2cc18500-c6f4-11e8-8241-6ba046cf03b4.png)

-Unity 2018.2.9f1
-Logcat says "FirebaseInstanceId: Failed to start service while in background: java.lang.IllegalStateException"

-Yes i did,it works well on my pc ,the problem occurs only android builds

Android Build(Only Auth Service) is ok
Android Build(Only Database Service) is ok
Android Build(Auth + Database Services ) Not ok

**Comment by chkuang-g** [comment]
Hi @Whenami 

I am truly sorry for your experience.  However, I cannot reproduce the problem from my side, and I would need a bit help from you.

I do not think InstanceId is relevant to the issue here.  Please do see if there is any auth related errors.  

Also it would be very helpful if you can reproduce the same issue using our [Unity TestApp](https://github.com/firebase/quickstart-unity/tree/master/database/testapp).  Here are steps to start with.
- Download the Testapp.
- Place google-services.json under Assets/ folder.
- Import only FirebaseDatabase.unitypackage from Firebase SDK 5.2.1
- Build and run on your Android device.
- You can modify UIHandler.cs like the following and see if anything fails during authentication. 

```
  Firebase.Auth.FirebaseAuth auth;

  // Initialize the Firebase database:
  protected virtual void InitializeFirebase() {
    FirebaseApp app = FirebaseApp.DefaultInstance;
    // NOTE: You'll need to replace this url with your Firebase App's database
    // path in order for the database connection to work correctly in editor.
    app.SetEditorDatabaseUrl("https://replace-with-your-project.firebaseio.com/");
    if (app.Options.DatabaseUrl != null) app.SetEditorDatabaseUrl(app.Options.DatabaseUrl);

    auth = Firebase.Auth.FirebaseAuth.DefaultInstance;
    // // NOTE: Create the hardcoded account on the console first!!!
    // auth.SignInWithEmailAndPasswordAsync("some@email.com", "p@ssw0rd").ContinueWith(task => {
    //   if (task.IsCanceled) {
    //     Debug.LogError("SignInWithEmailAndPasswordAsync was canceled.");
    //     return;
    //   }
    //   if (task.IsFaulted) {
    //     Debug.LogError("SignInWithEmailAndPasswordAsync encountered an error: " + task.Exception);
    //     return;
    //   }
    //   Firebase.Auth.FirebaseUser newUser = task.Result;
    //   Debug.LogFormat("User signed in successfully: {0} ({1})",
    //       newUser.DisplayName, newUser.UserId);
    //   StartListener();
    // });

    auth.SignInAnonymouslyAsync().ContinueWith(task => {
      if (task.IsCanceled) {
        Debug.LogError("SignInAnonymouslyAsync was canceled.");
        return;
      }
      if (task.IsFaulted) {
        Debug.LogError("SignInAnonymouslyAsync encountered an error: " + task.Exception);
        return;
      }
      Firebase.Auth.FirebaseUser newUser = task.Result;
      Debug.LogFormat("User signed in successfully: {0} ({1})",
          newUser.DisplayName, newUser.UserId);
      StartListener();
    });
  }
```  

Also, I like to learn a bit more about your WebSocket Exception problem.  
- Does it happen in both Editor and Android build?  Also, what is the OS of your desktop?
- May I learn a bit about your network environment?  Ex.  are you using the router from the provider or a customized one?  Is there any special setting like proxy on your router?  Which company is your ISP?

Thank you
Shawn

**Comment by Whenami** [comment]
chkuang-g thank you for your answer but couldnt solve it.Btw i found the problem 
![error](https://user-images.githubusercontent.com/43493064/46496021-9a1e0480-c81f-11e8-94c6-09c0f29b62ed.png)

A

**Comment by Whenami** [comment]
Guys i solved the problem.Now i am working on Websocket Exception Problem.Thanks for your supports.
You can close the issue.
