### ISSUE TITLE
firebase removes AndroidManifest.xml changes 

### ISSUE THREAD

**Issue by FaiyazMdAbdul** [firebase/quickstart-unity#249]
firebase removes AndroidManifest.xml changes like camera,  location permissions and third-party provider details.

**Comment by stewartmiles** [comment]
@FaiyazMdAbdul I'm fairly sure it doesn't remove changes.  Firebase Cloud Messaging ships with its own manifest since we need to override the default activity.  If you want to customize the manifest you're free to do so, see https://firebase.google.com/docs/cloud-messaging/unity/client#configuring_an_android_entry_point_activity
