### ISSUE TITLE
Automatic login when launching app again

### ISSUE THREAD

**Issue by ColorTwist** [firebase/quickstart-unity#266]
After the user quit the app and returns back, i want the app to automatically Sign-in to the last Credential for email/password authentication.

If i execute the Firebase email Sign-In authentication method it will work by placing email/password, however it means the email and password are saved locally in app or in database.

Is this the correct method?

**Comment by chkuang-g** [comment]
Hi @ColorTwist 

Once the user sign in, the CurrentUser from the Auth instance should persist even if you restart the app.
https://firebase.google.com/docs/auth/users

That is, if CurrentUser is not null when the app starts, it probably means the user login before.

Hope this helps.
Shawn

**Comment by ColorTwist** [comment]
Hi, thank for the reply.

Currently i did SignOut firebase auth when App quits, i guess Signing out would cause it not to auto sign in again when user enters app again.

I did a test and **removed** the Signout when App quits, it enters to:
```
 // Track ID token changes.
    private void IdTokenChanged(object sender, System.EventArgs eventArgs)
    {
        Firebase.Auth.FirebaseAuth senderAuth = sender as Firebase.Auth.FirebaseAuth;
        if (senderAuth == auth && senderAuth.CurrentUser != null && !fetchingToken)
        {
            senderAuth.CurrentUser.TokenAsync(false).ContinueWith(
              task => Debug.Log(String.Format("Token[0:8] = {0}", task.Result.Substring(0, 8))));
        }
    } 
```
 Giving me some Token ID, But it won't process with the entire login process, unless i am missing something

**Comment by chkuang-g** [comment]
Basically what you need to do is:
  Firebase.Auth.FirebaseAuth auth = Firebase.Auth.FirebaseAuth.DefaultInstance;
  if (auth.CurrentUser != null) {
    // User signed in before.
    DoUserDataPopulation();
  } else {
    // User did not sign-in.
    PromptForEmailPassword().ContinueWith(task => {
      auth.SignInWithEmailAndPasswordAsync(email, password).ContinueWith(DoUserDataPopulation);
    });
  }

Just be careful that the continuation function does not run from main thread in .NET 4.x.

**Comment by ColorTwist** [comment]
Thanks for the sample, 
Where should i place this code?
Starting to get confused between, 
HandleSignInWithSignInResultAsync, IdTokenChanged
since i am using:
```
  if (signInAndFetchProfile)
        { //.ContinueWith(task => RealContinuation(task, taskBState));
            return auth.SignInAndRetrieveDataWithCredentialAsync(
              Firebase.Auth.EmailAuthProvider.GetCredential(email, password)).ContinueWith(
                task => HandleSignInWithSignInResultAsync(task, ProviderEnum.password));
        }
```

**Comment by chkuang-g** [comment]
You can place the code anywhere after Firebase.FirebaseApp.CheckAndFixDependenciesAsync() is done.
Ex. in InitializeFirebase()

https://firebase.google.com/docs/reference/unity/class/firebase/auth/firebase-auth#class_firebase_1_1_auth_1_1_firebase_auth_1a9702ee15ade6886eb9cbfd6537ab5966
IdTokenChanged is triggered when Auth Id Token is changed.
AuthStateChanged is triggered when Auth state is changed.
As mentioned in the documentation, it is nice to monitor when the user logout.  AuthStateChanged should be sufficient.
HandleSignInWithSignInResultAsync() is called when the client get response from the server after the client starts a sign-in request, through ex. SignInAnonymouslyAsync() or SignInWithEmailAndPasswordAsync(), etc.  If you did not call any of these,  this function will not be triggered.

On the other hand, you can always check FirebaseAuth.DefaultInstance.CurrentUser.  Since this is a sync operation, it is not assigned right after SignInWithEmailAndPasswordAsync() is called.  However, if the user sign in before, this should be non-null after DefaultInstance is created.

**Comment by ColorTwist** [comment]
Thanks for the reply.
My project is based on Auth example here with a tweak to facebook.
Issue is that my mechanics don't totally work like that, since i also use Facebook, 
I need to redone everything to make this work this way,  at least from what it looks like, honestly i am not sure what needs to be done.
The only current way to solve this is to Sign out after user quit the app and Sign In again after users execute app without using Firebase State, issue is that i need to do the whole Sign in process for facebook and save email/password in App.

Is there any freelance assistance here?

**Comment by ColorTwist** [comment]
Thanks for the reply,  I appreciate your time and assistance. 
I managed to make it work.

I would recommend adding more examples for Authentication.
Like WHERE and HOW to handle data population correctly...

Maybe how to correctly combine other authentication like Facebook, etc..

**Comment by chkuang-g** [comment]
This information may be useful to you.

After some research, I realized that the designed behavior of CurrentUser and AuthStateChanged event, or equivalents, is different between C++/C#(Unity) implementation and native Android/iOS implementation.

In native Android/iOS implementation, it is always recommended to access CurrentUser during AuthStateChanged callback because CurrentUser is assigned asynchronously.  AuthStateChanged event is guarantee to be triggered once after the callback function is registered with the initial auth state.

In C++/C#(Unity) implementation, it is simplified that CurrentUser is always assigned during the creation of Auth instance, if the user login before.  It is not necessary to access it during AuthStateChanged event.  Also, the callback function will not be triggered right after it is added to AuthStateChanged delegate with initial state. It is only triggered if anything changes after registration.

I think our [testapp](https://github.com/firebase/quickstart-unity/blob/master/auth/testapp/Assets/Firebase/Sample/Auth/UIHandler.cs#L283) and [MechaHamster Demo](https://github.com/google/mechahamster/blob/master/Assets/Hamster/Scripts/States/Startup.cs#L44) subtly hint such behavior but we should make it clear in [the documentation](https://firebase.google.com/docs/reference/unity/class/firebase/auth/firebase-auth#class_firebase_1_1_auth_1_1_firebase_auth_1a9e2b7cd169e0c1ab8d764ac9e028de3d).

However, we discovered that there can be potential race condition for C++/C# implementation to access CurrentUser on iOS for such scenario.  We're starting an investigation to make sure it works as we expected.  If not, we would fix it in the next few releases.

It is ugly but I think the best work-around you can do is to wait for a second before accessing CurrentUser. 

Will keep you updated.
Shawn

**Comment by ColorTwist** [comment]
Thanks for this info..
I did not try it yet on iOS, but on android.
Like you suggested, after Fireabase auth initializes i check for:
`    if (auth.CurrentUser != null)`
I check if the user logged before or not, if logged on before I populate the date, otherwise you need to authenticate. 
from a few tests it seems to work on Android.
I would think to place a sample on your Auth example, for the sake of others as it is not obvious from Unity documentation, well i guess after you fix the iOS issue.

**Comment by E-Reg** [comment]
What happens if the user did not log in for 1 hour into the app and the token expires. Is the user then forced to re-enter his credentials?
When restarting the app, I don't have a currentUser object, I only stored the access token in the playerprefs. Surely this can be used for a bit of time, but only after it expires. This all works, if the user stays logged in and the token gets refreshed, or he logs in frequently. But if the token expires  (> 1h) and the user logs back in, the admin sdk rejects the token, the client has no currentUser object to TokenAsync and the custom token created by the admin sdk returns a invalid format exception on the client when SignInWithCustomTokenAsync. 
What am I missing?

**Comment by chkuang-g** [comment]
Hi @ColorTwist and to whom may concern

After some investigation, we are sure that you can directly use FirebaseAuth.CurrentUser after FirebaseAuth instance is created.  If the user signed in before, FirebaseAuth.CurrentUser would always be valid.

This should behave the same on iOS and Android.  We have not introduced persistence on desktop, just yet.  But once we do, we will make sure it behave the same as well.

Hope this helps!
