### ISSUE TITLE
Crashes on application exit ios (Messaging and Analytics sdks)

### ISSUE THREAD

**Issue by gilgil28** [firebase/quickstart-unity#271]
I have both packages in my project using unity 2018.2.6f1. After the initialization (CheckAndFixDependenciesAsync part) everything is working fine except when I close the app, I get a crash on xcode:
Thread 1: EXC_BAD_ACCESS (code=1, address=0x1267ddc48)

Here is the code that xcode is pointing at:
public:
       //internal
       static FORCE_INLINE const VirtualInvokeData& GetInterfaceInvokeDataFromVTable(const Il2CppObject* obj, const Il2CppClass* itf, Il2CppMethodSlot slot)
       {
           const Il2CppClass* klass = obj->klass;
           IL2CPP_ASSERT(klass->initialized);
           IL2CPP_ASSERT(slot < itf->method_count);

           for (uint16_t i = 0; i < klass->interface_offsets_count; i++)
           {
               if (klass->interfaceOffsets[i].interfaceType == itf)
               {
                   int32_t offset = klass->interfaceOffsets[i].offset;
                   IL2CPP_ASSERT(offset != -1);
                   IL2CPP_ASSERT(offset + slot < klass->vtable_count);
                   return klass->vtable[offset + slot];
               }
           }

           return GetInterfaceInvokeDataFromVTableSlowPath(obj, itf, slot);
       }

specifically on this line:
if (klass->interfaceOffsets[i].interfaceType == itf)

I tried latest 5.4.3 version and tried going back to 5.4.2 without any luck

**Comment by buihuuloc** [comment]
Hi there,
I got the same problem here.

**Comment by chkuang-g** [comment]
Hi all,

Could you provide the callstack if available?

Thank you!
Shawn

**Comment by chkuang-g** [comment]
I see.
I think the reason of this crash is because the Analytics static library is holding a reference of FirebaseApp until the very end of the app life cycle.  By the time when CppInstanceManager, which is also an static instance, is destroyed, il2cpp libraries has been unloaded or deallocated already.

I have added a task to track this bug.  Will keep you updated.

**Comment by buihuuloc** [comment]
OK. Thank you!

**Comment by TonyPovey** [comment]
I'm also getting this issue, any further info or work arounds?

**Comment by CriticalForce** [comment]
Same here. Don't want to downgrade or leave a broken version in the app store over the christmas 🤐

**Comment by AlekseySimonenko** [comment]
We have the same crashes in our app in new version (Analytics & remote config sdk) Unity 2018.2.8f1

**Comment by stewartmiles** [comment]
@chkuang-g has a fix checked in, we're going through the process of QA'ing a build.

**Comment by gilgil28** [comment]
Any updates?

**Comment by buihuuloc** [comment]
I think we should wait because of the holiday season

**Comment by kartikpatel1987** [comment]
any updates ?

**Comment by ozbra** [comment]
I hope you all had a great holiday time and ready to work. Because I didn't have. Please fix this problem  or at least give us a work around as soon as possible. I am not able to manage my clients anymore. They demand to fix crashes and this problem even seems to be reason of terminating my contract.

**Comment by chkuang-g** [comment]
We are managed to fix this issue and will include the fix in the next release.

This issue was introduced in 5.4.2 to fix the race condition when frequently create/destroy FirebaseApp.
The quick workaround is to revert the Firebase SDK version back to 5.4.1.  If the app, mostly iOS app, crashes when FirebaseApp/FirebaseDatabase is created/destroyed, try to hold a reference to prevent it from being GCed.

Hope this help and wish you to have a happy new year.

**Comment by bklooster** [comment]
We are also seeing this crash log. Do you know when 5.4.4 will be released that will fix this problem?

**Comment by tudorpopa39** [comment]
I also have this issue. Any news?

**Comment by tholmgren** [comment]
Hi, I'm also having this issue but can't replicated it.  Two questions.  Does anyone know if the user is aware of the crash?  2) Is there an ETA for the update with the fix?  Thanks.

**Comment by chkuang-g** [comment]
Hi folks,

Good news.  This issue is fixed in our [latest 5.4.4 release](https://firebase.google.com/download/unity). 
Please let us know if you are still experiencing similar crash.

Shawn
