### ISSUE TITLE
Update leaderboard using example database transactions

### ISSUE THREAD

**Issue by ColorTwist** [firebase/quickstart-unity#273]
I am using transaction example of database to generate leaderboard. 
https://github.com/firebase/quickstart-unity/blob/master/database/testapp/Assets/Firebase/Sample/Database/UIHandler.cs
See line 127, where it starts with:
`   TransactionResult AddScoreTransaction(MutableData mutableData) `
It works, but in some cases a user changes their information, like photo and user name and i need to update all the places in the leaderboard with the correct` photo url `and Display `Name `for that `userId`.

In my current test i also save `userId `in one of the fields besides the `photoUrl `and Display `Name`.

I might have duplicate `userIds` in the leaderboard as users can show up multiple times.
![image](https://user-images.githubusercontent.com/23701561/50055446-f2df1700-0157-11e9-9573-87509aa3db1f.png)

Only example somehow close is here :https://firebase.google.com/docs/database/unity/save-data#update_specific_fields 
in **Update specific fields** section.

There are no examples of how to handle such scenario with array numbering. 
Actually if i could remove the array numbering with Firebase transactions and replace them with userId for me to be able to update user information
Assistance would be appreciated ....

**Comment by ColorTwist** [comment]
Well, i just remove the usage of Transactions, and handled the leaderboard differently .. Transactions are fast and comfortable to use, but they are too limited for different scenarios, or at least limited documentation and support, i guess nobody knows :)

**Comment by stewartmiles** [comment]
@ColorTwist rather than storing player profiles in the leaderboard, have you considered storing player information in a separate part of the tree e.g users/${userid}/profile .  Then you can have one operation to read the leaderboard with the user IDs and another set of operations to read player profiles.  I know it's more transactions but it would keep the data centralized for each user.

Also, I recommend checking out https://github.com/FirebaseExtended/unity-solutions which contains a leaderboard plugin.  We're happy to take pull requests if you have suggested improvements.
