### ISSUE TITLE
How to detect if database connection is online/offline

### ISSUE THREAD

**Issue by shlighter** [firebase/quickstart-unity#280]
The only solution I found online was for Android- not for Unity- by listening to ('.info/connected')
But I tried it and it doesn't work (tried to translate their Android solution to C#)-
`  DatabaseReference connectedRef = FirebaseDatabase.DefaultInstance.GetReference(".info/connected");
    connectedRef.ValueChanged += (object sender, ValueChangedEventArgs a) => {
        bool isConnected = (bool)a.Snapshot.Value;
        print("isConnected" + isConnected);
    };`

How can I tell when the user isn't connected? It's important because I have to manage everything manually until the user is online again- and then update the database.

**Comment by ColorTwist** [comment]
Also related to my question: https://github.com/firebase/quickstart-unity/issues/277
If i can handle if connection is "online/offline" it would help.

**Comment by stewartmiles** [comment]
@shlighter it definitely sounds like a bug in the C++ layer if this isn't working.  I've filed a bug with our team internally to investigate this.

Though TBH .info/connected is only partially useful since you may get a message that indicates a database operation worked then the next database operation times out due to a flakey connection.  Another way of handling this is adding timeouts to your database operations, if an operation times out you can notify the user that they're offline.

**Comment by chkuang-g** [comment]
@shlighter
We verified that this is not happening on Android with our latest SDK (6.5.0+)
Could you try to update to the latest and see if this work for you now?
Thank you

**Comment by patm1987** [comment]
It looks like the bug has been fixed, and there hasn't been any activity on this thread. I'll close it for now, but feel free to comment/open it again if you're still experiencing the issue on the latest SDK.
