### ISSUE TITLE
bug) firebase realtime DB don't fire callback event when internet is not connected

### ISSUE THREAD

**Issue by green4you** [firebase/quickstart-unity#283]
when I called "FirebaseDatabase.DefaultInstance.RootReference.UpdateChildrenAsync()" function with no internet connection, there are no error log, no callback and it just running until call 
"FirebaseDatabase.DefaultInstance.PurgeOutstandingWrites()" function.

if I call purgeOutstandingWrites() , "fault" callback event is occured

**Comment by green4you** [comment]
> Hi @green4you
> 
> Just to clarify, what platform are you seeing this on? (Android/iOS/Windows/etc)

android

**Comment by a-maurice** [comment]
Got it, thanks.  We've been able to reproduce this on our side, and are looking into a fix.  Thanks for noting this issue.

**Comment by green4you** [comment]
ok, thanks.

and I want to request one more.

I'm using firebase SDK with GooglePlayGame SDK ( for firebase database auth with GooglePlayGameservice) and GoogleMobileAds (ADMOB)

But it is very hard to install and build with these SDKs because they don't work well together.

I reinstalled firebase SDK more than 4 times for update ( 1years ago, 6 months ago). and experience issue every time and it is very painful, give me stress.

if all SDKs is the latest versions, they should work well, but they always had issues.
so I must search a solution every time to solve it.

The problem of the latest firebase SDK was the version of the resolver.

so I download another resolver and can solve it.
(play-services-resolver-1.2.95.0.unitypackage)

and I found so many developers experience this issue every time.

so I request, please check compatibility of lastest SDKs( firebase, GooglePlayGame, ADMOB) before release it.

thanks

________________________________
보낸 사람: a-maurice <notifications@github.com>
보낸 날짜: 2019년 1월 10일 목요일 오전 6:12
받는 사람: firebase/quickstart-unity
참조: Phara; Mention
제목: Re: [firebase/quickstart-unity] bug) firebase realtime DB don't fire callback event when internet is not connected (#283)


Got it, thanks. We've been able to reproduce this on our side, and are looking into a fix. Thanks for noting this issue.

**Comment by stewartmiles** [comment]
@green4you we hear you about integration testing across all of Google's SDKs.  We're certainly working to improve the situation.  Pulling the latest Play Services Resolver plugin is usually not a bad idea in general though as it usually runs ahead of all other plugins released by other providers (i.e Google, Facebook, etc.).  We've been pondering an auto-update of the resolver but .. alas we have other fish to fry at the moment.

Now back to the RT DB issue.  @alexames took a look into it but still hasn't found the root cause, I believe @jonsimantov will be looking at this shortly to figure out what's happening.

**Comment by stewartmiles** [comment]
@green4you regarding the task FirebaseDatabase.DefaultInstance.RootReference.UpdateChildrenAsync() waiting forever while the device is offline, that is the expected behavior.  When the RT DB detects a connection it should eventually complete.  If you want to force a synchronization you should implement your own timeout mechanism around the Task returned by UpdateChildrenAsync().
