### ISSUE TITLE
there is no way to check internet connection with firebase database.

### ISSUE THREAD

**Issue by green4you** [firebase/quickstart-unity#284]
if a device's internet is not connected, and app request writes to firebase database, then firebase should fire error event about the internet connection.
but there is no event about this.

I was wondering this is caused by "offline mode" so I set Persistence enabled to false
(FirebaseDatabase.DefaultInstance.SetPersistenceEnabled(false);)
but not solved

**Comment by Thaina** [comment]
If your problem is specifically internet connection, you should just use `Application.internetReachability != NetworkReachability.NotReachable` it not relate to firebase sdk

`SetPersistenceEnabled` is totally difference story, it relate to caching not about internet. You could read it here > https://firebase.google.com/docs/reference/unity/class/firebase/database/firebase-database#setpersistenceenabled

Firebase database system let you create offline enabled app. So it never error when you try to use it offline. If you require your app to be always online then you need to did that yourself

**Comment by stewartmiles** [comment]
@green4you you're right that it's pretty tricky to detect a working internet connection.  It gets a bit complicated because cell phone providers can respond to pings for some IPs and not pass through others in congested or flakey network conditions.  So really all you can do is try to connect to a service with a timeout.  The database is pretty much the same, if you start an operation it will continue to retry indefinitely so you'll need to maintain your own timeout logic rather than waiting indefinitely for an operation to finish.

**Comment by DoubleALabs** [comment]
Does anyone have an example of how you could implement a network check with the .GetFileAsync() method?

**Comment by ataylor09** [comment]
@DoubleALabs I came across your question when looking for the same solution. Here is what I've done, hope it helps

        protected async void InitializeFirebase()
        {
            FirebaseApp app = FirebaseApp.DefaultInstance;
            app.SetEditorDatabaseUrl(FIREBASE_DATABASE_URL);

            if (app.Options.DatabaseUrl != null)
                app.SetEditorDatabaseUrl(app.Options.DatabaseUrl);            
            
            List<Task> tasks = new List<Task>();
            tasks.Add(GetDatabaseNode("path_to_node", SampleCallback));
            //Add more tasks here...
            
            int timeout = 10000;
            Task timeoutTask = Task.Delay(timeout);

            if (await Task.WhenAny(Task.WhenAll(tasks), timeoutTask) == timeoutTask)
            {
                // timeout logic
                Debug.Log("TIMED OUT");
                
            }
            else
            {
                // task completed within timeout 
            }

            isFirebaseInitialized = true;
        }


        public async Task GetDatabaseNode(string path, System.Action<DataSnapshot> callback) 
        {
            await FirebaseDatabase.DefaultInstance.GetReference(path).GetValueAsync().ContinueWith(task =>
            {
                if (task.IsFaulted || task.IsCanceled)
                {
                    Debug.Log("Inner task was " + (task.IsFaulted ? "faulted." : "cancelled."));
                    return;
                }

                callback?.Invoke(task.Result);
            });

            // anything that you put here will be run once the awaiting above has finished
        }

        private void SampleCallback(DataSnapshot snapshot)
        {
            foreach(var childSnapshot in snapshot.Children)
            {
                Debug.LogFormat("node contains: {0}", childSnapshot.Child("some_key").Value);
            }
        }

Credit to: @Suddoha from this unity forum:
[forum post](https://forum.unity.com/threads/how-to-wait-for-a-function-with-a-task-to-be-completed-before-continuing.625960/)

And this post from SO: [post](https://stackoverflow.com/questions/4238345/asynchronously-wait-for-taskt-to-complete-with-timeout)
