### ISSUE TITLE
Analytics question regarding,  SetUserId("uber_user_510");

### ISSUE THREAD

**Issue by ColorTwist** [firebase/quickstart-unity#291]
Hello Dear Friends,
A Question,

In analytics example UserID is set by:
```
 // Set the user ID.
      FirebaseAnalytics.SetUserId("uber_user_510");
```

I understand the UserId can be used later only with BigQuery, is that correct?

Also, Is it a good practice to use `SetUserId ` only after user authenticated with Firebase auth (facebook, email, etc..) and save UserId  value as Firebase userid?

**Comment by a-maurice** [comment]
I believe the user id will also be present in the Firebase Console's analytics dashboard.  And it's up to you on what you want the user id to represent, but having it tied to auth sounds reasonable.

Since it's not really Unity specific, I'd recommend looking at some of the discussions that have come up on the google group about it, as you can probably get better guidance on best practices and such:
https://groups.google.com/forum/#!forum/firebase-talk

**Comment by ColorTwist** [comment]
Posted in google groups firebase-talk. no answer.
Expending a bit more about SetUserId usages would be great.

**Comment by stewartmiles** [comment]
@ColorTwist you can use the analytics user ID however you want.  Some folks associate it with the auth user ID, others developers have their own concept of a user that they track across multiple applications they publish so they can run campaigns via Cloud Messaging to re-engage users.
