### ISSUE TITLE
Database RunTransaction function don't add new data 

### ISSUE THREAD

**Issue by green4you** [firebase/quickstart-unity#315]
Database RunTransaction function doesn't add new data to DB when there is no node at the path.
Is it a bug? or not?

 (e.g  I call RunTransaction with path "GameInfo/MyInfo" but there are no subpath "MyInfo" in the "GameInfo" )

If this is not a bug, how to add new data with RunTransaction When there are no data at the path?

**Comment by chkuang-g** [comment]
@green4you 
In short, you should be able to run transaction at a new location.  However, we really need more information from you to determine the cause and fix.
Please follow our report template, as the following.  Thank you.

## Please fill in the following fields:
Unity editor version: 
Firebase Unity SDK version: 
Additional SDKs you are using (Facebook, AdMob, etc.): 
Platform you are using the Unity editor on (Mac, Windows, or Linux): 
Platform you are targeting (iOS, Android, and/or desktop): 

## Please describe the issue here:
(Please list the full steps to reproduce the issue. Include device logs, Unity logs, and stack traces if available.)

## Please answer the following, if applicable:
Have you been able to reproduce this issue with just the Firebase Unity quickstarts (this GitHub project)?

**Comment by green4you** [comment]
## Please fill in the following fields:
Unity editor version: 2018.2.1f
Firebase Unity SDK version: firebase_unity_sdk_5.4.0
Additional SDKs you are using (Facebook, AdMob, etc.):
Platform you are using the Unity editor on (Mac, Windows, or Linux): Window
Platform you are targeting (iOS, Android, and/or desktop): Android

## Please describe the issue here:
(Please list the full steps to reproduce the issue. Include device logs, Unity logs, and stack traces if available.)
I'm using RunTransaction().
The path is not in the database.  
e.g) RunTransaction("Root/UserInfo"), but there is no path in "Root", and "Root" is default path of database.
Is this bug? how to fix it?
## Please answer the following, if applicable:
Have you been able to reproduce this issue with just the Firebase Unity quickstarts (this GitHub project)?
just try it with the path that is not in the database.

**Comment by chkuang-g** [comment]
Could you try with [Firebase Testapp](https://github.com/firebase/quickstart-unity/tree/master/database/testapp) and see if you can add a score to it?  It is using [RunTransaction](https://github.com/firebase/quickstart-unity/blob/master/database/testapp/Assets/Firebase/Sample/Database/UIHandler.cs#L180) as well.  And assuming the path "Leaders" does not exist in your project.

Try to use ContinueWith(), like the sample code, and try to catch any exception in this whole block.  Use "adb logcat" when your device is connect and see if anything is abnormal in the log.

Finally, you can check your [Database Security Rule](https://firebase.google.com/docs/database/security/)  and see if the location is allowed to be written.

**Comment by green4you** [comment]
I checked the sample project and I found this code.
"DatabaseReference reference = FirebaseDatabase.DefaultInstance.GetReference("Leaders");"

this is an only different code.

Here is my code
DatabaseReference rootReference = FirebaseDatabase.DefaultInstance.RootReference;
DatabaseReference destReference = rootReference.Child("Leaders");

I'll try using the sample code. 
but is my code wrong?

**Comment by green4you** [comment]
I tested the same code to the sample project.
The callback of RunTransaction() is complete. but nothing changed in the database.
There are no Leaders path after call RunTransaction()

**Comment by green4you** [comment]
the problem was the old sample project code.
