### ISSUE TITLE
Fail to load new Scene after Login successfully

### ISSUE THREAD

**Issue by kisanzxy** [firebase/quickstart-unity#332]
## Please fill in the following fields:
Unity editor version: 2018.3.1f
Firebase Unity SDK version: 5.5
Additional SDKs you are using (Facebook, AdMob, etc.): no
Platform you are using the Unity editor on (Mac, Windows, or Linux): windows
Platform you are targeting (iOS, Android, and/or desktop): android

## Please describe the issue here:
(Please list the full steps to reproduce the issue. Include device logs, Unity logs, and stack traces if available.)
My login method, this worked well before, the new scene loaded after login every time, I change nothing, and it suddenly cannot work today.

    public void Login( )
    {
        email = Email.text;
        password = Password.text;
        auth.SignInWithEmailAndPasswordAsync(email, password).ContinueWith(task =>
        {
            if (task.IsCanceled)
            {
                Debug.Log("SignInWithEmailAndPasswordAsync canceled.");
                return;
            }
            if (task.IsFaulted)
            {
                Debug.Log("SignInWithEmailAndPasswordAsync error: " + task.Exception);
                if (task.Exception.InnerExceptions.Count > 0)
                    UpdateErrorMessage(task.Exception.InnerExceptions[0].Message);
                Password.text = "";

                return;
            }

            FirebaseUser user = task.Result;
            Debug.LogFormat("User signed in successfully: ({0})", user.UserId);
            PlayerPrefs.SetString("LoginUser", user != null ? user.Email : "Unknown");
            PlayerPrefs.SetString("Uid", user != null ? user.UserId : "Unknown");
            SceneManager.LoadScene("StartMenu");
        });
    }

The Debug message did show in the log but it seems never run to the line 

SceneManager.LoadScene("StartMenu");
so it just stuck to the login page even though I got a login successfully message.

anyone can help?
## Please answer the following, if applicable:
Have you been able to reproduce this issue with just the Firebase Unity quickstarts (this GitHub project)?
No

**Comment by kisanzxy** [comment]
actually it didn't run these lines

PlayerPrefs.SetString("LoginUser", user != null ? user.Email : "Unknown");
PlayerPrefs.SetString("Uid", user != null ? user.UserId : "Unknown");
SceneManager.LoadScene("StartMenu");

**Comment by kisanzxy** [comment]
when I export the apk and test on an Android, everything works. The login to load new scene only fails Unity editor

**Comment by waze96** [comment]
I faced similar issues, and maybe your situation is the same as mine. If you are using Firebase SDK 5.5.0, then you have 2 packages downloaded: the 3dotnet and the 4dotnet, which refers to the Scripting Runtime Version (File -> Build Settings -> Player Settings -> Other Settings). If you have .NET 4.x Equivalent, then you need to import the packages from the 4dotnet folder of the Firebase Unity SDK.

IF that is your case, let me tell you about some very sad news: the way Firebase plugins for Unity work has changed: every method on the SDK runs on a separate thread (not the main one, where Unity runs), so when you try to call "Unity-code" from a Firebase method, it just won't execute. Ever. And you can't call a function from there, or even use events, because ANY call made from INSIDE the method body of the Firebase method will still run on another thread.

I will ask you to change your code like this, and test it if works, so I can know if that is actually your problem:

You need to make use of Tasks (and include "using System.Threading.Tasks;"). If you are calling Login() directly from a Button in the Editor, this won't work since Tasks are not a valid return type for that, but you can create a function like that to link it in the editor, and make the function call the Task:

**public void EditorFunction()
{
    Login();
}**

**async** Task Login ()
{
    email = Email.text;
    password = Password.text;
    **await** auth.SignInWithEmailAndPasswordAsync(email, password).ContinueWith(task =>
    {
        if (task.IsCanceled)
        {
            Debug.Log("SignInWithEmailAndPasswordAsync canceled.");
            return;
        }
        if (task.IsFaulted)
        {
            Debug.Log("SignInWithEmailAndPasswordAsync error: " + task.Exception);
            if (task.Exception.InnerExceptions.Count > 0)
                UpdateErrorMessage(task.Exception.InnerExceptions[0].Message);
            Password.text = "";

            return;
        }

        FirebaseUser user = task.Result;
        Debug.LogFormat("User signed in successfully: ({0})", user.UserId);
    });

    **PlayerPrefs.SetString("LoginUser", user != null ? user.Email : "Unknown");
        PlayerPrefs.SetString("Uid", user != null ? user.UserId : "Unknown");
        SceneManager.LoadScene("StartMenu");**
}

**Comment by kisanzxy** [comment]
@waze96
Thanks for your answer. I used 5.5.0 and dotNet4. Did Firebase just make this change? Cuz the load new scene did work before March 20th. And the wired thing is, load new scene failed on Unity Editor but success every time testing on an Android device. Anyway, I will modify the code as your example to see if it works. The other question is, since I need to retrieve the user Id and save it, how can I do this out of the Firebase thread

**Comment by alexames** [comment]
Is it possible that there's an exception being thrown by any of this code? Try putting a try/catch block around the entire lambda in your ContinueWith, and see if it catches an error. There's an issue right now where if the lambda throws an exception it will be silently fail. If that's happening, we can figure out why the exception is being thrown. If that's not happening, we'll have to figure out what else might be going wrong.

**Comment by kisanzxy** [comment]
@alexames 
I used the try catch, and here is the result
![image](https://user-images.githubusercontent.com/24818440/54791098-c92e0400-4c0e-11e9-8a47-1c4a758b1f3a.png)

The Unity method can only be called in the main thread

**Comment by kisanzxy** [comment]
I tried the async Task and how can I get the userId and store it in PlayerPrefs since it runs in a different thread

**Comment by kisanzxy** [comment]
I fixed this bug by following the solution at this thread #261

**Comment by zehidu** [comment]
> I fixed this bug by following the solution at this thread #261

i tried to follow the instructions from that thread and i couldn't figure out , is there any code that i could see to follow the steps? i would really appreciate  , i had the same problem with loading scene in firebaseauth method for signin
