### ISSUE TITLE
Firebase Analytics Unity iOS build - FIRAnalyticsVersionMismatch

### ISSUE THREAD

**Issue by sourav-paul** [firebase/quickstart-unity#335]
Unity editor version: 2018.2.16f1
Firebase Unity SDK version: 5.3.1
Additional SDKs you are using : Admob, Fabric, OneSignal, UnityAds, UnityIAP
Platform you are using the Unity editor on : Mac-macOS Mojave
Xcode Version : 10.1
Platform you are targeting : iOS

Reproduce:
-> Import Firebase 5.3.1
-> Initialised Firebase from script 
->Get *Plist project file from dashboard and put in Unity project 
-> Build 
-> Open *.xcworkspace with Xcode 
-> Workspace setting--Build Setting to "Legacy Build System" (without this there will be a cycle dependency error)
-> Run

Result:
Project builds successfully. Build runs and then there is an uncaught exception on the Xcode console with black screen

**Uncaught exception: FIRAnalyticsVersionMismatch: Google Analytics for Firebase version (50200000) does not match with Google App Measurement (50800000) version**

**Comment by a-maurice** [comment]
Hi @sourav-paul 

This was an issue with an older version of the library not pinning to the correct version of the Google App Measurement SDK.  If you can, I recommend updating to the latest version of the Firebase Unity SDK, which will use a newer version of the cocoapods that do not have this problem.  Otherwise, you can pin to the version you need, which I can give instructions for, though I recommend updating, as that will have other fixes as well.

**Comment by chkuang-g** [comment]
Hi @sourav-paul 
Does upgrading to 5.6.0 solve your problem?

**Comment by ryanmeier** [comment]
@sourav-paul 
I'm going to close this issue since we haven't heard anything in a few weeks and it seems like an SDK upgrade should solve the problem you're seeing.  If you run into any additional problems, feel free to let us know!
