### ISSUE TITLE
The same anonymous UserID cannot be obtained in the IOS environment.

### ISSUE THREAD

**Issue by berabue** [firebase/quickstart-unity#336]
Unity editor version: Unity 2018.2.0f2
Firebase Unity SDK version: 5.5.0
Additional SDKs you are using (Facebook, AdMob, etc.): Facebook, Admob, Twitter, Tapjoy
Platform you are using the Unity editor on (Mac, Windows, or Linux): Mac
Platform you are targeting (iOS, Android, and/or desktop): IOS

1. Log in as an anonymous user on the IOS device.
2. Exit and restart the app.
3. FirebaseAuth.CurrentUser returns null

How do I keep anonymous user login in my IOS environment?

It works perfectly in an Android environment.

**Comment by a-maurice** [comment]
Hi @berabue 

I haven't had any luck reproducing this on my end unfortunately.  Have you been able to reproduce this in the quickstart test app?  Another thing to try is we recently release version 5.6.0, which while I don't believe had a fix for a problem like that, might help.

**Comment by berabue** [comment]
Hi @a-maurice 

Thank you so much for your answer. Thanks to you, I found out the problem.
But I haven't found a solution yet.

As a result of using the sample, we have verified that it is working normally.
When combined with the Facebook SDK, I have verified that I cannot verify guest user information.

Can you help me?

**Comment by berabue** [comment]
I found it.

I realized that I was totally wrong.
I was calling [FIRApp configuration] from xCode.

Thank you @a-maurice

**Comment by chkuang-g** [comment]
Hi @berabue,

After some digging, seems like FB iOS SDK v4.39.0 broke our Auth while it worked with v4.38.1.

The latest FB Unity SDK v7.15.1 is using iOS library v4.39.1.
https://developers.facebook.com/docs/unity/change-log/
https://developers.facebook.com/docs/ios/change-log-4x/
However, I am not sure if this bug was fixed in 4.39.1.  You should contact Facebook for more detail.

Or you can revert back to FB Unity SDK v7.14.0, which uses iOS SDK v4.38.1.

Hope this helps.
Shawn
