### ISSUE TITLE
Crashlytics could not send build event. Error: HTTP_REDIRECT_ERROR

### ISSUE THREAD

**Issue by henriqueranj** [firebase/quickstart-unity#348]
## Issue:
Firebase Crashlytics SDK is not able to register the build during the build process.

The build id, unity version, and google-services xml files are properly generated, but any POST requests to the Crashlytics API is returning "HTTP REDIRECT ERROR". In the build log it states:

> Crashlytics could not send build event. Error: HTTP_REDIRECT_ERROR 

With this, no app crashes are reported to Crashlytics.

## Environment:
Unity editor version: Unity 2018.1.8
Firebase Unity SDK version: 5.6.1
Firebase plugins in use (Auth, Database, etc.): Analytics, Messaging, Crashlytics
Additional SDKs you are using (Facebook, AdMob, etc.): None
Platform you are using the Unity editor on (Mac, Windows, or Linux): Mac and Windows
Platform you are targeting (iOS, Android, and/or desktop): iOS and Android

## Please describe the issue here:
1. Fully remove all previous Fabric SDK and all Firebase Services SDKs.
2. Import Firebase Analytics, Messaging, and Firebase (by this order) from SDK 5.6.1.
3. AndroidManifest is also overwritten by Firebase SDK integration.
4. Import Android and iOS Firebase config files from Firebase Console.
5. Start build (either iOS or Android platforms)
6. Build steps show log: "Crashlytics could not send build event Error: HTTP_REDIRECT_ERROR"
7. Build succeeds, but upon forcing crashes, no crashes are shown in the Crashlytics dashboard.

Note: Result is the same for MacOS, Windows, and Unity Cloud Build.

## Please answer the following, if applicable:
Have you been able to reproduce this issue with just the Firebase Unity quickstarts (this GitHub project)?
Haven't been able yet to try this with the Firebase Unity quickstarts project.

**Comment by samedson** [comment]
Hey Henrique, I have a feeling this is indicative of a mismatch in configuration between the app and our backend. A couple questions to investigate:

1) Are you setting up this app as a new Firebase Crashlytics app, or migrating from Fabric so that you keep your historical crashes?
  a) If you're setting up as a new Firebase Crashlytics app, can you make sure you're gone to the Firebase Console and clicked "This app is new to Crashlytics"?
  b) If you're setting up as a migrated Fabric app, make sure you have linked using fabric.io/firebase_migration. In addition, make sure you have entered your Fabric API key in the menu in Window > Firebase > Crashlytics.
2) Can you try force running the resolver (Assets > Play Services Resolver > <Platform> Resolver > Force Resolve)?

**Comment by henriqueranj** [comment]
Hi @samedson , thanks for your quick reply.

I tried all the steps you presented and still have the same result.

1. The app was new to Firebase Crashlytics (not created first via Fabric Dashboard). However we first started using the Fabric Crashlytics SDK (instead of the Firebase Crashlytics SDK).
1. i. I remember I first configured this through "This app is new to Crashlytics" in the Firebase Console.
1. ii. Thank you for mentioning this step, I was unaware of it. And I think this is not even mentioned in your documentation. Now I can see that the `network_request.exe(/py)` command line now uses the proper Fabric API key.
2. I did Force Resolve after I configured the Fabric API key and still get the HTTP_REDIRECT_ERROR.

One extra question, is this Post-build process step inside the Crashlytics DLLs now (ie, not in open C# code)? Fabric used to have this in C# code that helped debugging and issue tracking.

**Comment by samedson** [comment]
Hey Henrique,

If you're using a Fabric API Key, then you should follow the setup in: https://firebase.google.com/docs/crashlytics/migrate-from-fabric?authuser=0 - it has the instructions for the Fabric API Key.

Since you have already clicked "This app is new to Crashlytics", you're in a state where we will have to "remove" the existing Firebase Crashlytics setup (that's not working), and replace it with the Fabric one you already got working. This is only a backend process - you can use the new Firebase Crashlytics Unity plugin, and keep your old Fabric data (that is why we have you enter your Fabric API Key)

When you go to https://fabric.io/firebase_migration you will be able to link it to your existing Fabric app, and it will remove the new Firebase setup, and start using your old Fabric setup (with all its existing crashes too).

Eg. you'll drag your Fabric app on the left to your Firebase Project on the right:
![Screen Shot 2019-04-23 at 3 16 16 PM (2)](https://user-images.githubusercontent.com/555046/56609411-09e8b680-65db-11e9-9464-3811e5d4471f.png)

And then a popup will confirm you want to remove the Firebase Crashlytics setup:
![Screen Shot 2019-04-23 at 3 16 26 PM](https://user-images.githubusercontent.com/555046/56609431-179e3c00-65db-11e9-8569-b6305c3e0a6d.png)

**Comment by henriqueranj** [comment]
Hello @samedson , just found out what was my problem! I was using the `Fabric Build Secret` instead of the `Fabric API key`... Sorry, the UX of the Fabric dashboard got the best of me. Thanks for all the help!

Now the builds properly register with the Firebase Crashlytics API. 
> Crashlytics build information sent

>

**Comment by samedson** [comment]
Ah makes sense - maybe we can add some validation to that box. Glad it's working!
