### ISSUE TITLE
Firebase Analytics unity package is 7.7mb bigger than it should be

### ISSUE THREAD

**Issue by stopiccot** [firebase/quickstart-unity#349]
## Please fill in the following fields:
Unity editor version: 2018.2.20f1
Firebase Unity SDK version: 5.4.4
Firebase plugins in use (Auth, Database, etc.): Analytics
Additional SDKs you are using (Facebook, AdMob, etc.):  -
Platform you are using the Unity editor on (Mac, Windows, or Linux): Mac
Platform you are targeting (iOS, Android, and/or desktop): iOS

## Please describe the issue here:
Adding FirebaseAnalytics unitypackage to Unity iOS app increases it's install size by 8.9mb
Compared to that adding FirebaseAnalytics pod to native iOS app increases it's install size by only 1.2mb. Considering that firebase analytics unity package is technically native iOS pod plus C# glue code for that I do not understand how glue code can by 7.7mb in size. (640% more than native iOS part). This forces our studio to develop own C# bindings.

**Comment by stopiccot** [comment]
`Assets/Firebase/Plugins/link.xml` seems to be the reason

**Comment by ryanmeier** [comment]
Hi @stopiccot,

The difference in install size you're seeing between the native iOS pod and the FirebaseAnalytics unity package is likely due to the fact that the unity package is built on top of our cross-platform C++ SDK, rather than as a lightweight C# wrapper around the native iOS SDK.

We'll certainly keep an eye out in the future for ways that we can reduce the impact these plugins have on install size, but unfortunately we don't have any concrete plans at the moment - so if the impact of the unity package is too large for your use case, writing your own bindings may be the best bet for the moment.

**Comment by stewartmiles** [comment]
@ryanmeier I sure hope the C++ components aren't that big.  The Analytics component is pretty tiny and everything else should be dead stripped. @stopiccot mentioned that the `Assets/Firebase/Plugins/link.xml` is the problem, from what I can remember this was required for RT DB when we used the C# implementation on mobile, I think it's safe to ditch it now.

@stopiccot if you remove `link.xml` does that solve the size issue?

**Comment by stopiccot** [comment]
@stewartmiles Yeah, in our usecase (we use only analytics feature of Firebase) removing link.xml reduces build size by roughly 6 megabytes. And analytics seems to still be working on both iOS and android.

**Comment by stewartmiles** [comment]
@stopiccot thanks for the feedback and root cause of the issue.  Yeah we don't need to pull in the .NET network stack in mobile builds since we now implement the entire RT DB and Storage SDKs in a combination of C/C++ Java & Obj-C rather than trying to get Unity's networking to work.

We'll need to figure out how to pull this out of our next release.  I think the main issue is that `link.xml` can't be configured per platform which means we'll need to do something horrible like rename the file depending upon the currently selected platform.

**Comment by stopiccot** [comment]
@stewartmiles But on which platform you'll still need link.xml?

**Comment by stewartmiles** [comment]
@stopiccot unfortunately it's still required for desktop standalone builds which quite a few of our developers use for testing.  Once we finally move the C# RT DB to C++ on desktop we'll be able to ditch the link.xml file.

**Comment by jonsimantov** [comment]
We just released version [6.0.0](https://firebase.google.com/support/release-notes/unity#6.0.0) of the Firebase Unity SDK, which excludes the link.xml file in mobile builds to address this issue. You can download the latest Firebase Unity SDK at https://firebase.google.com/docs/unity/setup#add_sdk.
