### ISSUE TITLE
Firebase anonymous first create wont finished the task and no error or any

### ISSUE THREAD

**Issue by dominicdev** [firebase/quickstart-unity#366]
## Please fill in the following fields:
Unity editor version: 2018.3.8f1
Firebase Unity SDK version: 5.5.0
Firebase plugins in use (Auth, Database, etc.): Auth
Additional SDKs you are using (Facebook, AdMob, etc.):  No
Platform you are using the Unity editor on (Mac, Windows, or Linux):  Windows
Platform you are targeting (iOS, Android, and/or desktop):  Android

## Please describe the issue here:
(Please list the full steps to reproduce the issue. Include device logs, Unity logs, and stack traces if available.) use basic code using SignInAnonymouslyAsync

auth.SignInAnonymouslyAsync().ContinueWith(task => {
  if (task.IsCanceled) {
    Debug.LogError("SignInAnonymouslyAsync was canceled.");
    return;
  }
  if (task.IsFaulted) {
    Debug.LogError("SignInAnonymouslyAsync encountered an error: " + task.Exception);
    return;
  }
//if I post or log something it wont show.. during first install
  Firebase.Auth.FirebaseUser newUser = task.Result;
  Debug.LogFormat("User signed in successfully: {0} ({1})",
      newUser.DisplayName, newUser.UserId);
});

## Please answer the following, if applicable:
Have you been able to reproduce this issue with just the Firebase Unity quickstarts (this GitHub project)?YES

**Comment by a-maurice** [comment]
Hi @dominicdev 

We haven't been able to reproduce this problem on our end.  I notice the version of the Unity SDK you are using is a bit older, could you try using the latest one, 6.0.0?

Also, you can enable more verbose logging by using: `Firebase.FirebaseApp.LogLevel = Firebase.LogLevel.Debug`, which might help indicate what the underlying problem is.

**Comment by Twinsens** [comment]
Hi @a-maurice 
I have similar issue. I use 6.0.0,  I was download code from  'Firebase Unity quickstarts' check the firebase functions one. 

https://github.com/firebase/quickstart-unity/blob/master/functions/testapp/Assets/Firebase/Sample/Functions/UIHandler.cs

I was debug the code. At line 104, .ContinueWith just sometimes triggered. Not always triggered. Because of the this I can not catch the result of request.

**Comment by chkuang-g** [comment]
Hi @dominicdev @Twinsens 
Did you see anything abnormal in the log through "adb logcat"?

One possible reason why continuation function did not run properly is due to an exception thrown inside the continuation function.  Prior to 6.0.0, it usually crashes the worker thread silently.  We changed it in 6.0.0 that we would always re-throw those exception on the main thread so that it can be logged properly.

Could you try the following?
1. See if any exception was logged.
2. Try to try-catch in the continuation function.

Shawn

**Comment by stewartmiles** [comment]
@dominicdev and @Twinsens since we haven't heard from you we're closing this issue.  Please let us know if you're still having issues.
