### ISSUE TITLE
Android Can not build. Please help!

### ISSUE THREAD

**Issue by yuya0902** [firebase/quickstart-unity#370]
I would like to introduce FireBaseSDK to the title that I am currently using with Unity 5.6.7f1, but I'm having trouble being unable to build with errors.

If you know the solution, please teach.

## Error 1
Create an empty project, install the necessary packages from the official Firebase site, and build, the following error occurs.
```
CommandInvokationFailure: Unable to merge android manifests. See the Console for more details

CommandInvokationFailure: Unable to merge android manifests. See the Console for more details. 
C:\Program Files\Java\jdk1.8.0_171\bin\java.exe -Xmx2048M -Dcom.android.sdkmanager.toolsdir="C:/Users/ユーザー名/AppData/Local/Android/Sdk\tools" -Dfile.encoding=UTF8 -jar "C:\Program Files\Unity\5.6.7f1\Editor\Data\PlaybackEngines\AndroidPlayer/Tools\sdktools.jar" -
```

I confirmed this.
[AndroidManifest merge fail. Please help! #192](https://github.com/firebase/quickstart-unity/issues/192#issuecomment-415622826)

Certainly by updating to Unity2018, it has been confirmed that the build is successful.

But I want to introduce Firebase SDK with Unity 5.6.7f1

Is it impossible to build with Unity 5.6.7f1?

## Error 2
If UnitySDK version is 26.1.1 with Unity 5.6.7f1, the following error will occur this time.

```
CommandInvokationFailure: Unable to list target platforms. Please make sure the android sdk path is correct. See the Console for more details. 
```

Please lend me your wisdom

**Comment by chkuang-g** [comment]
Hi @yuya0902 

#192 is a pretty old thread...

Are you sure you setup your Android SDK correctly?  The log literally asked  "Please make sure the android sdk path is correct."

One quick way for you to test if your Unity environment is setup correctly is to using our Unity quickstart.  
 https://github.com/firebase/quickstart-unity

Are you seeing the same error when building any of these testapp?  If so, please provide more detail, ex. log, plugin you used, etc.

Thank you,
Shawn

**Comment by patm1987** [comment]
Hi, for clarity as well, are you able to produce Android builds without the Firebase SDK?

Older versions of Unity do not work with newer versions of the Android SDK due to the fact that the command line tools that Unity used to use from the Android SDK did change at one point. If you are unable to produce an Android build whether or not you include the Firebase SDK, you may try this workaround:
https://answers.unity.com/questions/1323731/unable-to-list-target-platforms-please-make-sure-t.html
Although my personal (not official) recommendation would be to update Unity if possible. Newer versions of Unity (2019) give you the option of installing a version of the Android SDK with the version of Unity you're using to avoid this sort of issue in the future.

**Comment by stewartmiles** [comment]
@yuya0902 since we haven't heard from you we're closing this issue.
