### ISSUE TITLE
Messaging (Android): com.google.firebase.messaging.cpp.ListenerService  - ClassNotFoundException after upgrading from 5.4.3 to 5.6.1

### ISSUE THREAD

**Issue by NikoYuwono** [firebase/quickstart-unity#374]
## Please fill in the following fields:
Unity editor version: 2018.3.7f
Firebase Unity SDK version: 5.6.1
Firebase plugins in use (Auth, Database, etc.): Remote Config, Analytics, Push Notification
Additional SDKs you are using (Facebook, AdMob, etc.): AdMob, Play Game Services, AppLovin, IronSource, Vungle, MoPub, Facebook
Platform you are using the Unity editor on (Mac, Windows, or Linux): Mac
Platform you are targeting (iOS, Android, and/or desktop): Android

## Please describe the issue here:
(Please list the full steps to reproduce the issue. Include device logs, Unity logs, and stack traces if available.)

Hi team, we just updated our game Firebase SDK from 5.4.3 to 5.6.1 and saw this crash that **only happen at the first launch**, below is the crash log

Unable to instantiate service com.google.firebase.messaging.cpp.ListenerService: java.lang.ClassNotFoundException: Didn't find class "com.google.firebase.messaging.cpp.ListenerService" on path: DexPathList[[zip file "/data/app/my.package.name-Jxn3Yt_eJ5fMacA_SMHFOg==/base.apk"],nativeLibraryDirectories=[/data/app/my.package.name-Jxn3Yt_eJ5fMacA_SMHFOg==/lib/arm, /data/app/my.package.name-Jxn3Yt_eJ5fMacA_SMHFOg==/base.apk!/lib/armeabi-v7a, /system/lib, /vendor/lib, /product/lib]

Any idea why? This only happens in 5.6.1, we tried to revert to 5.4.3 and the crash was gone, but we want to use 5.6.1 or above, since we already use 5.6.1 in our other game and saw it's more stable than 5.4.3.

Thanks.

**Comment by alexames** [comment]
That's really weird, I'm not sure off the top of my head why that would be happening. Does this happen in the quickstart testapp when you run it, then upgrade, then run again?

**Comment by gabetoth-dgh** [comment]
I have the same issue but only when trying to build arm64.

**Comment by stewartmiles** [comment]
@NikoYuwono and @gabetoth-dgh any chance you could share the complete output of `adb logcat` when this occurs?

e.g on a Mac / Linux console run...

`adb logcat -c ; adb logcat | tee logcat.log`

on Windows...

`adb logcat -c & adb logcat > logcat.log`

Also, any chance you could share the Android devices and versions you're seeing this with? 

Finally, could you give the latest Unity SDK release a try, we've changed [a lot](https://firebase.google.com/support/release-notes/unity#version_611_-_june_7_2019) in the past 6 months since `5.4.3` was released.

**Comment by gabetoth-dgh** [comment]
Hi@stewartmiles ,

I moved on with an updated jar resolver, that fixed the issue. I am using now 6.0.0, newer versions had some other issue and we had to roll back to 6.0.0.

`--------- beginning of crash
06-05 15:45:46.291 23786 23786 E AndroidRuntime: FATAL EXCEPTION: main
06-05 15:45:46.291 23786 23786 E AndroidRuntime: Process: com.my.app, PID: 23786
06-05 15:45:46.291 23786 23786 E AndroidRuntime: java.lang.RuntimeException: Unable to instantiate service com.google.firebase.messaging.cpp.ListenerService: java.lang.ClassNotFoundException: Didn't find class "com.google.firebase.messaging.cpp.ListenerService" on path: DexPathList[[zip file "/data/app/com.my.app-2aeIZ0ct6oH_A-c5ZgtNWg==/base.apk"],nativeLibraryDirectories=[/data/app/com.my.app-2aeIZ0ct6oH_A-c5ZgtNWg==/lib/arm64, /data/app/com.my.app-2aeIZ0ct6oH_A-c5ZgtNWg==/base.apk!/lib/arm64-v8a, /system/lib64, /vendor/lib64]]
06-05 15:45:46.291 23786 23786 E AndroidRuntime: 	at android.app.ActivityThread.handleCreateService(ActivityThread.java:3524)
06-05 15:45:46.291 23786 23786 E AndroidRuntime: 	at android.app.ActivityThread.-wrap4(Unknown Source:0)
06-05 15:45:46.291 23786 23786 E AndroidRuntime: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1752)
06-05 15:45:46.291 23786 23786 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:105)
06-05 15:45:46.291 23786 23786 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:180)
06-05 15:45:46.291 23786 23786 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:6950)
06-05 15:45:46.291 23786 23786 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
06-05 15:45:46.291 23786 23786 E AndroidRuntime: 	at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
06-05 15:45:46.291 23786 23786 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:835)
06-05 15:45:46.291 23786 23786 E AndroidRuntime: Caused by: java.lang.ClassNotFoundException: Didn't find class "com.google.firebase.messaging.cpp.ListenerService" on path: DexPathList[[zip file "/data/app/com.my.app-2aeIZ0ct6oH_A-c5ZgtNWg==/base.apk"],nativeLibraryDirectories=[/data/app/com.my.app-2aeIZ0ct6oH_A-c5ZgtNWg==/lib/arm64, /data/app/com.my.app-2aeIZ0ct6oH_A-c5ZgtNWg==/base.apk!/lib/arm64-v8a, /system/lib64, /vendor/lib64]]
06-05 15:45:46.291 23786 23786 E AndroidRuntime: 	at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:93)
06-05 15:45:46.291 23786 23786 E AndroidRuntime: 	at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
06-05 15:45:46.291 23786 23786 E AndroidRuntime: 	at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
06-05 15:45:46.291 23786 23786 E AndroidRuntime: 	at android.app.ActivityThread.handleCreateService(ActivityThread.java:3521)
06-05 15:45:46.291 23786 23786 E AndroidRuntime: 	... 8 more
06-05 15:45:46.291 23786 23786 E AndroidRuntime: 	Suppressed: java.lang.NoClassDefFoundError: Failed resolution of: Lcom/google/firebase/messaging/FirebaseMessagingService;
06-05 15:45:46.291 23786 23786 E AndroidRuntime: 		at java.lang.VMClassLoader.findLoadedClass(Native Method)
06-05 15:45:46.291 23786 23786 E AndroidRuntime: 		at java.lang.ClassLoader.findLoadedClass(ClassLoader.java:738)
06-05 15:45:46.291 23786 23786 E AndroidRuntime: 		at java.lang.ClassLoader.loadClass(ClassLoader.java:363)
06-05 15:45:46.291 23786 23786 E AndroidRuntime: 		... 10 more
06-05 15:45:46.291 23786 23786 E AndroidRuntime: 	Caused by: java.lang.ClassNotFoundException: com.google.firebase.messaging.FirebaseMessagingService
06-05 15:45:46.291 23786 23786 E AndroidRuntime: 		at java.lang.VMClassLoader.findLoadedClass(Native Method)
06-05 15:45:46.291 23786 23786 E AndroidRuntime: 		at java.lang.ClassLoader.findLoadedClass(ClassLoader.java:738)
06-05 15:45:46.291 23786 23786 E AndroidRuntime: 		at java.lang.ClassLoader.loadClass(ClassLoader.java:363)
06-05 15:45:46.291 23786 23786 E AndroidRuntime: 		at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
06-05 15:45:46.291 23786 23786 E AndroidRuntime: 		... 13 more
06-05 15:45:46.291 23786 23786 E AndroidRuntime: 	Caused by: java.lang.IllegalAccessError: Class com.google.firebase.iid.zzb extended by class com.google.firebase.messaging.FirebaseMessagingService is inaccessible (declaration of 'com.google.firebase.messaging.FirebaseMessagingService' appears in /data/app/com.my.app-2aeIZ0ct6oH_A-c5ZgtNWg==/base.apk:classes5.dex)
06-05 15:45:46.291 23786 23786 E AndroidRuntime: 		... 13 more
06-05 15:45:46.324 23786 23791 I zygote64: Do partial code cache collection, code=28KB, data=28KB
06-05 15:45:46.324 23786 23791 I zygote64: After code cache collection, code=23KB, data=24KB
06-05 15:45:46.324 23786 23791 I zygote64: Increasing code cache capacity to 128KB`

**Comment by NikoYuwono** [comment]
Same here, fixed by upgrading the play service resolver. Will close this then.
