### ISSUE TITLE
Firebase Auth + Database setup in unity editor failure

### ISSUE THREAD

**Issue by sourabhverma** [firebase/quickstart-unity#41]
I am trying to make firebase work in unity editor but have no success so far. My rules setup to test database is like this
```
{
  "rules": {
    ".read": false,
    ".write": false,
    "unity-tests": {
      //This area is just for testing things
    	".read": "auth != null",
      	".write": "auth != null"
    }
}
```

I created service account, placed p12 file and also did initialisation as given in doc. I am facing 2 problems.

1) When i login, i am getting firebase user ID same as my email address and looking at console, it seems like user never logged In (Using Email / Password login)
2) When i connect to database, it responds in almost a min with error "Error obtaining service credential. Attempting unauthenticated access"

Logs screenshot attached. How can i make it work and i am wondering what i am doing wrong ?

P.S: Its working fine on iOS device & android too. Its the editor which i am trying to work with for faster development.

<img width="593" alt="unity logs" src="https://cloud.githubusercontent.com/assets/2278257/22123085/4eedf2ae-deb0-11e6-891d-3aeaa9101404.png">

**Comment by benwulfe** [comment]
Hi sourabhverma, if you see the error message "Error obtaining service credential. Attempting unauthenticated access" it means there is an issue with your service account setup and it has nothing to do with either your users or rules -- which are checked much later.

Can you attach your initialization code and the location where you are dropping the p12 file?  Also you can first attempt service account auth in the editor without any auth code and without setting the UId.  Even if your rules are set to "false, false", you will be able to access your data through a service account.  Of course, if you impersonate a uid, you could be denied which is why you should see if it works without it.

**Comment by sourabhverma** [comment]
Hi @benwulfe ,
Based on infos shared by you. I created a new p12 file but this time i created a key for "App Engine default service account" and used it and it worked !

However i am sharing screenshot of my service account console and wanted to understand if service account created by me by name "Unity Editor Service" can work or not for knowledge purpose

<img width="984" alt="google console service accounts" src="https://cloud.githubusercontent.com/assets/2278257/22173033/c66bdd0a-dfdc-11e6-9f67-a41cee22f467.png">

**Comment by benwulfe** [comment]
The name should not matter, but its possible it did not have the proper
permissions.  Did you give both the same?  Project Editor permissions
should be sufficient.

**Comment by sourabhverma** [comment]
Got it. It was permission issue, Permission in IAM was set to "service account actor" instead of "Editor". 

Thanks a ton !
