### ISSUE TITLE
We need the ability to run multiple atomic transactions

### ISSUE THREAD

**Issue by exzizt** [firebase/quickstart-unity#418]
We need the ability to run multiple atomic transactions. What I mean, for example, is the ability to have 5 transactions that are all atomic with one another (if one fails, they all fail).

**Comment by Thaina** [comment]
@exzizt That was already what a transaction is

One transaction can batch many unrelated operations in atomic way. I don't remember the exact number but it more than 20. You can write 20+ changes into anywhere of the database. Why you want to split it into 5 transaction?

**Comment by exzizt** [comment]
> @exzizt That was already what a transaction is
> 
> One transaction can batch many unrelated operations in atomic way. I don't remember the exact number but it more than 20. You can write 20+ changes into anywhere of the database. Why you want to split it into 5 transaction?

Hi Thaina. I don't think you understand the question. There is actually no way to do this in Firebase currently.

See for more details:

- https://www.reddit.com/r/Firebase/comments/ccrxak/how_can_i_have_multiple_transactions_be_atomic/etp60gg/

- https://stackoverflow.com/questions/43209533/use-transaction-to-update-value-at-two-different-nodes

**Comment by Thaina** [comment]
@exzizt Sorry I was misunderstand a little. Because I has a familiarity with firestore which could did that

In my case I was always doing transaction in firebase RTDB with the most common parent node of nodes I want to modified

So actually what you really want to do (modified any complex node) seem like it not possible in firebase RTDB yet

But still, my point is, you might not get the mechanism as you ask. I think firebase designer may create a new transaction system for RTDB in the same manner as firestore. The concept of transaction should be that a transaction will let you get multiple node and modified it, instead of batching multiple transactions

**Comment by exzizt** [comment]
> But still, my point is, you might not get the mechanism as you ask. I think firebase designer may create a new transaction system for RTDB in the same manner as firestore. The concept of transaction should be that a transaction will let you get multiple node and modified it, instead of batching multiple transactions

That would be BEAUTIFUL! :) 👍

**Comment by alexames** [comment]
Hi exzizt,

Thanks for the feedback. For feature requests like these, it helps to fill out our feature request form (which you can find here: https://firebase.google.com/support/) so that we can have the Firebase team evaluate the feature.

**Comment by exzizt** [comment]
> Hi exzizt,
> 
> Thanks for the feedback. For feature requests like these, it helps to fill out our feature request form (which you can find here: https://firebase.google.com/support/) so that we can have the Firebase team evaluate the feature.

Done!
