### ISSUE TITLE
EntryPointNotFoundExceptaion : Error (Only on Mac OSX)

### ISSUE THREAD

**Issue by kugimasa** [firebase/quickstart-unity#424]
Unity editor version: 2018.3.8f1
Firebase Unity SDK version: 6.2.1
Firebase plugins in use (Auth, Database, etc.):Analytics, Auth
Platform you are using the Unity editor on : macOS Mojave 10.14.5, Windows 
Platform you are targeting : iOS, Android

## Our Ploblem:
Hi! I've been working on a game development with my friends using Unity and we've imported the Firebase SDK to our project. We have followed your [workflow](https://firebase.google.com/docs/unity/setup) and added Firebase Analytics and Firebase Auth.
Our problem is that everything works well on Windows but we have the Error1 and Error2 on MacOS.

### Error1
![スクリーンショット 2019-07-17 11 12 50](https://user-images.githubusercontent.com/40158101/61342441-1f414a00-a885-11e9-8a3a-0534442da2c4.png)

![スクリーンショット 2019-07-17 11 12 59](https://user-images.githubusercontent.com/40158101/61342444-2405fe00-a885-11e9-9ecc-1307ec8caabd.png)

For this error we disabled the Firebase Object from the Inspector . When disabled the error was   
gone but I'm not sure it was the right thing to do.
The Manager Scene is called every time the game is played.
The Confirm Goolge Play Version (Script) is shown bellow
```c#
using System.Collections;
using System.Collections.Generic;
using UnityEngine;
using System.Threading.Tasks;
using Firebase;

public class ConfirmGooglePlayVersion : MonoBehaviour
{
    void Awake()
    {
        Firebase.FirebaseApp.CheckAndFixDependenciesAsync().ContinueWith(task => {
            var dependencyStatus = task.Result;
            if (dependencyStatus == Firebase.DependencyStatus.Available)
            {
                // Create and hold a reference to your FirebaseApp,
                // where app is a Firebase.FirebaseApp property of your application class.
                // app = Firebase.FirebaseApp.DefaultInstance;

                // Set a flag here to indicate whether Firebase is ready to use by your app.
            }
            else
            {
                UnityEngine.Debug.LogError(System.String.Format(
                  "Could not resolve all Firebase dependencies: {0}", dependencyStatus));
                // Firebase Unity SDK is not safe to use here.
            }
        });
    }
}
```

### Error2
![スクリーンショット 2019-07-17 11 08 56](https://user-images.githubusercontent.com/40158101/61342470-3718ce00-a885-11e9-8713-1fe7b0e8cb33.png)

Error2 occurred on our Sign Up Scene.
This is our Sign Up Manager (Script)
```c#
using System.Collections;
using System.Collections.Generic;
using UnityEngine;
using Firebase.Auth;
using System.Runtime.InteropServices;

public class SignUpManager : MonoBehaviour
{
    FirebaseAuth auth;
    void Start()
    {
        auth = FirebaseAuth.DefaultInstance;
    }

    public void SignUp(string email, string password)
    {
        GameObject.Find("SceneController").GetComponent<SceneController>().ToHomeScene();

        auth.CreateUserWithEmailAndPasswordAsync(email, password).ContinueWith(task => {
            if (task.IsCanceled)
            {
                Debug.LogError("CreateUserWithEmailAndPasswordAsync was canceled.");
                return;
            }
            if (task.IsFaulted)
            {
                Debug.LogError("CreateUserWithEmailAndPasswordAsync encountered an error: " + task.Exception);
                return;
            }

            // Firebase user has been created.
            FirebaseUser newUser = task.Result;
            Debug.LogFormat("Firebase user created successfully: {0} ({1})",
                newUser.DisplayName, newUser.UserId);
            Debug.Log(newUser.DisplayName);
            Debug.Log(newUser.UserId);

        });

    }
}
```  
### Thing we tried
* First we imported the Firebase SDK on Windows and pushed the commit to our remote GitHub repository. 
* Then we fetched that branch to our different environments (MacOS and other Windows) 
* We deleted the Unity.Compat.dll and Unity.Tasks.dll in Parse > Plugins
* We changed the Platform Settings of Firebase.Analytics, Firebase.App, and Firebase.Auth in
   * Firebase > Plugins > iOS  
     OS : Any OS -> MacOX
   * Firebase > Plugins
      OS : Any OS -> Windows 

![60942033-164bf800-a31c-11e9-8d79-d5be08fb701d](https://user-images.githubusercontent.com/40158101/61343371-74328f80-a888-11e9-96d3-850601a2a3e6.png)

* Every thing when well on Windows but not on MacOS

* We haven't built our Project on both iOS and Android after importing Firebase.

**Comment by alexames** [comment]
Hi, apologies for the late reply.

Have you tried running the Quickstart testapp, and verifying whether that works the way you expect when you run it? The easiest way to debug issues like these is to find a starting point that you know works, and then figuring out what you've done differently and working from there. I would also recommend putting some try/catch blocks in your code to print out the exceptions that are getting thrown, so you can get more information about what is failing.

**Comment by kugimasa** [comment]
@alexames Thanks for your reply!! 
No. We haven't tried it on the Quickstart app. We'll try to test it on the Quickstart too.
We have been sharing the Firebase SDK through GitHub. Do you think this was the bad idea??

**Comment by chkuang-g** [comment]
Hi @kugimasa 

If I understand it correctly, you created an Unity project, imported Firebase plugins and shared the whole project, including Firebase plugins, through Github. 
And you are accessing the project from both Windows and OSX.
And I assume you submit the first version from Windows and have trouble to run in editor on macOS.
Is that correct?

The error you saw is because the C# API cannot find the C++ library, which should be under Assets/Firebase/Plugins/x86_64/ or Assets/Plugins/x86_64
Ex.

- Assets/Plugins/x86_64/Firebase/FirebaseCppApp-6.2.1.dll is for Windows desktop
- Assets/Plugins/x86_64/Firebase/FirebaseCppApp-6.2.1.bundle is for macOS desktop
- Assets/Plugins/x86_64/Firebase/libFirebaseCppApp-6.2.1.so is for Linux desktop

Are you seeing those files in your project?
Or could you share what you see under those folders?  Seems like Unity 2019 would move all desktop plugins to Assets/Plugins/x86_64.

If you are still experiencing the problem, I would recommend you to give us the exact reproduction steps with our Unity quickstart.
https://github.com/firebase/quickstart-unity

Thank you!
Shawn

**Comment by kugimasa** [comment]
Thanks for your information @chkuang-g !!
Sorry for the late reply, This is what I got under my  *Assets/Plugins/x86_64/Firebase*.
(I only had the *iOS* directory and some files under my *Assets/Firebase/Plugins/*)
![スクリーンショット 2019-08-01 21 01 27](https://user-images.githubusercontent.com/40158101/62292038-6001ab80-b4a0-11e9-8911-df06569f0f41.png)
So do you me I have to delete the Windows and Linux files?? (I'm using macOS)
And should we not share them by selecting them in the .gitignore??
Sorry for asking you so many questions 😭

**Comment by patm1987** [comment]
Hi @kugimasa,

No worries about the questions! First off, do not delete those files.

You may be running into something that totally killed me on my first few projects. For the Firebase plugins, files that are _normally_ excluded in other build systems are actually important. This includes .a, .so, .dll, .bundle (this is actually a folder), .framework (also actually a folder), .aar, .jar, &c. If you pulled a default gitignore, these will often be ignored in an attempt to prevent shipping generated binaries (in many cases, this is the correct thing to do).

What you may want to try is, on your MacOS machine, just import the Firebase SDK again. If you've been playing around with platform membership for libraries, you may want to try to just delete evertying and pull them in again (all this data is stored in the .meta files if you wanted to just undo those specific changes).

Certainly try reproducing in the Quickstarts and see if you run across the same issue. But if just re-adding the unitypackage on a machine that doesn't compile fixes the issue, you may just have an overaggressive .gitignore.

Let me know if you're still running into issues. The problem you see does look like you're simply missing some native binaries. Since SWIG is in the name, I'm assuming that it's missing native files we try to ship in the SDK rather than something pulled in via CocoaPods (iOS) or gradle (Android).

--Patrick

**Comment by stewartmiles** [comment]
Since we haven't heard from you I'll assume @patm1987 's response solved your problem.
