### ISSUE TITLE
open webpage by click

### ISSUE THREAD

**Issue by saeedaliakbari** [firebase/quickstart-unity#425]
How to open a webpage by clicking on the message received in cloudmessaging?
I want a solution at Unity

**Comment by alexames** [comment]
Can you clarify exactly what behavior you're looking for? Is it that you want to tap the notification in the system tray, and have that notification open up a web page instead of your app? 

By default, tapping on a notification in the system tray will open your app. If you want to take another action instead, when you send a message you'll need to supply a field called `click_action`, then you'll have to add some custom code in Java (on android) or Objective C (on iOS) to deal with the action when it arrives. There isn't a way to do this purely with C# from within Unity. 

What platform is your app targeting?

**Comment by saeedaliakbari** [comment]
Hi dear friend @alexames 
My application platform is unity (C#) and the Android output is required by me
I want to open the web page by clicking on the notification and I do not want to open the app.
please guide me.

**Comment by alexames** [comment]
When you send you message to FCM, you will need to supply a `click_action`. The Firebase Console doesn't support this feature, so you will need to send the message manually using the rest interface. 

You will need to update your `AndroidManifest.xml` file to have an intent filter that listens for events sent to the `click_action` that you specified. This intent filter will ensure the proper Android Service or Activity receives the Intent that is fired from the notification. This code needs to be written in Java, there is no C# interface for this part of the task. In your `onHandleIntent` method you can add add whatever custom behavior you want, including opening up a webpage.

**Comment by saeedaliakbari** [comment]
Thanks for the description @alexames 
I do not control Java, is it possible for you to send me a sample?
My email: saliakbari6603@gmail.com

**Comment by saeedaliakbari** [comment]
please help me @alexames

**Comment by alexames** [comment]
This will be hard to do if you can't write Java, since this use case isn't directly supported by the API. 

You will need to [create your own android Service](https://developer.android.com/training/run-background-service/create-service#java) in java. In your service, you have to have a method to handle incoming Intents. You can open a webpage using the following code:

```
Intent browserIntent = new Intent(Intent.ACTION_VIEW, Uri.parse("http://www.example.com"));
startActivity(browserIntent);
```

You will also need to set up your AndroidManifest.xml file to filter incoming Intents that are tagged with the click_action that you specified. You can see how to set that up [here](https://stackoverflow.com/a/37531595/63791).

**Comment by stewartmiles** [comment]
Hi @saeedaliakbari , we don't perform general consulting on Unity application development we will happily help folks with issues related to Firebase though.  As @alexames pointed out, you could change the way a message is handled by hooking the behavior of Android activity which is documented [here](https://firebase.google.com/docs/cloud-messaging/unity/client#configuring_an_android_entry_point_activity) or customize how a notification is displayed with a custom action to open in another app (e.g a web page).  This is all far outside of the scope of Firebase and really gets into system level details.  So I recommend you play around with a vanilla Android or iOS application (outside of Unity) first then perhaps you can integrate your changes into Unity.
