### ISSUE TITLE
Incompatibility with Facebook SDK (Unity 2019.2, Firebase SDK 6.2.2)

### ISSUE THREAD

**Issue by andnoonesthere** [firebase/quickstart-unity#438]
Hi, just to let you know, with Unity 2019.2 it's basically impossible now to use Firebase and Facebook together. Have a look at an issue I've created here: https://github.com/facebook/facebook-sdk-for-unity/issues/303

There is a problem with incompatible dependencies. And now because of "DllNotFoundException" (fixed in Firebase 6.2.2) in the editor, you're practically unable to use older Firebase version with Unity 2019.2. That means we're stuck at the moment because of that and can't use Facebook authentication in Firebase for our game.

If you could suggest some workaround or help in fixing this somehow, it would be really helpful for us.

**Comment by michael-looply** [comment]
Hey @andnoonesthere, I had the same issue and spent some time yesterday making a fork that functions w/ 2019.2.0f1 and Firebase. I've tested functionality of both SDKs on Android and iOS and it _looks like_ everything's running as expected. As a warning, the changes in my fork should make the build process backwards-incompatible when building the SDK via the provided scripts with Unity versions prior to 2019.2.0f1.

Note that if you want to build the SDK locally, I updated the repo to require configuration of an environment variable so that Hub-based Unity instances can be used (the **.csproj** files and shell scripts have hard-coded paths in this repo, making it impossible to build on machines that don't use that exact path to Unity).

In case you're interested in the changes I made, the relevant diff is located [here](https://github.com/michael-looply/facebook-sdk-for-unity/compare/d2e361a067e9d45414649d2e875e86fdba84f63a...7d9f71f06e34d9fc248b2ecf055b253fdd5011ae). Package is located [here](https://github.com/michael-looply/facebook-sdk-for-unity/releases/tag/sdk-version-7.17.2-2019.2.0f1).

Let me know if you have any issues getting up and running.

**Comment by patm1987** [comment]
Hi @andnoonesthere,

Did @michael-looply resolve the issue to your liking, or should we investigate more?
If their suggestions don't help, are you using the latest (6.3.0) Unity SDK with Jetifier enabled in the settings:
![image](https://user-images.githubusercontent.com/1111611/63303766-0b32a300-c29e-11e9-8765-9ec3bf8222d0.png)

Thanks,
--Patrick

**Comment by andnoonesthere** [comment]
Yes, fix for Facebook SDK provided by Michael fixed it. I will close this issue for now.

**Comment by walaoRIKI** [comment]
> 
> 
> Hey @andnoonesthere, I had the same issue and spent some time yesterday making a fork that functions w/ 2019.2.0f1 and Firebase. I've tested functionality of both SDKs on Android and iOS and it _looks like_ everything's running as expected. As a warning, the changes in my fork should make the build process backwards-incompatible when building the SDK via the provided scripts with Unity versions prior to 2019.2.0f1.
> 
> Note that if you want to build the SDK locally, I updated the repo to require configuration of an environment variable so that Hub-based Unity instances can be used (the **.csproj** files and shell scripts have hard-coded paths in this repo, making it impossible to build on machines that don't use that exact path to Unity).
> 
> In case you're interested in the changes I made, the relevant diff is located [here](https://github.com/michael-looply/facebook-sdk-for-unity/compare/d2e361a067e9d45414649d2e875e86fdba84f63a...7d9f71f06e34d9fc248b2ecf055b253fdd5011ae). Package is located [here](https://github.com/michael-looply/facebook-sdk-for-unity/releases/tag/sdk-version-7.17.2-2019.2.0f1).
> 
> Let me know if you have any issues getting up and running.
> 
> Edit: Been flipping back and forth between the issue lists on both SDKs and posted this on the wrong SDK's issue! Will re-post on the Facebook SDK issue, apologies!

Thanks for the solution :D
