### ISSUE TITLE
Unity Editor Freezes (Firebase SDK 6.2.2 + 6.3.0)

### ISSUE THREAD

**Issue by yakirbu** [firebase/quickstart-unity#445]
After upgrading Firebase from 6.1.1 to 6.2.2 (almost all firebase packages),

When calling GetValueAsync() In verbose log mode,
the console prints "[conn_0] websocket message received" endlessly. 
Even when we stop the game, the console keeps printing the message.

When we reload the scripts / change the scripts / replay the game or anything that causes Unity to 'Reload Assemblies', Unity freezes (probably because the previous connection is still ongoing, and that might cause the freezes.

**Comment by yakirbu** [comment]
After turning on 'Verbose' logging, the console keeps printing endless messages of: "websocket message received", even when the game isn't running.
maybe that's part of the issue, then when I press 'Play' again, finally the websocket messages stops (also console clears on play) and it freezes as usual.

**Comment by radi-cho** [comment]
Hello. I had the same problem (with different versions tho). You can check out the [Unity Editor log](https://docs.unity3d.com/Manual/LogFiles.html) to see what possibly goes wrong:
```
macOS		~/Library/Logs/Unity/Editor.log
Windows 	C:\Users\_YOUR-USERNAME_\AppData\Local\Unity\Editor\Editor.log
```
In my case I solved the issue by re-importing all the Firebase packages I use with consistent versions.

Do **not** use some packages in 6.1.1 and others in 6.2.2. Clean the project, run the dependency resolver and if needed run `Assets -> Reimport All` & Restart the editor.

As a workaround: Some of the APIs are working in the editor for easier testing, but some files needed may be corrupted due to the update. If the reimports doesn't help you, just find which boilerplate code causes problems and comment it during the editor work. In my case I had a RemoteConfig initialization, but the Remote Config Editor dll was missing. As temprorary workaround I commented my remote config initialization during work in the editor. Then uncommented it for native Android/iOS builds. Later found out the actual issue and reimported the package which restored the missing dll.

Hopefully this is helpful ;)

**Comment by DellaBitta** [comment]
Hi @yakirbu,

Unfortunately I was not able to reproduce this issue.  Could you please alter testapp/database to reproduce the issue, and post the changes you made?

**Comment by yakirbu** [comment]
> Hello. I had the same problem (with different versions tho). You can check out the [Unity Editor log](https://docs.unity3d.com/Manual/LogFiles.html) to see what possibly goes wrong:
> 
> ```
> macOS		~/Library/Logs/Unity/Editor.log
> Windows 	C:\Users\_YOUR-USERNAME_\AppData\Local\Unity\Editor\Editor.log
> ```
> 
> In my case I solved the issue by re-importing all the Firebase packages I use with consistent versions.
> 
> Do **not** use some packages in 6.1.1 and others in 6.2.2. Clean the project, run the dependency resolver and if needed run `Assets -> Reimport All` & Restart the editor.
> 
> As a workaround: Some of the APIs are working in the editor for easier testing, but some files needed may be corrupted due to the update. If the reimports doesn't help you, just find which boilerplate code causes problems and comment it during the editor work. In my case I had a RemoteConfig initialization, but the Remote Config Editor dll was missing. As temprorary workaround I commented my remote config initialization during work in the editor. Then uncommented it for native Android/iOS builds. Later found out the actual issue and reimported the package which restored the missing dll.
> 
> Hopefully this is helpful ;)

Unfortunately, I'm not using any packages from 6.1.1 (removed all completely and validated)
Also, reloading all assets didn't help.
I'm not missing any dll, after using debugger, I noticed that my it stops when it reaches the point where I call 'GetValueAsync()' to retrieve data from Realtime-Database.
As I mentioned earlier, when using verbose log mode, it keeps printing "[conn_0] websocket message received" endlessly even after stopping the game.

**Comment by radi-cho** [comment]
@yakirbu can you post the code where you call `GetValueAsync`?

**Comment by yakirbu** [comment]
> @yakirbu can you post the code where you call `GetValueAsync`?

```
public async Task<T> GetData<T>(DatabaseReference dbRef, string child = null, string orderByChild = null, string equalTo = null)
    {
        Query tempRef = dbRef;
        if (!string.IsNullOrEmpty(child))
            tempRef = tempRef.Reference.Child(child);
        if (!string.IsNullOrEmpty(orderByChild))
            tempRef = tempRef.OrderByChild(orderByChild);
        if (!string.IsNullOrEmpty(equalTo))
            tempRef = tempRef.EqualTo(equalTo);
        var tempTask = tempRef.GetValueAsync();
        var snap = await tempTask;
        if (snap != null && snap.ChildrenCount > 0)
        {
            T val = default;
            foreach (var snapChild in snap.Children)
            {
                var json = snapChild.GetRawJsonValue();
                if(json[0] != '{')
                {
                    json = "{\"" + snapChild.Key + "\":" + json + "}";
                }
                val = GetObjFromJSON<T>(json);
                var keyField = val.GetType().GetField("key");
                if (keyField != null)
                    keyField.SetValue(val, snapChild.Key);             
            }
            return val;
        }
        Debug.Log("error - no children");
        return default;       
    }
```

**Comment by patm1987** [comment]
Thanks for that sample @yakirbu.

Can you give us some information on your current setup?
Unity version.
Unity Editor platform (mac/win/linux).
Unity target (android/ios/other). I know that this is an editor issue, but there could still could be some configuration changes according to your target platform.

Exceptions are used to indicate errors in data retrieval. Can you let us know if you see any of those?
You may see in our examples/docs that we handle these with `task.IsFaulted`, but an exception will be raised instead that you should try to capture with a try/catch block if you don't check this field.

If you don't mind, it would help us a _ton_ if you could get us instructions for how to reproduce this issue in the [test app](https://github.com/firebase/quickstart-unity/tree/master/database/testapp).

Another thing that would be super helpful if you could try is trying to take more direct control of the FirebaseDatabase.DefaultInstance. Internal to Firebase, this is currently a weak reference (although it should stay around for the duration of your query). If you have any sort of manager class (say, where you call CheckAndFixDependenciesAsync), it would be really helpful to know if keeping a reference there makes your issue go away.

Similarly, if you're already keeping a reference to FirebaseDatabase.DefaultInstance around, try setting it to null in OnDestroy. Ex (I'm writing this inline, so there may be a typo or two):
```
public class DatabaseManager: MonoBehaviour {
    FirebaseDatabase _db;
    void Start() {
        _db = FirebaseDatabase.DefaultInstance;
    }

    void OnDestroy() {
        _db = null;
    }
}
```

This changes behavior a little because in the UnityEditor, all the native plugins are kept around between play cycles (when you stop playing the game, the Database stays in its current state). Clearing all references to the database might clear it out.

Now, this might not work since you have an active query going on (it seem). What you can also do is try putting in a FirebaseDatabase.DefaultInstance.Dispose(); in a manager class (say in an OnApplicationQuit() callback). This _should not_ be necessary, but let us know if it does fix your issue!

I look forward to your response!
--Patrick

**Comment by yakirbu** [comment]
Hi,
So I'm glad to say that this issue is now resolved.
I've managed to fix it by doing a thorough clean-up to my project (Including Library folder and unused plugins).
Can't really say what caused the issue, but I'm glad it is no longer happening.
