### ISSUE TITLE
Sending Firebase analytics from OnApplicationQuit

### ISSUE THREAD

**Issue by ColorTwist** [firebase/quickstart-unity#451]
Hello,

Question, would it be a good practice to send some information to Firebase analytics from the App in the function [OnApplicationQuit ](https://docs.unity3d.com/ScriptReference/MonoBehaviour.OnApplicationQuit.html)(Triggers when the application quits), 
could it cause any issues?

I want to send values like how much time used in the App and some other statics before quit.
I am sending total time as a float of total seconds dividing by 60 to get a float value 'like' minutes and seconds.

**Comment by patm1987** [comment]
Hi @ColorTwist,

I've done a little bit of digging on this, and have a short answer and a fun answer.

The short answer is that you should be safe to send the data in OnApplicationQuit, but I'd probably recommend [OnApplicationPause](https://docs.unity3d.com/ScriptReference/MonoBehaviour.OnApplicationPause.html) on iOS and Android.

The long answer is that on Android, events are sent in Google Play Services. Once you log an event, it should get logged even if your app isn't running.

On iOS, the behavior is a little different. Firebase Analytics attempts to send all events up in the call to [applicationDidEnterBackground](https://developer.apple.com/documentation/uikit/uiapplicationdelegate/1622997-applicationdidenterbackground). If you look at the documentation for [OnApplicationQuit](https://docs.unity3d.com/ScriptReference/MonoBehaviour.OnApplicationQuit.html), it indicates that this may not be called immediately unless you have "Exit on Suspend" selected in the player settings. This leads me to assume that it's associated with the [applicationWillTerminate](https://developer.apple.com/documentation/uikit/uiapplicationdelegate/1623111-applicationwillterminate) callback which will happen after applicationDidEnterBackground. In this case though, and since the user may be offline anyway when an event is logged, Firebase Analytics does try to cache all the events locally. Then, the next time your game is running and the player has internet access, it will try to upload your events.

I have seen subtle changes between Unity versions when relying on this sort of native-level behavior in the past. The good news is that you can easily test the exact behavior for your combination of Unity, Analytics, your player settings, and your particular stack of other native plugins quickly using [realtime analytics](https://firebase.googleblog.com/2017/03/realtime-analytics-for-everyone.html).

I hope that this all helps!
--Patrick

**Comment by ColorTwist** [comment]
Thanks, @patm1987  for the reply.

Then I'll have to move to `OnApplicationPause` and find a way to distinguish between if the app Quit or Paused. Looking to know where player truly existed APP and not paused it to go to "Whatsup" and write something and return back again.


Regarding iOS, I guess the 'fun' with it will be with I publish the APP on iOS :)

**Comment by patm1987** [comment]
Awesome! I'm closing this issue, but do not hesitate to re-open and comment some more if you have no related questions.

I do find that, when at all possible, it's best to try to treat OnApplicationPause(true) as a pseudo-quit (in that you should try to persist everything as if you will need to resume from there, but try not to logically quit the game if possible). Something that occurred to me is that onDestroy (what typically corresponds to OnApplicationQuit) may not always get called on Android: https://developer.android.com/reference/android/app/Activity.html#onDestroy()
via
https://answers.unity.com/questions/824790/help-with-onapplicationquit-android.html

and I think similar rules may apply to iOS, especially in low memory situations.
