### ISSUE TITLE
CancellationToken ambiguous using Unity.Tasks dll

### ISSUE THREAD

**Issue by MartinGonzalez** [firebase/quickstart-unity#453]
Unity editor version: 2018.3.14f1
Firebase Unity SDK version: 6.0.0
Firebase plugins in use (Auth, Database, etc.): Dynamic Links
Additional SDKs you are using (Facebook, AdMob, etc.): UniRx
Platform you are using the Unity editor on (Mac, Windows, or Linux): Mac
Platform you are targeting (iOS, Android, and/or desktop): PC, iOS, Android

## Please describe the issue here:
My main problem is the following:

> CancellationToken' is an ambiguous reference between `System.Threading.CancellationToken' and `UniRx.CancellationToken'

This is when using the Unity.Tasks dll that comes with firebase plugins and UniRx plugin.
Without Unity.Tasks dll the error is gone because UniRx handle correctly .net versions. I would like to know what that Unity.Tasks dll has. Are you adding System.Threading class from 4.x inside of it?

**Comment by MartinGonzalez** [comment]
I understand that you want to use standard libraries, but it's like you are owning .net classes. If any other plugin does something similar to what you did code cannot coexists because libraries gonna be duplicated.
I guess the best approach to avoid ambiguity is to wrap those system classes Firebase need under Firebase namespace.
Just want to know if this can be possible, if not I'll close the issue.

**Comment by stewartmiles** [comment]
@MartinGonzalez we're not owning the standard libraries, as Alex mentioned we already namespace our usage of Tasks to the `Unity.Tasks.dll` and `Unity.Compat.dll` so that all references from Firebase libraries actually point at those DLLs first which are then either implemented by those components or redirect to system libraries.  With .NET 3.x if you're using another System.Threading.Tasks then as Alex pointed out you can replace Parse/Plugins/Unity.Tasks.dll and Parse/Plugins/Unity.Compat.dll with DLLs that redirect to the types in the library that you're using https://github.com/stewartmiles/Parse-SDK-dotNET/tree/master/Unity.Tasks.TypeForwards and https://github.com/stewartmiles/Parse-SDK-dotNET/tree/master/Unity.Compat.TypeForwards do this for .NET 4.x for example.

If you're using .NET 4.x then use System.Threading.Tasks and file a bug against UniRx to do the same as it sounds like it's polluting the system namespace.  If you're using .NET 3.x you'll need to build type forwarding DLLs https://docs.microsoft.com/en-us/dotnet/framework/app-domains/type-forwarding-in-the-common-language-runtime for Unity.Tasks.dll and Unity.Compat.dll that point at the types you want to use.  That _may_ cause other issues though if the Tasks implementation doesn't meet all of the requirements provided by the Parse implementation.
