### ISSUE TITLE
Can't receive different Registration Tokens to manage pushes for different users on the same device/app.

### ISSUE THREAD

**Issue by fliperamma** [firebase/quickstart-unity#459]
## Please fill in the following fields:
Unity editor version: 2019.1.14f
Firebase Unity SDK version: 6.2.2
Firebase plugins in use (Auth, Database, etc.): Messaging, Analytics, DynamicLinks and Crashlytics
Additional SDKs you are using (Facebook, AdMob, etc.): None
Platform you are using the Unity editor on (Mac, Windows, or Linux): Mac
Platform you are targeting (iOS, Android, and/or desktop): iOS and Android

## Please describe the issue here:
(Please list the full steps to reproduce the issue. Include device logs, Unity logs, and stack traces if available.)
I have a project which supports multiple user accounts. I would like to retrieve new tokens after logging in again so the pushes would be specific to the user that just logged in.

- Initialize Firebase Messaging as per example (FirebaseApp.DefaultInstance)
- Register for messages and token
- Confirm you received the token
- Unregister for messages and token
- Call Dispose on the FirebaseApp instance
- Repeat from the beginning and confirm that now no token is received

## Please answer the following, if applicable:
Have you been able to reproduce this issue with just the Firebase Unity quickstarts (this GitHub project)?
- The gihub project doesn't support this.

**Comment by stewartmiles** [comment]
Hi @fliperamma are you saying it doesn't work or you don't know how to do it?

I'm assuming the latter, you need to clear the token for the user using the InstanceId API then you can fetch a new token.  https://stackoverflow.com/questions/40315345/change-update-firebase-notification-token-or-instance-id-forcefully-via-code

The thing is this will have pretty nasty side-effects on other parts of Firebase, like Remote Config since it also uses the same token for targeting users.

Typically for this sort of thing, especially since notifications are outside of the app where the user isn't logged in, developers tell users to use multiple accounts on their device rather than supporting multiple sign-in in the application.

**Comment by fliperamma** [comment]
Hey @stewartmiles, thanks for getting back to me :)
We basically need to support an old version of this project, which was built using multiple accounts. Migrating everything is out of the table, for now at least.

Do we have access to the InstanceId API in the Unity plugin? I found it [here](https://firebase.google.com/docs/reference/unity/class/firebase/instance-id/firebase-instance-id) but it doesn't seem to be available in the 6.2.2 version, at least.
