### ISSUE TITLE
Unity Editor freezes at second Play Mode

### ISSUE THREAD

**Issue by unnanego** [firebase/quickstart-unity#460]
Hi! 
Haven't found a similar issue. It is mentioned here: https://issuetracker.unity3d.com/issues/editor-freezes-when-entering-play-mode-and-firebase-getvalueasync-was-used-in-the-last-play-mode
It says unity is not going to fix this. Is this the firebase issue? Will it be resolved? I'm using 2019.2.2 and Firebase 6.4.0 and I have this problem.

**Comment by unnanego** [comment]
Setting database reference to null in OnDestroy resolved the issue (so far).

**Comment by stewartmiles** [comment]
@chkuang-g is this related to the strong reference thing you're working on?

**Comment by kevinfoley** [comment]
@stewartmiles  We are experiencing this issue with Firebase 6.6.0, Unity 2019.2.8f1. unnanego's workaround does not affect the issue.

**Comment by chkuang-g** [comment]
@unnanego 
Your issue should be fixed in 6.6.0.  Two things may be related to the freeze

- 6.5.0 fixed the freeze when playing in the editor for the more than once or when closing the editor, when keeping a static reference to either FirebaseAuth or FirebaseDatabase instances
https://firebase.google.com/support/release-notes/unity#version_650_-_september_10_2019
- 6.6.0 fixed a couple to issues with database when play in editor.
https://firebase.google.com/support/release-notes/unity#version_660_-_september_25_2019 
Could you verify if 6.6.0 fixed your issue?

@kevinfoley 
It is very easy for us to miss a comment in a closed issue.  To help us to better support your issue, could you create a new issue, follow the template and offer some more detail in it?  Ex. Are you having the same freeze issue when play for the second time after calling GetValueAsync()?  Could you find anything abnormal in your Editor.log?

Thanks
Shawn
