### ISSUE TITLE
DllNotFoundException: Unable to load DLL 'FirebaseCppApp-6_4_0'

### ISSUE THREAD

**Issue by SteliosDaVitzi** [firebase/quickstart-unity#466]
## Please fill in the following fields:
Unity editor version: 2019.1.8
Firebase Unity SDK version: 6.4.0
Firebase plugins in use (Auth, Database, etc.):Analytics,DeepLinks
Additional SDKs you are using (Facebook, AdMob, etc.): GooglePlayServices, Facebook, Appodeal, Game Analytics, AppsFlyer, UTNotifications.
Platform you are using the Unity editor on (Mac, Windows, or Linux): Windows
Platform you are targeting (iOS, Android, and/or desktop): Android

## Please describe the issue here:
We build for arm 64 architecture.All working fine.
We build the game for arm 7 architecture.
One of the first logs appearing is 
DllNotFoundException: Unable to load DLL 'FirebaseCppApp-6_4_0': The specified module could not be found.
09-10 16:32:28.275 19551 19607 E Unity   :   at Firebase.AppUtilPINVOKE.FirebaseApp_DefaultName_get () [0x00000] in <00000000000000000000000000000000>:0
09-10 16:32:28.275 19551 19607 E Unity   :   at Firebase.FirebaseApp.get_DefaultName () [0x00000] in <00000000000000000000000000000000>:0
09-10 16:32:28.275 19551 19607 E Unity   :   at Firebase.FirebaseApp.get_DefaultInstance () [0x00000] in <00000000000000000000000000000000>:0
09-10 16:32:28.275 19551 19607 E Unity   :   at Firebase.DynamicLinks.DynamicLinks..cctor () [0x00000] in <00000000000000000000000000000000>:0
09-10 16:32:28.275 19551 19607 E Unity   :   at WildWestSaga.DeepLinksHandler.OnDestroy () [0x00000] in <00000000000000000000000000000000>:0
09-10 16:32:28.275 19551 19607 E Unity   : Rethrow as TypeInitializationException: The type initializer for 'Firebase.DynamicLinks.DynamicLinks' threw an exception.
09-10 16:32:28.275 19551 19607 E Unity   :   at WildWestSaga.DeepLinksHandler.OnDestroy () [0x00000] in <00000000000000000000000000000000>:0

## Please answer the following, if applicable:
Have you been able to reproduce this issue with just the Firebase Unity quickstarts (this GitHub project)?
Have not tried.

**Comment by tonyjoseph456** [comment]
Same issue is happening for me too. 
`E Unity : Unable to find FirebaseCppApp-6_4_0 E Unity : DllNotFoundException: Unable to load DLL 'FirebaseCppApp-6_4_0': The specified module could not be found. E Unity : at Firebase.AppUtilPINVOKE+SWIGExceptionHelper.SWIGRegisterExceptionCallbacks_AppUtil (Firebase.AppUtilPINVOKE+SWIGExceptionHelper+ExceptionDelegate applicationDelegate, Firebase.AppUtilPINVOKE+SWIGExceptionHelper+ExceptionDelegate arithmeticDelegate, Firebase.AppUtilPINVOKE+SWIGExceptionHelper+ExceptionDelegate divideByZeroDelegate, Firebase.AppUtilPINVOKE+SWIGExceptionHelper+ExceptionDelegate indexOutOfRangeDelegate, Firebase.AppUtilPINVOKE+SWIGExceptionHelper+ExceptionDelegate invalidCastDelegate, Firebase.AppUtilPINVOKE+SWIGExceptionHelper+ExceptionDelegate invalidOperationDelegate, Firebase.AppUtilPINVOKE+SWIGExceptionHelper+ExceptionDelegate ioDelegate, Firebase.AppUtilPINVOKE+SWIGExceptionHelper+ExceptionDelegate nullReferenceDelegate, Firebase.AppUtilPINVOKE+SWIGExceptionHelper+ExceptionDelegate outOfMemoryDelegate, Firebase.AppUtilPINVOKE+SWIGExceptionHelper+ExceptionDelegate overflowDelegate,`

**Comment by AliEnver** [comment]
Same issue is happening 6.3.0 version.

**Comment by markchandler-google** [comment]
Hi SteliosDaVitzi, thanks for the bug report. Just to confirm the problem platform you are having the problem with is arm64-v8a? Looking at the Firebase 6.4.0 package it looks like all the files are there and are built for the correct platform. I will look into this a little more to try and work out what is going on.

**Comment by SteliosDaVitzi** [comment]
Hi!Thanks for the answer.We have the problem when building for arm7.Arm64 works fine.

**Comment by markchandler-google** [comment]
Have you tried running the android resolver as outlined in this other issue about the same problem: https://github.com/firebase/quickstart-unity/issues/362

**Comment by tonyjoseph456** [comment]
Initially I was having issues with the 32 bit as well as 64 bit builds. After a little bit of hard work (removing all plugins including firebase, play service resolver etc) and, deleting library and unwanted project folders and copying the jar and aar files from this project to my project), now the 32 bit build is working fine. But the 64 bit is not working. 

Currently I'm using Unity 2019.2.5f1 and using 32 bit ARM architecture.

**Comment by tonyjoseph456** [comment]
New firebase sdk 6.5.0 is causing the application to crash as soon as its opened. The log is given below:

`--------- beginning of crash
09-16 11:07:36.088 22137 22137 E AndroidRuntime: FATAL EXCEPTION: main
09-16 11:07:36.088 22137 22137 E AndroidRuntime: Process: com.test.vk.ad, PID: 22137
09-16 11:07:36.088 22137 22137 E AndroidRuntime: java.lang.NoClassDefFoundError: Failed resolution of: Lcom/google/android/gms/common/internal/Preconditions;
09-16 11:07:36.088 22137 22137 E AndroidRuntime: 	at com.google.firebase.provider.FirebaseInitProvider.checkContentProviderAuthority(com.google.firebase:firebase-common@@19.0.0:64)
09-16 11:07:36.088 22137 22137 E AndroidRuntime: 	at com.google.firebase.provider.FirebaseInitProvider.attachInfo(com.google.firebase:firebase-common@@19.0.0:44)
09-16 11:07:36.088 22137 22137 E AndroidRuntime: 	at android.app.ActivityThread.installProvider(ActivityThread.java:6528)
09-16 11:07:36.088 22137 22137 E AndroidRuntime: 	at android.app.ActivityThread.installContentProviders(ActivityThread.java:6021)
09-16 11:07:36.088 22137 22137 E AndroidRuntime: 	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5927)
09-16 11:07:36.088 22137 22137 E AndroidRuntime: 	at android.app.ActivityThread.access$1200(ActivityThread.java:200)
09-16 11:07:36.088 22137 22137 E AndroidRuntime: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1673)
09-16 11:07:36.088 22137 22137 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:106)
09-16 11:07:36.088 22137 22137 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:201)
09-16 11:07:36.088 22137 22137 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:6806)
09-16 11:07:36.088 22137 22137 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
09-16 11:07:36.088 22137 22137 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:547)
09-16 11:07:36.088 22137 22137 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:873)
09-16 11:07:36.088 22137 22137 E AndroidRuntime: Caused by: java.lang.ClassNotFoundException: Didn't find class "com.google.android.gms.common.internal.Preconditions" on path: DexPathList[[zip file "/data/app/com.test.vk.ad-p3ge_XU2VeIsEMC025AeCA==/base.apk"],nativeLibraryDirectories=[/data/app/com.test.vk.ad-p3ge_XU2VeIsEMC025AeCA==/lib/arm64, /data/app/com.test.vk.ad-p3ge_XU2VeIsEMC025AeCA==/base.apk!/lib/arm64-v8a, /system/lib64, /vendor/lib64]]
09-16 11:07:36.088 22137 22137 E AndroidRuntime: 	at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:134)
09-16 11:07:36.088 22137 22137 E AndroidRuntime: 	at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
09-16 11:07:36.088 22137 22137 E AndroidRuntime: 	at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
09-16 11:07:36.088 22137 22137 E AndroidRuntime: 	... 13 more
`

**Comment by SteliosDaVitzi** [comment]
Hi!Is there any news or progress about the issue?

**Comment by SteliosDaVitzi** [comment]
When i complete the arm64 build,i open the apk with 7zip, and inside lib/arm64-v8a/ there is like this
![Screenshot_1](https://user-images.githubusercontent.com/35687170/65036916-38ce4300-d955-11e9-8503-9e54ec95e986.png)

but when i build for arm7 and open the .apk, the files inside lib/armeabi-v7a/ are like this
![Screenshot_2](https://user-images.githubusercontent.com/35687170/65037027-7df27500-d955-11e9-8899-5bc0e8ed1553.png)

**Comment by SteliosDaVitzi** [comment]
Fixed it!After poking around a bunch of files, i found that the files "com.google.firebase.firebase-analytics-unity-6.4.0.aar", "com.google.firebase.firebase-app-unity-6.4.0.aar" and "com.google.firebase.firebase-dynamic-links-unity-6.4.0.aar" didn't include the libraries for arm7.After some tries,i figured out that i had to check both arm7 and arm64 in project settings, and then do a force resolve.Now all working fine.

**Comment by AliEnver** [comment]
@SteliosDaVitzi thank you. All working fine.

**Comment by acoale** [comment]
I was going to try this, I updated to 2019.2.5 and Firebase 6.5. But no longer was getting the error. Perhaps it was fixed for 6.5 release.

**Comment by markchandler-google** [comment]
@SteliosDaVitzi im glad you found a fix for the issue. I tested creating a new project in unity and importing the Firebase Sdk's you mentioned and have all the correct files for arm7 after running the Play Services resolver in force mode.   

I ran the standard resolve menu option first and it did say that every thing was good but the apk was missing the files like you had above. I had to run the force resolve menu option and it found a issue with my setup and after fixing that had all the required files.

**Comment by tonyjoseph456** [comment]
@markchandler-google @stewartmiles Earlier in my project I was having this issue with the firebase auth and it was fixed in firebase sdk 6.5.0. Now I'm using 6.5.0. Today I need to add the firebase messaging to my project and this issue started again, with the following log:

`09-19 18:44:28.833 27399 27426 E Unity   : DllNotFoundException: Unable to load DLL 'FirebaseCppApp-6_5_0': The specified module could not be found.
09-19 18:44:28.833 27399 27426 E Unity   :   at Firebase.AppUtilPINVOKE.GetEnabledAppCallbackByName (System.String jarg1) [0x00000] in <00000000000000000000000000000000>:0 
09-19 18:44:28.833 27399 27426 E Unity   :   at Firebase.AppUtil.GetEnabledAppCallbackByName (System.String arg0) [0x00000] in <00000000000000000000000000000000>:0 
09-19 18:44:28.833 27399 27426 E Unity   :   at Firebase.FirebaseApp.InitializeAppUtilCallbacks () [0x00000] in <00000000000000000000000000000000>:0 
09-19 18:44:28.833 27399 27426 E Unity   :   at Firebase.FirebaseApp.CheckDependenciesAsync () [0x00000] in <00000000000000000000000000000000>:0 
09-19 18:44:28.833 27399 27426 E Unity   :   at Firebase.FirebaseApp.CheckAndFixDependenciesAsync () [0x00000] in <00000000000000000000000000000000>:0 
09-19 18:44:28.833 27399 27426 E Unity   :   at Firebase.Sample.Messaging.FCMUIHandler.Start () [0x00000] in <00000000000000000000000000000000>:0 
09-19 18:44:28.833 27399 27426 E Unity   :  
09-19 18:44:28.833 27399 27426 E Unity   : (Filename: currently not available on il2cpp Line: -1)
09-19 18:44:28.833 27399 27426 E Unity   : 
09-19 18:44:28.849 27399 27430 E Unity   : DllNotFoundException: Unable to load DLL 'FirebaseCppApp-6_5_0': The specified module could not be found.
09-19 18:44:28.849 27399 27430 E Unity   :   at Firebase.AppUtilPINVOKE.SetLogFunction (Firebase.LogUtil+LogMessageDelegate jarg1) [0x00000] in <00000000000000000000000000000000>:0 
09-19 18:44:28.849 27399 27430 E Unity   :   at Firebase.AppUtil.SetLogFunction (Firebase.LogUtil+LogMessageDelegate arg0) [0x00000] in <00000000000000000000000000000000>:0 
09-19 18:44:28.849 27399 27430 E Unity   :   at Firebase.LogUtil.Finalize () [0x00000] in <00000000000000000000000000000000>:0 
09-19 18:44:28.849 27399 27430 E Unity   : System.UnhandledExceptionEventHandler:Invoke(Object, UnhandledExceptionEventArgs)
09-19 18:44:28.849 27399 27430 E Unity   :  
09-19 18:44:28.849 27399 27430 E Unity   : (Filename: currently not available on il2cpp Line: -1)
09-19 18:44:28.849 27399 27430 E Unity   : 
09-19 18:44:28.854 27399 27426 E Unity   : DllNotFoundException: Unable to load DLL 'FirebaseCppApp-6_5_0': The specified module could not be found.
09-19 18:44:28.854 27399 27426 E Unity   :   at Firebase.AppUtilPINVOKE.PollCallbacks () [0x00000] in <00000000000000000000000000000000>:0 
09-19 18:44:28.854 27399 27426 E Unity   :   at Firebase.AppUtil.PollCallbacks () [0x00000] in <00000000000000000000000000000000>:0 
09-19 18:44:28.854 27399 27426 E Unity   :   at Firebase.Platform.FirebaseHandler.Update () [0x00000] in <00000000000000000000000000000000>:0 
09-19 18:44:28.854 27399 27426 E Unity   :  
09-19 18:44:28.854 27399 27426 E Unity   : (Filename: currently not available on il2cpp Line: -1)
`

Can you please suggest me a solution for this issue? I need to add firebase authentication and firebase cloud messaging to my app. 

@SteliosDaVitzi I did extracted the apk and found that the lib/arm64-v8a/ and lib/armeabi-v7a/ has the same files in the below screenshot:
![Screenshot 2019-09-19 at 6 54 38 PM](https://user-images.githubusercontent.com/2456421/65248224-74ad0800-db0f-11e9-930e-071b5408b75e.png)

So I dont know why this issue is happening to me again. I have force resolved using play services resolver. still I'm having issue now after adding firebase messaging to the project. Any help from anyone is appreciated. 

Thanks in advance.

**Comment by SteliosDaVitzi** [comment]
Hi @tonyjoseph456 !Did you force resolve having the project settings as below? When i did my settings were checked arm7, checked arm64, scripting runtime and api compatibility set to .NET 4.x , and scripting backend to IL2CPP.
