### ISSUE TITLE
Certain keys generate null results in Mac / Unity

### ISSUE THREAD

**Issue by ripperdoc** [firebase/quickstart-unity#468]
## Please fill in the following fields:
Unity editor version: 2018.3.14f1
Firebase Unity SDK version: 6.5.0, also on 6.4.0, 5.4.2
Firebase plugins in use (Auth, Database, etc.): Database
Additional SDKs you are using (Facebook, AdMob, etc.): Oculus
Platform you are using the Unity editor on (Mac, Windows, or Linux): Mac
Platform you are targeting (iOS, Android, and/or desktop): Desktop (using .NET 4x, Mono)

## Please describe the issue here:
When we GetValueAsync of a subtree which includes certain numbered keys, the result will return a list of nulls instead of expected values.

We use the following test code within quickstart-unity database testapp:
```csharp
protected virtual void InitializeFirebase() {
      FirebaseApp app = FirebaseApp.DefaultInstance;
      app.SetEditorDatabaseUrl("https://our-secret-project.firebaseio.com/");
      if (app.Options.DatabaseUrl != null)
        app.SetEditorDatabaseUrl(app.Options.DatabaseUrl);
      FirebaseDatabase.DefaultInstance.GetReference("path/to/subtree").
      GetValueAsync().ContinueWith(task => {
          DataSnapshot snapshot = task.Result;
          Debug.Log(snapshot.GetRawJsonValue());
        });
      isFirebaseInitialized = true;
    }
```

So if Firebase Realtime Database at "path/to/subtree" has the following imported JSON:
```json
{
  "sessions" : {
    "000006" : {
      "date" : "2019/01/31 10:46"
    },
    "000001" : {
      "date" : "2019/01/30 21:22"
    },
    "000000" : {
      "date" : "2019/01/31 10:46"
    }
  }
}
```
We get this correct printout to log: `{"sessions":{"000000":{"date":"2019/01/31 10:46"},"000001":{"date":"2019/01/30 21:22"},"000006":{"date":"2019/01/31 10:46"}}}`

However, if we modify the JSON to be:
```json
{
  "sessions" : {
    "000005" : {
      "date" : "2019/01/31 10:46"
    },
    "000001" : {
      "date" : "2019/01/30 21:22"
    },
    "000000" : {
      "date" : "2019/01/31 10:46"
    }
  }
}
```
It prints: `{"sessions":[null,null,null,null,null,null]}`

As you see, it generates a list with 6 items even if the DB only contain 3 keys in `session`. If i change the `000005` key to a `000004` number, it prints 5 items from the tree, and so on. Other keys like numbers of shorter character length or other strings seem to work fine. Something seems wrong in the serialization of the SDK when it gets these particular keys.

The real data we use has a long list of sessions written with keys 000000, 000001, 000002 and so on, and these always produce null results when used in this particular environment (it has worked with other environments). We believe we saw the same issue on Firebase 5.4.2 also.

**Comment by alexames** [comment]
Hi @ripperdoc, I was able to find out what the issue was and I have a fix, I'll update this bug issue when the fix has been released.

**Comment by ripperdoc** [comment]
Any chance you could mention what the fix is, so we know if we can do a workaround in the mean time?

**Comment by alexames** [comment]
So the issue was an unexpected combination of behaviors.

Firebase RTDB stores data either as values or as maps (never lists) internally, but if all of the keys are numeric it _may_ automatically convert the requested location to a list when it is passed to you. For example, if you have this data in your database:

```
{
  "0": "Zero",
  "1": "One",
  "2": "Two",
  "3": "Three"
}
```

and request that data like so:

`curl https://[PROJECT_ID].firebaseio.com/test_data.json`

You should get back `["Zero","One","Two","Three"]`.

Additionally, you are allowed to omit some entries and still get a list back, so if you didn't have anything at key "1" for example, it would return `["Zero",null,"Two","Three"]`. As long as all keys are numeric, and at least half are of the keys are present, it will return it as a list instead of a map.

When this behavior was implemented for the desktop, we added the same logic, except there was a slight oversight - when parsing the integer keys to see if the this automatic conversion should happen, our implementation treated "000001" as the integer 1. On other platforms, it won't parse the strings into numbers if they have leading 0's, so that you can have both keys "000001" and "1" in your database and have them be distinct. 

So what ended up happening in your case is that the implementation would see that there were values at keys "000000", "000001", and "000005", and those would be parsed as integers. The largest value was index 5 (which means if this were a list, there would be a total of 6 elements). Because at least half of the elements are present, it would convert it to a list instead of a map. And to top it off, it would go to fill in that list, but the entries at keys "0", "1", and "5" were all empty, so you'd get a list returned full of nulls. But if that final key is "000006", then that means that there would be 7 elements were it converted to a list, and with 3 elements present that's less than half of 7, so the automatic conversion doesn't kick in. 

I've fixed the integer parsing to match the other platforms, so now the behavior should be consistent. The next update is being prepped for release, so it should be out soon, but I can't make any firm promises as to when :-(

In the mean time, if you need to work around this there are a few options. The easiest thing you could do is probably to add a dummy element with a key like "dummy" and manually ignore that entry it in your app. The presence of a non-integer key in the map will ensure no list conversion occurs.

**Comment by alexames** [comment]
Hi @ripperdoc, the [release with the fix](https://firebase.google.com/support/release-notes/unity#realtime-database) has been pushed live. If you update to the the latest SDK (v6.6.0) the problem should be resolved. If you still have issues feel free to re-open this bug.
