### ISSUE TITLE
Firebase Messaging for Unity only showing default icon on notifications.

### ISSUE THREAD

**Issue by arjungaonkar** [firebase/quickstart-unity#477]
## Please fill in the following fields:
Unity editor version: 2018.4
Firebase Unity SDK version: 6.6.0
Firebase plugins in use (Auth, Database, etc.): Messaging
Platform you are using the Unity editor on (Mac, Windows, or Linux): Windows
Platform you are targeting (iOS, Android, and/or desktop): Android

## Please describe the issue here:
Firebase Messaging for Unity only showing default icon on notifications.

**Comment by a-maurice** [comment]
Hi @arjungaonkar 

In order to configure special icons on notifications, it requires additional setup in the AndroidManifest.  Take a look at https://firebase.google.com/docs/cloud-messaging/android/receive#edit-the-app-manifest for instructions on what needs to be done.

If you have done that, validate that the final merged manifest file that gets included in the APK contains this data.
