### ISSUE TITLE
Build in Android Studio (Gradle multidex)

### ISSUE THREAD

**Issue by echeg** [firebase/quickstart-unity#49]
**Preamble:**
We have big projects with 150.000+ references. So we use Gradle export https://dl.dropboxusercontent.com/u/1210840/ShareX/2017/01/chrome_2017-01-24_19-52-42.png

And then in gradle conf we enable multidex

```
        dependencies {
	compile fileTree(dir: 'libs', include: ['*.jar'])

       compile 'com.android.support:multidex:1.0.1' }

   android {
	compileSdkVersion 25
	buildToolsVersion '24.0.3'

	dexOptions {
		javaMaxHeapSize "4g"
	}

	defaultConfig {
		targetSdkVersion 25
		multiDexEnabled true
	}
```

**Problem:**
We tried to integrate Firebase into the empty Unity Project. If we use default build system, all works fine.
But if we export and open in Android Studio we have many errors:

```
Error:(20, 33) No resource found that matches the given name (at 'label' with value '@string/app_name').
Error:Execution failed for task ':firebase-messaging-unity-1.1.1:processDebugResources'.
> com.android.ide.common.process.ProcessException: org.gradle.process.internal.ExecException: Process 'command 'C:\asdk\build-tools\25.0.0\aapt.exe'' finished with non-zero exit value 1
```

Its very strange error because https://dl.dropboxusercontent.com/u/1210840/ShareX/2017/01/studio64_2017-01-24_20-05-29.png
To fix this we need copy strings.xml to firebase-messaging-unity-1.1.1
https://dl.dropboxusercontent.com/u/1210840/ShareX/2017/01/studio64_2017-01-24_20-08-14.png

When we have:
```
Error:Execution failed for task ':processDebugManifest'.
> Manifest merger failed : uses-sdk:minSdkVersion 14 cannot be smaller than version 15 declared in library [FirebaseTest:firebase-common-10.0.1:unspecified] C:\Repos\FirebaseTest\2\FirebaseTest\build\intermediates\exploded-aar\FirebaseTest\firebase-common-10.0.1\unspecified\AndroidManifest.xml
	Suggestion: use tools:overrideLibrary="com.google.firebase" to force usage
```

If we solve this. When we have:

```
Error:Execution failed for task ':processDebugResources'.
> Error: more than one library with package name 'com.google.firebase'
```

"Firebase" module and "firebase-common-10.0.1" module in Androidmanifest have same  package="com.google.firebase"

Tell me how to solve this problem?

**Comment by stewartmiles** [comment]
The `Error:Execution failed for task ':processDebugResources'.
> Error: more than one library with package name 'com.google.firebase'` problem looks like a bug on our end.  This is a dummy AndroidManifest.xml to work with Unity's old build system, you can change the package name to `com.google.firebase.unity` to workaround this error.

The `Manifest merger failed : uses-sdk:minSdkVersion 14 cannot be smaller than version 15` is very bizzare as we support API level 14 and above (see https://android-developers.googleblog.com/2016/11/google-play-services-and-firebase-for-android-will-support-api-level-14-at-minimum.html) .  I just took a look at a local project and I'm seeing the highest requirement set to `<uses-sdk android:minSdkVersion="14" android:targetSdkVersion="22" />` as expected.  Have you taken a look at the merged AndroidManifest.xml to see which component is causing this?


The messaging AAR is located in `Assets/Firebase/m2repository/com/google/firebase/firebase-messaging-unity`.  Copying just the strings.xml is a very bad idea, things will not work.  You should be able to add `Assets/Firebase/m2repository` as a maven repo at the top of your Gradle file which would allow it to find firebase-app-unity and firebase-messaging-unity which include the proguard rules required for the plugin, in addition the messaging AAR includes the messaging service implementation.

**Comment by echeg** [comment]
> uses-sdk:minSdkVersion 14 cannot be smaller than version 15 is very bizzare as we support API level 14

This small problem and yes we solve this by rewrite 
`sdk android:minSdkVersion="14" android:targetSdkVersion="22" /> ` 
to android:minSdkVersion=15 because all our projects use this.

> Copying just the strings.xml is a very bad idea, things will not work.

**Comment by stewartmiles** [comment]
Turns out the number of modifications you need to make should be pretty minimal - at least with our sample application - I've lined up fixes internally to hopefully get into our next release.  I tested this out with Unity 5.5.0f3.

1. Replace `firebase-messaging-unity-1.1.1.srcaar` with the attached file.  This simply changes a line in the AndroidManifest.xml from `<application android:label="@string/app_name">` to `<application>`.  This works around problems a missing reference to merging this package.
1. Delete `Assets/Plugins/Android/firebase-messaging-unity-1.1.1` which *should* result in the Play Services Resolver component expanding it with the updated component.
1. Replace `Assets/Plugins/Android/Firebase/AndroidManifest.xml` with the attached file.  This changes a line in the AndroidManifest.xml from `package="com.google.firebase"` to `package="com.google.firebase.unity"`.
1. Run the Android Resolver (use the `Assets --> Play Services Resolver --> Android Resolver --> Resolver Client Jars` menu option).
1. Export the Android Studio project.
1. (We're working on a better solution for this step) Copy the contents of `Assets/Plugins/Android/Firebase/libs/` to `your_android_studio_project/src/main/jniLibs`


[messaging_android_studio_patch.zip](https://github.com/firebase/quickstart-unity/files/729665/messaging_android_studio_patch.zip)
