### ISSUE TITLE
More than one file was found with OS independent path 'lib/arm64-v8a/libFirebaseCppDynamicLinks.so'

### ISSUE THREAD

**Issue by SniperED007** [firebase/quickstart-unity#494]
## Please fill in the following fields:
Unity editor version: 2019.2.8f1
Firebase Unity SDK version: firebase_unity_sdk_6.6.0
Firebase plugins in use (Auth, Database, etc.): 
- FirebaseAnalytics
- FirebaseDynamicLinks
- FirebaseMessaging
Additional SDKs you are using (Facebook, AdMob, etc.): 
- Facebook
Platform you are using the Unity editor on (Mac, Windows, or Linux): 
- Windows
Platform you are targeting (iOS, Android, and/or desktop): 
- Android (IL2CPP - 64bit)

## Please describe the issue here:
Upgraded to Firebase 6.6.0, try do a build to the phone and it throws the following error:
More than one file was found with OS independent path 'lib/arm64-v8a/libFirebaseCppDynamicLinks.so'

I tried deleting all Firebase files in the project and re-importing but got the same issue.
I tried a Force Resolve and then tried to build again but it still throws the same error.

## Please answer the following, if applicable:
Have you been able to reproduce this issue with just the Firebase Unity quickstarts (this GitHub project)?
Unable to reproduce this on a clean project.

What's the issue repro rate? (eg 100%, 1/5 etc)
100%

**Comment by DellaBitta** [comment]
Hi SniperED007,

Could you disable mainTemplate.gradle patching (Assets->Play Services Resolver->Android Resolver->Settings) and force run the resolver again to see if that clears things up?  If not, then please enable Verbose Logging in the Android Resolver Settings and provide the output of the failure?

Thank you!

**Comment by patm1987** [comment]
For clarity as well, when you say you removed all of Firebase did you get the files placed in `Assets/Plugins/Android`? For this specific issue, make sure you don't have duplicate com.google.firebase.firebase-dynamic-links-unity entries (for legacy reasons, we can't keep all of the Firebase plugin under the `Firebase` directory).

Also, if you have a mainTemplate.gradle file, make sure that you don't have the above file listed as a dependency there (the general rule of thumb is that you should never have to manually add any library dependencies to use the Firebase plugin).

It looks like you either have two entries in your mainTemplate.gradle file, two firebase-dynamic-links-unity aar files in your Assets/Plugins/Android directory, or one entry in your mainTemplate.gradle and one entry in Assets/Plugins/Android.

For your output, make sure that you've set this option:
![image](https://user-images.githubusercontent.com/1111611/67309531-44afa680-f4b9-11e9-8d12-28a7c0b8852e.png)

And it would help if you gave us the [entire editor log](https://docs.unity3d.com/Manual/LogFiles.html) since I don't see anything particularly informative WRT the resolver in the Output.txt provided.

**Comment by SniperED007** [comment]
"For this specific issue, make sure you don't have duplicate com.google.firebase.firebase-dynamic-links-unity"
Thanks, this solved the issue for me.

**Comment by patm1987** [comment]
Awesome! If it helps at all in the future to demystify the processes involved, I did a brief writeup of the Play Services Resolver here: https://medium.com/firebase-developers/how-to-manage-your-native-ios-and-android-dependencies-in-unity-like-firebase-921659843aef
