### ISSUE TITLE
Unity Freezes when I use Firebase database functions to reach database

### ISSUE THREAD

**Issue by canernurdag** [firebase/quickstart-unity#496]
Hello guys,

When i use the code below and click play button on Unity, unity freezes. I think there is a bug. Anyone idease?

 `usersDatabase = FirebaseDatabase.DefaultInstance.GetReference("Users");`

Unity: 2019.2.8f1
SDK: 6.6.0

**Comment by DellaBitta** [comment]
Hi canernurdag,

Can you reproduce this behavior in the test app?   If so, could you isolate the code to create small example for us to reproduce the issue? Finally, please provide the platform which you're running on and a log leading up to the hang.

Thank you!

**Comment by yakirbu** [comment]
Also happens to me... I just didn't find a time to report it yet.

It also happened to me in my previous project (Firebase 6.4.0), but I created a new project few days ago, imported newest Firebase version 6.6.0, and same thing happens.
All works in the first X minutes (could be 30-60, or more), after that, if you press 'Play' or change any script, unity freezes.
It's very annoying, and I have to restart Unity many times a day.

**Comment by patm1987** [comment]
For clarity, can either of you replicate this in the [test app](https://github.com/firebase/quickstart-unity/tree/master/database/testapp)? If so, can you let us know what you did (which scripts/data you attached).

I've run into a similar issue prior to 6.6.0, but I believe it's been fixed for a bit. Can you look for any instances of caching the FirebaseApp.DefaultInstance and FirebaseDatabase.DefaultInstance in a Script or MonoBehaviour and ensure that you set that handle to null in OnDestroy? If this fixes your issue, let us know as this shouldn't occur anymore.

If it's the old bug I'm thinking of, the issue was that your game never actually quits when you toggle the play/pause button in Editor. So there's a chance on your second (or later) run that the previous instance of Firebase is still shutting down when you open a new instance causing the Editor to lock up. If you've found a setup where this still occurs, it would help immensely if you could repro it in our QuickStart app!

**Comment by yakirbu** [comment]
When I have some time for testing, I"ll try running the test app and see if it occurs.
I can also send you the new project I started few days ago, and see if it might help figuring out the issue.

**Comment by patm1987** [comment]
The test app is far preferable as it would take less time to setup (most of us have it checked out and configured already!) and makes it easier to build tests for in the future. That said, if you can't repro it in the test app, I'll see what else we can do to try to sort through this!
