### ISSUE TITLE
Unity Editor crashes when entering playmode for the second time.

### ISSUE THREAD

**Issue by spvn** [firebase/quickstart-unity#497]
### Please fill in the following fields:
Unity editor version: 2019.1.14f1
Firebase Unity SDK version: 6.60
Firebase plugins in use (Auth, Database, etc.): Auth and Database
Additional SDKs you are using (Facebook, AdMob, etc.): 
Platform you are using the Unity editor on (Mac, Windows, or Linux): Mac
Platform you are targeting (iOS, Android, and/or desktop): iOS
Scripting Runtime (Mono, and/or IL2CPP): IL2CPP

I've seen this issue reported a couple of times so far, and one of them has been closed: issue #460 

However, I'm still facing this issue where my editor will crash the second time I try to enter play mode, using Auth and Database plugins. It was supposed to be fixed in 6.6.0 but it's still happening to me. Is there any workaround to get things working? Or should I downgrade to a previous version. This is kind of urgent so I hope to receive some help.

I can confirm it happens 100% of the time on my Mac. I'm not sure if it's consistently crashing on Windows too, but I know I was facing crashing problems a few days ago but I didn't make the link to Firebase at that point. I'll try and check again soon.

EDIT: Come to think of it, I think this only started happening when I tried attaching my Intellij Rider Debugger to Unity. I'm using Rider 2019.2. However I'm not 100% sure that this is what caused it.

Also this problem currently doesn't seem to be occurring on my Windows anymore strangely... However even after restarting my Mac, the crashing is still happening  the 2nd time I enter play mode (I don't have my Rider project open).

**Comment by chkuang-g** [comment]
Hi @spvn 

I tried to run Database and Auth quickstart with Firebase SDK 6.6.0 and Unity 2019.1.11f1 and I could not reproduce the crash.  I did not use Rider.

And here I found this Unity issue with Rider which is fixed in 2019.2.0a1 and backported to 2019.1.0b5.
https://github.com/Unity-Technologies/mono/pull/1141
https://issuetracker.unity3d.com/issues/crash-on-clear-assembly-from-modifiers-when-entering-play-mode-from-rider-debug

Could you verify a couple of thing to confirm this as a regression on our side?

- Does it crash if you do not attach Intellij Rider Debugger?  Does it crash if you attach Xcode project to Unity?  You should be able to find the crash point and stack trace for all threads using lldb in Xcode.
- When it crashed, is there any stack trace information from Rider or Editor.log?
- Could you reproduce the same issue with Database and/or Auth quickstart?

Shawn

**Comment by spvn** [comment]
Sorry I took awhile to get back. I realise that I had a wrong URL set when calling SetEditorDatabaseUrl. It was the URL of an older firebase project that wasn't the one I wanted to use for this project. But for some reason the editor would work fine on the first time pressing play but crash on the second time.

This is no longer an issue as the issue stopped happening once I corrected the URL. But thought it was worth highlighting.
