### ISSUE TITLE
Build java.lang.RuntimeException

### ISSUE THREAD

**Issue by tpaslou** [firebase/quickstart-unity#525]
### Please fill in the following fields:
Unity editor version:  2019.2.12f1
Firebase Unity SDK version: 6.7.0
Firebase plugins in use (Auth, Database, etc.): Database
Additional SDKs you are using (Facebook, AdMob, etc.): ARCore , Mapbox
Platform you are using the Unity editor on (Mac, Windows, or Linux): Windows
Platform you are targeting (iOS, Android, and/or desktop): Android
Scripting Runtime (Mono, and/or IL2CPP): Mono

### Please describe the issue here:

My application works on Editor and Connects to my database. Although when i am trying to build in android i get : 

java.lang.RuntimeException: Duplicate class android.support.v4.app.INotificationSideChannel found in modules classes.jar (:androidx.core.core-1.0.0:) and classes.jar (:support-compat-25.1.0:)

UnityEditor.BuildPlayerWindow:BuildPlayerAndRun() (at C:/buildslave/unity/build/Editor/Mono/BuildPlayerWindow.cs:122)

followed by 400errors about : 

Duplicate class android.support.v4.app.INotificationSideChannel$Stub found in modules classes.jar (:androidx.core.core-1.0.0:) and classes.jar (:support-compat-25.1.0:)

UnityEditor.BuildPlayerWindow:BuildPlayerAndRun() (at C:/buildslave/unity/build/Editor/Mono/BuildPlayerWindow.cs:122)

I have already tried to fix with android resolver. 

Any idea ?

**Comment by chkuang-g** [comment]
Hi @tpaslou 

I think the issue is the Mapbox package includes [legacy Android support library](https://developer.android.com/topic/libraries/support-library/packages).  
See Assets/Mapbox/Core/Plugins/Android/support-compat-25.1.0.aar in your project folder.  
As a result, it conflicts with the newer version of the support library, AndroidX, which ARCore and Firebase depends on.  And since Google Play Services requires AndroidX now, it is a very bad idea for a SDK provider to ship with legacy support library, instead of using [Play Services Resolver,](https://github.com/googlesamples/unity-jar-resolver), which helps to resolve the reference and dependency for you.  And you will need to do all the work to [migrate to AndroidX](https://developer.android.com/jetpack/androidx/migrate/artifact-mappings).

I would recommend you to file a bug to Mapbox and recommend them to utilize Play Service Resolver to specify Android dependencies.

\<sales-pitch\>
Or you can use [Map Unity SDK](https://developers.google.com/maps/documentation/gaming/overview_musk).  You might need to contact Google Map team for API key and full version of SDK.
\</sales-pitch\>

If none of these avenues works for you, you would need to make a AndroidDependency,xml file for Mapbox.  I would recommend you to consult with Mapbox team for more detail but the general idea is:
1. Delete support-compat-25.1.0.aar
2. Create a dependencies.xml like [this](https://github.com/googlesamples/unity-jar-resolver/blob/master/sample/Assets/PlayServicesResolver/Editor/SampleDependencies.xml).
3. Use Force Resolve from Android Resolver, which utilize Jetifier to resolve reference and dependencies for you.
    Assets > Play Services Resolver > Android Resolver > Force Resolve

Hope this helps!

Shawn
