### ISSUE TITLE
ApplicationException: Java class com/google/android/gms/common/GoogleApiAvailability not found.

### ISSUE THREAD

**Issue by k1151204** [firebase/quickstart-unity#53]
Hello.
I am a Korean person and I am mistaken in English. Thank you for your patience.
I'm trying to do FCM on FireBase on Android.
However, when I initialize the Start function, I get an error like the picture.

![error](https://cloud.githubusercontent.com/assets/16028998/22457484/0ab2b5c8-e7db-11e6-8f70-36eddfded5d7.jpg)

I want to use FireBase's Analytics and FCM services. However, I am worried about the error because of the error.

Answers I'll wait.

**Comment by k1151204** [comment]
I do not know which AAR file I do not know.

**Comment by stewartmiles** [comment]
Perhaps you have no AAR files in your project under Plugins/Android?

You may have disabled the Play Services Resolver which would add the AAR dependencies for you.  You can enable the Play Services Resolver from the menu under

"Assets --> Play Services Resolver--> Android --> Settings"
Then check "Enable Background Resolution"

Finally, since resolution was probably disabled run it manually using the 
"Assets --> Play Services Resolver--> Android --> Resolve Client Jars" menu option

**Comment by k1151204** [comment]
Wow, thank you very much. Thanks for the help !!!
