### ISSUE TITLE
Action Required Switch to the Play Referrer API by March 1, 2020

### ISSUE THREAD

**Issue by zhangjianshuai** [firebase/quickstart-unity#538]
Hello Google Play Developer,

    We recently announced that we’ll be deprecating the install_referrer intent broadcast mechanism. Because one or more of your apps uses this intent to track referrals, we wanted to ensure you make the switch before March 1, 2020. After this date, new versions of the Play Store app will no longer broadcast the install_referrer intent after app installs.

    Action required

    Migrate to the Play Install Referrer API to track your app installs for the following apps and/or games.The Play Install Referrer API offers better performance, uses a secure communication channel between your app and the Play Store, and offers a more robust solution against spoof and attribution fraud.We know this change may require some additional work on your part and appreciate your understanding.  Thank you for being a part of Google Play.

what can i do for it ? what's the time of firebase-unity sdk update to solve it? thanks~

**Comment by DellaBitta** [comment]
I believe that this is due to a dependency in the Firebase Analytics SDK. I have reached out to that team to discuss it further.  I'll let you know of what I find out.

**Comment by stewartmiles** [comment]
Chatted with @DellaBitta and he's still waiting to hear from the Google Analytics team.

**Comment by DellaBitta** [comment]
Hi @zhangjianshuai ,

which verison of the Firebase SDK are you using, and does occur as an issue for you on the latest release?

**Comment by stewartmiles** [comment]
@zhangjianshuai, @DellaBitta looked into this with our analytics SDK folks and it turns out you'll need to update to the Android analytics library, ideally to `com.google.firebase:firebase_analytics:17.2.0` as the install_referrer intent being deprecated (see [this](https://android-developers.googleblog.com/2019/11/still-using-installbroadcast-switch-to.html)) which was used by the Firebase Analytics Android library prior to version `16.5.0`.  Since `16.5.0` the SDK has moved to use the [Play Install Referrer API](https://developer.android.com/google/play/installreferrer/igetinstallreferrerservice).

Since quite a few Firebase libraries depend upon Firebase Analytics the easiest way to upgrade is to integrate the [6.9.0 release](https://firebase.google.com/support/release-notes/unity#version_690_-_december_27_2019) which depends upon this package.

Alternatively, if you just want to try upgrading the Android libraries and you're not too out of date that the API surface has changed, you could manually update the `Assets/Firebase/Editor/*Dependencies.xml` files to point at the latest Android library releases based upon the Android packages listed [here](https://firebase.google.com/docs/cpp/setup?platform=android#libraries-android-ndk).  For more information about these `*Dependencies.xml` files see https://github.com/googlesamples/unity-jar-resolver#android-resolver-usage
