### ISSUE TITLE
 Unity 2019.2.12 build failed

### ISSUE THREAD

**Issue by marad747** [firebase/quickstart-unity#558]
### Please fill in the following fields:
Unity editor version: 2019.2.12
Firebase Unity SDK version: 6.9.0(dotnet4)
Firebase plugins in use (Auth, Database, etc.): FirebaseMessaging
Additional SDKs you are using (Facebook, AdMob, etc.): No
Platform you are using the Unity editor on (Mac, Windows, or Linux): Windows
Platform you are targeting (iOS, Android, and/or desktop): Android and ios
Scripting Runtime (Mono, and/or IL2CPP): IL2CPP

### Please describe the issue here:
I have project on 2019.2.12, we decided to import firebase notification. I setup project in dev console, import sdk, update all( sdk, jdk, version handler,android resolver) and made build, after some time i have error
Screens:
https://prnt.sc/qq683c
http://prntscr.com/qq68wo
http://prntscr.com/qq696j

### Please answer the following, if applicable:
Have you been able to reproduce this issue with just the Firebase Unity quickstarts (this GitHub project)? - no, when i create empty project on same version - all fine

What's the issue repro rate? (eg 100%, 1/5 etc)

**Comment by paulinon** [comment]
Hi @marad747 thanks for notifying me about your issue. Based on the screenshots you provided, it looks like your issue is similar to this [community post](https://stackoverflow.com/questions/55756647/duplicate-classes-from-androidx-and-com-android-support). If that's the case, simply add the necessary lines in your gradle.properties file.

**Comment by marad747** [comment]
i found solution: need delete core-1.0.0-rc02 from NatShare(plugiin for sharing). But i dont know consequences
