### ISSUE TITLE
Disabling/Hiding FCM iOS push notification when app is in foreground

### ISSUE THREAD

**Issue by devauk** [firebase/quickstart-unity#560]
When my Unity app is in the foreground I receive a push notification and I get a callback to FirebaseMessaging.MessageReceived on my iOS device . I don't want to recieve notifications when the app is in foreground. Is there a way to disable push notification when app is in foreground.

**Comment by a-maurice** [comment]
Hi @devauk 

Just to be clear, when the app is in the foreground you are getting a call on `FirebaseMessaging.MessageReceived`, and not also getting a notification on the tray, or are you getting both?  If the first, then no, there is not a way to disable that, I would recommend adding some logic around the callback you use to check for that state.  If it is the second, please let us know, as that should not be happening.

**Comment by devauk** [comment]
I am getting both, I am getting notification on tray and a call on FirebaseMessaging.MessageReceived when the app is in foreground. I don't want show up the push notification on the tray and don't want to receive FirebaseMessaging.MessageReceived when the app is in the foreground.

**Comment by a-maurice** [comment]
I haven't been able to reproduce getting a notification on the tray when the app is in the foreground, using the quickstart.  Have you had this problem with the quickstart?  Also, what version of Unity, and what version of the Firebase SDK are you using?

As for `FirebaseMessaging.MessageReceived`, that isn't something that is designed to be disabled when in the foreground.  Instead, in the callback that you register to that function you should check if the app is in the foreground, and ignore it if that is the case.

**Comment by devauk** [comment]
I am using unity version 2018.3.13f1 and firebase sdk verso is 5.7.0. I haven't checked with quick start, I am getting this issue in my game.

**Comment by chkuang-g** [comment]
Hi @devauk 

You are using quite old version of Firebase Unity SDK!  Although I did not spot any related from [iOS Release Notes](https://firebase.google.com/support/release-notes/ios), it is worth trying our latest [6.10.0](https://firebase.google.com/download/unity) and see if this resolves your issue.

And again, it would be helpful if you can assist us to find the issue.  For example, able to reproduce with [quickstart](https://github.com/firebase/quickstart-unity/tree/master/messaging/testapp) would be extremely helpful since we use it, and additional test, for our release testing.  Also, the message data would be helpful too.

Thanks,
Shawn

**Comment by stewartmiles** [comment]
@devauk and others, the issue with double notifications is typically related to other SDKs included in the project.  As @chkuang-g and @a-maurice mentioned we don't pop up a notification when the app is in the foreground, so it's possible another SDK is swizzling the notification method and popping it up.  I recommend you try the quickstart and progressively add SDKs used in your game to the quickstart until the problem is reproduced.

**Comment by devauk** [comment]
It is working fine with quickstart sample. I am getting this issue only my app. Is there any specific flags which I need to disable this

**Comment by devauk** [comment]
Got the problem, I was using unity's mobile notification package for local notifications. This package has support for push notification also. When Firebase Messaging and Unity's mobile notification packages integrated together it behaves weirdly. Removing Unity's mobile notification package from the project solved the issue
