### ISSUE TITLE
Dynamic links posted in Facebook wall not working on Android

### ISSUE THREAD

**Issue by SebaDudzic** [firebase/quickstart-unity#575]
### Please fill in the following fields:
Unity editor version: 2018.4.5f1
Firebase Unity SDK version: 5.6, 5.10
Firebase plugins in use (Auth, Database, etc.): Analytics, RemoteConfig, Crashlytics, DynamicLinks
Additional SDKs you are using (Facebook, AdMob, etc.): Admob mediation, Facebook provider for Admob, Facebook SDK, Appsflyer, Android Native Pro,
Platform you are using the Unity editor on (Mac, Windows, or Linux): Windows
Platform you are targeting (iOS, Android, and/or desktop): Android
Scripting Runtime (Mono, and/or IL2CPP): IL2CPP

### Please describe the issue here:
(Please list the full steps to reproduce the issue. Include device logs, Unity logs, and stack traces if available.)

Use case: Post your dynamic link on facebook's wall (You have to post shortened url, because facebook doesn't allow using full firebase dynamic link url for some reason). Click on link.
Current behavior: Opening google play store with my app no matter if I have my app installed. After installing or clicking open there is no link invoked in the app.
Expected behavior: Opening app and invoking link if app is installed. Invoking link after installing app when there was no app on device.

### Please answer the following, if applicable:
Have you been able to reproduce this issue with just the Firebase Unity quickstarts (this GitHub project)?
Yes. It's used in video.

What's the issue repro rate? (eg 100%, 1/5 etc)
100%

Video with bug:
https://drive.google.com/file/d/1anCBvoLETZVhqGw6eyV19z9fGfnzuX4c/view?usp=sharing

**Comment by paulinon** [comment]
Thanks for reporting this issue @SebaDudzic. I was able to reproduce this issue on my end. As an action, I've filed an internal bug report for this. I can't give you any timelines for any updates, so I'll leave this open

**Comment by paulinon** [comment]
Thanks for waiting, @SebaDudzic. It turns out that new Facebook releases disabled the intent redirect in their Android in-app browser. The Google Play Client (version 3.5.12 or later) supports URL of the following form

market://details?id=<id>&url=<deep-link>&min_version=<min_version>
- id: (required) the package name of the app to launch. Example: com.android.vending
- url: (required) This is the URL to pass in the intent. Example: mycompany://show_product?id=12345
- min_version: (optional) The minimum android:versionCode of the application that supports handling the deep-link. If the version of the installed app is less than this, the user will be taken to the details page and asked to update (and then presented with a "Continue" button).

**Comment by SebaDudzic** [comment]
Thanks for response. But is there anything I can do to get Facebook working? Or I have to wait for new Firebase SDK with fix?

**Comment by paulinon** [comment]
Hi @SebaDudzic. Your settings may not enable your links to open externally. To change this setting, simply do the following:

1. Open the Facebook App
2. Click the “hamburger icon” menu near the upper right corner
3. Scroll down to “Settings & Privacy” and tap the down arrow.
4. Tap settings
5. Scroll all the way down and tap “Media and Contacts”
6. Toggle on the “Links open externally” button.

**Comment by SebaDudzic** [comment]
Thanks! We got it working. We had no idea that Facebook has its own settings for links. It's bad for us because we have to explain to users how to enable it. But this is on Facebook :) Thanks!

**Comment by erammos** [comment]
Hello, is any workaround except forcing the users to enable the "Links open externally"?
