### ISSUE TITLE
Apple sign in - credentials for sign in and linking

### ISSUE THREAD

**Issue by MartinVavrek** [firebase/quickstart-unity#576]
Unity editor version: 2018.3
Firebase Unity SDK version: 6.10.0
Firebase plugins in use (Auth, Database, etc.): Auth
Additional SDKs you are using (Facebook, AdMob, etc.): Apple sign in 
Platform you are using the Unity editor on (Mac, Windows, or Linux): MAc
Platform you are targeting (iOS, Android, and/or desktop): iOS
Scripting Runtime (Mono, and/or IL2CPP):IL2cpp

### Please describe the issue here
We are trying to implement apple sign in but we are having a problem with credentials. Since Apple is checking if nonce was already used we can not use same credentials twice - once for login and once for linking account. Solution for native iOS olugin is this one:
https://github.com/firebase/firebase-ios-sdk/issues/4434#issuecomment-564776016
`error.userInfo[FIRAuthErrorUserInfoUpdatedCredentialKey]`

How to solve this in Unity plugin, how can I access error object with fresh credentials returned by firebase? Only thing I get is `FirebaseException` when calling 
```
//this call will be successful
await authInstance.SignInWithCredentialAsync(credential);
//this call will fail due to "Duplicate credential received" exception
await firebaseUser.LinkWithCredentialAsync(credential)
```
### Please answer the following, if applicable:
Have you been able to reproduce this issue with just the Firebase Unity quickstarts (this GitHub project)? yes 

What's the issue repro rate? 100%

**Comment by chkuang-g** [comment]
Hi @MartinVavrek 

Why do you need to link credential after you have signed in with the same credential already?

Shawn

**Comment by MartinVavrek** [comment]
User already has anonymous account, and we are giving him possibility to link this account to Apple sing in. This cant be done in one step. It is the same issue as described here : [github.com/firebase/firebase-ios-sdk/issues/4434](url) but there is no solution for Unity sdk to deal with updated credentials sent from Firebase.

**Comment by chkuang-g** [comment]
Hi @MartinVavrek 

The iOS issue seems a bit different.  That user was trying to sign-in using the credential which was failed to link to current account.  So the order seems to be like this:

1. SignInAnonymous()
2. Link(credential)
3. If 2 failed, SignInWithCredential(credential)

Your order looks like

1. SignInAnonymous()
2. SignInWithCredential(credential)
3. LinkWithCredential(credential)

Step 2 seems redundant. Instead, you just need to do 1 and 3.  If the client has sign-in anonymously before, you do CurrentUser should be available once you create FirebaseAuth.

If you experience the same issue to that iOS post, all you need is to regenerate a new nonce.

Shawn

**Comment by MartinVavrek** [comment]
Thanks, but failed linking is exactly the reason why we are sing in to account in step 2. We just want to avoid that. Instead of getting exception when trying to link, we log in to account and see if we need to unlink it first and we get data about second account to show to user with some error dialog.  
That is how we designed our flow that worked for all other providers (facebook, game centre and google play).

Now it makes sense to rework it to first example just because of Apple and ask user for second credentials (logging in to Apple sing in with password again) only when linking fails. 

But in our case if we would receive fixed credentials in step 3, we can just retry linking without redesigning of login flow.

**Comment by cynthiajoan** [comment]
Hi @MartinVavrek, thanks for providing the details, we are working on a fix for that.

**Comment by DellaBitta** [comment]
Hi @MartinVavrek,

While we work on this issue would it be possible to query the  ProviderData on the signed-in user,  see if there's information from a Apple.com provider, and only link if it's missing but sign in if it's not?

**Comment by pistoleta** [comment]
Hello @MartinVavrek and @chkuang-g .

Having the exact  problem here. Im using the order chkuang-g mentioned:
1.SignInAnonymous()
2.Link(credential)
3. If 2 failed, SignInWithCredential(credential)

With Facebook sdk works flawless, but with Apple Sign-In I get the "Duplicate credential received" exception on the 3rd step. Is this a bug on the Apple Sign In asset or the Firebase SDK?

Hope it gets solved soon,  any workaround on this?
Cheers!!

**Comment by rbehshad** [comment]
@chkuang-g @cynthiajoan Any update on this?

**Comment by pistoleta** [comment]
Still  waiting too

**Comment by ed-yaku** [comment]
As it has been over a month without any update I thought I would check in on the status of this feature request?

I understand that the requirement for Apple Sign In has now been pushed back to June 30, 2020 so this may have had a knock on effect with your scheduling.

Thanks

**Comment by DellaBitta** [comment]
Hi @ed-yaku, we're working on the release of 6.14.0 right now.  Our plan is to subsequently turn around a 16.14.1 release targeting this feature specifically.  I can't quote a timeline but it's high priority.

**Comment by ed-yaku** [comment]
Hi @DellaBitta, thanks for the update!

**Comment by DellaBitta** [comment]
Hi all, 

[Version 6.14.1](https://firebase.google.com/support/release-notes/unity#version_6141_-_may_18_2020) went out yesterday which includes a change for these flows.  

When using Apple Sign In on iOS if a user link failure occurs due to there already being another Firebase account in the project that's linked to the iPhone's Apple account then a Firebase.Auth.FirebaseAccountLinkException will be thrown instead of a standard Firebase.FirebsaeException.  The FirebaseAccountLinkException includes an UserInfo result object with an UpdatedCredential.  If the credential is valid then it can be used to sign in the Apple Linked account via SignInWithCredential without asking for another nonce to be generated.

Please note that LinkAndRetrieveDataWithCredentialAsync must be be used for this operation to contain the UpdatedCredential as the credential is part of the UserInfo object returned by the RetrevieData operation. LinkWithCredentialAysnc will continue to fail with the same error as before.

Some example code below. I'm working to add it to the official [Unity Guide for Firebase Auth](https://firebase.google.com/docs/auth/unity/apple):

```
auth.CurrentUser.LinkAndRetrieveDataWithCredentialAsync(Firebase.Auth.OAuthProvider.GetCredential("apple.com", idToken, rawNonce, null)).ContinueWithOnMainThread( task => {
   if (task.IsCompleted) {
      // Link Success
   } else {
      if (task.Exception != null) {
         foreach (Exception exception in task.Exception.Flatten().InnerExceptions) {
            Firebase.Auth.FirebaseAccountLinkException firebaseEx = 
               exception as Firebase.Auth.FirebaseAccountLinkException;          
            if (firebaseEx != null && firebaseEx.UserInfo.UpdatedCredential.IsValid()) {
               // Attempt to sign in with the updated credential.
               auth.SignInWithCredentialAsync(firebaseEx.UserInfo.UpdatedCredential).ContinueWithOnMainThread(HandleSignInWithUser);
            } else {
               DebugLog("Link with Apple failed:" + firebaseEx );     
            }
         } // end for loop
      } 
   }
});
```

I hope this helps!

**Comment by ed-yaku** [comment]
Hi @DellaBitta, thanks you the update. I'll schedule the work for the upgrade our end and give this a test soon.

**Comment by jiyeershi** [comment]
Hi, @DellaBitta   I am suffering from the same problem
And with Version 6.14.1  
I use  "auth.CurrentUser.LinkAndRetrieveDataWithCredentialAsync" method to link current firebase user (provider is facebook) with a Apple Account  that account is already used to  create a firebase user. I do get "task.IsCompleted" in the callback method.  And this means Link success?

But, I goto  our Firebase Console ->Authentication ->Users,  and I found out my current firebase userid,  I can see the provider is still facebook.

I  do not quite understand with this behavior of "LinkAndRetrieveDataWithCredentialAsync" method

**Comment by DellaBitta** [comment]
Hi @jiyeershi,

Could you clarify the task.IsCompleted check?

Is it the task which attempted the Apple link of a pre-created Firebase User account using the same Apple ID?  Or is the task for the subsequent Sign In attempt with the updated credential returned from the link failure?

The Link *should* fail due to there being another Firebase account linked to the Apple provider.  The subsequent sign-in with the updated credential *should succeed* but the sign-in operation won't link the two accounts for you.  This sign-in is an optional operation to access pre-existing Apple provider Firebase account so that you can merge data between the two Firebase accounts as you see fit.

Please see the guide [Link Multiple Auth Providers to an Account in Unity](https://firebase.google.com/docs/auth/unity/account-linking).  Step 4 discusses how you might plumb data from one provider-linked account to another provider-linked account. 

I hope this was helpful, and if the Link is returning true for both Firebase accounts with the same Apple Sign In ID then please let me know. 

I tested this by creating an email-based Firebase Account (account A) and linking it with the Apple provider on my phone.  I then signed-out of that account and created a new email address account (account B) on my phone, and attempted to link with Apple again.  The linking of account B to Apple fails, but the returned credential in the failure signs me in to account A.

**Comment by jiyeershi** [comment]
Hi @DellaBitta 

I want to implement a function that my pre-existing Facebook Provider Firebase Account Link with A Apple Account.
And For this, i use logic like this:
`Credential credential = OAuthProvider.GetCredential("apple.com", idToken, nonce, null);  //idToken and nonce are returned by Apple Login flow

if (currentFirebaseUser != null)
{
    LinkAccount(credential, delegate(Credential refreshCredential) {
        StartLoginTask(refreshCredential);
    });
}
else
{
    StartLoginTask(credential);
}

private void LinkAccount(Credential credential, Action<Credential> failedAction)
{
    auth.CurrentUser.LinkAndRetrieveDataWithCredentialAsync(credential).ContinueWithOnMainThread( task => {
        if (task.IsCompleted)
        {
            // Link Success 
            Log.Error("Link Success");
        } 
        else
        {
            if (task.Exception != null)
            {
                foreach (Exception exception in task.Exception.Flatten().InnerExceptions)
                {
                    Firebase.Auth.FirebaseAccountLinkException firebaseEx = exception as Firebase.Auth.FirebaseAccountLinkException;
                    if (firebaseEx != null && firebaseEx.UserInfo.UpdatedCredential.IsValid())
                    {
                        failedAction(firebaseEx.UserInfo.UpdatedCredential);
                    }
                    else 
                    {
                        Log.Error("Link with Apple failed:" + firebaseEx );
                    }
                }
            }
        }
    });
}`

And I do my test like this:

1.  I install my app that recently implemented Apple login flow,  and I sign in Apple with my AppleId, and I use idToken, rawNonce returned by Apple login flow to create a Credential
to generate my Apple Provider Firebase account with Firebase Unity SDK(6.14.1). And this step went ok, because I go to my firebase console and found this account out. 

2. Then I uninstall my app, and reinstall my app, then I sign in my Facebook Provider Firebase account, this login flow was implemented Last year to identify our user to upload their game data.
This step also went ok, because i can do sync with my RealTime Database use this Facebook Provider Firebase account.

3. Last, With my Facebook Provider Firebase account login,  I sign in Apple ID to get idToken, rawNonce to create a Credential, and use this Credential and LinkAndRetrieveDataWithCredentialAsync Methd 
to attempt to link of current firebase user. 
I get "task.IsCompleted" in the callback of LinkAndRetrieveDataWithCredentialAsync method, but this means Link Success in official document?

I do think my operation in step 3 should triger "Firebase.Auth.FirebaseAccountLinkException", then I can use "FirebaseAccountLinkException.UserInfo.UpdatedCredential" to sign in my Apple Provider Firebase
account, so that I can change my current firebase user.

Please give me some help

**Comment by jiyeershi** [comment]
Hi, @DellaBitta 
I want to implement a function that my pre-existing Facebook Provider Firebase Account Link with A Apple Account.
And For this, i use logic like this:

1. Create a credential by use idToken and nonce returned by Apple Login flow
`Credential credential = OAuthProvider.GetCredential("apple.com", idToken, nonce, null);`

2. To use a credential created in above step to Attemp Link with current Firebase user of My running Game, that Firebase user is related to Facebook Provider, 
If Link operation failed, i will use UpdatedCredential included in FirebaseAccountLinkException returned by callback of LinkAndRetrieveDataWithCredentialAsync to sign in.

### `auth.CurrentUser.LinkAndRetrieveDataWithCredentialAsync(credential).ContinueWithOnMainThread( task => {
    if (task.IsCompleted){
        // Link Success 
        Log.Error("Link Success");
    } 
    else{
        if (task.Exception != null){
            foreach (Exception exception in task.Exception.Flatten().InnerExceptions){
                Firebase.Auth.FirebaseAccountLinkException firebaseEx = exception as Firebase.Auth.FirebaseAccountLinkException;
                if (firebaseEx != null && firebaseEx.UserInfo.UpdatedCredential.IsValid()){
                    StartLoginAuthTask(firebaseEx.UserInfo.UpdatedCredential);
                }
                else{
                    Log.Error("Link with Apple failed:" + firebaseEx );
                }
            }
        }
    }
});`


### I do my test like this:

1.  I install my app that recently implemented Apple login flow,  and I sign in Apple with my AppleId, and I use idToken, rawNonce returned by Apple login flow to create a Credential
to generate my Apple Provider Firebase account with Firebase Unity SDK(6.14.1). And this step went ok, because I go to my firebase console and found this account out. 

2. Then I uninstall my app, and reinstall my app, then I sign in my Facebook Provider Firebase account, this login flow was implemented Last year to identify our user to upload their game data.
This step also went ok, because i can do sync with my RealTime Database use this Facebook Provider Firebase account.

3. Last, With my Facebook Provider Firebase account login,  I sign in Apple ID to get idToken, rawNonce to create a Credential, and use this Credential and LinkAndRetrieveDataWithCredentialAsync Methd 
to attempt to link of current firebase user. 
I get "task.IsCompleted" in the callback of LinkAndRetrieveDataWithCredentialAsync method, but this means Link Success in official document?

I do think my operation in step 3 should triger "Firebase.Auth.FirebaseAccountLinkException", then I can use "FirebaseAccountLinkException.UserInfo.UpdatedCredential" to sign in my Apple Provider Firebase
account, so that I can change my current firebase user.

Please give me some help

**Comment by DellaBitta** [comment]
Hi @jiyeershi,

I think this might be a separate issue than the one reported (the fact that you can link to an Apple account that is already linked). If you find the following doesn't help debug the problem then please open up a new ticket and mention me in it.  Thank you.

Just a note: uninstalling an app from the phone does not clear the currently signed in user. This data is stored in secure storage and reinstalling the app should continue to re-use the last user that was signed-in.  I suggest that you shouldn't assume that uninstalling the app clears the auth state in case that affects the results. Signing-out the current user is your best bet.

I just ran through another test with a user that was linked to a Google provider account (sorry I don't have a Facebook developer account to test with) to ensure that our mismatch of results wasn't something to do with attempting to link with an email & password auth provider like I have been. Unfortunately I could not produce the problem with an attempt to link a Google provider account to an already linked Apple account, either.  The link request properly produced an exception with an updated credential to sign-in with.

My suggestion is to print out the user data every step of the way.  There's a (good implementation to log everything in our quickstart)[https://github.com/firebase/quickstart-unity/blob/74621d5eee844ae0dd4f0adbb0e478ae87779de1/auth/testapp/Assets/Firebase/Sample/Auth/UIHandler.cs#L204].  This way we can ensure each operation originates from the correct user.  The example implementation also logs the providers that a particular user is linked with which could be helpful.

I suggest adding code to log user data when:
 - your app starts to ensure that there's no signed-in user,
 - you sign in with Apple and receive a new user,
 - you sign in with Facebook and receive a new user,
 - and finally, log the user before you attempt to link w/ Apple and also DisplayUserInfo (from the quick start example) on the data you receive in the task.IsComplete on link success.

Thanks.

**Comment by jiyeershi** [comment]
Hello @DellaBitta 
Thanks for your very useful advice.
These information inspire me a lots. I improve some implement logic and add some log followed the above link you refered to. And now, I think i have solved this problem.
Thanks a lot again.

**Comment by DellaBitta** [comment]
Hi @jiyeershi,

Thanks for getting back to us with the good news.  Great to know!

@MartinVavrek and @ed-yaku, I'm going to close this issue for now since the change went live in 6.14.1, and is also in the latest 16.15.0.  If you still have problems after updating to the latest version then please reopen the issue and/or mention me.  Thanks!
