### ISSUE TITLE
Build Error 'targetApi', valid instructions

### ISSUE THREAD

**Issue by querywilly** [firebase/quickstart-unity#583]
### Please fill in the following fields:
Unity editor version: 5.6.7
Firebase Unity SDK version: unity 5.6.7F1
Firebase plugins in use Realtimedatabase 6.10.0
Additional SDKs you are using facebook admob
Platform you are using the Unity editor on (Mac, Windows, or Linux): macos
Platform you are targeting (iOS, Android, and/or desktop): android
Scripting Runtime (Mono, and/or IL2CPP):Mono

error message
when i tried build.
error message
'targetApi', valid instructions are : REMOVE,REPLACE,STRICT.

how can i delete or replace.
firebase manifest generated automatic

**Comment by paulinon** [comment]
Thanks for reporting this issue @querywilly. Your issue sounds similar to this [community post](https://stackoverflow.com/questions/35844427/gradle-fails-on-manifest-merging-for-targetapi). Try following along to see if it helps resolve your issue. Otherwise, please share a [minimal, reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of your project so I can isolate what's causing the issue.

**Comment by querywilly** [comment]
@paulinon 
its same issue.
but firebase auto generate androidmanifest file.
i cant change "targetapi"
all manifest file not include targetapi.

**Comment by paulinon** [comment]
Hi @querywilly. Could you try updating your Unity editor and see if the issue persists? If it does, please provide a [minimal, reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) so I can replicate the issue and hopefully give you a solution. Thanks.

**Comment by DellaBitta** [comment]
Hi @querywilly,

Could you try to run Assets->Play Services Resolver->Android Resolver->Force Resolve, and see if that clears up the issue? Thanks.
