### ISSUE TITLE
FCM sample can't receive token on the first time  app starts on iOS device.

### ISSUE THREAD

**Issue by KyoCloudS** [firebase/quickstart-unity#603]
### Please fill in the following fields:
Unity editor version: 2017.4.30
Firebase Unity SDK version: 6.7.0
Firebase plugins in use (Auth, Database, etc.):FCM
Additional SDKs you are using (Facebook, AdMob, etc.): 
Platform you are using the Unity editor on (Mac, Windows, or Linux): Mac
Platform you are targeting (iOS, Android, and/or desktop): iOS
Scripting Runtime (Mono, and/or IL2CPP):IL2CPP

### Please describe the issue here:
(Please list the full steps to reproduce the issue. Include device logs, Unity logs, and stack traces if available.)
FCM sample can't receive token on the first time  app starts on iOS device.
I have agree the permisson  on push.
I must restart the app to receive the token.

### Please answer the following, if applicable:
Have you been able to reproduce this issue with just the Firebase Unity quickstarts (this GitHub project)?
yes,any time.every time i  try,i fail to get the token on the first time the app starts.
I must restart to get  token.

What's the issue repro rate? (eg 100%, 1/5 etc) 
100% on ios device.

**Comment by jonsimantov** [comment]
Please try updating to the most recent version of the Firebase Unity SDK, 6.12.0, and see if that fixes your issue. Since this is happening with the quickstart, you should also verify that your app ID is set up for APNS push notifications on Apple's developer site, and that the correct bundle ID is being used in the Firebase project.

**Comment by KyoCloudS** [comment]
ok,i'll test in 6.12.0
