### ISSUE TITLE
Slow download from Storage- even for small files

### ISSUE THREAD

**Issue by shlighter** [firebase/quickstart-unity#654]
Unity editor version: 2019.3.6f1
Firebase Unity SDK version: 6.13
Source you installed the SDK : unitypackage
Firebase plugins in use : Auth, sorage
Platform you are using the Unity editor on : Windows, Android

Why is it so slow to download an image? I get the same results for 60kb image and 1MB image file it's always around 0.6 seconds to download it (avg) is there a minimum processing time no matter how small the file is?
  

    const long maxAllowedSize = (1 * 1024*1024);
    storage = FirebaseStorage.DefaultInstance;
    storage_ref = storage.GetReferenceFromUrl("gs://myproject.appspot.com/1mbImage.jpg");
    DateTime before = DateTime.Now;
    var task2 = await storage_ref.GetBytesAsync(maxAllowedSize).ContinueWith(t => t);
    DateTime after = DateTime.Now;`

I made a button to download the image, the first click is about 0.9 seconds, second click is 0.6 (same file), 0.4, 0.7 and so on. I tried to download both from android phone wi-fi, and Unity editor Windows, I have fast internet (227mbps per second) And I want to download multiple images- the user waits 4 seconds, it's so frustrating, please help

**Comment by jonsimantov** [comment]
One suggestion is, you could try calling GetDownloadUrlAsync() on the storage references to generate a set of download URLs, then use Unity's WWW or UnityWebRequest to download them directly. Downloading files from gs:// URLs does have a bit of an overhead as it needs to verify your auth credentials, etc.

Another thing to try, if these files are meant to be publicly accessible, is setting the cloud storage bucket they are in to be publicly readable. This will remove the overhead of checking auth credentials before Firebase Storage sends the data.

Please feel free to reopen this issue if you have further questions.

**Comment by shlighter** [comment]
I just checked with your demo project, I clicked on Download Bytes to download a 400kb image- it takes 1.1 seconds to download. Is it supposed to be this way?
The pics aren't supposed to be public. Let's say I build an Instagram app, some pics are private.
Am I going to wait 10 seconds to load an entire page because of Auth checks?
What do you suggest me to do?

**Comment by shlighter** [comment]
Open please

**Comment by patm1987** [comment]
Hi @shlighter ,

Sorry to have left this this long, but there is a noted overhead per request - [see this post](https://cloud.google.com/blog/products/gcp/optimizing-your-cloud-storage-performance-google-cloud-performance-atlas).

How you deal with this is really up to you, but the best way to improve speed to make the URLs public - but you get the speed at the cost of privacy as you noted.

You could get a [download URL directly](https://firebase.google.com/docs/storage/unity/download-files#download_from_a_url) and reference that. These URLs should be secret, and you could cache them in something like Realtime Database with read constraints to lock it to only users who should view the image. You can also revoke download URLs. Depending on the amount of privacy you want and how secure the data needs to be, this may not work for you (ex: if you're building instagram, I would not use this approach).

I think that the best solution would be take advantage of the asynchronous nature of the Firebase API and file streaming to mask the latency by firing off many image downloads at once. That is, instead of saying:
```
for (imageRef in Images) {
    var bytes = await imageRef.GetBytesAsync(long.MaxValue);
    var texture = new Texture2D(2, 2);
    texture.LoadImage(bytes);
}
```

you could write:
```
for (imageRef in Images) {
    imageRef.GetBytesAsync(long.MaxValue).ContinueWithOnMainThread(task=>{
        var texture = new Texture2D(2,2);
        texture.LoadImage(task.Result);
    });
}
```

You'll still have (say) 1 second download times per image - but as you mentioned it doesn't seem like you're actually saturating your connection. This way you can interlace your download.

Now if you _do_ have some public images and you want to download them really really fast, you can take advantage of Firebase Hosting's CDN and serve locally cached images as [mentioned in this article](https://dev.to/dbanisimov/building-image-cdn-with-firebase-15ef).

Let me know if that helps.
