### ISSUE TITLE
iOS: Same remote notifications are shown in running app and at system level

### ISSUE THREAD

**Issue by Fellhuhn** [firebase/quickstart-unity#668]
### Please fill in the following fields:
Unity editor version: 2018.4.19f1
Firebase Unity SDK version: can't find any info about that. Neitherin the readme, nor in the Docs or in the downloaded files... 19th April it was downloaded though
Source you installed the SDK (.unitypackage or Unity Package Manager): .unitypackage
Firebase plugins in use (Auth, Database, etc.): Auth, Database, Messaging
Additional SDKs you are using (Facebook, AdMob, etc.): Discord
Platform you are using the Unity editor on (Mac, Windows, or Linux): Windows
Platform you are targeting (iOS, Android, and/or desktop): iOS, Android, desktop
Scripting Runtime (Mono, and/or IL2CPP): IL2CPP

**Please describe the issue here:**
The app is running on an iOS device. My server sends a notification which then gets displayed within the app (as it should) AND as system notification (which it shouldn't).
It works fine on Android.

Remote Notifications are enabled as background operations in XCode.

The notification payload consists of:
registration_ids, data, and the notification with title, body and android_channel_id all send as json with the according header, using https://fcm.googleapis.com/fcm/send.

**Have you been able to reproduce this issue with just the Firebase Unity quickstarts (this GitHub project)?**

No, I don't have any iOS devices myself.

**What's the issue repro rate? (eg 100%, 1/5 etc)**
100%.

**Comment by chkuang-g** [comment]
@Fellhuhn 

Sorry for the late reply.  

It would be helpful to learn Firebase SDK version in order to pinpoint the problematic iOS SDK.

Could you checkout `Assets/Firebase/Editor/MessagingDependencies.xml` and find this line
```
   <iosPod name="Firebase/Messaging" version="version number" minTargetSdk="8.0">
```

Also. could you clarify the expected behavior?  As you mentioned, it worked as intended on Android.  Do you mean that when the app is at foreground, when you send a message with both notification and data, 
- On Android, only `Firebase.Messaging.FirebaseMessaging.MessageReceived` event was triggered, no system notification in system tray at all.
- On iOS, not only `Firebase.Messaging.FirebaseMessaging.MessageReceived` event was triggered, but also the system notification in system tray appeared as well.

Shawn

**Comment by Fellhuhn** [comment]
The version is 6.14.0 according to the MessagingDependencies.xml.

Aye, you described it correctly. Even though the iOS app is running the notification gets shown in the game (MessageReceived) as well as the system try notification appears.

**Comment by patm1987** [comment]
Hi @Fellhuhn ,

There should be:
```
<iosPod name="Firebase/Messaging" version="6.24.0" minTargetSdk="8.0">
```

```
<androidPackage spec="com.google.firebase:firebase-messaging-unity:6.15.0">
```

and
```
<androidPackage spec="com.google.firebase:firebase-messaging:20.1.7">
```

entry (in this case on the 6.15 SDK). Can you share the `Firebase/Messaging` rather than `firebase-messaging-unity`?

It would also help a lot if you could test on a local iOS device or build the test app for a friend to experiment with. Among other things, it helps us to run the test locally exactly to your specifications to recreate the issue.

--Patrick
