### ISSUE TITLE
Unity ios: firebase realtime RunTranscation fireLocalEvents set to false dosent work on IOS devices 

### ISSUE THREAD

**Issue by waelkonsowa** [firebase/quickstart-unity#678]
Unity IOS devices: firebase realtime RunTranscation fireLocalEvents set to false dosent work on IOS devices it always called twice otherwise set true or false but work properly on editor and android devices

**Comment by chkuang-g** [comment]
@waelkonsowa 

To better support you, could you kindly fill out the information in the template? That is:

### Please fill in the following fields:
Unity editor version: 
Firebase Unity SDK version: 
Source you installed the SDK (.unitypackage or Unity Package Manager):
Firebase plugins in use (Auth, Database, etc.):
Additional SDKs you are using (Facebook, AdMob, etc.): 
Platform you are using the Unity editor on (Mac, Windows, or Linux): 
Platform you are targeting (iOS, Android, and/or desktop): 
Scripting Runtime (Mono, and/or IL2CPP):

### Please describe the issue here:
(Please list the full steps to reproduce the issue. Include device logs, Unity logs, and stack traces if available.)

### Please answer the following, if applicable:
Have you been able to reproduce this issue with just the Firebase Unity quickstarts (this GitHub project)?

What's the issue repro rate? (eg 100%, 1/5 etc)
