### ISSUE TITLE
so many bugs!

### ISSUE THREAD

**Issue by green4you** [firebase/quickstart-unity#69]
1. link not work and just show infinit loaing box when app already open so long times

2. short app link json parameter is not working

3. can't add custom parameters to link

4. when i recieve dynamic link , it only show "link" value

sh**!

**Comment by a-maurice** [comment]
What platform are you seeing these issues on, Android or iOS (or both)?  And at least for the first issue, have you been able to reproduce it with the invites testapp?

**Comment by green4you** [comment]
platform : android (unity)

this issue is reproducing every times.


step

1. invite me on my app( with Invite function)

2. click link from invite message ( didnt close app )


condition

1. run app and go to background

2. dont anything with phone untill 30~60 minute

3. and do step

4. infinite loading box accur!


________________________________
보낸 사람: a-maurice <notifications@github.com>
보낸 날짜: 2017년 3월 15일 수요일 오전 9:14
받는 사람: firebase/quickstart-unity
참조: green4you; Author
제목: Re: [firebase/quickstart-unity] so many bugs! (#69)


What platform are you seeing these issues on, Android or iOS (or both)? And at least for the first issue, have you been able to reproduce it with the invites testapp?

**Comment by a-maurice** [comment]
Sorry for the delay in getting back to you.

Unfortunately, we haven't been able to reproduce the issue with the
infinite loading box.  Our best guess is that maybe the network connection
is going to sleep, because the phone is idling, so possibly the network
connection is never responding.  However, the box should be timing out.
Sorry we don't have a fix yet, we will continue to investigate.

As for the link parameters, we need a bit more context as to what you are
trying to send, like how you are providing the parameters.  If you haven't
seen it, I'd also recommend looking at
https://firebase.google.com/docs/dynamic-links/create-links, which
describes how to create dynamic links.

**Comment by johnb003** [comment]
@green4you Any updates on how you're sending the link parameters?

Also, in your instructions above: "3. and do step" ... and do step what?

**Comment by johnb003** [comment]
@green4you Can you also provide additional details we might use to repro this?

Have you tried with the sample app to see if this happens or if it's part of your setup?
What architecture are you seeing the problems on your android phone?
What version of the Unity plugin are you using?
What version of Unity are you using?

**Comment by stewartmiles** [comment]
@green4you since we haven't heard from you we'll assume you've either resolved your issue or given up.  I'm afraid without additional information we can't help out.
