### ISSUE TITLE
AndroidManifest.xml do not contains `default_notification_icon` tag when updated to firebase 6.15.0 and use UnityPackageManager

### ISSUE THREAD

**Issue by square1983** [firebase/quickstart-unity#710]
### Please fill in the following fields:
Unity editor version: 2018.4.9f1
Firebase Unity SDK version: 6.15.0
Source you installed the SDK (.unitypackage or Unity Package Manager): Unity Package Manager
Firebase plugins in use (Auth, Database, etc.):Firebase Cloud Messaging
Additional SDKs you are using (Facebook, AdMob, etc.): none 
Platform you are using the Unity editor on (Mac, Windows, or Linux): Mac
Platform you are targeting (iOS, Android, and/or desktop): iOS/Android
Scripting Runtime (Mono, and/or IL2CPP):Mono and IL2CPP

### Please describe the issue here:
When I use firebase of ver6.5.0, it builds successfully.
Last week we had to update firebase to ver6.15.0 to resolve an error of Firebase.Messaging.FirebaseMessaging.SubscribeAsync("/topics/example").

After we update firebase to ver6.15.0(Unity Package Manager), it works again but show incorrect icon on Android.
Finally we found that 
```
<meta-data android:name="com.google.firebase.messaging.default_notification_icon"
android:resource="@drawable/notification_icon" />
``` 
disappeared from AndroidManifest.xml after updated.
`Assets/Plugins/Android/Firebase/AndroidManifest.xml` and
`Assets/Plugins/Android/AndroidManifest.xml`  were deleted when update to Unity Package Manager.  
I tried to restore `Assets/Plugins/Android/AndroidManifest.xml` but another build error occoured .

### Please answer the following, if applicable:
Have you been able to reproduce this issue with just the Firebase Unity quickstarts (this GitHub project)?
I tried to do the same thing with this GitHub project and reproduced this issue.

What's the issue repro rate?  → 100%

[AndroidManifest.xml.zip](https://github.com/firebase/quickstart-unity/files/4779773/AndroidManifest.xml.zip)

**Comment by patm1987** [comment]
Thanks for this bug report! does this occur if you don't use UPM as well?

**Comment by chkuang-g** [comment]
Hi @square1983 

I think the issue is that when you migrate Firebase to Unity Package Manager (UPM), EDM4U thinks `Assets/Plugins/Android/AndroidManifest.xml` and `Assets/Plugins/Android/Firebase/AndroidManifest.xml` are both part of the package (See `Assets/Firebase/Editor/FirebaseMessaging_version-6.15.0_manifest.txt`). What happen after the migration is 

1. Both `AndroidManifest.xml` are removed from `Assets` folder
2. Once migration is done, Firebase.Editor.dll should be enabled and generate `Assets/Plugins/Android/Firebase/AndroidManifest.xml` again.
3. Firebase.Messaging.Editor.dll should also be enabled and generate `Assets/Plugins/Android/AndroidManifest.xml` as the one came with Firebase SDK.

About `Assets/Plugins/Android/Firebase/AndroidManifest.xml`, are you sure this file is not generated after migration?  Perhaps wait for a couple of seconds?

About `Assets/Plugins/Android/AndroidManifest.xml`, I think the best approach is to revert the changes with your version control tool.  We are thinking about a better way to modify AndroidManifest.xml instead of including it with the package.  Will let you know when the feature is finished.

If the problem is still not resolved, could you include the error message to this post?

Thank you,
Shawn

**Comment by square1983** [comment]
> Thanks for this bug report! does this occur if you don't use UPM as well?

I have some troubles(build error or Unity Editor error occurs) when not use UPM.

**Comment by square1983** [comment]
> Hi @square1983
> 
> I think the issue is that when you migrate Firebase to Unity Package Manager (UPM), EDM4U thinks `Assets/Plugins/Android/AndroidManifest.xml` and `Assets/Plugins/Android/Firebase/AndroidManifest.xml` are both part of the package (See `Assets/Firebase/Editor/FirebaseMessaging_version-6.15.0_manifest.txt`). What happen after the migration is
> 
> 1. Both `AndroidManifest.xml` are removed from `Assets` folder
> 2. Once migration is done, Firebase.Editor.dll should be enabled and generate `Assets/Plugins/Android/Firebase/AndroidManifest.xml` again.
> 3. Firebase.Messaging.Editor.dll should also be enabled and generate `Assets/Plugins/Android/AndroidManifest.xml` as the one came with Firebase SDK.
> 
> About `Assets/Plugins/Android/Firebase/AndroidManifest.xml`, are you sure this file is not generated after migration? Perhaps wait for a couple of seconds?
> 
> About `Assets/Plugins/Android/AndroidManifest.xml`, I think the best approach is to revert the changes with your version control tool. We are thinking about a better way to modify AndroidManifest.xml instead of including it with the package. Will let you know when the feature is finished.
> 
> If the problem is still not resolved, could you include the error message to this post?
> 
> Thank you,
> Shawn

Both of the two AndroidManifest.xml are not generated after migration in my case.
The inspector of that two dll is grayout. 
![image](https://user-images.githubusercontent.com/6021158/84729385-86540b00-afce-11ea-9cbd-0c495d39a5e4.png)

**Comment by square1983** [comment]
@chkuang-g 
I think I know why AndroidManifest.xml was not generated in my case.
I updated firebase unter Unity Platform `iOS` and the migration removes all the xml files as you said before. After migration I tried to build for iOS and it worked, so I thought the migration was over and commited the changes to github.And then I pulled the changes in another folder(because swtich platform to `Android` cost long time) and Unity generated AndroidManifeset.xml this time.Maybe the new generated xml files are different from the origin files causes the `default_notification_icon`tag lost.

I think I know how to resolve this.
@chkuang-g  @patm1987 
Thank you very much.
