### ISSUE TITLE
Crashlytics is not being enabled (Did not register exception handlers: Crashlytics SDK was not initialized)

### ISSUE THREAD

**Issue by kjyv** [firebase/quickstart-unity#715]
### Please fill in the following fields:
Unity editor version: 2019.4.0f
Firebase Unity SDK version: 6.15.0
Source you installed the SDK (.unitypackage or Unity Package Manager): UPM
Firebase plugins in use (Auth, Database, etc.): Auth, Analytics, Storage
Additional SDKs you are using (Facebook, AdMob, etc.): /
Platform you are using the Unity editor on (Mac, Windows, or Linux): Mac
Platform you are targeting (iOS, Android, and/or desktop):  iOS
Scripting Runtime (Mono, and/or IL2CPP): IL2CPP

### Please describe the issue here:
I've just tried adding crashlytics to our project following the manual. We've been using Firebase storage successfully for a while and I now added the Crashlytics package. Since there is nothing to call explicitly, I didn't change the init code (I added a FireBaseApp.LogLevel = LogLevel.Debug;). So just the usual 
```
FirebaseApp.CheckAndFixDependenciesAsync().ContinueWithOnMainThread(task => {
				dependencyStatus = task.Result;
				if (dependencyStatus == DependencyStatus.Available) {
			             app = FirebaseApp.DefaultInstance;
                                      ...
				} else {...}
```
Starting in the editor, I see 
`Did not register exception handlers: Crashlytics SDK was not initialized` after storage was initialized. In iOS I get
```
2020-06-17 21:09:48.764316+0200 (...) DEBUG: auth app initializer Enabling
2020-06-17 21:09:48.765526+0200 (...) DEBUG: App initializer crashlytics not found, failed to enable.
...
```
Hence, nothing is visible on the firebase console.
Am I doing anything wrong?

### Please answer the following, if applicable:
Have you been able to reproduce this issue with just the Firebase Unity quickstarts (this GitHub project)?
Didn't try.

What's the issue repro rate? (eg 100%, 1/5 etc)
100%

**Comment by patm1987** [comment]
Hi @kjyv ,

I'm not seeing a similar issue on my machine with [the quickstart](https://github.com/firebase/quickstart-unity/tree/master/crashlytics/testapp). Can you try running in the Quickstart (feel free to use your same bundleid and GoogleService-Info.plist file to keep your current Firebase project) and let me know if you're still seeing the issue?

**Comment by kjyv** [comment]
Hey, thanks for your answer. I've tried the quickstart project and used the GoogleService-Info.plist from our existing project, also installing firebase using the unity package manager. I get the same build messages (including a warning "AssetDatabase.FindAssets: Folder not found: 'Assets/Firebase/Editor'") and "Crashlytics build information sent" as I've had before. This didn't initialize the crashlytics console as before yet. Then using the app on iOS to trigger some messages, the console now shows empty graphs and seems to have received some messages. It is not showing any of the logged test exceptions but that might just take a while I guess. So while this is good, I'm not sure where the difference to our project is now. The initialisation code is pretty much the same.
So when I ad firebase logging to quickstart, I can also see "Did not register exception handlers: Crashlytics SDK was not initialized" in the editor, that is apparently telling me it won't run in the editor.
In an iOS build, I also get "App initializer crashlytics not found, failed to enable." but a bit after that "Registering Crashlytics exception handlers" that was apparently triggered by the first Crashlytics.Log which I didn't use in our app. As I've understood it should not be necessary to call any specific Crashlytics methods to achieve crash logging.

**Comment by patm1987** [comment]
Sorry to have let this issue slip through the cracks.

I went and verified that everything was working for me as expected with the 6.15.2 Unity plugin on iOS. See this page for release notes: https://firebase.google.com/support/release-notes/unity

Based on your description and my own investigation, you may need to call `FirebaseApp.DefaultInstance` or otherwise force some Firebase function to fire:
```
FirebaseApp.CheckAndFixDependenciesAsync().ContinueWithOnMainThread(task => {
    var dependencyStatus = task.Result;
    if (dependencyStatus != DependencyStatus.Available) {
        // Failed to initialize Firebase, do something/log an error here
        // on iOS this probably shouldn't happen.
        // On Android this probably means that the user can't or won't install Play Services
        return;
    }

    // force Firebase singleton to initialize, you just need to call DefaultInstance but don't need the returned app
    var firebaseApp = FirebaseApp.DefaultInstance;
});
```

The reason why this is needed is that if you were to read the [iOS getting started guide](https://firebase.google.com/docs/crashlytics/get-started?platform=ios#add-sdk), you'd see that you need to call `FirebaseApp.configure()`. For the Unity SDK, because there's no strictly enforced API entry, it uses a C# singleton that's lazily initialized when you first try to access it. If you make _any_ call into Firebase, this will get initialized - but if you don't call any Firebase functions then you may need to explicitly invoke `DefaultInstance`.

I did check that this worked with and without Unity Package Manager integration.

And I did find a similar issue when my `GoogleService-Info.plist` pointed to an old project, so you may want to [try to redownload that](https://support.google.com/firebase/answer/7015592?hl=en).

If you're still unable to resolve the issue, we'll need you to enable debug logging. To do so, add somewhere (you can and should add this _before_ you call `CheckAndFixDependenciesAsync`):
```
Firebase.FirebaseApp.LogLevel = Firebase.LogLevel.Debug;
```

Sorry again to have left this this long, let me know if any of these steps helped!

--Patrick

**Comment by kjyv** [comment]
Thanks for your reply and explanation. As you can see in my initial description, I think I did all of these things already.
Different from your code, our code adapted from the firebase example code checks for DependencyStatus.Available and only then get the FirebaseApp.DefaultInstance reference but I think that code was always reached and should have done the same as yours. I also added the logging and the message posted only appear then. The thing is, without changing anything in the code, I did see crash reports appearing recently (I just left everything in) so this somehow magically solved itself (I think I uninstalled the unitypackage version again and switched to the upm version and also updated from 6.14.1/6.15.0 to 6.15.1). I'll report back if it reappears.
