### ISSUE TITLE
Detect Firebase Test Lab device

### ISSUE THREAD

**Issue by gayanW** [firebase/quickstart-unity#724]
Can we detect if a Unity app being run on a Firebase Test Lab device or not?

According to the documentation, for Android (Java) we could do:

```
String testLabSetting = Settings.System.getString(getContentResolver(), "firebase.test.lab");
if ("true".equals(testLabSetting)) {
    // Do something when running in Test Lab
    // ...
}
```

Can this be done on Unity?  Because I want to exclude the analytics of the pre-launch reports appearing in Google Analytics.

**Comment by kevinkokomani** [comment]
This is probably not directly possible in C#, but you could likely use a wrapper to call the Java method required to do this.

**Comment by gayanW** [comment]
@kevinkokomani  BTW Is there any other workaround to exclude Test Lab devices from the statistics?

**Comment by kevinkokomani** [comment]
If you're able to get the [ANDROID_ID](https://developer.android.com/reference/android/provider/Settings.Secure.html#ANDROID_ID) of your test devices, you may be able to do something with those IDs where you conditionally don't log events if the ID matches one of your test devices'. Although I don't know that this method would help to stop install or user tracking data from being collected from test devices, or if it only works to stop logging events. I'm getting this info from [this stackoverflow post](https://stackoverflow.com/questions/40959903/exclude-testing-device-from-firebase-analytics-logging); perhaps someone else has more up-to-date info.

**Comment by gayanW** [comment]
Thanks for the input. But that's on how to disable analytics collection on your own test device. But I'm referring to tests provided by Google Play itself like Test Lab option, Pre-launch reports etc.

Existing resources show on how to exclude these devices on Android apps, but the question is can it be done in a Unity application?

REF:

- [Disable Google Analytics from Android pre-launch reports](https://stackoverflow.com/a/41005702/3647002)
- [Modify instrumented test behavior for Test Lab](https://firebase.google.com/docs/test-lab/android/android-studio#modify_instrumented_test_behavior_for)

**Comment by katowulf** [comment]
Your tests should be run in a staging project, not your prod project with Analytics data.

**Comment by patm1987** [comment]
Unfortunately, Unity doesn't expose this low level Java/Android logic directly but it does allow you to call into Java using Unity's own JNI abstractions (such as [AndroidJavaClass](https://docs.unity3d.com/ScriptReference/AndroidJavaClass.html)).

Rather than providing a complete tutorial, I'd recommend going through the [Test Lab Codelab](https://codelabs.developers.google.com/codelabs/unity-firebase-test-lab-game-loop/). But if you're impatient like I am, [skip right to step 9](https://codelabs.developers.google.com/codelabs/unity-firebase-test-lab-game-loop/#8) to get the code that will work with Unity. This code will get the TEST_LOOP for if you intend on using [Game Loops](https://firebase.google.com/docs/test-lab/android/game-loop).

If you just want to test for `"firebase.test.lab"`, here are the important bits:
You need to [Activity](https://developer.android.com/reference/android/app/Activity) by retrieving the static field `currentActivity` in `UnityPlayer`:
```
AndroidJavaClass unityPlayer = new AndroidJavaClass("com.unity3d.player.UnityPlayer");
_activity = unityPlayer.GetStatic<AndroidJavaObject>("currentActivity");
```

You can call `getContentResolver` with this snippet I copied out:
```
AndroidJavaObject contentResolver = _activity.Call<AndroidJavaObject>("getContentResolver")
```

Now I'm coding a little blind as my IDE really doesn't like this part of the Unity API, but `String testLabSetting = Settings.System.getString(getContentResolver(), "firebase.test.lab");` should be:
```
AndroidJavaClass system = new AndroidJavaClass("android.provider.Settings.System");
string testLabSetting = system.CallStatic<string>(contentResolver, "firebase.test.lab");
```

And you should have a C# `string`, so the rest of the logic you can do as:
```
if (testLabSetting == "true") {
    // Something really cool
}
```

Let me know if that works for you!
--Patrick
