### ISSUE TITLE
[Mesaging] Disable iOS module/swizzle

### ISSUE THREAD

**Issue by MartinGonzalez** [firebase/quickstart-unity#747]
### Please fill in the following fields:
Unity editor version: 2018.4.16
Firebase Unity SDK version: 6.15.2
Source you installed the SDK (.unitypackage or Unity Package Manager): UPM
Firebase plugins in use (Auth, Database, etc.): Messaging
Additional SDKs you are using (Facebook, AdMob, etc.): Facebook-Appboy(Braze)
Platform you are using the Unity editor on (Mac, Windows, or Linux): Mac
Platform you are targeting (iOS, Android, and/or desktop): iOS-Android
Scripting Runtime (Mono, and/or IL2CPP): IL2CPP

## Issue
We need to disable firebase notifications in iOS. This is because we are handling push notifications ourself, but we need it in Android. The problem, I guess it's happening, is that Firebase swizzle the didReceiveRemoteNotification method and do not allow others to hear it.

Is there a way to disable iOS Messaging feature without affecting android?
Is there a way to let Firebase continue emitting the didReceiveRemoteNotification to other push providers?

Ive tried setting FirebaseAppDelegateProxyEnabled to NO but it keeps stealing the native method

**Comment by patm1987** [comment]
So, the short answer is that there's not a good way to disable parts of the Firebase SDK for certain platforms right now.

To disable swizzling, you should be able to use `FirebaseAppDelegateProxyEnabled` as you mentioned. Are you doing it on your `Info.plist` rather than your `GoogleService-Info.plist`?

Note that if you haven't worked with this before, you'll likely have to use a [`[PostProcessBuild]` attribute](https://docs.unity3d.com/ScriptReference/Callbacks.PostProcessBuildAttribute.html) mixed with [Unity's `PlistDocument` class](https://docs.unity3d.com/ScriptReference/iOS.Xcode.PlistDocument.html). [This forum post](https://forum.unity.com/threads/how-can-you-add-items-to-the-xcode-project-targets-info-plist-using-the-xcodeapi.330574/?_ga=2.125650764.758387660.1597336197-566425448.1558130724) seems to have a decent example (you shouldn't need its linked Xcode Manipulation API anymore). You can always experiment by exporting the project first and modifying the `Info.plist` before writing custom build scripts.

If you want to try to remove as much of the Messaging SDK as you can, you can locate the `MessagingDependencies.xml` file and try deleting the `<iosPods>` section (this removes the ObjC library):
```
  <iosPods>
    <iosPod name="Firebase/Messaging" version="6.24.0" minTargetSdk="8.0">
    </iosPod>
  </iosPods>
```

Followed by removing the `libFirebaseCppMessaging` (the C++ library) under `Plugins/iOS/Firebase` and removing `Firebase/Plugins/iOS/Firebase.Messaging.dll` (the C# library). At this point, any call to a Messaging feature will be a crash of some kind - so be careful.

Let me know if any of this helps (and what you went with)!

**Comment by MartinGonzalez** [comment]
Thanks for replying @patm1987 
Yes I did it manually first in our Info.plist. I've created a new package without any iOS dependency and seems to work. I will try again that ProxyEnabled property later.
