### ISSUE TITLE
Build fails in Unity 2020.1.3f1 due to wrong named generated folder

### ISSUE THREAD

**Issue by NilokiloxD** [firebase/quickstart-unity#761]
### Please fill in the following fields:
Unity editor version: 2020.1.3f1
Firebase Unity SDK version: 6.15.2
Source you installed the SDK (.unitypackage or Unity Package Manager): UPM
Firebase plugins in use (Auth, Database, etc.): Auth, Crashlytics, Analytics
Additional SDKs you are using (Facebook, AdMob, etc.): AdMob
Platform you are using the Unity editor on (Mac, Windows, or Linux): Windows
Platform you are targeting (iOS, Android, and/or desktop): Android
Scripting Runtime (Mono, and/or IL2CPP): IL2CPP

### Please describe the issue here:
in Unity 2020 android libs must be located in .androidlib folders. Following these instructions: 
https://firebase.google.com/docs/unity/setup?authuser=1#missing_firebase_android_config_file_in_unity_2020 
I renamed the Firebase folder to Firebase.androidlib in Plugins. 2 things happen now:
1. When building, the sdk regenerates the Firebase folder without .androidlib extension and fills it with the usual files. This causes duplication and build errors
2. the Andriodmanifest contains minSdkVersion tag which is not supported anymore it seems

The Crashlytics build id file is put into the wrong folder as well.

So how can i prevent the sdk from regenerating this Folder and only use the renamed one?

### Please answer the following, if applicable:
Have you been able to reproduce this issue with just the Firebase Unity quickstarts (this GitHub project)?
yes

What's the issue repro rate? (eg 100%, 1/5 etc)
100%

**Comment by a-maurice** [comment]
Hi @NilokiloxD 

We've made a post about the issues with Unity 2020.1, and how to work around them here: https://firebase.googleblog.com/2020/08/firebase-compatibility-with-unity-20201.html

We're looking into how to fix the SDK so that these workarounds are not necessary, but it will still take a bit of time. If that blog post doesn't resolve your issues, please let us know.

**Comment by Volcore** [comment]
We have the same issue.

This is currently (the only issue) blocking us from adopting Unity 2020 (we don't want to do any changes or "hacks" to third party SDKs in order to make it work). Do you guys have an ETA for when this will be fixed (days/weeks/months)?

**Comment by chkuang-g** [comment]
@NilokiloxD Yup `minSdkVersion` is not supported anymore in Unity 2020.  I think this is the only missing part from the blog post @a-maurice mentioned.  I have removed that for the next release.

I think the duplication will not cause any error, since Unity basically ignore any folder without `.androidlib` postfix for the Android build, at least that is what I saw with Unity 2020.1.2f1.  What is the build error?

@Volcore We are currently in the process to roll out our next release.  Usually take one to two weeks.  However, since it is awhile since the last release, there may be additional works for this time.  I think most of the workaround documented in the blog post is not really hacks but just changes for new requirement in Unity 2020.  It should be safe to apply them.  Let us know if you run into any issue.

**Comment by chkuang-g** [comment]
Hi folks,

6.16.0 was release! `.androidlib` and `minSdkVersion` issues should be fixed in this release.
You can download .unitypackage [here](https://firebase.google.com/download/unity) or upgrade it through Unity Package Manager.

I'll close this issue for now.  If the issue remains, please report a new bug using [bug template](https://github.com/firebase/quickstart-unity/issues/new?labels=new&template=issue.md)
