### ISSUE TITLE
SignInWithCredentialAsync fails with CredentialAlreadyInUse

### ISSUE THREAD

**Issue by Nyankoo** [firebase/quickstart-unity#774]
### [REQUIRED] Please fill in the following fields:

  * Unity editor version: 2019.4.7f1
  * Firebase Unity SDK version: 6.15.2
  * Source you installed the SDK: Unity Package Manager (.unitypackage or Unity Package Manager)
  * Problematic Firebase Component: Auth (Auth, Database, etc.)
  * Other Firebase Components in use: Crashlytics, Firestore, Messaging (Auth, Database, etc.)
  * Additional SDKs you are using: AdMob (Facebook, AdMob, etc.)
  * Platform you are using the Unity editor on: Windows (Mac, Windows, or Linux)
  * Platform you are targeting: iOS, Android (iOS, Android, and/or desktop)
  * Scripting Runtime: IL2CPP (Mono, and/or IL2CPP)

### [REQUIRED] Please describe the issue here:

(Please list the full steps to reproduce the issue. Include device logs, Unity logs, and stack traces if available.)

#### Steps to reproduce:
- Starts app for first time. Anonymous account A gets created
- User links account with eg. Google (LinkWithCredentialAsync)
- User uninstalls the app
- User installs app again -> new anonymous account B gets created
- User wants to link account to above Google account
- LinkWithCredentialAsync fails, as Google account is already linked
- SignInWithCredentialAsync fails with error CredentialAlreadyInUse

Have you been able to reproduce this issue with just the Firebase Unity quickstarts (this GitHub project)?
What's the issue repro rate? (eg 100%, 1/5 etc) 100%

What happened? How can we make the problem occur?
See above

If you have a downloadable sample project that reproduces the bug you're reporting, you will
likely receive a faster response on your issue.

#### Relevant Code:

```
Credential credential = GoogleAuthProvider.GetCredential(idToken, authCode);
try
{
        FirebaseUser = await FirebaseUser.LinkWithCredentialAsync(credential);
}
catch
{
         FirebaseUser = await firebaseAuth.SignInWithCredentialAsync(credential);
}
```

**Comment by vimanyu** [comment]
Hi @Nyankoo,
Thanks for bringing this up. We discussed this internally and here is an explanation of the system,

account A (anonymous) is created, it's linked to credential G thereby creating account B (non-anonymous)
After deleting and re-installing app, 
account C (anon) is created, it can no longer be linked to credential G since that credential is owned by account B.

So this explains why the linking fails.

Also, in the code snippet, please note that credential is used twice (once in try block and again in catch block). That won't work because credentials are one-time use only as the authCode is invalidated after the first failed attempt to link. It should work if you try re-creating the credential in catch block before signing in. 

Please note that a successful sign-in will result in losing all data from the account C (new anonymous account). 

Let us know if this works for you or if you have more questions.

**Comment by Nyankoo** [comment]
@vimanyu Thank you for the explanation!

Like I mentioned, I know why the link fails, but the sign-in fails with above error too (not just the link)!

When you mention I should recreate the credentials, do I just do `credential = GoogleAuthProvider.GetCredential(idToken, authCode); ` again? 
Or do I need to get another auth code by repeating the provider’s sign in method?

**Comment by vimanyu** [comment]
Hi @Nyankoo ,
The auth code is "used up" during the failed attempt to link. You will have to get a new one before the sign in. 
Let us know if that works for you.

**Comment by Nyankoo** [comment]
@vimanyu I'm just checking about the auth code, but it seems that the Unity Google Sign In plugin doesn't need one? The sample code passes null as the authCode:
https://github.com/googlesamples/google-signin-unity

**Comment by vimanyu** [comment]
Can you do the same steps as you are already doing for creating the credential the first time (before try-catch), and create a new credential before the sign-in in catch? 
Let us know if that doesn't work and we can take a look at it.

**Comment by Nyankoo** [comment]
@vimanyu Generating new credentials seem to work, even without the auth code!

**Comment by vimanyu** [comment]
Awesome! Thanks for confirming @Nyankoo.
