### ISSUE TITLE
Firebase Unity AuthState ChangeListener

### ISSUE THREAD

**Issue by mckar02** [firebase/quickstart-unity#777]
Hi. I am using firebase auth and realtime database in my unity game project. I want to know when there is a change in the authentication state. for this i use AuthStateChanged listener. Here is my code to handle this sitituation:
`public class AuthManager : MonoBehaviour
{
    Firebase.Auth.FirebaseAuth auth;
    Firebase.Auth.FirebaseUser user;

    private void Awake()
    {
        DontDestroyOnLoad(this);
    }
    void Start()
    {
        StartCoroutine(InitializationCorotine()); 
    }

   private IEnumerator InitializationCorotine()
    {
        var dependencyTask = FirebaseApp.CheckAndFixDependenciesAsync();
        yield return new WaitUntil(() => dependencyTask.IsCompleted);

        if (dependencyTask.Result != DependencyStatus.Available)
        {
            yield break;
            //buradaki durumlar senaryoya göre ele alınacak
        }

         auth = FirebaseAuth.DefaultInstance;

        if (auth.CurrentUser == null)
        {
            var authTask = auth.SignInAnonymouslyAsync();
            yield return new WaitUntil(() => authTask.IsCompleted);
            Debug.Log("User Sign in == null:" + auth.CurrentUser.UserId);

            auth.StateChanged += AuthStateChanged;
            AuthStateChanged(this, null);

            if (authTask.Result == null)
            {
                yield break;
                //buradaki durumlar senaryoya göre ele alınacak
            }
        }
        else
        {
            Debug.Log("User Sign in else:" + auth.CurrentUser.UserId);
            auth.StateChanged += AuthStateChanged;
            AuthStateChanged(this, null);
        }

      
    }

    private void AuthStateChanged(object sender, EventArgs eventArgs)
    {
        if (auth.CurrentUser != user)
          {
              bool signedIn = user != auth.CurrentUser && auth.CurrentUser != null;
              if (!signedIn && user != null)
              {
                    DatabaseReference mMatchmakingRef= FirebaseDatabase.DefaultInstance.GetReference("MatchMakingDatabase");
                    mMatchmakingRef.Child("draw-2").Child(user.UserId).SetValueAsync(false);
                    Debug.Log("Signed out " + user.UserId);
              }

              user = auth.CurrentUser;
              if (signedIn)
              {
                  Debug.Log("Signed in AuthStateChanged" + user.UserId);
              }
          }
    }
}
`
when user sign in AuthStateChanged listener triggered. but when i close my internet or kill my app there is no trigger on AuthStateChanged listener. How can Track state changes of the user auth?

**Comment by DellaBitta** [comment]
Hi @mckar02,

AuthStateChanged tracks Auth operations only and doesn't monitor network connectivity.  Losing an internet connection does not sign out the user so you shouldn't expect to see changes in the auth state due to this.  Closing and re-opening the application also doesn't sign out the user since the user data is persisted in secure storage.  Please see the [documentation for when AuthState and idTokenState listeners](https://firebase.google.com/docs/reference/unity/class/firebase/auth/firebase-auth#class_firebase_1_1_auth_1_1_firebase_auth_1a849f6a1fbcc42d7f470bdf33a98654fd) are invoked.

In the end Firebase doesn't provide a standard API to determine if the phone currently has network connectivity.   However, you could try something: since the Unity API wraps the Android and iOS SDK implementations on those respective platforms, you can try to [construct a Reference to the FirebaseDatbase .info/connected](https://firebase.google.com/docs/database/android/offline-capabilities#section-connection-state) to poll connectivity status, but I haven't personally tested this before.

Also I recommend adding your AuthStateChange listener as one of the first things you configure after you setup Auth. In the code above you configure it after the SignIn attempt which means there's a possibility that you miss the event change.

Please let me know if this helps!

**Comment by mckar02** [comment]
Hi @DellaBitta . Firs of all thank you for your detailed answer.  
I'll try what you say and let youknow if it works.

**Comment by mckar02** [comment]
Hi again @DellaBitta . I  tried to construct a Reference to the FirebaseDatbase .info/connected to poll connectivity status and it definitely worked. now i can know the user has'nt got network connectivity after 2 minutes via firebase. and also i can know the user has'nt got network connectivity immediately when users phone shot down or application kills.

**Comment by DellaBitta** [comment]
Hi @mckar02,

Great to hear!  I'll close this issue for now.  Thanks for following up with the results.
