### ISSUE TITLE
Unable to submit to apple store because CFBundleSupportedPlatforms

### ISSUE THREAD

**Issue by comtaler** [firebase/quickstart-unity#78]
After installing the latest Invite SDK, it failed to submit to apple store with the error pointing to invalid CFBundleSupportedPlatforms in Resources/GINInviteResources.bundle/Info.plist. The value is set to iPhoneSimulator.

**Comment by comtaler** [comment]
I googled the error and it should be set to iPhoneOS.

**Comment by stewartmiles** [comment]
I circled back with the Invites team and it turns out this bug was discovered in Firebase iOS pod 3.14.0 and fixed in 3.15.0.

We - Firebase Games SDK folks - will move the Unity plugin up to 3.17.0 in our next release which is coming *very soon* (we're doing QA now).

In the meantime you can update your project to use the 3.15.0 or above Cocoapod by changing all lines in Firebase/Editor/*Deps.cs files from stuff like this:

Google.VersionHandler.InvokeStaticMethod(iosResolver, "AddPod", new object[] { "Firebase/Core" }, new Dictionary<string, object>() { { "version", "3.14.0" }, { "minTargetSdk", "7.0" } });

to:

Google.VersionHandler.InvokeStaticMethod(iosResolver, "AddPod", new object[] { "Firebase/Core" }, new Dictionary<string, object>() { { "version", "3.17.0" }, { "minTargetSdk", "7.0" } });

Cheers,
Stewart

**Comment by jonsimantov** [comment]
We have released version 3.0.2 of the Firebase Unity SDK, which fixes this issue. You can view the release notes and download the new version from http://firebase.google.com/docs/unity/setup.
