### ISSUE TITLE
Auth: How to detect if user exists without email or phone number

### ISSUE THREAD

**Issue by wei-jiaxing** [firebase/quickstart-unity#784]
Hi,

In our project, we only use Firebase Auth By Anonymous, Sign In With Apple, Twitter Login, and Google Sign-in.

For example, there is a user who linked Twitter account with Firebase, but didn't link his Apple account. When he uses the Sign In With Apple, could I detect the user does not exist?

As the [document](https://firebase.google.com/docs/auth/unity/apple#next-steps) said, 
>After a user signs in for the first time, a new user account is created and linked to the credentials

in this situation if I call `SignInWithCredentialAsync`, Firebase will create a new account and link it to the apple's credentials. 

```
Firebase.Auth.Credential credential = Firebase.Auth.OAuthProvider.GetCredential("apple.com", appleIdToken, rawNonce, null);
auth.SignInWithCredentialAsync(credential)
```

Of course, this Firebase account does not exist in our server, ~so the sign-in will failed~ so we will make the sign-in fail with error dialog.
But the problem is, after that, when the user signed in the app with his Twitter account, and want to link with Apple account, there will be a ERROR which say the Apple account was already linked.

---
In the sample project, when I use `SignInWithEmailAndPasswordAsync` with a non-registered email address, it will return `AuthError.UserNotFound: Firebase.FirebaseException: There is no user record corresponding to this identifier` and not do anything else.

My question is, when user signed in by Sign In With Apple, Twitter Login, or Google Sign-in,
is there a similar function to detect if user exists without creating a new Firebase account?

Thank you

**Comment by Thaina** [comment]
You can use admin sdk for that

I have been propose this functionality for such times. You could also voice your request along with me here https://github.com/firebase/firebase-js-sdk/issues/1945

Firebase unity SDK will mostly reflect js. google most likely implement anything in js first

**Comment by Thaina** [comment]
However

> Of course, this Firebase account does not exist in our server, so the sign-in will failed.

I think this is wrong. If you do things correctly, all `SignIn` function always create non existed account immediately. The error most likely came from wrong token

**Comment by DellaBitta** [comment]
Hi @wei-jiaxing,  

As Thaina mentioned, the API doesn't have a method to directly query Firebase User and provider relationships.

If you don't have a Firebase User signed in (starting Firebase Auth from scratch) and the customer signs in with any provider then it should create an account for them.  If the Application starts from scratch again from the same phone and the customer choses a different provider, then yes, the backend will create a new Firebase User and the two Firebase users won't be associated with each other.

However, user data from the previous application session is stored in secure storage on the device.  When your application starts-up you can query the current Firebase User from Firebase Auth and if the user from the previous session should be returned to you and it can be reused.  You can query the providers associated with that FirebaseUser via the [ProviderData](https://firebase.google.com/docs/reference/unity/class/firebase/auth/firebase-user#providerdata) property.  Additionally if a customer attempts to sign in with a provider then I suggest the use of a link operation first (instead of a direct sign in).  Three scenarios could occur here:

1. If the provider hasn't been used before then you will have the happy path of one Firebase User account associated with multiple providers.  

1. If the provider has already been used before then you will have an error that the account is already linked, but the backend will have essentially a no-op and you can sign in.  

1. And if the provider has been linked with another account then you'll know that you'll have to do an account merge and maybe you can provide better messaging to the customer in your app.

I hope this helps!

**Comment by wei-jiaxing** [comment]
@Thaina 
Thanks for the information and we will discuss this.

>I think this is wrong. If you do things correctly, all SignIn function always create non existed account immediately. The error most likely came from wrong token

Sorry for the mistake, this is not the failure made by Firebase. I have modified the original text.

@DellaBitta
Thank you for the suggestion. We are using the similar strategies for our auto-login system, but this problem is occurred when user logs in from different phone.

Anyway, we will use the admin sdk or anything else to resolve the problem

**Comment by DellaBitta** [comment]
Hi @wei-jiaxing,

Ok, thanks for checking back in on this issue.  I'm going to close it for now but feel free to re-open it and/or mention me if you have follow ups on this particular topic.
