### ISSUE TITLE
Auth: Fake timeout during the phone number verification on iOS

### ISSUE THREAD

**Issue by adlercoder** [firebase/quickstart-unity#786]
* Unity editor version: 2019.4.10f1
  * Firebase Unity SDK version: 6.5.2
  * Source you installed the SDK: Unity Package Manager
  * Problematic Firebase Component: Auth
  * Other Firebase Components in use: Cloud Firestore, Remote Config
  * Additional SDKs you are using: Vuforia
  * Platform you are using the Unity editor on: Mac
  * Platform you are targeting: iOS, Android
  * Scripting Runtime: IL2CPP

The SDK calls `codeSent` and `codeAutoRetrievalTimeOut` callbacks on `VerifyPhoneNumber` immediately at the same time and doesn't wait for the timeout time. But I receive a SMS with code and still can get the credential with it.

1) Call `VerifyPhoneNumber` to get the verification code;
2) Receive the SMS with a `codeSent` callback;
3) Receive a timeout error;
4) Sigh in with this code, ignore the timeout error;
5) Successful authorization.

Works perfect on Android device with the same code logic.

**Comment by DellaBitta** [comment]
Hi @adlercoder,

Thanks for the ticket, The behavior you've encountered is expected on iOS.  Auto Retrieval isn't supported on that platform so the SDK returns this event immediately instead of waiting for the timeout.  This is documented in our [C++ SDK Reference Docs](https://firebase.google.com/docs/reference/cpp/class/firebase/auth/phone-auth-provider/listener#oncodeautoretrievaltimeout), but for some reason not at all in the [Unity SDK Reference Docs](https://firebase.google.com/docs/reference/unity/class/firebase/auth/phone-auth-provider#codeautoretrievaltimeout).  I'll create a ticket to update that documentation.  Thanks again!
