### ISSUE TITLE
Crashlytics not sending any crash reports, getting "failed to retrieve settings" error on logcat.

### ISSUE THREAD

**Issue by Brian-McElroy** [firebase/quickstart-unity#798]
### [REQUIRED] Please fill in the following fields:

  * Unity editor version: 2019.3.15f1
  * Firebase Unity SDK version:  firebase_unity_sdk_6.15.2
  * Source you installed the SDK: .unitypackage 
  * Problematic Firebase Component: Crashlytics
  * Other Firebase Components in use: Analytics
  * Additional SDKs you are using: Unity IAP, Gamesparks, Ironsource, Facebook, Appsflyer, GameAnalytics
  * Platform you are using the Unity editor on: Windows
  * Platform you are targeting: Android
  * Scripting Runtime: IL2CPP

### [REQUIRED] Please describe the issue here:

I am getting some data on analytics, but I cannot get crashlytics to report anything. Im stuck on this...
![image](https://user-images.githubusercontent.com/2582934/94442542-011aed80-019c-11eb-884e-be07075f395c.png)

#### Steps to reproduce:

Add the firebase analytics and crashlytics sdks.
Add the google-services.json  GoogleService-Info.plist files somewhere in assets folder
Add this code to initialise the firebase

`// Use this for initialization
    void Start () 
    {
        // Initialize Firebase
        Firebase.FirebaseApp.CheckAndFixDependenciesAsync().ContinueWith(task => {
            var dependencyStatus = task.Result;
            if (dependencyStatus == Firebase.DependencyStatus.Available)
            {
                // Create and hold a reference to your FirebaseApp,
                // where app is a Firebase.FirebaseApp property of your application class.
                // Crashlytics will use the DefaultInstance, as well;
                // this ensures that Crashlytics is initialized.
                Firebase.FirebaseApp app = Firebase.FirebaseApp.DefaultInstance;

                // Set a flag here for indicating that your project is ready to use Firebase.
                VisualDebugger.SetText("crashlytics initialised");
            }
            else
            {
                UnityEngine.Debug.LogError(System.String.Format(
                  "Could not resolve all Firebase dependencies: {0}",dependencyStatus));

                VisualDebugger.SetText("crashlytics NOT initialised: " + dependencyStatus);
                // Firebase Unity SDK is not safe to use here.
            }
        });

        Invoke("IsCrashEnabled", 5f);
    }

    void IsCrashEnabled()
    {
        VisualDebugger.AddLine("IsCrashlyticsCollectionEnabled: "+Firebase.Crashlytics.Crashlytics.IsCrashlyticsCollectionEnabled);
    }`

When I run the app, firebase is initialised successfully. Also Firebase.Crashlytics.Crashlytics.IsCrashlyticsCollectionEnabled returns true.

I crash the app in a number of different ways, then open it again without reinstalling. But no crash reports are sent.

When I watch logcat when starting the app I see this error from firebase each time the app is opened

![image](https://user-images.githubusercontent.com/2582934/94443976-bb5f2480-019d-11eb-9fcd-765ba6763538.png)

**Comment by Olegkodysh** [comment]
Could you enable debug mode (https://firebase.google.com/docs/crashlytics/test-implementation?platform=unity#enable_debug_logging) and post the full debug logs?

**Comment by Brian-McElroy** [comment]
@Olegkodysh I enabled full logging before intialising firebase.. Theres all the logs  https://pastebin.com/CqKpT0mT

There is an error at the very bottom  

com.SandwichGeneration.MakeASquare E/FirebaseCrashlytics: Settings request failed.
java.io.IOException: Canceled

**Comment by cynthiajoan** [comment]
Hi @Brian-McElroy ,

I'd like to ask a few questions.

1. Is this a new created app? Has the app been deleted and recreated?
2. Is the app created directly for Crashlytics, or migrate from Fabric?
    If migrate from Fabric, can you double check the following:

    Make sure no Fabric related file/folders in your app setup, eg Fabric related code in MainActivity.java
    Make sure your google-services.json is pointing to the correct Firebase project
    Make sure your Manifest file doesn't contain Fabric API key.

If you don't mind sharing your project setup files (google-services.json, gradle, manifest etc), we can investigate together of the above checks

**Comment by Brian-McElroy** [comment]
@cynthiajoan 
1. It is a new app. But during the process of setting up firebase in the web-app, I think at least once I deleted it and made a new one so I could start over.
2. Directly for Crashlytics, I dont even know what Fabric is.
3. ok But I cant post the google-services.json here otherwise anyone could connect their app to my firebase. Whats ure email?

**Comment by cynthiajoan** [comment]
Hi @Brian-McElroy, good to know this is a project directly created in Crashlytics, that makes things easy and you don't have to share the configuration files. The "Fail to retrieve settings" error usually happens once an app is deleted, and not restored properly. If you can take some time double check with this [doc](https://firebase.google.com/docs/crashlytics/get-started?authuser=0&platform=unity) to see if there is any step missing.

If everything looks correct to you but you are still suffering with the issue, it worth to submit a ticket [here](https://firebase.google.com/support/troubleshooter/crashlytics/missing) so our support team can get access to your project and see if anything not look correct.

**Comment by ikitae** [comment]
Same here

**Comment by sp-duarte-roso** [comment]
I am having the same issue and it's most likely related with the way Unity exports the android project starting from 2019.3.
In 2019.2 things work fine, but since 2019.3 (my case I'm on 2019.4) it stoped working.

**Comment by nchodelski** [comment]
I'm experiencing this as well in Unity 2019.4.11f1 w/ an Android app. At startup, I see the same error about not being able to retrieve settings (and can confirm the appId in the error URL matches the appId in Firebase Settings)

However, **i'm only experiencing it for 1 of 2 Firebase projects in the same Unity project - if I swap out Firebase configurations to those for a different Firebase project & appId, my Crashlytics reports start arriving in the console again**.  (I am triggering test crashes w/ a 'CrashlyticsTester' script as suggested in the guide). 

So in the same Unity project:
- if i swap in the config info for the 'working' Firebase android app and run a build, i start getting crash reports in Firebase.
- If I update my project with the config info from the 'not working' Firebase android app, I dont see any more crash reports arrive (have waited 24+ hrs to be sure they are not delayed).
- if i then replace the Firebase config info with the values for the 'working' Firebase android, crash reports start showing up in the console again.

So what I  makes me think it is not related to the Unity version and is related specifically to the contents of the 'firebase settings' json the Android app is trying to load. 

Also, I have Analytics setup and events are working in android for both Firebase projects - only the Crashlytic console for Android is not working for me.


**Other potentially useful details i noticed while investigating:**
JSON response for the android Crashlytics settings URL for the 'crashlytics is working' app:

I noticed when I called the settings URL fro the error but swapped in the Firebase ID for the Firebase app w/ working crashlytics setup, I got this JSON response:
`{"settings_version":3,"cache_duration":86400,"features":{"collect_logged_exceptions":true,"collect_reports":true,"collect_analytics":false,"prompt_enabled":false,"push_enabled":false,"firebase_crashlytics_enabled":false},"app":{"status":"activated","update_required":false,"report_upload_variant":2},"fabric":{"org_id":"5f6b8dbe629549d560000019","bundle_id":"com.greenparksports.XXX"}}
`

Meanwhile the settings link for the Firebase app where Android Crashlytics is broken returns only an empty dictionary:
`{}`
My theory is that the fact there are no settings at that endpoint is the reason why Crashlytics events are not being sent (my theory is because the app believes Crashlytics is not enabled if there are no settings available)

**Comment by sp-duarte-roso** [comment]
I wonder if there is a limit for free accounts, a limit in how many projects one can have, and so on.
After Natalia's hint I created another project and it gets the same error in 2019.2 🤷‍♂️ 

@nchodelski Did you also create "a lot" of projects in a short time like?

**Comment by nchodelski** [comment]
@sp-duarte-roso - My org has a paid Firebase account and both of the Firebase projects we have are about a year old, i think.

**Comment by sp-duarte-roso** [comment]
Turns out the message in Firebase console was pointing to the error.
> Add the Firebase Android SDK (17.1.1 or higher) or Unity Plugin (6.15.0 or higher), then build, run, and crash your app

We are using Plugin 6.15.0 but the dependency being added is 17.0.0. 

I've contacted support which shed some light into the problem:
> The error you are seeing "Failed to retrieve settings" is related to the SDK version being used. If you go to "Assets > Firebase > Editor> CrashlyticsDependencies" you can manually update the SDK to point to the latest Crashlytics SDK version 17.2.2. Please give it a try and if you continue having issues, let me know. 

Updating the dependency in our `mainTemplate.gradle` fixed it for us.

**Comment by starburst997** [comment]
I can confirm using `firebase-crashlytics:17.2.2` fixed the issue.

An easy way using the latest package (`6.16.0`) is to create a dependency file ending with `...Dependencies.xml` under an `Editor` folder anywhere in `Assets`
```xml
<dependencies>
  <androidPackages>
    <androidPackage spec="com.google.firebase:firebase-crashlytics:17.2.2">
    </androidPackage>
  </androidPackages>
</dependencies>
```

**Comment by Splitkill** [comment]
Tried these two solutions with 6.15.2 and 6.16.0. I just get more errors when I set crashlytics lib to 17.2.2. I get the following in logcat:
E/firebase: method_ids[i] || (method.optional == kMethodOptional)
E/Unity: method_ids[i] || (method.optional == kMethodOptional)
     
    (Filename: ./Runtime/Export/Debug.bindings.h Line: 45)
E/firebase: Unable to find Method com/google/firebase/crashlytics/internal/common/DataCollectionArbiter.setCrashlyticsDataCollectionEnabled (signature '(Z)V', instance).  Please verify the AAR which contains the com/google/firebase/crashlytics/internal/common/DataCollectionArbiter class is included in your app.

From Unity when I call Crashlytics.Log():
E/Unity: NullReferenceException: A null value was found where an object instance was required.
      at Firebase.Crashlytics.Crashlytics.Log (System.String message) [0x00000] in <filename unknown>:0 
      at System.Reflection.MonoMethod.Invoke (System.Object obj, BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture) [0x00000] in <filename unknown>:0

**Comment by nchodelski** [comment]
@Splitkill - I had the same issue as you did after setting my Unity project to use a custom `mainTemplate.gradle` file and manually setting the `Crashlytics-Dependencies.xml` to say `"com.google.firebase:firebase-crashlytics:17.2.2"

I found [this other unity-quckstart issue](https://github.com/firebase/quickstart-unity/issues/758) where it was explained we're seeing this problem when using 17.2.2 with unity:
 > It is caused by the latest version of 'com.google.firebase.firebase-crashlytics-17.2.1' where they change the method name while the Unity wrapper 'com.google.firebase.firebase-crashlytics-unity-6.15.2' is not updated yet. Ref: (https://firebase.google.com/support/release-notes/android#crashlytics_v17-2-1)

I was able to resolve the `Unable to find Method` error by instead specifying "com.google.firebase:firebase-crashlytics:17.1.1".
Finally i no longer see the settings error and I see from the logs the android app initializes version 17.1.1.

**Comment by Splitkill** [comment]
@nchodelski - Thanks for The recommendation. However, I tried this with both versions(6.15.2,6.16.0) of the unity SDK. The errors seem resolved but we still don't receive any crash reports.

**Comment by nchodelski** [comment]
Thanks for contacting support @sp-duarte-roso - the info about 17.0.0 being broken was key for me!

It took me 3 days to get all my ducks lined up, I was able to resolve my "can't retrieve settings" issue
some of the specific things I changed in my problem setup to fix this issue:
- In Unity, I modified the build process  to use a custom `mainTemplate.gradle` file to specify dependencies, rather than using the External Dependency Resolver to manage and embed unity packages (option in Build Settings > PlayerSettings > Android) - this seemed like the only way to specify the version for the android library `com.google.firebase:firebase-crashlytics`
     - I updated the library version in the `Crashlytics-Dependencies.xml` file within Assets > Plugins > Firebase to specify "com.google.firebase:firebase-crashlytics:17.1.1".
     - I also made a `MyProject-Dependencies.xml` file and placed it in Assets > Config > Editor  w/ same contents as @starburst997  shared, except i changed the version to specify `"com.google.firebase:firebase-crashlytics:17.1.1"` - Assets > Config is where i placed my `google-services.json` and `.plist` files for Firebase.
- i then ran External Dependency Resolver > Android > Force Resolve, which embeds a list of the dependencies for the Android build into the `mainTemplate.gradle` file - make sure to check this file and confirm you see version 17.1.1 after resolving.  (see below what was this looks like for my project).  
- I also noticed that ProjectSettings > AndroidResolverDependencies.xml was also updated to include `firebase-crashlytics:17.1.1` after resolving dependencies.

Weirdly, I noticed after running a local build the project for Android, both `firebase-crashlytics:17.0.0` and `firebase-crashlytics:17.1.1` were listed in my project's `mainTemplate.gradle` file (and in AndroidResolverDependencies.xml) - see below.
Why is this happening? My theory is that Firebase automatically specifies 17.0.0 as a dependency, but one or more of my *Dependency.xml files seems to be ensuring v17.1.1 is also compiled, and therefore I see in the logs `I/FirebaseCrashlytics: Initializing Crashlytics 17.1.1`, so i can confirm that version is actually running.
 

```
Dependencies section of my `mainTemplate.gradle` after doing Android dependency force resolve then Android local build (I'm using Crashlytics, Analytics, and Firebase Messaging)
dependencies {
    implementation fileTree(dir: 'libs', include: ['*.jar'])
// Android Resolver Dependencies Start
    implementation 'com.google.android.gms:play-services-base:17.4.0' // Packages/com.google.firebase.app/Firebase/Editor/AppDependencies.xml:17
    implementation 'com.google.firebase:firebase-analytics:17.5.0' // Packages/com.google.firebase.analytics/Firebase/Editor/AnalyticsDependencies.xml:13
    implementation 'com.google.firebase:firebase-analytics-unity:6.16.0' // Packages/com.google.firebase.analytics/Firebase/Editor/AnalyticsDependencies.xml:18
    implementation 'com.google.firebase:firebase-app-unity:6.16.0' // Packages/com.google.firebase.app/Firebase/Editor/AppDependencies.xml:22
    implementation 'com.google.firebase:firebase-common:19.3.1' // Packages/com.google.firebase.app/Firebase/Editor/AppDependencies.xml:13
    implementation 'com.google.firebase:firebase-crashlytics:17.0.0' // Packages/com.google.firebase.crashlytics/Firebase/Editor/CrashlyticsDependencies.xml:13
    implementation 'com.google.firebase:firebase-crashlytics:17.1.1' // Assets/Config/Editor/Dependencies.xml:4
    implementation 'com.google.firebase:firebase-crashlytics-unity:6.16.0' // Packages/com.google.firebase.crashlytics/Firebase/Editor/CrashlyticsDependencies.xml:20
    implementation 'com.google.firebase:firebase-messaging:20.2.4' // Packages/com.google.firebase.messaging/Firebase/Editor/MessagingDependencies.xml:13
    implementation 'com.google.firebase:firebase-messaging-unity:6.16.0' // Packages/com.google.firebase.messaging/Firebase/Editor/MessagingDependencies.xml:20
// Android Resolver Dependencies End
**DEPS**}
```

**Comment by nchodelski** [comment]
@Splitkill, are you using a custom `mainTemplate.gradle` file in your Unity build process for Android (see my previous post)?  

My rough understanding is that the `firebase-crashlytics-unity` library is a wrapper around `firebase:firebase-crashlytics` that allows the underlying functionality to be used in Unity. 

I think if you use Android External Dependency Manager to manage your dependencies but without using a custom gradle template, there is no way to manually specify which underlying version of the Android `firebase:firebase-crashlytics` library is included, and therefore `firebase:firebase-crashlytics-unity:6.16.0` is by default still loading `firebase-crashlytics:17.0.0. (i also didn't have success just updating from `6.15.2 to `6.16.0`

**Comment by nchodelski** [comment]
@Splitkill, one other thing i noticed is that when I upgraded from Firebase Crashlytics package `6.15.2` to `6.16.0`, and tried the solution, I found there was an extra `google-services.xml` file w/ the values for an older Firebase project & older Android app Id that were initially getting loaded (i was seeing the settings error again, except I noticed the config values in the settings were wrong - i'd deleted the old project so the settings URL 404s). 

What i did was I deleted the whole Assets/Plugins/Android folder, [realized i didn't know how to recreate missing plugin files), so I uninstalled and then re-installed Firebase Crashlytics 6.16.0 in the Unity Package manager.    
This recreated my Assets/Plugins/Android folder and I could confirm that all the `google-services.xml` files now had the correct config values.

My explanation for this is that Firebase Crashlytics version `6.15.2` keeps it's xlm files in a different place to version `6.16.0`, so the old file hanging around was possibly screwing up what Firebase project Crashlytics was getting config info for.

It seems like a long shot, but maybe you have this situation too when you use Firebase Crashlytics untiy 6.16.0.

If it helps, this is the structure of my `Assets/Plugins/Android` folder now after doing the above deletion and uninstall/reinstall of Unity Crashlytics package:
![Screen Shot 2020-10-12 at 8 53 42 PM](https://user-images.githubusercontent.com/10591026/95813613-1bd98000-0ccd-11eb-8155-a315ea3f8263.png)

**Comment by Splitkill** [comment]
@nchodelski Thanks, your info helped. I did have to clear out the older version of Crashlytics completely and clean install from the 6.16.0 unity package. However, I still found my self without any crash reports. 6.16.0 Unity Package Doesn't work with Unity 2018.4.6f1. The app would build and Chrashlytics 17.1.1 would initialize but crashes would not be reported. I had to update my unity editor to the latest of 2018.4 LTS.

**Comment by FaisalAbtach** [comment]
I m seeing this in logcat and still no crash reported in console:

2020-10-19 10:52:16.706 6085-6085/? D/FirebaseApp: com.google.firebase.auth.FirebaseAuth is not linked. Skipping initialization.
2020-10-19 10:52:16.706 6085-6085/? D/FirebaseApp: com.google.firebase.crash.FirebaseCrash is not linked. Skipping initialization.
2020-10-19 10:52:16.723 6085-6085/? I/FirebaseInitProvider: FirebaseApp initialization successful

**Comment by mrichards** [comment]
Hi folks, there may be a few different issues going on at once here. We recently discovered a backend issue that was preventing some new Android Unity apps from being properly registered with Crashlytics. That was fixed on Friday, so if you were still having trouble last week, please give it another attempt and let us know if you are still having trouble.

The next release of the Crashlytics Unity Plugin will include a fix for the NoSuchMethodException, and will ship with the newest Crashlytics for Android SDK. Until that release, manually updating to version 17.2.x of the Android will not work, as @nchodelski described.

**Comment by FaisalAbtach** [comment]
Hi, I m seeing this message at the moment.

```
CrashlyticsInitProvider: CrashlyticsInitProvider skipping initialization:
crashlytics app initializer Disabling:
```

**Comment by swap-mpl** [comment]
Hi,

I am getting this error while trying to run Crashlytics for a test app.

`Failed to read Firebase options from the app's resources. Either make sure google-services.json is included in your build or specify options explicitly.`

Unity 2019.2.21f1
Firebase SDK 6.16.0

**Comment by chkuang-g** [comment]
@swap-mpl 

As mentioned in https://github.com/firebase/quickstart-unity/issues/824#issuecomment-713072851, `Disable module 'crashlytics'` log is harmless.

I think the main issue is `Failed to read Firebase options from the app's resources.`.  Could you check if `Assets/Plugins/Android/FirebaseApp.androidlib/res/value/google-services.xml` exists?

**Comment by laminhtruong** [comment]
> @swap-mpl
> 
> As mentioned in [#824 (comment)](https://github.com/firebase/quickstart-unity/issues/824#issuecomment-713072851), `Disable module 'crashlytics'` log is harmless.
> 
> I think the main issue is `Failed to read Firebase options from the app's resources.`. Could you check if `Assets/Plugins/Android/FirebaseApp.androidlib/res/value/google-services.xml` exists?

I have same problem and I can confirmed that file is exist

**Comment by swap-mpl** [comment]
@chkuang-g Updated to SDK 6.16.1, now I dont get the above error. SDK is initialized but I dont see any errors logged in the dashboard. I am using a test script to generate non fatals. Attached is a screenshot for your reference.
<img width="1422" alt="Screenshot 2020-10-22 at 9 02 18 AM" src="https://user-images.githubusercontent.com/73164247/96821404-684b5b00-1445-11eb-93ec-f00db4a739ea.png">

**Comment by FaisalAbtach** [comment]
> @swap-mpl
> 
> As mentioned in [#824 (comment)](https://github.com/firebase/quickstart-unity/issues/824#issuecomment-713072851), `Disable module 'crashlytics'` log is harmless.
> 
> I think the main issue is `Failed to read Firebase options from the app's resources.`. Could you check if `Assets/Plugins/Android/FirebaseApp.androidlib/res/value/google-services.xml` exists?

What about this one ? 

CrashlyticsInitProvider: CrashlyticsInitProvider skipping initialization:

**Comment by chkuang-g** [comment]
@swap-mpl 

Could you try your Firebase project with Crashlytics quickstart?
https://github.com/firebase/quickstart-unity/tree/master/crashlytics/testapp

Crashlytics would only start working after at least one instance of FirebaseApp is created, like this
https://github.com/firebase/quickstart-unity/blob/master/crashlytics/testapp/Assets/Firebase/Sample/Crashlytics/UIHandler.cs#L59

@FaisalAbtach 
I am not sure what that message is.  As long as it is followed by `crashlytics .... initialize ....successful`, you should be good.
Are you not seeing any statistics on your dashboard either?

**Comment by FaisalAbtach** [comment]
No I m not seeing any statistics in the dashboard, nor `crashlytics .... initialize ....successful` message in the logs.

**Comment by AllanRW** [comment]
> No I m not seeing any statistics in the dashboard, nor `crashlytics .... initialize ....successful` message in the logs.

I've added "Crashlytics.IsCrashlyticsCollectionEnabled = true;" to get it working... maybe we just need to add something related to Crashlytics on the project to Unity add the dependencies.

**Comment by FaisalAbtach** [comment]
> > No I m not seeing any statistics in the dashboard, nor `crashlytics .... initialize ....successful` message in the logs.
> 
> I've added "Crashlytics.IsCrashlyticsCollectionEnabled = true;" to get it working... maybe we just need to add something related to Crashlytics on the project to Unity add the dependencies.

I will try this.

**Comment by FaisalAbtach** [comment]
Now i m seeing these logs in logcat, and still no stats on dashboard.

```
Disable module 'crashlytics' for 'Firebase.Crashlytics.FirebaseCrashlytics, Firebase.Crashlytics'
crashlytics app initializer Disabling
```

**Comment by fernando-closs-clansoft** [comment]
Same here. I've update from 6.15 to 6.16.1 to solve the Gradle error (duplicated BuildConfig) and now I get nothing new on the dashboard (no crash, no event, not even shows my newest version there). No other changes were made. It was a simple Firebase Package update on Package Manager.

**Comment by ZaheerFaisal** [comment]
> > No I m not seeing any statistics in the dashboard, nor `crashlytics .... initialize ....successful` message in the logs.
> 
> I've added "Crashlytics.IsCrashlyticsCollectionEnabled = true;" to get it working... maybe we just need to add something related to Crashlytics on the project to Unity add the dependencies.

@AllanRW Where you have added this code ? I have added after checking dependencies but still no luck.

**Comment by AllanRW** [comment]
@ZaheerFaisal I've added at Start method of my Firebase Manager script, before the Firebase init code, make sure to also add "Firebase.FirebaseApp.LogLevel = Firebase.LogLevel.Debug;" to show debug messages.

**Comment by Vasilisk7** [comment]
Hello, I have the same problem.

I ab use Unity 2019.4.13f1
My app was already connected to firebase and working. I decided to add crashlitics and update the library to 6.16.1.
![image](https://user-images.githubusercontent.com/35864378/97785607-0a421480-1bb7-11eb-82c1-71329a667058.png)

In the console, I get a message that "FirebaseCrashlytics successfully initialized"
![image](https://user-images.githubusercontent.com/35864378/97785619-2776e300-1bb7-11eb-87ad-cc2e7fec27be.png)

BUT, in console.firebase.google.com not connected FirebaseCrashlytics
![image](https://user-images.githubusercontent.com/35864378/97785644-660c9d80-1bb7-11eb-86d4-d84cb1038c68.png)

**Comment by ZaheerFaisal** [comment]
> @ZaheerFaisal I've added at Start method of my Firebase Manager script, before the Firebase init code, make sure to also add "Firebase.FirebaseApp.LogLevel = Firebase.LogLevel.Debug;" to show debug messages.

I have done exactly the same and the logs says:

Unity: Disable module 'crashlytics' for 'Firebase.Crashlytics.FirebaseCrashlytics, Firebase.Crashlytics'
    UnityEngine.Logger:Log(LogType, Object)
    Firebase.FirebaseApp:InitializeAppUtilCallbacks()
    Firebase.FirebaseApp:CreateAndTrack(CreateDelegate, FirebaseApp)
    Firebase.Crashlytics.AndroidImpl:.ctor()
    Firebase.Crashlytics.Impl:Make()
    Firebase.Crashlytics.PlatformAccessor:.cctor()
    Firebase.Crashlytics.Crashlytics:set_IsCrashlyticsCollectionEnabled(Boolean)

**Comment by ZaheerFaisal** [comment]
> @ZaheerFaisal I've added at Start method of my Firebase Manager script, before the Firebase init code, make sure to also add "Firebase.FirebaseApp.LogLevel = Firebase.LogLevel.Debug;" to show debug messages.

Ok now I m seeing test crashes in the dashboard, it worked.

**Comment by Vasilisk7** [comment]
> > @ZaheerFaisal I've added at Start method of my Firebase Manager script, before the Firebase init code, make sure to also add "Firebase.FirebaseApp.LogLevel = Firebase.LogLevel.Debug;" to show debug messages.
> 
> Ok now I m seeing test crashes in the dashboard, it worked.

did not help :(

**Comment by ZaheerFaisal** [comment]
@Vasilisk7 Did you followed these steps ?
[https://firebase.google.com/docs/crashlytics/get-started?platform=unity](url)
[https://firebase.google.com/docs/crashlytics/test-implementation?platform=unity](url)

**Comment by Vasilisk7** [comment]
> @Vasilisk7 Did you followed these steps ?
> [https://firebase.google.com/docs/crashlytics/get-started?platform=unity](url)
> [https://firebase.google.com/docs/crashlytics/test-implementation?platform=unity](url)

Yes and yes, did everything as written.

**Comment by Vasilisk7** [comment]
I am deleted folder Assets/ExternalDependencyManager. Downloading files started automatically, then I installed the application on my phone and everything worked.
Crashlytics is visible on the site.

**Comment by chkuang-g** [comment]
@Vasilisk7 

According to your posts, I assume you install Firebase through Unity Package Manager.  In that case, a copy of EDM4U will be installed through UPM as well and result in duplicated copy of EDM4U.  See [this issue](https://firebase.google.com/docs/unity/setup#installation_conflict_when_using_unity_package_manager)

Removing `Assets/ExternalDependencyManager` is the right way to go.  I would also recommend you to reinstall EDM4U through UPM just in case any file is missing because they shares the same GUID.

Shawn

**Comment by bilck** [comment]
This issue is happening to us.

Unity 2019.4.14f1
Firebase Crashlytics v6.16.1
EDM4U v1.2.161

Log sample:

`2020/11/22 23:17:43.791 23823 23951 Warn System ClassLoader referenced unknown path: system/framework/mediatek-cta.jar
2020/11/22 23:17:43.792 23823 23951 Info System.out [okhttp] e:java.lang.ClassNotFoundException: com.mediatek.cta.CtaUtils
2020/11/22 23:17:43.793 23823 23951 Info System.out [socket]:check permission begin!
2020/11/22 23:17:43.793 23823 23951 Warn System ClassLoader referenced unknown path: system/framework/mediatek-cta.jar
2020/11/22 23:17:43.794 23823 23951 Info System.out [socket] e:java.lang.ClassNotFoundException: com.mediatek.cta.CtaUtils
2020/11/22 23:17:43.953 23823 23948 Error FirebaseCrashlytics Settings request failed.
2020/11/22 23:17:43.953 23823 23948 Error FirebaseCrashlytics java.io.InterruptedIOException: timeout
2020/11/22 23:17:43.953 23823 23948 Error FirebaseCrashlytics 	at okhttp3.y.a(Unknown Source:13)
2020/11/22 23:17:43.953 23823 23948 Error FirebaseCrashlytics 	at okhttp3.y.a(Unknown Source:58)
2020/11/22 23:17:43.953 23823 23948 Error FirebaseCrashlytics 	at com.google.firebase.crashlytics.internal.d.b.b(Unknown Source:10)
2020/11/22 23:17:43.953 23823 23948 Error FirebaseCrashlytics 	at com.google.firebase.crashlytics.internal.settings.b.c.a(Unknown Source:62)
2020/11/22 23:17:43.953 23823 23948 Error FirebaseCrashlytics 	at com.google.firebase.crashlytics.internal.settings.d$1.a(Unknown Source:13)
2020/11/22 23:17:43.953 23823 23948 Error FirebaseCrashlytics 	at com.google.firebase.crashlytics.internal.settings.d$1.a(Unknown Source:2)
2020/11/22 23:17:43.953 23823 23948 Error FirebaseCrashlytics 	at com.google.android.gms.tasks.q.run(Unknown Source:12)
2020/11/22 23:17:43.953 23823 23948 Error FirebaseCrashlytics 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
2020/11/22 23:17:43.953 23823 23948 Error FirebaseCrashlytics 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
2020/11/22 23:17:43.953 23823 23948 Error FirebaseCrashlytics 	at com.google.firebase.crashlytics.internal.common.q$1$1.a(Unknown Source:2)
2020/11/22 23:17:43.953 23823 23948 Error FirebaseCrashlytics 	at com.google.firebase.crashlytics.internal.common.d.run(Unknown Source:5)
2020/11/22 23:17:43.953 23823 23948 Error FirebaseCrashlytics 	at java.lang.Thread.run(Thread.java:919)
2020/11/22 23:17:43.953 23823 23948 Error FirebaseCrashlytics Caused by: java.io.IOException: Canceled
2020/11/22 23:17:43.953 23823 23948 Error FirebaseCrashlytics 	at okhttp3.internal.c.j.a(Unknown Source:288)
2020/11/22 23:17:43.953 23823 23948 Error FirebaseCrashlytics 	at okhttp3.internal.c.g.a(Unknown Source:158)
2020/11/22 23:17:43.953 23823 23948 Error FirebaseCrashlytics 	at okhttp3.internal.c.g.a(Unknown Source:6)
2020/11/22 23:17:43.953 23823 23948 Error FirebaseCrashlytics 	at okhttp3.y.g(Unknown Source:115)
2020/11/22 23:17:43.953 23823 23948 Error FirebaseCrashlytics 	at okhttp3.y.a(Unknown Source:31)
2020/11/22 23:17:43.953 23823 23948 Error FirebaseCrashlytics 	... 10 more
`

**Comment by chkuang-g** [comment]
@bilck 

This is interesting log.  Seems like the exception is thrown at [this line of code](https://github.com/firebase/firebase-android-sdk/blob/5440af41f0d15ff1358038dc31fcd1d4eac0a89c/firebase-crashlytics/src/main/java/com/google/firebase/crashlytics/internal/settings/network/DefaultSettingsSpiCall.java#L91). 

I can imagine many reasons why an HTTP request is failed from timeout.  For instance, spotty network or some issues in backend. Could you try it again and perhaps try with [quick start](https://github.com/firebase/quickstart-unity/tree/master/crashlytics/testapp) so that we can isolate the issue a bit more.
