### ISSUE TITLE
Unity -  OnMessageReceived provides "null" notification when app in background

### ISSUE THREAD

**Issue by andr-construction** [firebase/quickstart-unity#80]
Hi,
I'm using the Unity code with an Android app. When the app is running in foreground the notification is properly received, OnMessageReceived is called and the e.Message.Notification is proper. When the application is in background, or not running, then a notification appears in the Android tray, but when clicked - the application opens and OnMessageReceived is called with e.Message.Notification == null. 
Is this the proper behaviour? Should e.Message.Notification become "null" in the app callback when opened from tray?

**Comment by stewartmiles** [comment]
Yep this is currently the expected behavior.  From https://firebase.google.com/docs/cloud-messaging/android/receive#handling_messages

**Messages with both notification and data payload, both background and foreground.** In this case, the notification is delivered to the device’s system tray, and the data payload is delivered in the extras of the intent of your launcher Activity.

Also, see https://firebase.google.com/docs/cloud-messaging/concept-options#notifications_and_data_messages

Essentially the intent for the notification component is simply to be displayed to the user where the data is where you can add a payload for your app to process.   You receive the notification when the app is in the foreground so that you can pop up the notification in whatever way you want.

**Comment by nabeelpkl** [comment]
Have the same issue. In my case, I will receive an image url in data and I have to show a Notification with big image using that. I want to invoke that inside onMessageRefceived. But here I am not able to do that. Is there a work around to this ?

**Comment by longvannguyendx** [comment]
The same issue, , how to detect message is received from clicked on push notification?

**Comment by giggioz** [comment]
Same issue.

I don't think the expected behaviour is not calling OnMessageReceived when in background: if you build an apk from the official quickstart-unity-master (https://github.com/firebase/quickstart-unity/tree/master/messaging/testapp) **it does call the OnMessageReceived!**

Thanks!

**Comment by giggioz** [comment]
Important Update:

I think I've found something: the quickstart project above was built with Unity 2018.3.4f1 and worked as I described.

Now I upgraded the project to 2019.1.2.f1 (to match the project in which I have the issue) and the behavior has changed!
OnMessageReceived is not called anymore when the app is in background!

**Comment by giggioz** [comment]
Sorry guys, I don't know what to say: I've just re-tested my project and the sample project (both in 2019.1.2.f1) and now everything works fine.

OnMessageReceived is called in background and foreground with the custom payload.

I'm 100% sure that my previous tests were correct (I took notes because I was getting crazy) so I can only suppose that one needs to wait a while until Firebase sets everything right in its platform.

I also deleted my previous comments, sorry for that.
