### ISSUE TITLE
 Could not load type of field 'Firebase.Editor.SettingsWindow:measurementSettings'

### ISSUE THREAD

**Issue by codexyz1** [firebase/quickstart-unity#813]
Patrick Martin asked me to present my issue here. Please help
I tried to open 'Window > Firebase > Documentation' in Unity but it would give me this error:

TypeLoadException: Could not load type of field 'Firebase.Editor.SettingsWindow:measurementSettings' (1) due to: Could not resolve type with token 01000005 (from typeref, class/assembly Google.EditorMeasurement, Google.VersionHandlerImpl, Version=1.2.0.0, Culture=neutral, PublicKeyToken=null) assembly:Google.VersionHandlerImpl, Version=1.2.0.0, Culture=neutral, PublicKeyToken=null type:Google.EditorMeasurement member:(null) signature:<none>

**Comment by chkuang-g** [comment]
Hi @codexyz1 

Sorry I do not have context about your previous conversation with Patrick Martin. Could you fill out this template? This will really help us to narrow down the issue.

FWIW, this type of issue usually happens when EDM4U is not properly loaded (Google.VersionHandlerImpl.dll specifically).  I can blindly give you some suggestions if that help.

- Remove `Assets/ExternalDependencyManager` and `Assets/PlayServicesResolver` folders
- Reimport Firebase SDK, which includes EDM4U
- Restart your Unity editor, which usually helps to properly load all dlls.

If these do not help, please give us more information.  And/Or the link to your previous comments.

Thanks,
Shawn

### [REQUIRED] Please fill in the following fields:

  * Unity editor version: _____
  * Firebase Unity SDK version: _____
  * Source you installed the SDK: _____ (.unitypackage or Unity Package Manager)
  * Problematic Firebase Component: _____ (Auth, Database, etc.)
  * Other Firebase Components in use: _____ (Auth, Database, etc.)
  * Additional SDKs you are using: _____ (Facebook, AdMob, etc.)
  * Platform you are using the Unity editor on: _____ (Mac, Windows, or Linux)
  * Platform you are targeting: _____ (iOS, Android, and/or desktop)
  * Scripting Runtime: _____ (Mono, and/or IL2CPP)

### [REQUIRED] Please describe the issue here:

(Please list the full steps to reproduce the issue. Include device logs, Unity logs, and stack traces if available.)

#### Steps to reproduce:

Have you been able to reproduce this issue with just the Firebase Unity quickstarts (this GitHub project)?
What's the issue repro rate? (eg 100%, 1/5 etc)

What happened? How can we make the problem occur?
This could be a description, log/console output, etc.

If you have a downloadable sample project that reproduces the bug you're reporting, you will
likely receive a faster response on your issue.

#### Relevant Code:

```
// TODO(you): code here to reproduce the problem
```
