### ISSUE TITLE
FBLPromise+Any.m line 33 Crash 

### ISSUE THREAD

**Issue by okanulas** [firebase/quickstart-unity#825]
### [REQUIRED] Please fill in the following fields:

  * Unity editor version: 2018.4.19
  * Firebase Unity SDK version: 6.16.0
  * Source you installed the SDK: .unitypackage
  * Problematic Firebase Component: Analytics
  * Other Firebase Components in use: Messaging, Crashlytics
  * Additional SDKs you are using: Facebook, Adjust, Helpshift, One Signal
  * Platform you are using the Unity editor on: Mac
  * Platform you are targeting: iOS & Android
  * Scripting Runtime: IL2CPP

### [REQUIRED] Please describe the issue here:

We can not reproduce the issue in-house but we're receiving crash reports from the Crashlytics. I'm adding a few crash reports. It looks like the users only experience this crash once then move on. We're suspecting it could be related to the Firebase upgrade.

[FBL003.txt](https://github.com/firebase/quickstart-unity/files/5383916/FBL003.txt)
[FBL002.txt](https://github.com/firebase/quickstart-unity/files/5383917/FBL002.txt)
[FBL001.txt](https://github.com/firebase/quickstart-unity/files/5383918/FBL001.txt)

#### Steps to reproduce:

Have you been able to reproduce this issue with just the Firebase Unity quickstarts (this GitHub project)?
No
What's the issue repro rate? (eg 100%, 1/5 etc)
We don't know.

What happened? How can we make the problem occur?
We don't know. We only have crash reports.

If you have a downloadable sample project that reproduces the bug you're reporting, you will
likely receive a faster response on your issue.

**Comment by chkuang-g** [comment]
Hi @okanulas 

Did you see this on both iOS and Android devices, or iOS device only? Your callstack looks like iOS one.

According to the second and the third callstack, it looks like some firebase::Mutex failed to be destroyed and try to log the message by invoking Unity Debug API when the app is terminated. While the app is being torn apart, it is probably not a good time to call a Unity API. 
https://github.com/firebase/firebase-cpp-sdk/blob/f0a9d5b65e3a014aee347ea9bb3b664cdce2ae55/app/src/mutex.h#L53

We can potentially try to detect when iOS app is going to be torn apart and unhook the log function from Unity API. Do you think this is causing your user any trouble?  I assume this is a minor app crash which may not deteriorate user experience.

For your first callstack, it resembles #788 up until `RuntimeInvoker_FalseSByte_` part. Is it possible to find `Il2CppInvokerTable.cpp:40724` in your xcode project and see if you find more information? That callstack does not look like related to Firebase SDK.

**Comment by okanulas** [comment]
Hi, @chkuang-g. Thank you for your patience. It is a busy week for me. 

Yes, this crash only affects iOS devices. I didn't see any crash reports from Android devices. 

I found that there are "FBLPromise+Any.m - Line 33" logs in other crash reports. Firebase most likely trying to access memory locations when the app is crashing. I think it is a good idea to remove Unity log calls or stop Firebase threads if the app is crashing. 

Here is the Il2CppInvokerTable.cpp:40724 . I couldn't find the caller method and the real usage scenario. Hope it helps.
`void* RuntimeInvoker_TrueVoid_t22962CB4C05B1D89B55A6E1139F0E87A90987017_RuntimeObject_Int32_t585191389E07734F19F3156FF88FB3EF4800D102_Int32_t585191389E07734F19F3156FF88FB3EF4800D102 (Il2CppMethodPointer methodPointer, const RuntimeMethod* methodMetadata, void* obj, void** args)
{
	typedef void (*Func)(void* obj, RuntimeObject * p1, int32_t p2, int32_t p3, const RuntimeMethod* method);
	((Func)methodPointer)(obj, (RuntimeObject *)args[0], *((int32_t*)args[1]), *((int32_t*)args[2]), methodMetadata);
	return NULL;
}`

**Comment by Bomadeno** [comment]
I'm seeing a similar issue. Different stack traces leading to it, but always FBLPromise+Any.m - Line 33 at the root. These issues occur on launch, and also mid-game.

We have almost identical stack:
Unity editor version: 2018.4.**24**
Firebase Unity SDK version: 6.16.0
Source you installed the SDK: **External dependency manager**
Problematic Firebase Component: Analytics **(?probably?)**
Other Firebase Components in use: FCM/Messaging, Crashlytics, **Analytics, Dynamic links**
Additional SDKs you are using: a bunch
Platform you are using the Unity editor on: Mac, Windows
Platform you are targeting: iOS & Android (only iOS is affected)
Scripting Runtime: IL2CPP

Steps to reproduce:
Have you been able to reproduce this issue with just the Firebase Unity quickstarts (this GitHub project)?
No
What's the issue repro rate? (eg 100%, 1/5 etc)
**10% of iOS users.** (by users affected. Probably a much lower % by session. Only shows in Firebase, is not reported by iTunes)

What happened? How can we make the problem occur?
We don't know. We only have crash reports.

**Comment by chkuang-g** [comment]
Hey folk,

I think it is worth to share some of my findings.

- If you look into [FBLPromise+Any.m:33](https://github.com/google/promises/blob/b2f2c2dbc7d0deef3f86d08957151671c8df5f41/Sources/FBLPromises/FBLPromise%2BAny.m#L33), you should find this assert when one of the passed-in promise is still pending.  This part of code has not been changed since Jan 2018 so I assume the line number should be accurate enough.
- Based on the code,`FBLPromiseCombineValuesAndErrors` can only be accessible through Objective-C call like `[FBLPromise onQueue:myQueue any:myPromises]`.  However, I cannot find any this kind of usage in [Firebase iOS SDK](https://github.com/firebase/firebase-ios-sdk).
- When you see callstack like `RuntimeInvoker_FalseSByte_`, this is most likely generated by [Unity IL2CPP](https://docs.unity3d.com/Manual/IL2CPP.html). Unfortunately I do know know what that is generate from, nor do we have control about it.
- It seems that all the user who experienced this issue is using Unity 2018 (three on 2018.4)

All these information leads me to think that this might be an issue in Unity instead of Firebase.

FWIW, could you try to upgrade to later version of Unity and see if you are still seeing the crash reporting?

Shawn
