### ISSUE TITLE
FR: Make FirebaseApp.Dispose() call FirebaseHandler.Terminate()

### ISSUE THREAD

**Issue by henriqueYS** [firebase/quickstart-unity#839]
### Feature proposal

* Firebase Component: Analytics (Auth, Core, Database, Firestore, Messaging, Storage, etc)

We currently use only Firebase Analytics in our project.

We have a few tests that end up initializing a FirebaseApp instance and when we finish a run we call `FirebaseApp.DefaultInstance.Dispose()`. But a Firebase object is still running (marked as `DontDestroyOnLoad`), introducing some issues for us. 

We ended up using reflection to call `FirebaseHandler.Terminate()`, which works as it is but  it's a very vulnerable code.

Thanks!

**Comment by DellaBitta** [comment]
Hi @henriqueYS,

The DontDestroyOnLoad object is there by design and is used as a safeguard our internal systems in scenarios where there are multiple apps .  We've attempted to destroy the handler, as you mentioned, but it caused other issues and bugs.

Long story short: you're currently doing the right thing by calling Terminate() for your testing purposes. 

Thanks for the ticket!
