### ISSUE TITLE
Deprecated gradle features Firestore MacOS

### ISSUE THREAD

**Issue by KikiLebrun** [firebase/quickstart-unity#843]
### [REQUIRED] Please fill in the following fields:

  * Gradle version: 5.6.4
  * Unity editor version: 2019.3.8f1
  * Firebase Unity SDK version: 6.16.0
  * Source you installed the SDK: Unity Package Manager & .unitypackage
  * Problematic Firebase Component: Firestore (Auth, Database, etc.)
  * Additional SDKs you are using:  No one (Facebook, AdMob, etc.)
  * Platform you are using the Unity editor on: Mac OS (Mac, Windows, or Linux)
  * Platform you are targeting: Android (iOS, Android, and/or desktop)
  * Scripting Runtime: IL2CPP & Mono (Mono, and/or IL2CPP)

### [REQUIRED] Please describe the issue here:

(Please list the full steps to reproduce the issue. Include device logs, Unity logs, and stack traces if available.)

#### Steps to reproduce:

Install firestore sdk from UPM or unitypackage. Then, build the app and finally it doesn't build.

Have you been able to reproduce this issue with just the Firebase Unity quickstarts (this GitHub project)?
Yes (with Firestore sample project)

What's the issue repro rate? (eg 100%, 1/5 etc)
100%

What happened? How can we make the problem occur?
This could be a description, log/console output, etc.

When I try to build an Android app with Firestore, I have this error in Unity: 
```
Note: /Users/kilianlebrun/Github/Immersiv/quickstart-unity/firestore/testapp/Temp/gradleOut/unityLibrary/src/main/java/com/unity3d/player/UnityPlayerActivity.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
error processing /Users/kilianlebrun/Github/Immersiv/quickstart-unity/firestore/testapp/Temp/gradleOut/unityLibrary/libs/com.google.code.gson.gson-2.8.6.jar
...
\> Task :launcher:transformClassesWithDexBuilderForRelease FAILED
Deprecated Gradle features were used in this build, making it incompatible with Gradle 6.0.
```

#### Relevant Code:
No code

**Comment by patm1987** [comment]
@KikiLebrun : can you expand on how you're building for Android? Are you clicking "Build" or "Build and Run":
![image](https://user-images.githubusercontent.com/1111611/98577187-ce731300-2278-11eb-9e6f-1c938391e3e8.png)

Or are you exporting your project:
![image](https://user-images.githubusercontent.com/1111611/98577211-da5ed500-2278-11eb-8633-cfcef6b165ac.png)

I ask because Unity packages a version of gradle with its editor, and typically uses [that](https://docs.unity3d.com/2020.2/Documentation/Manual/android-gradle-overview.html) in Unity itself.

If you're invoking gradle directly, it may be worth checking the [gradle version in Unity's docs](https://docs.unity3d.com/2020.2/Documentation/Manual/android-gradle-overview.html) then generating a wrapper for that. For example, since you're using 2019.3.8f1, you could export your project and then type this in that directory:
```
gradle wrapper --gradle-version 5.1.1
```

And then do a `./gradlew build` rather than a `gradle build`

**Comment by KikiLebrun** [comment]
Hello Patrick, thank you very much for your answer first.
Then, I use the first method, and I usually do a "Build and Run"

Is it a problem of Unity version then ? because according to the link of Unity doc that you sent me, 2019.3 is using 5.1.1

Thank you

**Comment by schmidt-sebastian** [comment]
@KikiLebrun Are you still blocked on this? Otherwise, I would like to close this issue. Thank you and sorry for the slow replies.

**Comment by ahmedaniss25** [comment]
Problem fixed here : https://youtu.be/A5cbLhoLehs

**Comment by KikiLebrun** [comment]
I'll look for it thank, you for the help !
