### ISSUE TITLE
Android: Execution failed for task ':launcher:uploadCrashlyticsMappingFileDebug'.

### ISSUE THREAD

**Issue by rlehmannJC** [firebase/quickstart-unity#863]
### [REQUIRED] Please fill in the following fields:

  * Unity editor version: 2019.4.13f1
  * Firebase Unity SDK version: 6.16.1
  * Source you installed the SDK: UPM
  * Problematic Firebase Component: Crashlytics
  * Other Firebase Components in use: Auth, DynamicLinks, etc.
  * Additional SDKs you are using: Facebook, Admob, etc.
  * Platform you are using the Unity editor on: Mac
  * Platform you are targeting: Android
  * Scripting Runtime: IL2CPP

### [REQUIRED] Please describe the issue here:

I tried to gain Android NDK crash reports.
For that I added to baseProjectTemplate.gradle:
`classpath 'com.google.firebase:firebase-crashlytics-gradle:2.2.0'`
and into the launcherTemplate.gradle:
`apply plugin: 'com.google.firebase.crashlytics'`
and at the end of my mainTemplate.gradle
`android {
    sourceSets {
        main {
            def unityProjectPath = $/file:///**DIR_UNITYPROJECT**/$.replace("\\", "/")
            res.srcDirs += (unityProjectPath +  '/Assets/Plugins/Android/Firebase/res/values/google-services.xml')
        }
    }
}`

The android build will then return the following error during build:
`* What went wrong:
Execution failed for task ':launcher:uploadCrashlyticsMappingFileDebug'.
> Crashlytics could not find the resource file generated by Google Services. You may need to execute the :process<Variant>GoogleServices Task. Please check your Firebase project configuration (https://firebase.google.com/docs/android/setup). `

Even so I can find the correct 'google-services.xml'. (I once duplicated the res.srcDirs operation and got the expected Duplicated Error), so that is working for it.

#### Steps to reproduce:

Have you been able to reproduce this issue with just the Firebase Unity quickstarts (this GitHub project)?
100%

What happened? How can we make the problem occur?
Just build Android :)

#### Relevant Code:
I think the problem lies within the com.google.firebase:firebase-crashlytics-gradle:2.2.0 plugin,
I quick look into the the decompiled code of it revealed, that the issue is inside:
`public static String getGoogleAppId(final Object project, final Object variant)`

It tries to combine the following path in order to find the resource:
`<project>/generated/res/google-services/<variant>/values/values.xml`

I think this is not correct. 
I also checked the guide here:
https://firebase.googleblog.com/2020/08/firebase-compatibility-with-unity-20201.html

Don't see why it should work there, expect Unity changed something on the resulting StagingArea structure.

Cheers

**Comment by cynthiajoan** [comment]
Hi @rlehmannJC, In 6.15.2+, the Firebase resource file is under /Assets/Plugins/Android/FirebaseApp/androidlib/res/values/google-services.xml.

Also that line in mainTemplate.gradle shouldn't be necessary in the latest version, can you try remove it and resolve again to see if that fixes the issue?

Thanks!

**Comment by rlehmannJC** [comment]
Hey @cynthiajoan 
Well I tried without that line, it doesn't work. Still the same issue, Crashlytics Task complaining about it couldn't find the file. 

But it seems the project still contains a commited services file at:
/Assets/Plugins/Android/Firebase/res/values/google-services.xml

Unfortunately it seems it doesn't auto generates the correct one on the path where it should be (all other stuff is generated, like chraslytics_unity_version.xml, etc. but not this one...
Currently checking if it is maybe an issue on our project :)

**Comment by rlehmannJC** [comment]
Okay I fixed the auto generation, and now I can see the file:
/Assets/Plugins/Android/FirebaseApp/androidlib/res/values/google-services.xml.

Unfortunately this doesn't fix the issue. Still getting:
`Execution failed for task ':launcher:uploadCrashlyticsMappingFileDebug'.
> Crashlytics could not find the resource file generated by Google Services. You may need to execute the :process<Variant>GoogleServices Task. Please check your Firebase project configuration (https://firebase.google.com/docs/android/setup). `

**Comment by chkuang-g** [comment]
@rlehmannJC 

Allow me to clarify several things:
- You should not need to add `classpath 'com.google.firebase:firebase-crashlytics-gradle:2.2.0` to baseProjectTemplate.gradle.  Crashlytics Unity editor tool actually would do exactly what `firebase-crashlytics-gradle` does.
- From Firebase `6.16.0`, all Firebase components will generate Android resources under `Assets/Plugins/Android/Firebase[ComponentName].androidlib`.  For instance, `/Assets/Plugins/Android/FirebaseApp.androidlib/res/values/google-services.xml` or `/Assets/Plugins/Android/FirebaseCrashlytics.androidlib/res/values/crashlytics_unity_version.xml`.  The Crashlytics resources are generated during build time so you will not see them before the first build.  Make sure they are generated properly in the right folder.

I suspect the failure about `launcher:uploadCrashlyticsMappingFileDebug` is related to `firebase-crashlytics-gradle` since it is looking for google-services.json in the generated Android project but cannot find it (because it is included as an Android resource google-services.xml).  Could you try to remove that line, make sure all the files are generated after the first build?

Shawn
