### ISSUE TITLE
InvalidOperationException FirebaseAuth.DefaultInstance Multiple Firebase services

### ISSUE THREAD

**Issue by gclaret** [firebase/quickstart-unity#870]
### [REQUIRED] Please fill in the following fields:

  * Unity editor version: 2019.4.12f1
  * Firebase Unity SDK version: 6.16.0
  * Source you installed the SDK: Unity Package Manager
  * Problematic Firebase Component: Auth
  * Other Firebase Components in use: App
  * Additional SDKs you are using: Applovin, Amplitude
  * Platform you are using the Unity editor on: Mac
  * Platform you are targeting: iOS
  * Scripting Runtime: IL2CPP

### [REQUIRED] Please describe the issue here:

I'm seeing an error in about 30/40% of our users in iOS regarding firebase.

```
Non-fatal Exception: InvalidOperationException
0  ???                            0x0 ThrowIfCheckDependenciesRunning (Firebase.FirebaseApp)
1  ???                            0x0 GetInstance (Firebase.FirebaseApp)
2  ???                            0x0 get_DefaultInstance (Firebase.FirebaseApp)
3  ???                            0x0 get_DefaultInstance (Firebase.Auth.FirebaseAuth)
4  ???                            0x0 RegisterWithDeviceId (BigfootSdk.Backend.FirebaseAuthenticationService)
5  ???                            0x0 SeeIfThingsReadyToLoad (BigfootSdk.DependencyManager)
```

I have a class, that first checks and fixes dependencies:

```
FirebaseApp.CheckAndFixDependenciesAsync().ContinueWithOnMainThread(task => {
                
                var dependencyStatus = task.Result;
                    if (dependencyStatus == DependencyStatus.Available)
                    {
                        callback?.Invoke();
                    } 
                    else {
                        LogHelper.LogError(string.Format(
                            "Could not resolve all Firebase dependencies: {0}", dependencyStatus));
                }
            });
```

Once that callback is called, I run the following, which is what causes the above error.

`FirebaseAuth auth = FirebaseAuth.DefaultInstance;
`

#### Steps to reproduce:

I have no idea, it happens sometimes

Have you been able to reproduce this issue with just the Firebase Unity quickstarts (this GitHub project)? haven't tried
What's the issue repro rate? (eg 100%, 1/5 etc) around 40% I would say

What happened? How can we make the problem occur?
This could be a description, log/console output, etc.

If you have a downloadable sample project that reproduces the bug you're reporting, you will
likely receive a faster response on your issue.

#### Relevant Code:

```
// TODO(you): code here to reproduce the problem
```

**Comment by chkuang-g** [comment]
@gclaret 

That exception is thrown when you try to use (almost) any Firebase API after you call `CheckAndFixDependenciesAsync()` and before it is finished.  Using Firebase SDK like `FirebaseAuth auth = FirebaseAuth.DefaultInstance;` in `ContinueWithOnMainThread ()` callback should be totally safe.

Since it is flaky, it does seems to be a race condition. Once scenario I can think of is when `FirebaseApp.CheckAndFixDependenciesAsync()` is being called multiple time, like in `MonoBehavior.Awake()`.

Could you provide the snippets of the code around the usage of Firebase SDK?  Also, please try to turn on verbose logging through `Firebase.FirebaseApp.LogLevel = Firebase.LogLevel.Verbose;` before you call `CheckAndFixDependenciesAsync()` and attach the log to your post.

Shawn
