### ISSUE TITLE
Assets from ".../Editor/Resources" being included in our builds When Firebase Added to Project. Blows up build size.

### ISSUE THREAD

**Issue by jcox-playq** [firebase/quickstart-unity#876]
### [REQUIRED] Please fill in the following fields:

  * Unity editor version: 2019.1.14f1
  * Firebase Unity SDK version: 16.6.1
  * Source you installed the SDK: .unitypackage (.unitypackage or Unity Package Manager)
  * Problematic Firebase Component: Crashlytics (possibly more too) (Auth, Database, etc.)
  * Other Firebase Components in use: none (Auth, Database, etc.)
  * Additional SDKs you are using: none (Facebook, AdMob, etc.)
  * Platform you are using the Unity editor on: Windows (but also reproduces on our Mac build machines) (Mac, Windows, or Linux)
  * Platform you are targeting: Android (have not test iOS) (iOS, Android, and/or desktop)
  * Scripting Runtime: Reproduces on both (Mono, and/or IL2CPP)

### [REQUIRED] Please describe the issue here:

See this Slack thread for discussion: https://firebase-community.slack.com/archives/C0QPFJ472/p1605916038020200
We've encountered a strange issue with old Editor assets suddenly started being included in our game builds.
Details:
All assets in the whole project that are in Resources folders that are nested under Editor folders are now being included in the base game build. These assets have not been touched (some for years), were not affected by the relevant commits, and according to Unity's build rules should never be included (see https://docs.unity3d.com/Manual/SpecialFolders.html). For example, the really big ones are the various reference screen shots for our internal test tools, which have not been changed (nor their metadata) since 2018.
These assets are not being referenced anywhere, are not assigned to asset bundles, are not being affected by asmdefs, etc. None of the usual means for getting assets into builds apply.
It started occurring with the update of Firebase to 6.16.1 (done via asset package instead of UPM, because of a bad interaction between Unity 2019.1.14, Firebase, and UPM). I have confirmed by checking the main branch builds builds before and after merging, checked the builds in the integration branch itself, and also rebuilding main branch from right before the integration to ensure it was not due to a concomitant change in our build pipeline, as well as removing Firebase entirely and rebuilding. I also did a local build on my machine, with the same result; the assets get included in the build. I was able to create a minimal reproducing project with just a single texture and Crashlytics.

#### Steps to reproduce:

Have you been able to reproduce this issue with just the Firebase Unity quickstarts (this GitHub project)?
What's the issue repro rate? (eg 100%, 1/5 etc)
Yes, 100%

What happened? How can we make the problem occur?
This could be a description, log/console output, etc.

1. Create a new Unity project (I used 2019.1.14f1)
2. Create a large texture and add it to "Assets/Editor/Resources"
3. Set build target to Android
4. Create a build, and notice that your giant texture is not included in the build (inspect apk, or look for its absence in the Build Report in the Unity editor log)
5. Download Firebase 6.16.1 unity package, unzip, and import Crashlytics into your project (resolve android libs, but can cancel packages resolver). No need to set up project on Firebase dashboard.
6. Create a new build, and notice that your giant texture is now included in the build (inspect apk, or look for its in the Build Report in the Unity editor log)

If you have a downloadable sample project that reproduces the bug you're reporting, you will
likely receive a faster response on your issue.

#### Relevant Code:

```
// TODO(you): code here to reproduce the problem
```

**Comment by jcox-playq** [comment]
@patm1987 Tagging as requested

**Comment by chkuang-g** [comment]
@jcox-playq 

I did exactly what you said, but with Unity 2019.4.9f1.  However, I did not find the large texture I put under `Assets/Editor/Resources` inside the apk.  The way I inspected the apk is through unzipping it since it is basically a zip file. If I export the Android project, instead of building the apk, I cannot find that texture in the exported project either.

- Could you try to unzip your apk and make sure you see that large texture in it?
- I have a feeling that this might be some bug with Unity.  Could you try your reproduction step on a later version of Unity?
- One possible thing I can think of that breaks Unity is the `Editor Default Resources` folder introduced by Firebase SDK. Could you try to remove it and see if that solves your issue?

Thanks,
Shawn

**Comment by jcox-playq** [comment]
- The apk does indeed have the large texture in it; I made sure to verify that before reporting the bug
- I tried deleting Editor Default Resources and creating another build; the large texture in Editor/Resources was still included in the build
- I also updated the project to 2019.4.15f1 and did another build. In this case, the issue did not reproduce. This is consistent with another project of ours one 2019.2.7f2, which also does not reproduce the issue.

So it does appear to be an interaction between Firebase and Unity version. Given that it is not reproducing with 2019.4 versions of Unity (at least the 2 tried so far), will you try to address it from the Firebase side to prevent triggering it for earlier versions?

Cheers,
Jonathan

**Comment by chkuang-g** [comment]
Based on what you said, this is definitely a Unity bug. 

Unfortunately I do not know what in Firebase SDK that can trigger this issue, since we follows what Unity said in their public documentation, and there is very little things we can do to Unity's Android build system.  

I would recommend you to update to later version of Unity.
Or you may follow what is recommended in [this post](https://answers.unity.com/questions/1571571/how-do-i-get-unity-to-not-include-editor-folder-in.html).

We can try to investigate to provide workaround for this specific version of Unity. But this will be very low priority for us.

Shawn
