### ISSUE TITLE
Still getting a null result for "1" key in Mac/Unity/Firebase 6.16.1

### ISSUE THREAD

**Issue by ztratner** [firebase/quickstart-unity#878]
* Unity editor version: 2019.4.12f1
  * Firebase Unity SDK version: 6.16.1
  * Source you installed the SDK: .unitypackage
  * Problematic Firebase Component: Database
  * Other Firebase Components in use: Auth
  * Additional SDKs you are using: N/A
  * Platform you are using the Unity editor on: Mac
  * Platform you are targeting: iOS/Android
  * Scripting Runtime: Mono

This issue that was reportedly addressed seems to still be around in 6.16.1. The key in Realtime Database console is "1" but reads "null" when I log the raw JSON value. I'm going to use the "dummy" workaround mentioned in the original issue but I don't love it.

There is only one key value pair in the child with key = 1.

Hi @ripperdoc, the [release with the fix](https://firebase.google.com/support/release-notes/unity#realtime-database) has been pushed live. If you update to the the latest SDK (v6.6.0) the problem should be resolved. If you still have issues feel free to re-open this bug.

_Originally posted by @alexames in https://github.com/firebase/quickstart-unity/issues/468#issuecomment-535739193_

**Comment by vimanyu** [comment]
Hi @ztratner,
Thanks for reporting this. 
Is this what you are noticing?
```
{
1: "One"
}

# Access values
[ null, "One"]
```

If yes, this is expected as explained in #468. Since you have a key "1" and since it is a numeric key, the auto conversion to list kicks in, and yields a list who last index is 1, which means a list with 2 entries. Since there is no corresponding entry for the key "0" a null value is kept in its place. 
So, if you had the following,
```
{
0: "Zero",
1: "One"
}

# Access values
[ "Zero", "One"]
```
Please note that missing numeric keys will show up a value of "null" in the final list that is returned to the user. 
The fix in #468 was to avoid treating "00001" as "1", and treat it as a string instead. 
So something like this,
```
{
"00001": "One"
}

# Access values
{
"00001": "One"
}
```

Hope this helps. Am closing this ticket but if you are noticing something different, please feel free to reopen this.
