### ISSUE TITLE
GetValueAsync() wrong outdated / weird results on Editor and sometimes on phone.

### ISSUE THREAD

**Issue by Subtle-Tea** [firebase/quickstart-unity#913]
### [REQUIRED] Please fill in the following fields:

  * Unity editor version: 2019.4.15f1
  * Firebase Unity SDK version: 7.0.1
  * Source you installed the SDK: Unity Package Manager
  * Problematic Firebase Component: Realtime Database
  * Other Firebase Components in use: Authentication, Analytics, Crashlytics, Remote Config
  * Additional SDKs you are using: Facebook, Ironsource, GameAnalytics
  * Platform you are using the Unity editor on: Windows and Mac
  * Platform you are targeting: iOS and Android
  * Scripting Runtime: IL2CPP

### [REQUIRED] Please describe the issue here:

I have two leaderboard implementations:
The Realtime implementation (I use ValueChanged listener) - works just fine and returns correct snapshots.
The Cached Implementation - I use GetValueAsync() to get a snapshot once a day, store it in json and load it until the next day.

When testing the second implementation in the editor, after deleting my json and forcing GetValueAsync() I get outdated data, or data containing weird entries that I tested a few days ago. When I try on my Android phone, it works for the most part normally, when I force clean data on my phone, the same behavior of the editor happens at times.

I use a uid from Auth module in my database, I noticed that when clearing data on my phone it creates a new UID, but not on my Editor - could that be why old leaderboard entries just randomly show up out of nowhere after I clear data on my Editor? When I use the ValueChanged listener everything seems to work fine so I have a feeling I am using GetValueAsync for the wrong use case, or it is cached behind the scenes in a weird way, please explain.
PS: Could it also be related to my rules in db using .indexOn score? Maybe that would cause outdated snapshots? I didn't have this issue in older versions of Firebase.

dbRef = FirebaseDatabase.DefaultInstance.GetReference("highscores");

Rules:
{
  "rules": {
    "highscores": {
      ".read": true,
      "$uid": {
        ".write": "$uid === auth.uid"
 			 },
       ".indexOn": "score"
     }
   }
}

Structure is just Root > highscores ; then each entry is uid with two children, name and score.

Code below. I don't know why I can never get an updated snapshot on Editor.

#### Relevant Code:

```
[ContextMenu("Get Snapshot")]
    void GetSnapshot()
    {
        Debug.Log("Getting Snapshot");

        dbRef.OrderByChild("score").LimitToLast(QUERY_LIMIT)
          .GetValueAsync().ContinueWith(task =>
          {
              if (task.IsFaulted)
              {
                  // Handle the error...
                  Debug.LogWarning("Could not update local List: " + task.Exception.Message);
              }
              else if (task.IsCompleted)
              {
                  DataSnapshot snapshot = task.Result;
                  // Do something with snapshot...
                  UpdateLocalList(snapshot);
              }
          });
    }

```

**Comment by alexames** [comment]
So, Database should be doing on-device caching for you. I don't think you should need to have two implementations. The way the database works is when you request data at a location, not only does it pass the data to the necessary callbacks or return values, but it also saves it under the hood, so that next time you request it it can hand you the most up to date data it is aware of without needed to do a whole server roundtrip.

I suspect what is happening is that with your ValueListener version, the values are up to date because it's actively listening for changes on that location. Meanwhile, on your GetValueAsync version, it's immediately returning the data that it has cached, which might be old.

If you run GetValueAsync a second time after some small delay, does it still return old values or does it return the expected values? I think (but I could be misremembering here) that retrieving the value from GetValueAsync should trigger a server update, even though by the time the new values make it to your client the future has already completed with the cached values.

If you want to force that location to stay up to date, you can run [KeepSynced](https://firebase.google.com/docs/reference/unity/class/firebase/database/query#keepsynced) on it. That will have the same effect as having a listener on that location, and will force the cache to have the latest values while your app runs, even though no callbacks are triggered.

**Comment by Subtle-Tea** [comment]
@alexames Thanks for your reply, yeah sometimes the second time I run GetValueAsync it does get the updated version, but you're right I get the cached ones on the first try before the update happens most likely. KeepSynced is probably not an option, will be too costly if it's like the listener, the reference in question contains too many leaderboard entries / app has too many users for that. Thanks for your help, I was hoping there was a way to get an updated GetValueAsync snapshot every time without needing to keep it synced / query it more than once.

**Comment by alexames** [comment]
Yeah, I've never been super happy with the GetValueAsync API. You're generally better off with listeners. If you don't want to keep it constantly synced you could just let it run an update once and then stop listening on that location until you need it again. 

I'm going to go ahead and close this since it sounds like there's nothing more to do here

**Comment by puf** [comment]
The native SDKs for [iOS](https://firebase.google.com/docs/database/ios/read-and-write#read_data_once), [Android](https://firebase.google.com/docs/database/android/read-and-write#read_data_once), and [Web](https://firebase.google.com/docs/database/web/read-and-write#read_data_once) nowadays have a `get()` API, which changes the behavior and returns the value from the server if possible, and only a cached value if the client is offline.
