### ISSUE TITLE
LoadSceneWhenUserAuthenticated.cs not working properly

### ISSUE THREAD

**Issue by Nicokkam** [firebase/quickstart-unity#915]
### [REQUIRED] Please fill in the following fields:

Unity editor version: _____2020.1.0f1
Firebase Unity SDK version: _____Latest
Source you installed the SDK: _____ .unitypackage
Problematic Firebase Component: _____ Database
Other Firebase Components in use: _____ Auth, Database and Analytics
Additional SDKs you are using: _____ Facebook
Platform you are using the Unity editor on: _____ Mac
Platform you are targeting: _____ iOS, Android
Scripting Runtime: _____ IL2CPP

### [REQUIRED] Please describe the issue here:

So, I was in doubt if this was indeed a bug or just a question. As I don't know where else to post it, I decided to do it here.

I am stuck with a functionality of this SDK regarding the Scenes and it's integration. Here's how they work:

#### 1st: Loading Scene
Here, I just added the FirebaseInit code EXACTLY as suggested by Patrick, which it's only function is to call the next scene (Login/Register) once everything loads correctly.

#### 2nd: Login/Register Scene
Here I do all the Login AND ALSO the register logic. I set up a button that alternates between the two (Activating the respective parent gameObject within the Canvas). Once the user log's in, the 3rd scene comes into play.

#### 3rd: App's Main Screen Scene
Main Screen of the app, where the user can LOGOUT and return to the Login Scene.

### Problem
I added the 'LoadSceneWhenUserAuthenticated.cs' in the 2nd Scene, and it works (kind of).
It actually does what it is supposed to. If I log in, quit the game without loging out, and open it again, it does come back directly to the 3rd scene. BUT some things are happening and they aren't supposed to.
#### First
When I Sign Up a user, I call the method 'CreateUserWithEmailAndPasswordAsync()'. Once it completes, it should activate the login screen and stay there, waiting for the user to fill in the password, but the 'FirebaseAuth.DefaultInstance.StateChanged' comes into play and forces the 3rd screen to be loaded, skipping several other steps that should be taken (email registration for example).
#### Second
As I mentioned in the end of number 1 above, if I try to log in to an account that does not have it's email verified, it works! (due to the 'LoadSceneWhenUserAuthenticated.cs' which is added in the scene). Code:

```
var LoginTask = auth.SignInWithEmailAndPasswordAsync(_email, _password);
      LoginTask.ContinueWithOnMainThread(task =>
       {
         if (task.IsCanceled || task.IsFaulted)
         {
           Firebase.FirebaseException e =
             task.Exception.Flatten().InnerExceptions[0] as Firebase.FirebaseException;
           GetErrorMessage((AuthError)e.ErrorCode, warningLoginText);
           return;
         }
         if (task.IsCompleted)
         {
           User = LoginTask.Result;
            if (User.IsEmailVerified == true)
           {
             UIControllerLogin.instance.MainScreenScene();
           }
           else
           {
             warningLoginText.text = Lean.Localization.LeanLocalization.GetTranslationText($"Login/VerifyEmail");
           }
```

I know that it's possible to fix this issue by adding an extra scene just before the login scene (as Patrick does in the youtube video) but it doesn't make any sense in my app. It would actually only harm the UX of it.

**Comment by chkuang-g** [comment]
Hi @NickChittle 

Without diving too deep into your code, here are several things which might help you to debug your situation.
1. When you are switching scene, Unity will destroy all objects which is not marked as [DontDestroyOnLoad](https://docs.unity3d.com/ScriptReference/Object.DontDestroyOnLoad.html).  Your FirebaseAuth instance and login status will not be reset, since they are stored internally.  But if you try to store FirebaseAuth as a static reference in a MonoBehavior, that reference will very likely be cleared, if the game object it attaches to is not marked as DontDestroyOnLoad.  What you need to do is just to get the reference again using `Firebase.FirebaseAuth.DefaultInstance`.
2. Firebase Auth has a persistence feature.  That is, if the user logged in and did not logout before the app is closed, the login state persists next time when the app is launched. That is, you do not need to call `SignInWithEmailAndPasswordAsync()` again. If the user logged in before, `FirebaseAuth.DefaultInstance.StateChanged` will be called once after `FirebaseAuth` instance is created, since the login state changed after it loads the persistence data. That is one way the SDK tell you that the user has successfully login before.  Another way is to check `FirebaseAuth.DefaultInstance.CurrentUser` and see if it is `null`. It is designed to tell you login state whenever you call it.

Here is my recommendation for your 3 scenes
- **1st: Loading Scene** - Firebase Init (`CheckAndFixDependenciesAsync` and all that jazz).  Once the init is done, check `FirebaseAuth.DefaultInstance.CurrentUser`.  If null, go to 2nd scene.  If not null, go to 3rd scene.
- **2nd: Login/Register Scene** - Your login and register flow.
- **3rd: App's Main Screen Scene** - Your main screen flow.

Hope this helps.
Shawn
