### ISSUE TITLE
Firestore listener gets triggered even after leaving Play mode

### ISSUE THREAD

**Issue by Jack37** [firebase/quickstart-unity#931]
### [REQUIRED] Please fill in the following fields:

  * Unity editor version: 2019.4.17f1
  * Firebase Unity SDK version: 7.0.2
  * Source you installed the SDK: Unity Package Manager
  * Problematic Firebase Component: Firestore
  * Other Firebase Components in use: -
  * Additional SDKs you are using: -
  * Platform you are using the Unity editor on: Mac
  * Platform you are targeting: Desktop, Android, iOS
  * Scripting Runtime: Mono, IL2CPP

### [REQUIRED] Please describe the issue here:

Firestore listeners are triggered inside Unity editor, when the user is no longer in Play mode. In our case this causes errors, instantiating prefabs, etc..

#### Steps to reproduce:

1. Register a listener for Firestore collection
2. Enter Play mode
3. Exit Play mode
4. Make a change to the database that affects the listener
5. Listener gets triggered

Reproduction rate: 100%

#### Relevant Code:

```
public void Awake()
{
    FirebaseFirestore.DefaultInstance.Collection("test").Listen(snapshot => Debug.Log("snapshot received"));
}
```

**Comment by rafikhan** [comment]
When the Unity Editor exits play mode code all continues to execute until the containing `AppDomain` is torn down. This usually happens when code is recompiled or you press play again. This is true for all libraries, not just Firestore.

The UnityEditor API provides a hook to detect play mode changes but it means the Firestore DLL (and subsequently your final compiled game) would also need to take this as a dependency. This is problematic for lots of reasons and again applies to all 3rd party libraries. We're not aware of alternative options.

To work around this you need to manage the lifecycle of a Firestore instance or track all the listener registrations and `Dispose()` them when an appropriate GameObject is torn down or inside an appropriate hook provided by the UnityEditor API. If you decide to track listener registrations you can do it manually in a global `List<>` or rely on a single `CancellationToken` that's passed around once it's supported (#907).

**Comment by Jack37** [comment]
Thank you. I will use `ListenerRegistration.Stop()` inside `OnApplicationQuit()` to prevent this from happening inside the editor.
