### ISSUE TITLE
[Storage] Database URL not set in the Firebase config.

### ISSUE THREAD

**Issue by Morgan-6Freedom** [firebase/quickstart-unity#932]
### [REQUIRED] Please fill in the following fields:

  * Unity editor version: 2019.4.17
  * Firebase Unity SDK version: 7.0.2
  * Source you installed the SDK: unitypackage (.unitypackage or Unity Package Manager)
  * Problematic Firebase Component: Storage (Auth, Database, etc.)
  * Other Firebase Components in use: Analytics, Firestore (Auth, Database, etc.)
  * Additional SDKs you are using: None (Facebook, AdMob, etc.)
  * Platform you are using the Unity editor on: Windows (Mac, Windows, or Linux)
  * Platform you are targeting: Android (iOS, Android, and/or desktop)
  * Scripting Runtime: Mono (Mono, and/or IL2CPP)

### [REQUIRED] Please describe the issue here:

When calling ` FirebaseStorage storageInstance = FirebaseStorage.DefaultInstance ` I have a warning `Database URL not set in the Firebase config. `

#### Steps to reproduce:

1) Start new Unity Project 2019.4.17
2) put the google-services.json at root of Assets/
3) Import package Firebase.analytics
4) Import package Firebase.database
5) call `FirebaseStorage storageInstance = FirebaseStorage.DefaultInstance;` in Start()
6) The Console displays :

![image](https://user-images.githubusercontent.com/49686866/104479627-f148dd00-55c3-11eb-88d5-96ee14ec322b.png)

#### Relevant Code:

```csharp
using UnityEngine;
using Firebase.Storage;

public class DatabaseManager : MonoBehaviour
{

    // Start is called before the first frame update
    void Start()
    {
        FirebaseStorage storageInstance = FirebaseStorage.DefaultInstance;
    }


}

```

**Comment by chkuang-g** [comment]
Ah, interesting. I think that warning is harmless. I guess `google-services.json` no longer includes `firebase_url` field if the database is not created.
It is just some precheck when Firebase App is created [here](https://github.com/firebase/firebase-cpp-sdk/blob/b09efc279ab2102beb82d18bbeaff96c9bc353b2/app/src/app_options.cc#L165).

Just to double check:
- Make sure you call `CheckAndFixDependenciesAsync()` before you try to access `FirebaseStorage.DefaultInstance`.  You only need to call it ONCE, like an initialization step. Please take a look of [this example](https://github.com/firebase/quickstart-unity/blob/241b0e5f527fb0b2088709a16e747d080853ca89/storage/testapp/Assets/Firebase/Sample/Storage/UIHandler.cs#L83).
- Make sure `Assets/StreamingAssets/google-services-desktop.json` is generated by our tool since it is required to run in editor.

Let us know.
Shawn
