### ISSUE TITLE
Crash with SWIGRegisterStringCallback_StorageInternal

### ISSUE THREAD

**Issue by JonCodesThings** [firebase/quickstart-unity#933]
### [REQUIRED] Please fill in the following fields:

  * Unity editor version: 2019.2.21f (also tested with 2019.4.18f)
  * Firebase Unity SDK version: 7.02 (also previously tested on 6.15.2)
  * Source you installed the SDK: Unity Package Manager
  * Problematic Firebase Component: Unknown (Auth, Database and Storage)
  * Other Firebase Components in use: (Auth, Database and Storage)
  * Additional SDKs you are using: None
  * Platform you are using the Unity editor on: Windows
  * Platform you are targeting: Desktop
  * Scripting Runtime: Mono

### [REQUIRED] Please describe the issue here:
When attempting to read/write/get data via event listeners from a Realtime Database the Unity Editor crashes giving the following logs.

(2019.2.21f)
[Editor.log](https://github.com/firebase/quickstart-unity/files/5815042/Editor.log)
[error.log](https://github.com/firebase/quickstart-unity/files/5815043/error.log)

(2019.4.18f)
[error.log](https://github.com/firebase/quickstart-unity/files/5815219/error.log)

(Please list the full steps to reproduce the issue. Include device logs, Unity logs, and stack traces if available.)

#### Steps to reproduce:

Have you been able to reproduce this issue with just the Firebase Unity quickstarts (this GitHub project)? No
What's the issue repro rate? 90% (with the caveat that there's no way of knowing what code seems to cause the crash.)
What happened? Unity crashed. 
How can we make the problem occur? Unknown.
This could be a description, log/console output, etc.

If you have a downloadable sample project that reproduces the bug you're reporting, you will
likely receive a faster response on your issue.

#### Relevant Code:
Seemingly random lines of code cause this issue. Previously it was code running in an event callback function that seemed like a sure-fire way of crashing it, but now it is unclear what is causing it after that code was removed.

**Comment by chkuang-g** [comment]
Hi @JonCodesThings 

This is very odd that the callstack shows `SWIGRegisterStringCallback_StorageInternal` while you are using Real Time Database. It almost feels like it is loading a wrong library.

Just to double check
- Are you calling any Storage API in your project?
- Is there a particular Firebase/Unity version that worked before? For example, did it work when you use Firebase `6.15.2`?
- When you upgrade to `7.0.2`, were EVERY Firebase packages upgrade to the same version? This includes `Firebase App`, `Firebase Database` and `Firebase Auth` (as Database's default dependency).
- Try to uninstall all Firebase packages and reinstall them again.

Please let us know.
Shawn

**Comment by JonCodesThings** [comment]
Hello @chkuang-g

A day after submitting this issue we removed the Storage API calls that we did have in the application and still experienced the same crashes with identical call stacks so that's no longer part of the problem.
As for the version upgrading they were all upgraded to 7.0.2 manually (Unity's Package Manager really could do with automatic updating of dependencies!). We were experiencing the same crash with 6.15.2 which was the reason we upgraded the packages in the first place.
After some more code changes we switched to using the REST API for updating the Realtime Database instead of using UpdateChildrenAsync and the crash no longer occurs. We still use event listeners from the Firebase plugin and we don't experience this crash so if I were to wager on where the issue was introduced it'd be UpdateChildrenAsync. Another theory is that this crash could be caused by some weird interactions with UpdateChildrenAsync and the event listeners we have in place but I couldn't say for sure..

I'm sorry I can't provide a lot of information on it but I hope the bits I can prove useful.

Kind regards
Jon

**Comment by abogarsukov-braingames** [comment]
We have the same issue.

- Unity 2019.4.15
- Firebase SDK 6.16.1
- We use Auth, Realtime Database, Crashlitycs, Messaging and Analytics modules.

The crash appears at random times. Usually right after pressing Play button. We do call Dispose() for the Firebase App and Auth on exit.

**Comment by abogarsukov-braingames** [comment]
Additional information that might help. Not calling Dispose() on FirebaseAuth instance AND without internet connection results in Unity crashing (both editor and player) on the next launch in 100% of cases. Otherwise crashes are random. After adding dispose call random crashes are still there, but no-internet crashes are gone. In all cases there multiple SWIGRegisterStringCallback_StorageInternal references in crash logs.

**Comment by DellaBitta** [comment]
Hi @abogarsukov-braingames,

I attempted to reproduce the random crashes by running one of our internal tests which aggressively exercises similar logic.  Unfortunately I couldn't reproduce the problem on repeat executions both in-editor and stand alone.  I understand that you've moved on to using the REST API, but please, if you can and have time, could you update this issue with a minimum reproducible test case and we'll look into the problem further?  Thank you.

**Comment by abogarsukov-braingames** [comment]
Hey @DellaBitta,

Unfortunately, I wasn't able to reproduce the issue on a minimal test application. And I cannot share sources of our project.

This happens for all team members, both on Mac and Windows (for Mac it seems to happen not so often though) at random times (but usually right after pressing Play). Here is stack trace we get on each crash:
`ERROR: SymGetSymFromAddr64, GetLastError: 'The specified module could not be found.' (Address: 0000016F821F0930)
ERROR: SymGetModuleInfo64, GetLastError: 'A dynamic link library (DLL) initialization routine failed.' (Address: 0000016F821F0930)
0x0000016F821F0930 ((<unknown>)) (function-name not available)
0x00007FFCC7379B96 (FirebaseCppApp-6_16_1) SWIGRegisterStringCallback_StorageInternal
0x00007FFCC738EC83 (FirebaseCppApp-6_16_1) SWIGRegisterStringCallback_StorageInternal
0x00007FFCC73973E8 (FirebaseCppApp-6_16_1) SWIGRegisterStringCallback_StorageInternal
0x00007FFCC738D38D (FirebaseCppApp-6_16_1) SWIGRegisterStringCallback_StorageInternal
0x00007FFCC73F1855 (FirebaseCppApp-6_16_1) SWIGRegisterStringCallback_StorageInternal
0x00007FFCC73A46C8 (FirebaseCppApp-6_16_1) SWIGRegisterStringCallback_StorageInternal
0x00007FFCC7816F8D (FirebaseCppApp-6_16_1) SWIGRegisterStringCallback_StorageInternal
0x00007FFD37C97C24 (KERNEL32) BaseThreadInitThunk
0x00007FFD3906D4D1 (ntdll) RtlUserThreadStart`

I wish I could provide more info to you.

**Comment by chkuang-g** [comment]
`FirebaseCppApp-6_16_1` - This is odd.  I think you are using `7.0.2`

This sounds like a situation that you have old Firebase libraries in your project.
Since you are using `Unity Package Manager`, could it be possible that you has legacy Firebase libraries under `Assets` folder? You can try to do a search for `FirebaseCppApp-6_16_1` in your project.

If that is the case, I would recommend you to remove all Firebase libraries from `Assets` folder and `Unity Package Manager`.
- From `Assets` folder, remove the following folders
  - `Assets/Editor Default Resources/Firebase`
  - `Assets/ExternalDependencyManager`
  - `Assets/Firebase`
  - `Assets/Parse`
  - `Assets/Plugins/iOS/Firebase`
- From Unity Package Manager, make sure you uninstall every Firebase package as well as `External Dependency Manager`.

Once you remove everything, you can reinstall them through Unity Package Manager again.

Hope this help
Shawn

**Comment by abogarsukov-braingames** [comment]
Hello @chkuang-g,

I'm not the topic starter, just happen to have the same issue. We use Firebase 6.16.1 because there was an error building v7+ with Facbook SDK 8.1.1 for iOS. Here is a summary or our setup:
- Unity editor version: 2019.5.15f
- Firebase Unity SDK version: 6.16.1
- Source you installed the SDK: Unity Package Manager
- Problematic Firebase Component: Unknown (Database?)
- Other Firebase Components in use: (Auth, Database, Crashlytics, Messaging, Analytics)
- Additional SDKs you are using: Facebook SDK, Ironsource, Adjust, Addressables, Unity IAP
- Platform you are using the Unity editor on: Windows, MacOS
- Platform you are targeting: Android, iOS
- Scripting Runtime: IL2CPP

We don't have any of the listed folders in the project, all Firebase packages have the same version (6.16.1). There are several folders with Firebase content in project:
- `Editor Default Resources/CrashlyticsSettings`;
- `Plugins/Android/FirebaseApp.androidlib/*`;
- `Plugins/Android/FirebaseCrashlytics.androidlib/*`;
- `Plugins/Android/*` (resolved android libs and gradleTemplate).

**Comment by alexovi** [comment]
Hi guys. 

I have same problem. Unity 2019.3.12f1, firebase Auth, Analytics and Database all 6.16.1.
Today I've been trying all day to find out why it sometimes crash and sometimes not (only in Editor play mode)

In short, it crashes 100% when whole object size is over ~16KB. (the object passed to SetValueAsync )

Here is my minimal testing code: (The last info in log is: Current string size: **16384**)
```
int stringsize = multiplier++ * 1024;
Log.Info($"Current string size: {stringsize}");

var _data               = new Dictionary<string, object>();
_data["SaveData"]       = RandomStringGenerator.RandomString(stringsize, RandomStringGenerator.Alphabet.Base32);
_data["SaveCounter"]    = (long)saveCounter;
_data["SaveServerTime"] = ServerValue.Timestamp;

FirebaseDatabase.DefaultInstance.RootReference.Child( "users" ).Child( userId ).SetValueAsync( _data );
```

I was looking for some limits, but I have found only one, 10MB for strings. Hopefully it helps

**Comment by abogarsukov-braingames** [comment]
I've got more info on this issue after upgrading to v7.1.0:
`========== OUTPUTTING STACK TRACE ==================

0x00007FF941EB6255 (FirebaseCppApp-7_1_0) SWIGRegisterStringCallback_StorageInternal
0x00007FF941E2D7F5 (FirebaseCppApp-7_1_0) SWIGRegisterStringCallback_StorageInternal
0x00007FF941DB5E31 (FirebaseCppApp-7_1_0) SWIGRegisterStringCallback_StorageInternal
0x00007FF941DB87F3 (FirebaseCppApp-7_1_0) SWIGRegisterStringCallback_StorageInternal
0x00007FF941DA61E5 (FirebaseCppApp-7_1_0) SWIGRegisterStringCallback_StorageInternal
0x00007FF941D56C28 (FirebaseCppApp-7_1_0) SWIGRegisterStringCallback_StorageInternal
0x00007FF942168C8D (FirebaseCppApp-7_1_0) SWIGRegisterStringCallback_StorageInternal
Failed to initialize persistence storage engine at path C:\Users\PC-10\AppData\Local/com.wordfarm.scapes/the-word-farm-users-10.firebaseio.com: IO error: C:\Users\PC-10\AppData\Local/com.wordfarm.scapes/the-word-farm-users-10.firebaseio.com/000968.dbtmp: Unable to remove the file to be replaced.

UnityEngine.DebugLogHandler:Internal_Log(LogType, LogOption, String, Object)
UnityEngine.DebugLogHandler:LogFormat(LogType, Object, String, Object[])
UnityEngine.Logger:Log(LogType, Object)
UnityEngine.Debug:LogError(Object)
Firebase.Platform.FirebaseLogger:LogMessage(PlatformLogLevel, String) (at Z:\tmp\tmp.pKCgWTopY4\firebase\app\client\unity\src\Unity\FirebaseLogger.cs:95)
Firebase.LogUtil:LogMessage(LogLevel, String) (at Z:\tmp\tmp.teccva8Fjv\firebase\app\client\unity\proxy\LogUtil.cs:68)
Firebase.LogUtil:LogMessageFromCallback(LogLevel, String) (at Z:\tmp\tmp.teccva8Fjv\firebase\app\client\unity\proxy\LogUtil.cs:76)
Firebase.AppUtilPINVOKE:PollCallbacks()
Firebase.AppUtil:PollCallbacks() (at Z:\tmp\tmp.teccva8Fjv\firebase\app\client\unity\proxy\AppUtil.cs:32)
Firebase.Platform.FirebaseAppUtils:PollCallbacks() (at Z:\tmp\tmp.teccva8Fjv\firebase\app\client\unity\proxy\FirebaseAppUtils.cs:33)
Firebase.Platform.FirebaseHandler:Update() (at Z:\tmp\tmp.pKCgWTopY4\firebase\app\client\unity\src\Unity\FirebaseHandler.cs:208)
Firebase.Platform.FirebaseMonoBehaviour:Update() (at Z:\tmp\tmp.pKCgWTopY4\firebase\app\client\unity\src\Unity\FirebaseMonoBehaviour.cs:45)
 
(Filename: Z:/tmp/tmp.pKCgWTopY4/firebase/app/client/unity/src/Unity/FirebaseLogger.cs Line: 95)

Could not initialize persistence
UnityEngine.DebugLogHandler:Internal_Log(LogType, LogOption, String, Object)
UnityEngine.DebugLogHandler:LogFormat(LogType, Object, String, Object[])
UnityEngine.Logger:Log(LogType, Object)
UnityEngine.Debug:LogError(Object)
Firebase.Platform.FirebaseLogger:LogMessage(PlatformLogLevel, String) (at Z:\tmp\tmp.pKCgWTopY4\firebase\app\client\unity\src\Unity\FirebaseLogger.cs:95)
Firebase.LogUtil:LogMessage(LogLevel, String) (at Z:\tmp\tmp.teccva8Fjv\firebase\app\client\unity\proxy\LogUtil.cs:68)
Firebase.LogUtil:LogMessageFromCallback(LogLevel, String) (at Z:\tmp\tmp.teccva8Fjv\firebase\app\client\unity\proxy\LogUtil.cs:76)
Firebase.AppUtilPINVOKE:PollCallbacks()
Firebase.AppUtil:PollCallbacks() (at Z:\tmp\tmp.teccva8Fjv\firebase\app\client\unity\proxy\AppUtil.cs:32)
Firebase.Platform.FirebaseAppUtils:PollCallbacks() (at Z:\tmp\tmp.teccva8Fjv\firebase\app\client\unity\proxy\FirebaseAppUtils.cs:33)
Firebase.Platform.FirebaseHandler:Update() (at Z:\tmp\tmp.pKCgWTopY4\firebase\app\client\unity\src\Unity\FirebaseHandler.cs:208)
Firebase.Platform.FirebaseMonoBehaviour:Update() (at Z:\tmp\tmp.pKCgWTopY4\firebase\app\client\unity\src\Unity\FirebaseMonoBehaviour.cs:45)
 
(Filename: Z:/tmp/tmp.pKCgWTopY4/firebase/app/client/unity/src/Unity/FirebaseLogger.cs Line: 95)

0x00007FF9B1807C24 (KERNEL32) BaseThreadInitThunk
0x00007FF9B37AD721 (ntdll) RtlUserThreadStart

========== END OF STACKTRACE ===========`

@chkuang-g could you take a look please?

**Comment by JonCodesThings** [comment]
Hello all,

@alexovi  You might find this link useful as it gives you the hard limits on write sizes and such (although it appears you've already discovered these through manual testing) https://firebase.google.com/docs/database/usage/limits#writes.

@google-oss-bot It appears that @abogarsukov-braingames has produced another stacktrace (far more detailed than the ones I was able to produce), so I'd argue this issue should be reopened.

**Comment by chkuang-g** [comment]
Ah, interesting.  This error log is actually from Realtime Database, when the persistent storage is turned on (by default actually) on desktop.

https://github.com/firebase/firebase-cpp-sdk/blob/c02e173d119cb3bdb240d79585108227ba342a4f/database/src/desktop/persistence/level_db_persistence_storage_engine.cc#L305

This path looks not right, since it contains both forward and backward slash.
```
C:\Users\PC-10\AppData\Local/com.wordfarm.scapes/the-word-farm-users-10.firebaseio.com/000968.dbtmp
```

Though I am not sure if this is the cause.

@alexames What do you think?

**Comment by alexames** [comment]
Yeah, ask chkuang@ says, this is an issue with trying to open multiple copies of the database at once, which isn't supported on desktop right now. When your app opens it acquires a lock on the database file, which prevents any other applications from accessing it. It's unfortunate that it crashes though, ideally we should fail more gracefully than that. In the short term I'll look into making it fail more gracefully, and long term I'll need to think about if and how we might support multiple connections to the database.

**Comment by alexames** [comment]
I don't think the forward and back slashes in the path would be the culprit, but I suppose it's possible if they were to confuse Window's filesystem handling in some way. The error is with opening the Level DB persistence layer, which is what we use to write database values to disk. For whatever reason it's having trouble removing a file at that path. You would get an error similar to this for sure if you tried to run two instances of the app simultaneously, but it doesn't sound like you're doing that.

I notice in the LevelDB repository had a [similar issue](https://github.com/google/leveldb/issues/743) a few months ago, so that might be related. 

Is it possible for you to see if some process has a lock on that file? You can use Microsoft's Process Explorer for this sort of thing. If you manually delete the local database cache, does the problem still occur? (note that doing so will result in the app needing to re-sync all data to the local client)

**Comment by abogarsukov-braingames** [comment]
@chkuang-g I had one Unity instance opened at the time of this crash. I did try disabling database persistence in editor and got the same crash (this was the case with v6.16.2). I'll try disabling persistence with v7.1.0 and report back.

I had the same errors in console several time without crash as well.

The timing of crashes seems random, usually it happens when I press Play in Unity (not every time, the rate is about 10-20%).

@alexames deleting the database manually doesn't cause any problems. I'm able to start the app from Unity Editor as usual. I'll check the file locks when I catch this crash again.

**Comment by abogarsukov-braingames** [comment]
@alexames I had the crash again today and there was no locks on the database (used Process Explorer).

**Comment by marcin-wrobel-sheepyard** [comment]
We're having the same issue. Full stack:
```
0x00007FFAE4E68EF4 (FirebaseCppApp-7_0_1) SWIGRegisterStringCallback_StorageInternal
0x00007FFAE4DF1BF4 (FirebaseCppApp-7_0_1) SWIGRegisterStringCallback_StorageInternal
0x00007FFAE4EEE8AD (FirebaseCppApp-7_0_1) SWIGRegisterStringCallback_StorageInternal
0x00007FFAE4E6E323 (FirebaseCppApp-7_0_1) SWIGRegisterStringCallback_StorageInternal
0x00007FFAE4E6EFCC (FirebaseCppApp-7_0_1) SWIGRegisterStringCallback_StorageInternal
0x00007FFAE4E67AF7 (FirebaseCppApp-7_0_1) SWIGRegisterStringCallback_StorageInternal
0x00007FFAE4E67C8A (FirebaseCppApp-7_0_1) SWIGRegisterStringCallback_StorageInternal
0x00007FFAE4E6E98C (FirebaseCppApp-7_0_1) SWIGRegisterStringCallback_StorageInternal
0x00007FFAE4BF53E8 (FirebaseCppApp-7_0_1) SWIGRegisterStringCallback_StorageInternal
0x00007FFAE4FF79BD (FirebaseCppApp-7_0_1) SWIGRegisterStringCallback_StorageInternal
0x00007FFB87B87034 (KERNEL32) BaseThreadInitThunk
0x00007FFB88F7D241 (ntdll) RtlUserThreadStart
```

Seems like it happens when we make to many SetRawJsonValueAsync calls

**Comment by jonigata** [comment]
same issue:
```
0x00007FF9B8F4D124 (FirebaseCppApp-7_1_0) SWIGRegisterStringCallback_StorageInternal
0x00007FF9B8ED5A44 (FirebaseCppApp-7_1_0) SWIGRegisterStringCallback_StorageInternal
0x00007FF9B8FDE932 (FirebaseCppApp-7_1_0) SWIGRegisterStringCallback_StorageInternal
0x00007FF9B8F52533 (FirebaseCppApp-7_1_0) SWIGRegisterStringCallback_StorageInternal
0x00007FF9B8F531DC (FirebaseCppApp-7_1_0) SWIGRegisterStringCallback_StorageInternal
0x00007FF9B8F4BD27 (FirebaseCppApp-7_1_0) SWIGRegisterStringCallback_StorageInternal
0x00007FF9B8F4BEBA (FirebaseCppApp-7_1_0) SWIGRegisterStringCallback_StorageInternal
0x00007FF9B8F52B9C (FirebaseCppApp-7_1_0) SWIGRegisterStringCallback_StorageInternal
0x00007FF9B8CD6C28 (FirebaseCppApp-7_1_0) SWIGRegisterStringCallback_StorageInternal
0x00007FF9B90E8C8D (FirebaseCppApp-7_1_0) SWIGRegisterStringCallback_StorageInternal
0x00007FFA24277034 (KERNEL32) BaseThreadInitThunk
```

**Comment by abogarsukov-braingames** [comment]
Disabling database persistence for editor seem to resolve the issue for usю
