### ISSUE TITLE
Firebase works fine in the Unity3D Editor, but there is a dependency issue in the Windows build.

### ISSUE THREAD

**Issue by Soichiro-xse** [firebase/quickstart-unity#936]
### [REQUIRED] Please fill in the following fields:

  * Unity editor version: 2019.4.10
  * Firebase Unity SDK version: 7.0.2
  * Source you installed the SDK: Unity Package Manager
  * Problematic Firebase Component: Database,Stprage
  * Platform you are using the Unity editor on:  Windows
  * Platform you are targeting: desktop
  * Scripting Runtime: Mono

### [REQUIRED] Please describe the issue here:

It works fine in UnityEditor, but when I build it for Windows, I get the following error.
"One or more Firebase dependencies are not present".

#### Steps to reproduce:

Have you been able to reproduce this issue with just the Firebase Unity quickstarts (this GitHub project)?
What's the issue repro rate? (eg 100%, 1/5 etc)

What happened? How can we make the problem occur?
This could be a description, log/console output, etc.

If you have a downloadable sample project that reproduces the bug you're reporting, you will
likely receive a faster response on your issue.

#### Relevant Code:

```
// TODO(you): code here to reproduce the problem
```

**Comment by DellaBitta** [comment]
Hi @Soichiro-xse,

I just tried installing both Firebase Storage and Firebase Database in the Database Quickstart and I was able to successfully build and run without an error.  Could you describe more where you see the error?

Additionally, if you open `Window` -> `Package Manager` and select `My Registries` from the drop down at the top (near the + sign), can you confirm that you see a check mark next to 
 
 - Cloud Storage for Firebase 7.0.2
 - External Dependency Manager (and which version?)
 - Firebase App (Core) 7.0.2
 - Firebase Authentication 7.0.2
 - Firebase Realtime Database 7.0.2

Thanks!

**Comment by Soichiro-xse** [comment]
This is the situation.

![image](https://user-images.githubusercontent.com/49627411/106103032-a2827200-6183-11eb-8345-006c3802490d.png)


![image](https://user-images.githubusercontent.com/49627411/106102727-2a1bb100-6183-11eb-8fcc-7cf17e79d0b9.png)

**Comment by patm1987** [comment]
Hi @Soichiro-xse ,

Since we're having a little bit of an issue repro'ing this, would you mind trying to reproduce your issue in one of the quickstarts hosted in this repository ([Database](https://github.com/firebase/quickstart-unity/tree/master/database/testapp), [Storage](https://github.com/firebase/quickstart-unity/tree/master/storage/testapp))? The easiest way to test these would be to just drop your `google-services.json` or `GoogleService-Info.plist` into one of these projects locally and build since the issue appears to happen at startup.

If this does fix the issue, we'd know to investigate some configuration issue in your project. If this doesn't fix the issue then we should figure out how your local system differs from ours.

Also, theoretically `CheckAndFixDependenciesAsync` should mostly be a no-op on Windows (really every platform except Android, where it checks for Google Play Services). I heard the theory echoed around that maybe your built project is having a hard time finding the google services configuration file. An easy way to test this theory would be to make sure that you block _any_ access to _any_ Firebase singleton until after you initialize Firebase (taking into account the fact that `CheckAndFixDependenciesAsync` fires off in the background. If you're not doing this yet, initialize Firebase in a different scene then load your main scene to be extra sure). Then call [`FirebaseApp.Create`](https://firebase.google.com/docs/reference/unity/class/firebase/firebase-app#class_firebase_1_1_firebase_app_1aaeb3418d9c118fcb63a409ee05a5e4aa) with `AppOptions` but no `name` field and with the `AppOptions` manually copy/pasted from your `google-services.json` file. If you do all of this right, `FirebaseApp.DefaultInstance` will be the version created with `.Create` (but if anything invoke `.DefaultInstance` before this, even another Firebase singleton, you'll already have an app created) and you'd bypass any issues with finding the services file. Obviously this would be a non-optimal solution, but if it did fix your issue it would give us an actionable bug to track.

Let me know what you find!
--Patrick
