### ISSUE TITLE
Unable to find FirebaseCppApp-7_0_0

### ISSUE THREAD

**Issue by iningwei** [firebase/quickstart-unity#941]
### [REQUIRED] Please fill in the following fields:

  * Unity editor version: Unity 2019.4.11f1
  * Firebase Unity SDK version: 6.15.0
  * Source you installed the SDK: Unity Package Manager
  * Problematic Firebase Component: RemoteConfig
  * Other Firebase Components in use: Analytics
  * Additional SDKs you are using: Facebook、IronSource、IAP
  * Platform you are using the Unity editor on: Windows
  * Platform you are targeting: Android and iOS
  * Scripting Runtime: IL2CPP

### [REQUIRED] Please describe the issue here:

(Please list the full steps to reproduce the issue. Include device logs, Unity logs, and stack traces if available.)

#### Steps to reproduce:

Have you been able to reproduce this issue with just the Firebase Unity quickstarts (this GitHub project)?
What's the issue repro rate? (eg 100%, 1/5 etc)
**I can not reproduce by Firbase Unity quickstarts。This error message occur in our own project as a sudden。Several days before i can build apk and run ok，but now the logcat output the error as title shown,and the remote config cannot be download any long**
**I have unzipped my apk, and find libFirebaseCppApp-6_15_0.so at lib/arm64-v8a、libFirebaseCppApp-6_15_0.so at lib/armeabi-v7a。The annoy thing is that why apk need version7_0_0**
**Also I checked Android Resolver Settings, also unchecked Resolution On Build**
**Also I checked my svn history,no any new or update for aar/jar recently**

What happened? How can we make the problem occur?

If you have a downloadable sample project that reproduces the bug you're reporting, you will
likely receive a faster response on your issue.

**Comment by DellaBitta** [comment]
Hi @iningwei,

It's dififcult to determine what might have started to suddenly cause this issue.  Perhaps one of your other imports has a dependency on Firebase version 7.0.0?  For instance, I searched for IronSource and noted that it has some sort of integration with Admob.  I'm not sure it's at the SDK level or in the backend, but it might be worth removing the other Assets that you're importing and add them back one by one, testing the build each time as you go.

I hope this helps.

**Comment by iningwei** [comment]
Sorry no more can afford,now we quit use remote config,just use default value~

**Comment by itsfaisalali** [comment]
Still i'm facing the same issue in latest SDK , after adding Firebase latest SDK (7.1.0) in unity i'm facing the  log error unable to load Dll "FirebaseCppApp-7_1_0: The specified module could not be found.

**Comment by itsfaisalali** [comment]
Please can someone help me about it ? . if i integrate firebase in empty project its working well but when i integrate in my main project it giving me log error after build apk .

**Comment by chkuang-g** [comment]
@iningwei 
In your first post, you mentioned that you are using Firebase `6.15.0`, but you are getting error related to `FirebaseCppApp-7_0_0` which is from Firebase `7.0.0`. Are you sure you are not mixing different version of Firebase in your project?
I would recommend you to reimport both RemoteConfig and Analytics from the same version of Firebase. If you are using Unity Package Manager, make sure `Firebase App` is in the same version as well.

Otherwise, could you provide the log when this issue occurs?

@itsfaisalali 
As I mentioned above, this error usually occurs when you mix different version of Firebase in your project.
If reimport does not work for you, could you include a bit more information about your configuration, like the followin:
  * Unity editor version: _____
  * Firebase Unity SDK version: _____
  * Source you installed the SDK: _____ (.unitypackage or Unity Package Manager)
  * Problematic Firebase Component: _____ (Auth, Database, etc.)
  * Other Firebase Components in use: _____ (Auth, Database, etc.)
  * Additional SDKs you are using: _____ (Facebook, AdMob, etc.)
  * Platform you are using the Unity editor on: _____ (Mac, Windows, or Linux)
  * Platform you are targeting: _____ (iOS, Android, and/or desktop)
  * Scripting Runtime: _____ (Mono, and/or IL2CPP)

Also, logs would be helpful too!

Shawn

**Comment by chkuang-g** [comment]
FYI, the way @google-oss-bot setup is that it will wait for the original author to response.  After a while, it would close the issue automatically.  This is one little tool to make our support rotation live a bit easier.

It does look like @ningwei  is no longer using Firebase.  I would assume there will be no more response from them.

@itsfaisalali I would actually recommend you to open a new issue and include your configuration in it, if reimport does not work for you.  This way, the bot will not close the issue until we resolve your issue.

**Comment by itsfaisalali** [comment]
> FYI, the way @google-oss-bot setup is that it will wait for the original author to response. After a while, it would close the issue automatically. This is one little tool to make our support rotation live a bit easier.
> 
> It does look like @ningwei is no longer using Firebase. I would expect no more response from them.
> 
> @itsfaisalali I would actually recommend you to open a new issue and include your configuration in it, if reimport does not work for you. This way, the bot will not close the issue until we resolve your issue.

@chkuang-g  Thanks for reply . i reimport the firebase sdk in survival times but no success . you can check my actual issue briefly from [here](https://github.com/firebase/quickstart-unity/issues/978#issue-822009545)
