### ISSUE TITLE
The Games SDK expects projects to have a Realtime Database URL in google-services.json and GoogleService-Info.plist

### ISSUE THREAD

**Issue by korober** [firebase/quickstart-unity#946]
Having the identical problem.  Trying to consume Google Analytics and Crashlytics on Unity 2020, exact same error.  Why is creating a Realtime Database required when I am using Google Analytics and Crashlytics only?  Others on other platforms consuming Google Analytics and Crashlytics are able to do so without having to create a Realtime Database.

It may be a bug if Realtime Database is a mandatory requirement, and it is not actually a requirement...

_Originally posted by @BigEndahs in https://github.com/firebase/quickstart-unity/issues/892#issuecomment-745696331_

**Comment by patm1987** [comment]
If a Firebase project was created without a Realtime Database, the Firebase console used to insert a "default" URL in both the downloaded `google-services.json` and `GoogleService-Info.plist` files. Now that field is omitted entirely if a user doesn't add a Realtime Database to their project.

It appears that `generate_xml_from_google_services_json.py` is still expecting this key in the file.

I've attached both files generated for a "dummy" project (called `com.empty.project`), adding these to any of the quickstarts should trigger the related failure case.
[Archive.zip](https://github.com/firebase/quickstart-unity/files/5935740/Archive.zip)

**Comment by patm1987** [comment]
Thanks for filing this report @korober ,

You can use Analytics and Crashlytics without a Database instance, this is a bug that snuck into the games SDK when an upstream behaviour was updated.

As a temporary workaround if you don't wish to add a Database instance, you can add a "dummy" database. For this find your project name (this might have some numbers/digits appended to the end. So "empty-project" here is "empty-project-95e84"):
![image](https://user-images.githubusercontent.com/1111611/107098180-dd138c80-67cb-11eb-9be1-9c8bc3274d7b.png)

If you're building an Android game, open your generated `google-services.json` and locate a section called `"project_info"` at the top:
```
  "project_info": {
    "project_number": "324982186402",
    "project_id": "empty-project-95e84",
    "storage_bucket": "empty-project-95e84.appspot.com"
  },
```

Add a `"firebase_url"` to it like so:
```
  "project_info": {
    "project_number": "324982186402",
    "firebase_url": "https://empty-project-95e84.firebaseio.com",
    "project_id": "empty-project-95e84",
    "storage_bucket": "empty-project-95e84.appspot.com"
  },
```

Substituting the `empty-project-95e84` with your project id.

Similarly, if you're building an iOS game, open your `GoogleService-Info.plist` file and scroll down to the bottom before:
```
</dict>
</plist>
```

And write
```
	<key>DATABASE_URL</key>
	<string>https://empty-project-95e84.firebaseio.com</string>
</dict>
</plist>
```

again replacing `empty-project-95e84` with your project name.

Let me know if that helps!
--Patrick

**Comment by chkuang-g** [comment]
To summarize, there are two place need to be update in order to support the case when RT DB is not created in a Firebase project.

1. [generate_xml_from_google_services_json.py](https://github.com/firebase/firebase-cpp-sdk/blob/master/generate_xml_from_google_services_json.py) should support the case when database url is missing. When it is missing, it should use `https://<project-id>-default-rtdb-<region>.firebasedatabase.app` by default.  For example, [this line](https://github.com/firebase/firebase-cpp-sdk/blob/a7e77482bea5ac5dfa646bd4a3bfc8a608bbb786/generate_xml_from_google_services_json.py#L124)  should be replaced by something like  
   ```
   'firebase_url': xml_dict.get('DATABASE_URL', xml_dict['PROJECT_ID'] + "-default-rtdb.firebaseio.com"
   ```
2. When Firebase App is created. There is no need to [warn when database_url is missing](https://github.com/firebase/firebase-cpp-sdk/blob/a7e77482bea5ac5dfa646bd4a3bfc8a608bbb786/app/src/app_options.cc#L154).  This is harmless for now but slightly annoying.

Shawn

**Comment by alexames** [comment]
This should be fixed as of [this pull request](https://github.com/firebase/firebase-cpp-sdk/pull/445). Feel free to reopen this issue if the problem persists.
