### ISSUE TITLE
[Question] User Property values coming in late

### ISSUE THREAD

**Issue by abittman** [firebase/quickstart-unity#977]
### [REQUIRED] Please fill in the following fields:

  * Unity editor version: 2019.4.17f1
  * Firebase Unity SDK version: 7.0.1
  * Source you installed the SDK: Unity Package Manager
  * Problematic Firebase Component: Analytics
  * Other Firebase Components in use: Cloud Messaging, Crashlytics, Remote Config
  * Additional SDKs you are using: Facebook, MoPub
  * Platform you are using the Unity editor on: Windows, Mac
  * Platform you are targeting: iOS, Android
  * Scripting Runtime: Mono

### [REQUIRED] Please describe the question here:
We have been using a few user properties (or custom definitions) in our project since it was launched a couple of years ago. We noticed that throughout reports our user properties appear to come in a little late, and are not updated frequently.

In the image below, for example, you can see the events coming in through a Debug View. The orange `clean` user property gets set at 11:10:00AM, however it should have been before the `earn_virtual_currency` events fired at 11:09:58AM as per our code. It appears that, for some reason, the user property has a delay that the analytics do not share when being set?

![Screen Shot 2021-02-26 at 11 18 05 am](https://user-images.githubusercontent.com/10857352/109910690-d14cb480-7cfc-11eb-8827-65b4c05e28dc.png)

Additionally, if I ever attempt to update this value, it seems to take longer on subsequent updates. E.g. we had a value to track the current time for testing, and noticed that the first time to come through was half a minute after launching the app (when it basically should have been almost instant). Then next one to come through was at almost 4 minutes (when really it should have been only frames after the other). So either sometimes they aren't getting set, they are being ignored, or they are coming in with a large delay.

So the question is basically - is this intended for the user properties to come in much later than an analytic I might set in the next line of code? Or is this a bug?

**Comment by chkuang-g** [comment]
@abittman 

A couple of quick questions
- Did this happen to both iOS and Android devices? 
- Did it happen with [debug mode DISABLED](https://firebase.google.com/docs/analytics/debugview#enabling_debug_mode)?
- Could you provide a snippet of your code related to the user property and the Analytics event reporting?  I know you mentioned `is this intended for the user properties to come in much later than an analytic I might set in the next line of code` but just like to double check.

Thanks!
Shawn

**Comment by abittman** [comment]
Hey @chkuang-g - apologies, thought I had replied to this already.

1 - We were able to get it on both iOS and Android, though I primarily test on android other team members were able to get it on iOS.
2 - The original report was based on unusual reports from our analyst who was looking at live data, thus from devices where debug mode would have been disabled. We were locally able to confirm by having debug mode on.
3 - The code is across multiple scripts, so it's not really feasible to easily throw it in here. But basically we run a:
`FirebaseAnalytics.SetUserProperty(name, property);`
and then only a few lines later, we run a:
`FirebaseAnalytics.LogEvent(eventName);`
and this event being fired when logged in Firebase does not show the user property set a few lines earlier.

If there's no clear ideas here I'll try Firebase Support next. Thanks!

**Comment by patm1987** [comment]
Would you be able to help us out by providing the iOS or Android debug logging on your local device (rather than debug view in the console) so we can see if the issue is related to the console/backend or the local client?

This will work on [iOS](https://firebase.google.com/docs/analytics/debugview#ios) or [Android](https://firebase.google.com/docs/analytics/debugview#android), which you choose is up to your comfort level on each -- but you will have to use native dev tools rather than just Unity.

I've included instructions below, but run the same experiment you did above. And let us know if you see the user property properly associated with each event as it leaves your device.

# Android
If you choose the Android route, open a terminal [with `adb` configured](https://medium.com/androiddevelopers/help-adb-is-not-found-93e9ed8a67ee) and type:
```
adb shell setprop debug.firebase.analytics.app com.your.package.name
```
(obviously swapping in your package name) to put your app into debug mode.

Then enter:
```
adb shell setprop log.tag.FA VERBOSE
adb shell setprop log.tag.FA-SVC VERBOSE
```
to enable debug logging.

Finally
```
adb logcat -v time -s FA FA-SVC
```
will let you view analytics events.

# iOS
Alternatively, if you're building for iOS, export your XCode project and open the generated workspace.

Locate your projet name at the top of the screen:
![image](https://user-images.githubusercontent.com/1111611/112368246-7c1f1580-8ca0-11eb-83c7-edbab5bd2974.png)

Click on it and select "Edit Scheme":
![image](https://user-images.githubusercontent.com/1111611/112368335-948f3000-8ca0-11eb-96e6-aae10fa510d5.png)

It should open to the "Info" panel, so go over to "Argument" and add `-FIRDebugEnabled`:
![image](https://user-images.githubusercontent.com/1111611/112368521-c99b8280-8ca0-11eb-9611-f1443dab9f34.png)

You should get Analytics debug output in the XCode output window.
