### ISSUE TITLE
[Bug] unable to load Dll "FirebaseCppApp-7_1_0: The specified module could not be found.

### ISSUE THREAD

**Issue by itsfaisalali** [firebase/quickstart-unity#978]
### [REQUIRED] Please fill in the following fields:

  * Unity editor version: _____2019.4.21f1
  * Firebase Unity SDK version: _____7.1.0
  * Source you installed the SDK: _____ .unitypackage 
  * Problematic Firebase Component: _____ Analytics any other firebase Component 
  * Other Firebase Components in use: _____ Analytics ,cloud Messaging,Crashlynatics 
  * Additional SDKs you are using: _____ Appodeal,UIAP
  * Platform you are using the Unity editor on: _____ Windows
  * Platform you are targeting: _____  Android
  * Scripting Runtime: _____ IL2CPP

### [REQUIRED] Please describe the issue here:

am facing the issue in latest SDK of Firebase after adding Firebase latest SDK (7.1.0) in unity can't able to use any Component of firebase because of error after building on android . the log error is 
( unable to load Dll "FirebaseCppApp-7_1_0: The specified module could not be found.)
Please can someone help me about it ? . if i integrate firebase in empty project its working well but when i did integrate in my main project which have other sdk too it giving me error which i mentioned above .

#### Steps to reproduce:

Have you been able to reproduce this issue with just the Firebase Unity quickstarts (No )? 
What's the issue repro rate? ( 100%,)

What happened? How can we make the problem occur?
DllNotFoundException: Unable to load DLL "FirebaseCppApp-7_1_0": The specified module could not be found.

If you have a downloadable sample project that reproduces the bug you're reporting, you will
likely receive a faster response on your issue.

#### Relevant Code:

```
// TODO(you): code here to reproduce the problem
```

**Comment by itsfaisalali** [comment]
Urgently need help can someone help me out ?

**Comment by itsfaisalali** [comment]
@patm1987

**Comment by chkuang-g** [comment]
As mentioned here https://github.com/firebase/quickstart-unity/issues/941#issuecomment-791078080, this `DllNotFoundException` is pretty common when you mix multiple version of Firebase in your project.  

Since you mentioned that `if i integrate firebase in empty project its working well but when i did integrate in my main project which have other sdk too it giving me error which i mentioned above .`, let do some diagnostic to your own project.

- I know you mentioned that you install Firebase through `unitypackage`, but let's make sure you does not have anything from UPM (Unity Package Manager).  Please you check `Library/PackageCache/` folder under your project and see if there is any folder start with `com.google`.  If there is any, means you have installed Firebase through UPM before.  This usually would conflict the one you installed through `.unitypackage`.  Try to remove them through [UPM interface](https://docs.unity3d.com/Packages/com.unity.package-manager-ui@1.8/manual/index.html#:~:text=Use%20the%20Unity%20Package%20Manager,update%20packages%20for%20each%20project.).
- Let's try to clean-up all Firebase SDK from your project before reimport it again.  Try to remove the following folders
  - `Assets/Editor Default Resources/Firebase`
  - `Assets/ExternalDependencyManager`
  - `Assets/PlayServicesResolver`
  - `Assets/Firebase`
  - `Assets/Parse`
  - `Assets/Plugins/iOS/Firebase`
- Try to reimport `.unitypackage` again.

If these steps does not help, could you try to include your logs from `adb logcat`? Feel free to replace any sensitive information in it.

Shawn

**Comment by CoderGamester** [comment]
I'm having the same issue but installed via UPM

**Comment by CoderGamester** [comment]
Made a issue in here: https://github.com/firebase/quickstart-unity/issues/990

I get the Firebase CppApp error on Android devices & this following error on iOS buildss:
```
UnityException: Creating asset at path Assets/Editor Default Resources/CrashlyticsSettings.asset failed.
Firebase.Crashlytics.Editor.ScriptableSettingsStorage.CreateOrLoadInstance (Firebase.Crashlytics.Editor.ScriptableSettingsStorage+AssetContext assetContext) (at Z:/tmp/tmp.wJHRiHkqvO/firebase/crashlytics/client/unity/editor/src/Storage/ScriptableSettingsStorage.cs:141)
Firebase.Crashlytics.Editor.StorageProvider..cctor () (at Z:/tmp/tmp.wJHRiHkqvO/firebase/crashlytics/client/unity/editor/src/Storage/StorageProvider.cs:40)
Rethrow as TypeInitializationException: The type initializer for 'Firebase.Crashlytics.Editor.StorageProvider' threw an exception.
Firebase.Crashlytics.Editor.iOSPostBuild.OnPostprocessBuild (UnityEditor.BuildTarget buildTarget, System.String buildPath) (at Z:/tmp/tmp.wJHRiHkqvO/firebase/crashlytics/client/unity/editor/src/iOSPostBuild.cs:76)
System.Reflection.MonoMethod.Invoke (System.Object obj, System.Reflection.BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture) (at <9577ac7a62ef43179789031239ba8798>:0)
Rethrow as TargetInvocationException: Exception has been thrown by the target of an invocation.
System.Reflection.MonoMethod.Invoke (System.Object obj, System.Reflection.BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture) (at <9577ac7a62ef43179789031239ba8798>:0)
System.Reflection.MethodBase.Invoke (System.Object obj, System.Object[] parameters) (at <9577ac7a62ef43179789031239ba8798>:0)
UnityEditor.Build.BuildPipelineInterfaces+AttributeCallbackWrapper.OnPostprocessBuild (UnityEditor.Build.Reporting.BuildReport report) (at /Users/bokken/buildslave/unity/build/Editor/Mono/BuildPipeline/BuildPipelineInterfaces.cs:184)
UnityEditor.Build.BuildPipelineInterfaces+<>c__DisplayClass17_0.<OnBuildPostProcess>b__1 (UnityEditor.Build.IPostprocessBuildWithReport bpp) (at /Users/bokken/buildslave/unity/build/Editor/Mono/BuildPipeline/BuildPipelineInterfaces.cs:448)
UnityEditor.Build.BuildPipelineInterfaces.InvokeCallbackInterfacesPair[T1,T2] (System.Collections.Generic.List`1[T] oneInterfaces, System.Action`1[T] invocationOne, System.Collections.Generic.List`1[T] twoInterfaces, System.Action`1[T] invocationTwo, System.Boolean exitOnFailure) (at /Users/bokken/buildslave/unity/build/Editor/Mono/BuildPipeline/BuildPipelineInterfaces.cs:406)
UnityEditor.BuildPlayerWindow:BuildPlayerAndRun() (at /Users/bokken/buildslave/unity/build/Editor/Mono/BuildPlayerWindow.cs:123)
```
