### ISSUE TITLE
[FR] Remove reference to NSUserTrackingUsageDescription in Firebase Analytics

### ISSUE THREAD

**Issue by Seleznov** [firebase/quickstart-unity#989]
### Feature proposal

* Firebase Component: Analytics

Hi, we are developing apps for Kids Catefory and got rejects from Apple like this:
> Your app implements the App Tracking Transparency framework, which is used when apps collect data about users and share it with third-parties for tracking purposes. Since Kids Category apps are not allowed to collect, transmit or share identifiable information with third-parties, you should not implement App Tracking Transparency in your app.

We faced problem this using Firebase Unity SDK started from 6.16.1 and newer.

Also we found out that this problem was perfectly described and solved in [this issue for Firebase iOS SDK](https://github.com/firebase/firebase-ios-sdk/issues/7652).

We do not use AppTrackingTransparency in our projects. Unfortunately without this feature/fix we have to remove Firebase Analytics package to be in compliance with Apple guidelines for Kids category application.

As we are highly interested to keep using Firebase Analytics in our projects we would appreciate you for new release of Firebase Unity SDK with fix like you done for iOS SDK ([#7652](https://github.com/firebase/firebase-ios-sdk/issues/7652)).

**Comment by vimanyu** [comment]
Thanks for bringing this to our attention.
Looks like the iOS team pushed a fix for this in Firebase 7.8.0 (M91) and we will have to upgrade our C++ and Unity SDKs to use the latest version of the pods.

**Comment by vimanyu** [comment]
Digging some more into this, we will have to wait for another pod release as there are still some issues being figured out. 
https://github.com/firebase/firebase-ios-sdk/issues/7695

**Comment by Seleznov** [comment]
@vimanyu Thanks for replay. So waiting for the fix on iOS SDK side first.

By the way, am I right about that there are two different C++ code base for iOS SDK and Unity SDK. And with this point of view we can not make next trick as temporary solution while waiting updates in Unity SDK that have been done already in iOS SDK?

I mean can we in theory use Firebase Unity SDK 7.1.0 but with manualy changed pod dependency to ios 7.9.0 (asuming that the fix will be in that iOS SDK version)?

**Comment by vimanyu** [comment]
We have a C++ code base and the Unity API is a wrapper (with some modifications) over this code base.
You could try updating the pod versions yourself and if there are no API changes to be done on Unity side for this change or any other major SDK changes in the iOS side, it might work. 

If you want to try it, here are the steps to bump up Pod version:

- Upgrade Firebase Unity SDK to 7.1.0
There are two ways you can bump up Pod version, both have pros and cons
- Modify Podfile in Xcode project directly.
Pro: easiest to change.
Con: EDM4U may override your change after rebuilding Xcode project. To prevent EDM4U from override your changes, you can disable Podfile Generation settings in Assets > External Dependency Manager > iOS Resolver > Settings menu item.

- Modify all files in your project which ends with Dependencies.xml and bump up the iosPod version to 7.8.0
Pro: EDM4U will use this version number when rebuilding Xcode project
Con: Since you will need to modify a file in the package, you will need to migrate from Unity Package Manager to .unitypackage. Otherwise, Unity Package Manager tends to revert your changes after modification. Make sure Firebase and EDM4U are uninstalled from Unity Package Manager before installing .unitypackage version.

**Comment by vimanyu** [comment]
Just to keep it simpler to follow any updates, closing this ticket as a duplicate https://github.com/firebase/quickstart-unity/issues/994.

**Comment by vimanyu** [comment]
Hi @Seleznov, were you able to try again with the latest pod 7.8.1?

**Comment by Seleznov** [comment]
@vimanyu unfortunately just today got a reject with the latest pod 7.8.1 too :/
Reason is the same as in my [first message here](https://github.com/firebase/quickstart-unity/issues/989#issue-827699557)

**Comment by jkb0o** [comment]
we also got a rejection from the Apple team with 7.8.1 (firebase-ios-sdk is the only third-party library we use)
