### ISSUE TITLE
[Question] [IOS] Xcode throw : Deeplink url is empty but the diagnostic is completely fine

### ISSUE THREAD

**Issue by Nolkeg** [firebase/quickstart-unity#996]
### [REQUIRED] Please fill in the following fields:

  * Unity editor version: _____2019.4.21
  * Firebase Unity SDK version: _____7.5
  * Source you installed the SDK: _____ .unitypackage 
  * Problematic Firebase Component: _____ dynamic link
  * Other Firebase Components in use: _____Analytics and FCM
  * Additional SDKs you are using: _____ Facebook
  * Platform you are using the Unity editor on: _____ Mac
  * Platform you are targeting: _____ iOS
  * Scripting Runtime: _____  IL2CPP

### [REQUIRED] Please describe the question here:
When opening the dynamic links(both short and long link), the app was opened correctly. But Xcode throw "Deeplink url is empty" and the dynamicLinkEventArgs.ReceivedDynamicLink.Url.OriginalString is null

I have not tried the quick start app but I tried using the diagnostic tool and it showed

---- Firebase Dynamic Links diagnostic output start ----
Firebase Dynamic Links framework version 7.5.0
System information: OS iOS, OS version 12.5.1, model iPhone
Current date 2021-03-13 07:13:26 +0000
Device locale en-US (raw en_US), timezone Asia/Bangkok
 Specified custom URL scheme is com.spacears.space.ios and Info.plist contains such scheme in CFBundleURLTypes key.
 AppID Prefix: LM75BQWF97, Team ID: LM75BQWF97, AppId Prefix equal to Team ID: YES
performDiagnostic completed successfully! No errors found.
---- Firebase Dynamic Links diagnostic output end ----

the code I used to recieve dynamic link is
string[] query = dynamicLinkEventArgs.ReceivedDynamicLink.Url.OriginalString.Split("?"[0])[1].Split("&"[0]);
this worked fine in Android.

Additional info
-I used the provided domain of page.link
-I have already added keychain sharing and associate domain in capabilities tab
-I also added the https://mydomain.page.link to info.plist(I'm not sure if this is what's caused the problem)

**Comment by paulinon** [comment]
Hi @Nolkeg,

It seems that you're not using the latest version of the SDK. Could you try using it and see if the issue persists? If so, please provide the following information so that I can identify what's causing the issue:

- Dynamic Link used
- App where the Dynamic Link has been opened
- Expected and actual behavior
- Minimal repro that I can run locally (i.e. [MCVE](https://stackoverflow.com/help/mcve))
- Steps to replicate the issue
- Complete stack trace and for iOS, include logs from [iOS self-diagnostic tool](https://firebase.google.com/docs/dynamic-links/debug#ios_self-diagnostic_tool)

Additionally, I'd like you to try out the [quickstart](https://github.com/firebase/quickstart-unity/tree/master/dynamic_links/testapp) and verify if you can also encounter the same issue there.

Thanks!

**Comment by Nolkeg** [comment]
I already use the latest Unity sdk (7.1)
I'll try to reproduce the issue with quickstart app.
My hypothesis is that: the universal link is activated because it still opened my app just with no url data.

**Comment by Nolkeg** [comment]
BTW, the problem was exactly the same as
https://gitmemory.com/issue/FirebaseExtended/flutterfire/3081/667818124

**Comment by Nolkeg** [comment]
I have fixed this issue. turn out I have to build Xcodeworkspace instead of Xcodeproj
